### ISSUE TITLE
Can't read from a PDF document

### ISSUE THREAD

**Issue by andela-araimi** [PHPOffice/PHPWord#1010]
I noticed that reading from RTF and word document samples are available in the repository but reading from pdf document is missing. I guess the library doesn't have that capacity yet. Can you kindly make this feature available or otherwise show me some samples of how to do it if I am wrong.

**Comment by troosan** [comment]
reading pdf files is not in the scope of this project.
Please check [StackOverFlow](https://stackoverflow.com/questions/1004478/read-pdf-files-with-php) for similar requests
