### ISSUE TITLE
ZipArchive::getFromName(): Invalid or uninitialized Zip object

### ISSUE THREAD

**Issue by Shmasya** [PHPOffice/PHPWord#1012]
Hello! I try open file .docx in templateProcessor and he return me this error.
I try download template file from your examples, but this doesn't work!
Screenshot of error:
https://i.imgur.com/QjwOAqx.png

**Comment by ctrlaltca** [comment]
Probably the file is not in docx format or the web server has no permisison to load it. try to check with is_readable()

**Comment by Global90** [comment]
only work on ext DOC ??

**Comment by muhiddingithub** [comment]
I have same error and I checked is_readable()  returned true. how to fixed this?

**Comment by muhiddingithub** [comment]
I convert format doc to docx its worked !!!

**Comment by troosan** [comment]
can you open your docx file (template-typography-request-new.docx) with as a zip archive?
If not it means your file not really a docx file. open it with word and be sure to save as docx.

**Comment by aben1188** [comment]
The same problem occurs, but for some reason, can't convert doc to docx, what should I do? Thanks!

**Comment by ctrlaltca** [comment]
I'm not sure posting on an issue closed one year ago is the best way to get help, but anyway..
As far as i know the template processor only supports docx files; the old, binary doc format is not supported.

**Comment by mguilhermealves** [comment]
> você pode abrir seu arquivo docx (template-typography-request-new.docx) como um arquivo zip? Caso contrário, significa que seu arquivo não é realmente um arquivo docx. abra-o com o word e salve como docx.

realmente isso funciona

**Comment by ksombrah** [comment]
Estou com o mesmo problema, mas eu realmente quero usar um modelo doc, pois o docx está travando e não abre, alguma dica?
