### ISSUE TITLE
TemplateProcessor dollar sign issue

### ISSUE THREAD

**Issue by krtorio** [PHPOffice/PHPWord#1022]
I have a docx template file going through the Template Processor, but the resulting output docx file has an error and cannot be opened.

Further inspection revealed that the error is caused by individual dollar sign or $ characters located anywhere in the docx file. Output docx file is now readable after removing $ characters from the template.

Is this something to do with the ${search pattern}? Does phpword expect $ characters to be followed by open close brackets?

The docx template file is a financial document so $ characters are expected to show up everywhere. I am surprised that the issue exists I expected phpword to ignore $ characters that do not follow the pattern.

**Comment by ozilion** [comment]
@krtorio you can use any other preffix and suffix instead of ${ and } just modifying two function in TemplateProcessor as below but i must say i am using version 12 so you shouldn't just copy paste the code

`public function setValue($search, $replace, $preffix = '${', $suffix = '}', $limit = -1)
    {
        foreach ($this->temporaryDocumentHeaders as $index => $headerXML) {
            $this->temporaryDocumentHeaders[$index] = $this->setValueForPart($this->temporaryDocumentHeaders[$index], $search, $replace, $preffix, $suffix, $limit);
        }

        $this->temporaryDocumentMainPart = $this->setValueForPart($this->temporaryDocumentMainPart, $search, $replace, $preffix, $suffix, $limit);

        foreach ($this->temporaryDocumentFooters as $index => $headerXML) {
            $this->temporaryDocumentFooters[$index] = $this->setValueForPart($this->temporaryDocumentFooters[$index], $search, $replace, $preffix, $suffix, $limit);
        }
    }`

and 

`protected function setValueForPart($documentPartXML, $search, $replace, $preffix = '${', $suffix = '}', $limit)
    {
        $pattern = '|' . $preffix . '([^' . $suffix . ']+)' . $suffix . '|U';
        //$pattern = '|\$\{([^\}]+)\}|U';
        preg_match_all($pattern, $documentPartXML, $matches);
        foreach ($matches[0] as $value) {
            $valueCleaned = preg_replace('/<[^>]+>/', '', $value);
            $valueCleaned = preg_replace('/<\/[^>]+>/', '', $valueCleaned);
            $documentPartXML = str_replace($value, $valueCleaned, $documentPartXML);
        }
        $preffix = str_replace("\\", "", $preffix);
        $suffix = str_replace("\\", "", $suffix);

        /*        if (substr($search, 0, 2) !== '${' && substr($search, -1) !== '}') {
                    $search = '${' . $search . '}';
                }*/
        if (substr($search, 0, 2) !== $preffix && substr($search, -1) !== $suffix) {
            $search = $preffix . $search . $suffix;
        }

        if (!SharedString::isUTF8($replace)) {
            $replace = utf8_encode($replace);
        }

        $regExpDelim = '/';
        $escapedSearch = preg_quote($search, $regExpDelim);
        return preg_replace("{$regExpDelim}{$escapedSearch}{$regExpDelim}u", $replace, $documentPartXML, (int)$limit);
    }`

**Comment by krtorio** [comment]
I'm using version 0.13.0, thanks for the warning
