### ISSUE TITLE
Converting docx to pdf with phpword

### ISSUE THREAD

**Issue by 50l3r** [PHPOffice/PHPWord#1027]
I want to convert a docx file to pdf

I put this line in bootstrap.php

`define('PHPWORD_BASE_DIR', realpath(__DIR__));`

And my code looks like this:

```
$FilePath = APPPATH."media/Documentos/Facturas/Factura ".$FacturaId.".docx";
$FilePathPdf = APPPATH."media/Documentos/Facturas/Factura ".$FacturaId.".pdf";

require_once APPPATH.'third_party/phpword/bootstrap.php';

$domPdfPath = realpath(PHPWORD_BASE_DIR . '/../vendor/dompdf/dompdf');
\PhpOffice\PhpWord\Settings::setPdfRendererPath($domPdfPath);
\PhpOffice\PhpWord\Settings::setPdfRendererName('DomPDF');

$phpWord = \PhpOffice\PhpWord\IOFactory::load($FilePath);
$pdfWriter = \PhpOffice\PhpWord\IOFactory::createWriter( $phpWord, 'PDF' );
$pdfWriter->save($FilePathPdf);
```

But i got this error:

`{"status":false,"error":{"classname":"PhpOffice\\PhpWord\\Exception\\Exception","message":"PDF rendering library or library path has not been defined."}}`

I read info about this topic without results: http://stackoverflow.com/questions/25563870/making-dompdf-as-my-pdf-writer-for-phpword

**Comment by wqj97** [comment]
I also got the same problem

**Comment by wqj97** [comment]
I also got the same problem
Do you find how to fix it?

**Comment by 50l3r** [comment]
Try modify this line:

`\PhpOffice\PhpWord\Settings::setPdfRendererName('DOMPDF'); //Try uppercase` 

I solved it but dompdf create a blank file: https://github.com/PHPOffice/PHPWord/issues/1030

Try with libreoffice cli: https://stackoverflow.com/questions/43008759/converting-docx-to-pdf-with-phpword

**Comment by kaystrobach** [comment]
@50l3r problem solved? please close issue

**Comment by SkubaBogdan** [comment]
In my case this error was because of not  right path to library.

**Comment by JoorgeFerrari** [comment]
I still get a blank file, any solutions of hints by now?

**Comment by akashict** [comment]
Still having the same issue, any solutions please?
