### ISSUE TITLE
MHTML в DOCX

### ISSUE THREAD

**Issue by procurement-doc** [PHPOffice/PHPWord#1034]
Заранее извиняюсь за глупый вопрос,
подскажите пожалуйста, есть ли в библиотеке возможность  экспорта формата MHTML в DOCX ?
Если нет, то будет ли в ближайшей перспективе добавлен такой функционал?

**Comment by troosan** [comment]
Conversion from MHTML to Docx is not supported and there are no plans to support this.
Прости!
