### ISSUE TITLE
Bug: Invalid style value: japaneseCounting 

### ISSUE THREAD

**Issue by wk1025** [PHPOffice/PHPWord#1041]
Invalid style value: japaneseCounting Options:bullet,decimal,upperRoman,lowerRoman,upperLetter,lowerLetter

修复Bug :
PhpWord\Style\NumberingLevel.php

/**
     * Set format
     *
     * @param string $value
     * @return self
     */
    public function setFormat($value)
    {
        $enum = array('bullet', 'decimal', 'upperRoman', 'lowerRoman', 'upperLetter', 'lowerLetter', 'japaneseCounting');
        $this->format = $this->setEnumVal($value, $enum, $this->format);
        return $this;
    }

**Comment by troosan** [comment]
to be complete we should support all the following
http://www.datypic.com/sc/ooxml/t-w_ST_NumberFormat.html
