### ISSUE TITLE
Need FrontEnd Doc file editor (Advice)

### ISSUE THREAD

**Issue by AneebImamdin** [PHPOffice/PHPWord#1045]
Hi, 
Actually this not an issue i just need a suggestion or help. I am having much trouble to open a office doc , docx file (in browser), edit this (in browser) and then save this.  I need something , some editor for this.Can i get some help for finding any library or js plugin for this ?

What i am thinking is that this library or plugin opens the doc file in browser then changes it so i will manage the html then use your Api to re save the doc file.

**Comment by troosan** [comment]
PHPWord is not the tool for this, it's not a WYSIWYG editor. I guess you should investigate tools like onlyoffice ...
