### ISSUE TITLE
How to save my document in read only mode?

### ISSUE THREAD

**Issue by ingcarlos91** [PHPOffice/PHPWord#1052]
Hi friends i'm a code but i have a question, how to save my document in read only mode with templateProcessor??

my end line code is
```php
$templateProcessor->saveAs('$file_name'.docx');
```
i want that only save from read, not write... sorry for my english, is not good

**Comment by wqj97** [comment]
Is exec('chmod -w {$file_name}.docx') work?

**Comment by troosan** [comment]
This is not possible with the templateProcessor.

If you create a document from scratch (or load it) you can use
```php
$phpWord = new \PhpOffice\PhpWord\PhpWord();
$phpWord->getProtection()->setEditing('readOnly');
```
The value for setEditing can be one of none, readOnly, comments, trackedChanges, forms
http://www.datypic.com/sc/ooxml/a-w_edit-1.html

Also you can currently not set a password to protect your document.

**Comment by troosan** [comment]
FYI pull request #1019 adds password protection

**Comment by arunsraga** [comment]
Hi Friends,

 My requirement is to make **docx** only readable, If user wish to make any changes he should provide valid password.
I'm running this Code  Sample [https://github.com/PHPOffice/PHPWord/blob/develop/samples/Sample_38_Protection.php](url). 

options given as READ_ONLY but it allows to make changes and changes get saved without password requirement.

Is anything i missed from my end  **or** any changes required in Sample code to make it run.

**Comment by troosan** [comment]
@arunsraga Are you sure this document is the result of the Sample 38?
Here is the result I'm getting
[Sample_38_Protection.docx](https://github.com/PHPOffice/PHPWord/files/1691968/Sample_38_Protection.docx)

**Comment by troosan** [comment]
@ingcarlos91 just make your original template readonly. It should not prevent the TemplateProcessor from running the replacements.

**Comment by arunsraga** [comment]
@troosan Thank You for your Response, Sorry for the Delay in response from my end. 
The Code is working fine for MS WORD DOCX. It not works for Liber Office in Ubuntu.

**Comment by troosan** [comment]
@arunsraga indeed, not implemented for ODText yet, feel free to contribute :-)

**Comment by e1sep0** [comment]
Please help. I can`t protect document from Template Processor
        ```
        $phpWord = new PhpWord();
        $documentProtection = $phpWord->getSettings()->getDocumentProtection();
        $documentProtection->setEditing(DocProtect::READ_ONLY);
        $documentProtection->setPassword('123123');
        $section = $phpWord->addSection();

        $processor = new TemplateProcessor('contract.docx');
        foreach ($variables as $key => $value) {
            $processor->setValue($key, $value);
        }

        $processor->saveAs('sample.rtf');
```

How can i protect my sample.rtf? Thank you
