### ISSUE TITLE
Style Loss of word 2007 file

### ISSUE THREAD

**Issue by NingerJohn** [PHPOffice/PHPWord#1069]
I met the style loss issue by running the following code. I barely change the original file `1.docx`, however after I save it as `helloWorld.docx` and open it, I found the style of table, header, footer was lost.
```php
// Read a docx file
$source = './temp/1.docx';
$phpWord = \PhpOffice\PhpWord\IOFactory::load($source, 'Word2007');
// Saving the document as OOXML file...
$objWriter = \PhpOffice\PhpWord\IOFactory::createWriter($phpWord, 'Word2007');
$objWriter->save('./temp/helloWorld.docx');
```

**Comment by chrisribe** [comment]
Yes this seems to be a general issue with PHPWord.
Loading any document with a style is lost. I cannot seem to find a way to load a document with styles and reuse them with other created documents. Like a styles template.

Did you find a workaround ?
Thanks
