### ISSUE TITLE
Exported docx is invalid if data labels contain ampersand

### ISSUE THREAD

**Issue by jbebe** [PHPOffice/PHPWord#1072]

**Comment by troosan** [comment]
How are you adding the legend to the chart?

**Comment by jbebe** [comment]
Sorry, I meant data label. It only appears in a specific layout though.

**Comment by troosan** [comment]
can you submit a code sample of what you are trying to do?

**Comment by jbebe** [comment]
```php
$labels = [....
$labels = str_replace('&', ' and ', $labels);
$section->addChart('pie', $labels, $values, ...
```
If I remove the second line, the document will be corrupted.

**Comment by troosan** [comment]
@jbebe do you by any change the the following set
```php
Settings::setOutputEscapingEnabled(false);
```
When I set this I have the same behaviour as the one you are describing. If I put it to `true` it works as expected.

If you really need to keep it set to `false`, you will have to replace your second line with
```php
$labels = str_replace('&', '&amp;', $labels);
```
