### ISSUE TITLE
How to get Title and content from Doc File? i use in Yii2

### ISSUE THREAD

**Issue by Global90** [PHPOffice/PHPWord#1073]
How to get Title and content from Doc File? i use in Yii2

Please Sample Code For read Doc file (UTF8) and echo in page.

**Comment by troosan** [comment]
did you try the reader?
plz check Sample_11_ReadWord2007.php

```php
$phpWord = \PhpOffice\PhpWord\IOFactory::load($source);
echo $phpWord->getDocInfo()->getTitle();
```

**Comment by Global90** [comment]
> did you try the reader?
> plz check Sample_11_ReadWord2007.php
> 
> $phpWord = \PhpOffice\PhpWord\IOFactory::load($source);
> echo $phpWord->getDocInfo()->getTitle();

i use this but i dont get content from my Docx File. but i get Creator (i dont need creator)

please check my sample file 
[sample.docx](https://github.com/PHPOffice/PHPWord/files/1116901/sample.docx)

**Comment by Global90** [comment]
i use with this code ang get text:
```
$phpWord = \PhpOffice\PhpWord\IOFactory::load($filename);

                $sections = $phpWord->getSections();
                foreach ($sections as $key => $value) {
                    $sectionElement = $value->getElements();
                    foreach ($sectionElement as $elementKey => $elementValue) {
                        if ($elementValue instanceof \PhpOffice\PhpWord\Element\TextRun) {
                            $secondSectionElement = $elementValue->getElements();
                            foreach ($secondSectionElement as $secondSectionElementKey => $secondSectionElementValue) {
                                if ($secondSectionElementValue instanceof \PhpOffice\PhpWord\Element\Text) {
                                    echo $secondSectionElementValue->getText();
                                    echo "<br>";
                                }
                            }
                        }
                    }
                }
```

but i need Text (attach image) from red Box , blue Box , how to get This part from Docx?
![untitled](https://user-images.githubusercontent.com/8215910/27760185-9963c63a-5e56-11e7-9661-e9fc5abf918f.jpg)

**Comment by troosan** [comment]
getCreator returns the creator, getTitle returns the title of the document (defined in the Metadata).

But with your example I understand this is not what you are looking for :-)

As far as I can see the only thing that differentiates what you call title from the rest is that it is in bold. Maybe you can use that to do the distinction? I'm afraid I do not have enough time to help you more than that. :-(

**Comment by xuliangliang22** [comment]
php5.2 how to use phpword?
