### ISSUE TITLE
MSDoc Reader error 

### ISSUE THREAD

**Issue by andreypronkin** [PHPOffice/PHPWord#1076]
file  PHPWord/src/PhpWord/Reader/MsDoc.php 
in line 1634  Style\Font::UNDERLINE_NONE;
but Style not imported like  " use  PhpOffice\PhpWord\Style"

**Comment by troosan** [comment]
Which version of the code are you using?
In the development branch the import is there: https://github.com/PHPOffice/PHPWord/blob/develop/src/PhpWord/Reader/MsDoc.php#L22

**Comment by andreypronkin** [comment]
I tried to install "phpoffice/phpword": "v0.13.*"  from "master"
according docs

**Comment by troosan** [comment]
this issue was fixed in PR #935 which is already merged in the development branch.
It will be part of the 0.14 release
