### ISSUE TITLE
Insert image in TemplateProcessor

### ISSUE THREAD

**Issue by gmmaraccini** [PHPOffice/PHPWord#1079]
When I create a file through TemplateProcessor, it does not add images.

I would like a simple example of how to do this. The idea is to put a logo on the document that repeats on every page

**Comment by troosan** [comment]
I do not think you will be able to achieve this with the TemplateProcessor as as far as I know it does not allow you to add images to the archive.
You could try to unzip the docx, add the image to the correct directory (word/media) and then replace a placeholder with the "correct" XML like in issue #1082 but it's not going to be easy!

**Comment by troosan** [comment]
you can try out the pull request #1084 which seems to be doing exactly what you want

**Comment by FBnil** [comment]
You can add a dummy image with the right size and location (for example, in the footer), then open your docx with zip, and see where your dummy file is located (relative path and name)
```
$fileindocx = "word/media/image2.jpeg";
$newimage = file_get_contents($fqnameofjpeg);
$templateProcessor = new TemplateProcessor($file_dir);
$templateProcessor->zipClass->AddFromString($fileindocx ,$newimage );
```
For these actions, you need to save to disk. $templateProcessor->saveAs(...)
The new image will have the position and dimensions you gave the dummy image. (at least, libreoffice shows no errors on opening the file)

**Comment by rkorebrits** [comment]
@FBnil, `zipClass->AddFromString` works perfect, however `zipClass` is a protected method... I've made it public for now, but gonna cause issues with `composer`. What do you suggest? Should we make it `public`?
