### ISSUE TITLE
TemplateProcessor insert PageBreak possible?

### ISSUE THREAD

**Issue by alexmilde** [PHPOffice/PHPWord#1082]
Hi
ist it possible to insert a pagebreak inside a processed document?

thanks!
Alex

**Comment by troosan** [comment]
Can you try the following?

in you word document, put
```code
${pageBreakHere}
${/pageBreakHere}
```
Then run:
```php
$templateProcessor = new \PhpOffice\PhpWord\TemplateProcessor('resources/template.docx');
$templateProcessor->replaceBlock('pageBreakHere', '<w:p><w:r><w:br w:type="page"/></w:r></w:p>');
$templateProcessor->saveAs('results/generated_templateFile.docx');
```

Unfortunately, depending on how word will generate the template this will work or it wont.

**Comment by SalvatorePollaci** [comment]
This is not working for me. Can anyone confirm that it is working?

**Comment by NickCoolii** [comment]
@SalvatorePollaci this worked for me.
PHP 7.0
phpoffice/phpword current (dev-master)

**Comment by Bluestart83** [comment]
It's only working when opening on Word, not LibreOffice...
May be using xml is simplier than using the library...

**Comment by Bluestart83** [comment]
I've found your solution working also on OpenOffice.

First you need to close previous text tag and reopen new row in the same paragraph with page break:
$templateProcessor->setValue('PAGE_BREAK', '</w:t></w:r>'.'<w:r><w:br w:type="page"/></w:r>'
. '<w:r><w:t>');

**Comment by gautamkoshiya** [comment]
Not worked for me please can you share with more detail

**Comment by MikeStrike94** [comment]
> I've found your solution working also on OpenOffice.
> 
> First you need to close previous text tag and reopen new row in the same paragraph with page break: $templateProcessor->setValue('PAGE_BREAK', '</w:t></w:r>'.'<w:r><w:br w:type="page"/></w:r>' . '<w:r><w:t>');

Thank you very much!
