### ISSUE TITLE
Cannot find documentation on how to read .doc files with this.

### ISSUE THREAD

**Issue by th-m** [PHPOffice/PHPWord#1083]
I guess I fit the entire issue into the title.  I guess I have a question too. Can this parse .doc files from urls?

**Comment by troosan** [comment]
Is Sample_11_ReadWord97.php what you are looking for?

**Comment by Global90** [comment]
my file is UTF8 (String Farsi) and dont read this file.

**Comment by FBnil** [comment]
@Global90 How about converting your doc to docx, and then reading it with PHPWord?
