### ISSUE TITLE
Headers and Footers in document generated from HTML 

### ISSUE THREAD

**Issue by pankamilr** [PHPOffice/PHPWord#1105]
I try to generate .docx file from HTML and by now it generates good. But I want to add footer to the document and I think that HTML writer doesn't include `addFooter` method. How I supposed to add footer to HTML generated document?

**Comment by troosan** [comment]
@pankamilr Header & Footer are only applicable when printing pages, which is not the case for HTML. Do you want to a footnote maybe? In that case please check Sample_06_Footnote.php

**Comment by pankamilr** [comment]
@troosan thanka for your reply. After some research finally I got the fact, that I use previous version of phpWord (0.12) - i participate in step project, that's way. After update to 0.13 there's is method `\PhpOffice\PhpWord\Shared\Html::addHtml` which can be use to add HTML to docx and add header and footer to the section. So issue is closed.

**Comment by troosan** [comment]
great!

**Comment by harbvxz** [comment]
> @troosan thanks for your reply. After some research finally I got the fact, that I use previous version of phpWord (0.12) - I participate in the project after someone, that's why. After update to 0.13 there's is method `\PhpOffice\PhpWord\Shared\Html::addHtml` which can be use to add HTML to docx and add header and footer to the section. So issue is closed.

Hi @pankamilr,

How did you add header and footer?

**Comment by arce701** [comment]
` Html::addHtml($footer, view($footerTemplate), false, false);`
