### ISSUE TITLE
\PhpOffice\PhpWord\IOFactory::load($path) dont work with UTF8 filename.

### ISSUE THREAD

**Issue by Global90** [PHPOffice/PHPWord#1107]
\PhpOffice\PhpWord\IOFactory::load($path) dont work with UTF8 filename.

my file name is: **تست تست.docx**

**Comment by troosan** [comment]
@Global90 are you sure it's because the filename? I tried with the name you gave and it works fine.
Can you share a sample document for which it does not work?

**Comment by Global90** [comment]
@troosan please download attach file and check with more address:

"files/test Name+900+JSF900.docx"
"files/test Name+900+JSF900.docx"
"files/test Name+900+JSF900.docx"

**Comment by Global90** [comment]
i have this error if file name or path be UTF8 like (شهروندي 20صJSF900900100files/100-تحقیق معلمین/حقوق شهروندي 20ص+900+JSF900.docx)

Adress:
**files/100-تحقیق معلمین/
حقوق شهروندي 20ص+900+JSF900.docx**

![1](https://user-images.githubusercontent.com/8215910/28492548-049e7268-6f1b-11e7-810e-ecc88e4ab382.png)
![2](https://user-images.githubusercontent.com/8215910/28492549-049efd96-6f1b-11e7-99d2-33fce0d0672d.png)
