### ISSUE TITLE
Find and Replace with PHPWord

### ISSUE THREAD

**Issue by YassYakh** [PHPOffice/PHPWord#1110]
hi is there a method to find a specific string and replace it using PHPWord ?

**Comment by VickG** [comment]
yes, the method is called `setValue`
e.g
```
$templateProcessor = new \PhpOffice\PhpWord\TemplateProcessor($fileName);
$templateProcessor->setValue('year', date('Y'));
$templateProcessor->saveAs($newFileName);

```
year has to be mentioned like
${year} in your Word Doc.

I hope this helps

**Comment by kamleshwebtech** [comment]
`setValue` is not replacing the given word in the docx file. any other suggestion? Please share. Thanks a lot.
