### ISSUE TITLE
Getting Text Run Content

### ISSUE THREAD

**Issue by Anexo** [PHPOffice/PHPWord#1111]
Hi!

I'm getting almost all the content of a docx file with this script:

https://gist.github.com/Anexo/106c25dc4a99843936562ab71c5eef18

But I'm struggling getting the content under TextRun.

Is there any getTextRun function or similar I can use?

Thanks!

**Comment by Anexo** [comment]
I suppose I need to make a foreach through the TextRun elements, but it is not working... :(

**Comment by Anexo** [comment]
Got it!!!!

Here you are, for any who has interest:

https://gist.github.com/Anexo/106c25dc4a99843936562ab71c5eef18

**Comment by troosan** [comment]
good job!
