### ISSUE TITLE
Add charts side by side

### ISSUE THREAD

**Issue by diggamies** [PHPOffice/PHPWord#1115]
Hi everybody,

i don't know if this is the right place to ask, but is there a way to add charts side by side within a table or somewhat? I tried with textrun and cell containers, but you cannot add a chart to either one of these. If someone has an idea how to place them side by side, please let me know.

Thanks, diggamies

**Comment by FBnil** [comment]
I would hack "vendor/phpoffice/phpword/src/PhpWord/Element/AbstractContainer.php" around line 282, allowing Table Cell's to contain a Chart:
```
            'Chart'         => array('Section', 'Cell'),
```
And then try to put my chart in a cell that is 4500 wide (half)
```
$phpWord->addSection()->addTable()->addRow()->addCell(4500)->addChart($type,[],[]);
```
If this works, maybe you can send a patch in?
