### ISSUE TITLE
How to use TemplateProcessor in .xlsx files?

### ISSUE THREAD

**Issue by donriga** [PHPOffice/PHPWord#1118]
i want to use similar functional in PHPExcel,
TemplateProcessor in .xlsx files
$templateProcessor = new \PhpOffice\PhpExcel\TemplateProcessor($tmpfile);

**Comment by troosan** [comment]
What's your question exactly? TemplateProcessor exists in PHPWord, please check the documentation.
If you want a similar feature in PHPExcel, keep in mind that PHPExcel is not maintained anymore, you should use PHPSpreadsheet instead. I have no idea if a similar feature exists in PHPSpreadsheet.
I suggest you ask your question there.
