### ISSUE TITLE
Class 'PhpOffice\PhpWord\PhpWord' not found

### ISSUE THREAD

**Issue by ANWSY** [PHPOffice/PHPWord#1124]
I could not use the PhpWord class ,but I composer the plugin to my project. How can I do?

**Comment by xsaad67** [comment]
You need to first include autload of composer. then instantiate an object see this below
**require_once 'vendor/autoload.php';
$phpWord = new \PhpOffice\PhpWord\PhpWord();**

**Comment by abubakarcodes** [comment]
i am unable to find the class TemplateProcessor 
Class 'phpoffice\PhpWord\TemplateProcessor' not found

**Comment by ElMoho** [comment]
Hello @abubakarcodes,
Try the following syntax : use PhpOffice\PhpWord\TemplateProcessor;
