### ISSUE TITLE
Class 'PhpOffice\Common\Text'  not found

### ISSUE THREAD

**Issue by avinash1785** [PHPOffice/PHPWord#1126]
I am getting below mentioned error:

Fatal error: Class 'PhpOffice\Common\Text' not found in E:\xampp\htdocs\PHPWord-develop\src\PhpWord\Style\AbstractStyle.php on line 164

I have also installed composer after that I am getting this error.

Thanks,
Avinash

**Comment by troosan** [comment]
if you installed using composer, you should have in your vendor directory phpoffice/common/... which contains this class

**Comment by avinash1785** [comment]
Thank you for your help, Could you please let me know with an example how to repeat the first row of the table on each page of a Word document. I have tried with the below mentioned option, but table header is not repeating on the second page.

$fancyTableFirstRowStyle = array('borderBottomSize' => 18, 'borderBottomColor' => '0000FF', 'bgColor' => '66BBFF', **'tblHeader' => true**);

Thank you,
Avinash

**Comment by troosan** [comment]
@avinash1785 please do not hijack a thread to ask all your questions.
Even better, ask you question on [StackOverflow](https://stackoverflow.com/questions/tagged/phpword), you'll have a lot more people reading your question.

As far as I read the documentation it's indeed with tblHeader that you repeat a row on each page.
I have not tested it myself, please ask on SOF with a more complete code sample.

**Comment by javanmohamad** [comment]
How can I use Asian characters with this class

**Comment by juanjulio21** [comment]
Good evening that error comes out when I am integrating with codeigniter3

**Comment by seanhuxioaowei** [comment]
do we have another way to get the PhpOffice/Common. which contain the Text Class ?
