### ISSUE TITLE
Problem with & ampersand from db

### ISSUE THREAD

**Issue by Zhaugasharov** [PHPOffice/PHPWord#1129]
Hi! I am getting text with ampersand from db 
`$person = SPerson::find($id);`
`$word = new PhpWord();`
`$word->setDefaultFontName('freeserif');`
`$word->setDefaultFontSize(14);`
`$section->addText('Aнкета научного руководителя - '.$person->getFullName(), $fontbold, $pStyle);`
`$section->addTextBreak(1, null, $pStyle);`
`$table = $section->addTable('general');`
`$table->addRow();`
`$table->addCell(5000, $cellColSpan2)->addText(trans('persons.sname') );`
`//--------------`
`/*$person->sname <= this text have & and i want insert this text to cell but if i do it i will get broken  doc file, if i insert another text in the cell i still get broken doc file. If i remove & ampersand from database i will get worked file with another or with text from database 
htmlspecialchars doesn't help because problem in antoher
*/ `
`//----------`
`$table->addCell(5000, $cellColSpan2)->addText("text");`
`$responseName = 'Anketa_'.$person->id.'.docx';`
`$writer = IOFactory::createWriter($word, 'Word2007');`
`$writer->save($responseName);`
Thank you in advance!

**Comment by dagomar** [comment]
I have the same issue. How should I escape?

**Comment by Zhaugasharov** [comment]
I used function htmlspecialchars, but on another day we have problem with «» and i can't solve problem with it. So we decided to buy phpdocx

**Comment by dagomar** [comment]
I was able to use this:

`Settings::setOutputEscapingEnabled(true);`

It works for me, even with «»

Thanks for your reply :)
