### ISSUE TITLE
Images are not getting displayed while converting docx to pdf 

### ISSUE THREAD

**Issue by xparthxvorax** [PHPOffice/PHPWord#1131]
Hello,

I'm trying to generate PDF from the docx. The images are not getting displayed in the generated PDF file.
I have also tried this solution, but no luck:
https://github.com/PHPOffice/PHPWord/issues/431#issuecomment-194815644

Here is my complete code:

            Settings::setOutputEscapingEnabled(true);
            Settings::setPdfRendererPath(base_path() . '/vendor/tecnickcom/tcpdf');
            Settings::setPdfRendererName('TCPDF');

            // Convert docx file into PDF file
            $phpWord = IOFactory::load($exportFilePath); 
            $xmlWriter = IOFactory::createWriter($phpWord , 'PDF');

            // Delete the docx file
            unlink($exportFilePath);

            // Save PDF file
            $exportFilePath = $exportPath . '/' . time() . '_pdf.pdf';
            $xmlWriter->save($exportFilePath);

PS: I'm using TCPDF.

**Comment by hubertinio** [comment]
Please, check what is pass on to the TCPDF library in that file /src/PhpWord/Writer/PDF/TCPDF.php
Is there your image?

**Comment by troosan** [comment]
with which version did you try? Could you please try with the latest development version? It should be fixed (fixed by #1074)

**Comment by psohm** [comment]
@troosan I'm sorry I tryied with the latest development release
it doesn't work :(
I use a template issued inside the word document (docx)
any clue ?

**Comment by troosan** [comment]
this fix was not for templates, only for "from scratch" document generation

**Comment by psohm** [comment]
wow you're fast @troosan 
any clue to make it work from templates ?
That fix permits to make image templating works and - with that - it works with the pdf conversion
can we add that code in phpword ?
https://stackoverflow.com/a/48565596/584448

**Comment by troosan** [comment]
@psohm There a few TemplateProcessor improvements I need to merge to the main branch.
I'm planning on doing this the version after the current one.

**Comment by shahinraza1** [comment]
I have my code. Image is not displaying while converting docx to pdf . Please suggest me

<?php
require_once 'php-word/bootstrap.php';

$objReader = \PhpOffice\PhpWord\IOFactory::createReader('Word2007');
$phpWord   = $objReader->load('sa-report.docx');

$rendererName = \PhpOffice\PhpWord\Settings::PDF_RENDERER_TCPDF;
$rendererLibrary = 'tcpdf';
$rendererLibraryPath = ''.$rendererLibrary;

if(!\PhpOffice\PhpWord\Settings::setPdfRenderer($rendererName,$rendererLibraryPath)) {
	die('please set renderer name');
}
$rendererLibraryPath = ''.$rendererLibrary;

$objWriter = \PhpOffice\PhpWord\IOFactory::createWriter($phpWord , 'PDF');
$objWriter->save('sa.pdf');

**Comment by babthamotharan** [comment]
I have changed the Image class with following code.
For references check this link
https://stackoverflow.com/questions/48043581/tcpdf-and-insert-an-image-base64-encoded?answertab=active#tab-top

```
class Image extends Text
{
    public function write()
    {
        if (!$this->element instanceof ImageElement) {
            return '';
        }
        $content = '';
        $imageData = $this->element->getImageStringData(true);
        if ($imageData !== null) {
            $styleWriter = new ImageStyleWriter($this->element->getStyle());
            $style = $styleWriter->write();
            $imageData = 'data:' . $this->element->getImageType() . ';base64,' . $imageData;            
            //Start == This lines are added to write the image in PDF
            $imageContent = file_get_contents($imageData);
            $imageData = tempnam(sys_get_temp_dir(), 'prefix');
            file_put_contents($imageData, $imageContent);
            //End            
            $content .= $this->writeOpening();
            $content .= "<img border=\"0\" style=\"{$style}\" src=\"{$imageData}\"/>";
            $content .= $this->writeClosing();
        }
        return $content;
    }
}
```
