### ISSUE TITLE
phpWord generated documents behave different in MSWord and OpenOffice? bug?

### ISSUE THREAD

**Issue by warkol66** [PHPOffice/PHPWord#1132]
I opened a question on StackOverflow
https://stackoverflow.com/questions/45760304/phpword-generated-documents-behave-different-in-msword-and-openoffice-bug?

Is there any chance there is a solution for this problem?

**Comment by FBnil** [comment]
I checked your code on SO, but can you please make a concise self running example? You have xml as text, but your function accept a section object? How do I get that xml in?

**Comment by warkol66** [comment]
Hi FBnil.
Thanks for your answer. It's not easy for my to create new self running example since we have a wrapper that handles our xml and creates the word docs.
But did you saw the screenshots? I am attaching two documents and you can easily notice the difference on linebreaks (second page) when opening the doc with word or open office. What really worries me is that linebreaks  behaves totally different. One document was created using textrun, the other normal \n new lines.
[export.docx](https://github.com/PHPOffice/PHPWord/files/1372560/export.docx)
[export(1).docx](https://github.com/PHPOffice/PHPWord/files/1372561/export.1.docx)

**Comment by FBnil** [comment]
LibreOffice autofixes your document and converts newlines put in with `setValue("uno\ndos\tres")`  into paragraphs. However MSOffice does not (strictly taken, that _is_ be the official behavior).

So you have 2 options:

1. Each `"\n"` actually means that you put each line into a separate `<w:p><w:pPr><w:t>TEXTO AQUI</w:t></w:p>` paragraph.

2. You actually want a newline similar to shift-Enter, where the `\n` is replaced by `</w:t><w:br/><w:t>`, a soft-break.

For the option 2, copy the setValueForPart() function from
 [TemplateProcessor.php](https://github.com/FBnil/PHPWord/blob/FBnil-patch-blocks/src/PhpWord/TemplateProcessor.php)

It contains: `\R` (line break: matches unix and windows newlines `\n`, `\r` and `\r\n`) and u (PCRE_UTF8) as modifier, which looks at the string as unicode. Now, assuming your text is always between `<w:t>` is not that risky, so it is a fair solution.

For option 1, you need to explode your string into separate lines, count them, 
clone a block n times, and insert each line in a separate block.

```
$txtArr = explode("\n", "uno\ndos\ntres");
$n = count($txtArr);
for($i=1;$i<=$n;$i++){ cloneBlock("párrafo", $n); }
for($i=1;$i<=$n;$i++){ setValue("miTexto",  $txtArr[$i-1], 1); }
```
for a template that looks like:

```
${párrafo}
${miTexto}
${/párrafo}
```
End of real example for 0.13.0
----
Start thinking on 0.14.x:
I'll make a `setBlock()` which will increase the DWIMmyness (do what I mean) for the TemplateProcessor.
maybe let them accept a closed block... 
```
${myblock/}
```
and `setBlock("myblock/", "uno\ndos\ntres")`. Yes, the marker is a Block, AND can be used as a value...

**Comment by warkol66** [comment]
Thank you for your answer. 
We were able to fix our code and now paragraphs created are treated equal.
Used a different approach, parsing the xml content and looking for "\n" and creating individual texts on each one.
