### ISSUE TITLE
Can't find any option to different align on same line

### ISSUE THREAD

**Issue by vikashdragongo** [PHPOffice/PHPWord#1134]
Hello

My requirement is to create a document with dynamic text. And for this i am using PHPWord, but I am facing some issues on aligning different text on same line. ie:

![untitled](https://user-images.githubusercontent.com/20084848/30200267-d36bf3d4-9493-11e7-94d1-088d71fc644d.png)

I have googled too much but I didn't find any solution.

Please help.

**Comment by troosan** [comment]
I guess what you need are tab stops.
Please check out sample Sample_02_TabStops.php

**Comment by diggamies** [comment]
For this case, I used a table without borders with two cells. It's just a workaround, but it's working as expected.
