### ISSUE TITLE
An error upon saving the symbol "&" into text

### ISSUE THREAD

**Issue by roman-yakimkin** [PHPOffice/PHPWord#1135]
Hello.

I encounted with a problem.
Namely, if I use the symbol "&" in the added text and save the document, after it the document can't be loaded. And I have to replace this symbol to "and".

**Comment by troosan** [comment]
Please try enable output escaping like this
```php
\PhpOffice\PhpWord\Settings::setOutputEscapingEnabled(true);
```

**Comment by SalvatorePollaci** [comment]
@troosan Your solution works. But if i need to insert a pageBreak in the same template i would need to disable output escaping(https://github.com/PHPOffice/PHPWord/issues/1082#issuecomment-311202462).

**Comment by FBnil** [comment]
Then create a Xml instance, and only escape the parts you need:
``` 
use PhpOffice\PhpWord\Escaper\Xml;
$xmlEscaper = new Xml();
$goodstring= $xmlEscaper->escape($badstring);
```

**Comment by FBnil** [comment]
@roman-yakimkin Please review my reply, and if this solves your problem, close this issue. T.Y!
