### ISSUE TITLE
How to process word template and download as .docx

### ISSUE THREAD

**Issue by ruchisheth** [PHPOffice/PHPWord#1136]
```
$templateProcessor = new \PhpOffice\PhpWord\TemplateProcessor(public_path('\sample_template\\'.$path));
$templateProcessor->setValue('fnm', 'John Doe');
$templateProcessor->saveAs($filename);
```
But this download the template only. it won't replace **fnm** value

Tried also
```
$templateProcessor = new \PhpOffice\PhpWord\TemplateProcessor(public_path('\sample_template\\'.$path));
$templateProcessor->setValue('fnm', 'John Doe');
$templateProcessor->saveAs($filename);
$phpWord = \PhpOffice\PhpWord\IOFactory::load($filename); // Read the temp file
$xmlWriter = \PhpOffice\PhpWord\IOFactory::createWriter($templateProcessor, 'Word2007');
$xmlWriter->save('result.docx');
```

**Comment by troosan** [comment]
How did you format the placeholder in your template?
It should be like this: ${fnm}

**Comment by SalvatorePollaci** [comment]
I'm getting the same results. Have you found a solution?

**Comment by tinasherobert** [comment]
Try to use header location in php

`$templateProcessor = new \PhpOffice\PhpWord\TemplateProcessor(public_path('\sample_template\\'.$path));`
`$templateProcessor->setValue('fnm', 'John Doe');`
`$templateProcessor->saveAs($filename);`
`$phpWord = \PhpOffice\PhpWord\IOFactory::load($filename); // Read the temp file`
`$xmlWriter = \PhpOffice\PhpWord\IOFactory::createWriter($templateProcessor, 'Word2007');`
`$xmlWriter->save('result.docx'); `

**Add this code**

`header("Location: result.docx")  ;`

**Comment by kidzen** [comment]
more detail please...
did you format the template like @troosan wrote?
what your template document version?is it word 2007?

**Comment by FBnil** [comment]
@ruchisheth  Can you `var_dump( $templateProcessor->getVariables() )` just to see what variables it detects to be present in that template example. also, is `$path` a filename or a path? Did you check it was the correct upper/lowercase ? Which version of php and which version of PHPWord are you using?

**Comment by FBnil** [comment]
@ruchisheth Please reply to our questions, or close if the solutions given helped you (but add details so that others that have the same problem can learn from it)

**Comment by troosan** [comment]
no response, closing
