### ISSUE TITLE
cloneBlock dont work

### ISSUE THREAD

**Issue by mathiastm** [PHPOffice/PHPWord#1148]
Hi everyone, i have one Word documment "test1.docx" with one block ${MYBLOCK} ... ${/MYBLOCK}.
in this document the cloneBlock function work well but in an other document i have the same block but the preg_match function in cloneBlock() match nothing...
i dumped the $matches variable.

in my first document 
```
array:5 [▼
  0 => """
    <?xml version="1.0" encoding="UTF-8" standalone="yes"?>\r\n
    <w:document xmlns:wpc="http://schemas.microsoft.com/office/word/2010/wordprocessingCanvas" xmlns:cx="http://schemas.microsoft.com/office/drawing/2014/chartex" x ▶
    """
  1 => """
    <?xml version="1.0" encoding="UTF-8" standalone="yes"?>\r\n
    <w:document xmlns:wpc="http://schemas.microsoft.com/office/word/2010/wordprocessingCanvas" xmlns:cx="http://schemas.microsoft.com/office/drawing/2014/chartex" x ▶
    """
  2 => "<w:p w:rsidR="005A380F" w:rsidRDefault="005A380F" w:rsidP="00662B52"><w:r w:rsidRPr="00CD65D3"><w:rPr><w:highlight w:val="yellow"/></w:rPr><w:t>${BOUCLE1_CLIENT ▶"
  3 => "<w:p w:rsidR="005A380F" w:rsidRDefault="00A8472A" w:rsidP="00105810"><w:pPr><w:ind w:left="1418"/></w:pPr><w:r><w:t>${CONT/ETATCIVIL}</w:t></w:r><w:r w:rsidR="0 ▶"
  4 => "<w:p w:rsidR="005A380F" w:rsidRDefault="005A380F" w:rsidP="00662B52"><w:r w:rsidRPr="00CD65D3"><w:rPr><w:highlight w:val="yellow"/></w:rPr><w:t>${/BOUCLE1_CLIEN ▶"
]
```
in the second : 
```
[]
```
any ideas?

**Comment by FBnil** [comment]
Keep a look out on this https://github.com/PHPOffice/PHPWord/pull/1147
Are you using PHP7?
Can you make a small document for me where it does not work? I can then add it as a testcase (to ensure the consistency of fixes). Email it to me at niltoncastillo signthingyhere pimarox.nl .
If you are savvy enough, try replacing my version of TemplateProcessor.php in your vendor directory and see how it goes then.

**Comment by mathiastm** [comment]
Thank you @FBnil  for your answer,I finally found a solution using `DOMDocument` and `DOMXPath` classes.
have a good day.
