### ISSUE TITLE
Phpword loadTemplate() finction behave differently on php thread safe and php non thread safe

### ISSUE THREAD

**Issue by kidzen** [PHPOffice/PHPWord#1149]
How to replicate error:

Use phpword loadTemplate function..
$object = new/phpoffice/phpword/phpword()->loadTemplate('template.docx');

Error: 
ZipArchive::getFromName():invalid or uninitialized zip object

**Comment by FBnil** [comment]
I get a syntax error with that. Can you give also the configuration information? 
Which version of PHP, which OS, which PHP add-ons you are using (like fcgi), which frontend (hiawatha/apache/etc). I assume PHPWord is at 0.13?

```
	($object = new \PhpOffice\PhpWord\PhpWord())->loadTemplate('template.docx');
	$object->save(storage_path('y.docx'));
	return response()->download(storage_path('y.docx'))->deleteFileAfterSend(true);   
```

**Comment by kidzen** [comment]
@FBnil  im currently running PHP 7.1 with IIS as web server..
try this..

> $object = new \PhpOffice\PhpWord\PhpWord();
$object->loadTemplate('template.docx');
	$object->save(storage_path('y.docx'));
	return response()->download(storage_path('y.docx'))->deleteFileAfterSend(true);

**Comment by kidzen** [comment]
By the way, turn out that this issue related to permission when PhpOffice try to create a temp file inside windows default temporary directory (C:/windows/Temp )..

My suggestion, by default Settings:getTempDir() should return webroot path instead of windows/Server Temp Directory.

``` 
public static function getTempDir()
{
     $tempDir = sys_get_temp_dir();      <----the culprit
     if (!empty(self::$tempDir)) {
          $tempDir = self::$tempDir;
     }
     return $tempDir;
}
