### ISSUE TITLE
Upgrade to Magento 2.2 is blocked because of phpword v0.13.0

### ISSUE THREAD

**Issue by MariosPrifti** [PHPOffice/PHPWord#1158]
Hey,

I have the phpoffice installed in my magento 2.1.9 installation, and it is working like a charm. However I cannot upgrade to magento 2.2. The error during upgrade is the following (during readiness test):

Command "update" failed: Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

Problem 1
- Installation request for magento/product-community-edition 2.2.0 -> satisfiable by magento/product-community-edition[2.2.0].
- phpoffice/phpword v0.13.0 requires zendframework/zend-stdlib 2.4.* -> satisfiable by zendframework/zend-stdlib[2.4.0, 2.4.0rc1, 2.4.0rc2, 2.4.0rc3, 2.4.0rc4, 2.4.0rc5, 2.4.0rc6, 2.4.0rc7, 2.4.1, 2.4.10, 2.4.11, 2.4.12, 2.4.13, 2.4.2, 2.4.3, 2.4.4, 2.4.5, 2.4.6, 2.4.7, 2.4.8, 2.4.9].
- Can only install one of: zendframework/zend-stdlib[2.7.7, 2.4.0].
- Can only install one of: zendframework/zend-stdlib[2.7.7, 2.4.0rc1].
- Can only install one of: zendframework/zend-stdlib[2.7.7, 2.4.0rc2].
- Can only install one of: zendframework/zend-stdlib[2.7.7, 2.4.0rc3].
- Can only install one of: zendframework/zend-stdlib[2.7.7, 2.4.0rc4].
- Can only install one of: zendframework/zend-stdlib[2.7.7, 2.4.0rc5].
- Can only install one of: zendframework/zend-stdlib[2.7.7, 2.4.0rc6].
- Can only install one of: zendframework/zend-stdlib[2.7.7, 2.4.0rc7].
- Can only install one of: zendframework/zend-stdlib[2.7.7, 2.4.1].
- Can only install one of: zendframework/zend-stdlib[2.7.7, 2.4.10].
- Can only install one of: zendframework/zend-stdlib[2.7.7, 2.4.11].
- Can only install one of: zendframework/zend-stdlib[2.7.7, 2.4.12].
- Can only install one of: zendframework/zend-stdlib[2.7.7, 2.4.13].
- Can only install one of: zendframework/zend-stdlib[2.7.7, 2.4.2].
- Can only install one of: zendframework/zend-stdlib[2.7.7, 2.4.3].
- Can only install one of: zendframework/zend-stdlib[2.7.7, 2.4.4].
- Can only install one of: zendframework/zend-stdlib[2.7.7, 2.4.5].
- Can only install one of: zendframework/zend-stdlib[2.7.7, 2.4.6].
- Can only install one of: zendframework/zend-stdlib[2.7.7, 2.4.7].
- Can only install one of: zendframework/zend-stdlib[2.7.7, 2.4.8].
- Can only install one of: zendframework/zend-stdlib[2.7.7, 2.4.9].
- magento/product-community-edition 2.2.0 requires zendframework/zend-stdlib ^2.7.7 -> satisfiable by zendframework/zend-stdlib[2.7.7].
- Installation request for phpoffice/phpword ^0.13.0 -> satisfiable by phpoffice/phpword[v0.13.0].

Is there any walkaround or new version?

Thanks

**Comment by omarpiani** [comment]
+1 for new composer package!

**Comment by troosan** [comment]
There is a new version 0.14.0, but which is not released yet.
If you want to give it a try just, try the dev-master version

**Comment by omarpiani** [comment]
atm i have a software in production with dev-master

![I like to live dangerously](http://i3.kym-cdn.com/photos/images/newsfeed/000/511/991/3a5.jpg)

**Comment by troosan** [comment]
;-) sure, don't use it in production. just in test to make sure it works.
