### ISSUE TITLE
how to set Paragraph  textAlignment center ?

### ISSUE THREAD

**Issue by agang235** [PHPOffice/PHPWord#1165]
###  I want set textAlignment center
![000](https://user-images.githubusercontent.com/25738075/31847376-f148ff74-b64d-11e7-9f7f-3c62b8601579.png)

[对比.docx](https://github.com/PHPOffice/PHPWord/files/1403745/default.docx)

**Comment by troosan** [comment]
I do not think this is implemented.

http://www.datypic.com/sc/ooxml/e-w_textAlignment-1.html

**Comment by agang235** [comment]
@troosan 
I hope PHPWORD can do this, and it's very useful in math,think you!

**Comment by troosan** [comment]
implemented in develop branch
