### ISSUE TITLE
Question: How can I have an outer border on table and no border on cells

### ISSUE THREAD

**Issue by gaurav-chandra** [PHPOffice/PHPWord#1169]
Hi,

I need to have my table an outer border like so:

![microsoft word_2017-10-23 16-57-27](https://user-images.githubusercontent.com/3168243/31886751-4e603ed6-b813-11e7-87d2-3eed64b27b50.png)

But currently I am having borders like:

![microsoft word_2017-10-23 16-58-45](https://user-images.githubusercontent.com/3168243/31886913-f1c8f3e2-b813-11e7-8701-884419b5e514.png)

Is this possible?

**Comment by FBnil** [comment]
Well, with ->addTable() you pass a $style. And the fastest way to know what should be in there is to make a word document with a styled table, then read it into phpword:

`$phpWord = \PhpOffice\PhpWord\IOFactory::load($file_dir);`

Now you have a `$phpWord`, which you can check, with for example `get_class_methods($phpWord)` and after a few var_dump() or dd() you will be able to reach the style for that table.

so the first thing you will see is that there is a section, which you can access with getSections() and [0] is the first one, so something like:
dd($template->getSections()[0]->getelements()[0]->getFontStyle());
Now you have the style, and you can pass it 

You then can use a style ` addTableStyle($styleName, $styleTable, $styleFirstRow = null)`:
```
$phpWord->addTableStyle('tblStyle', array('width' => 100));
$table = $section->addTable('tblStyle')->addRow()->addCell();
```
or an inline style:
```
$table = $section->addTable(array('width' => 50 * 50, 'unit' => 'pct', 'alignment' => \PhpOffice\PhpWord\SimpleType\JcTable::CENTER));
```

**Comment by gaurav-chandra** [comment]
Wow thanks @FBnil for the answer. I never thought about reading a word doc. That is a good suggestion. 

The one thing which confuses me a lot is lack for proper documentation. I started using phpword yesterday only and kept scratching my head as I could not find the proper documentation.

Thanks again. I will try this.

**Comment by FBnil** [comment]
There are lots of examples in the sourcecode, the testcases, although incomplete, hint at things you may find helpful. also: http://phpword.readthedocs.io/en/latest/
