### ISSUE TITLE
read docx error when contains image from remote url

### ISSUE THREAD

**Issue by yeluolei** [PHPOffice/PHPWord#1173]
I have a docx with image from an url, the rels like this
```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Relationships 
    xmlns="http://schemas.openxmlformats.org/package/2006/relationships">
    <Relationship Id="rId3" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/webSettings" Target="webSettings.xml"/>
    <Relationship Id="rId7" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/theme" Target="theme/theme1.xml"/>
    <Relationship Id="rId2" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/settings" Target="settings.xml"/>
    <Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles" Target="styles.xml"/>
    <Relationship Id="rId6" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/fontTable" Target="fontTable.xml"/>
    <Relationship Id="rId5" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/image" Target="https://image0.lietou-static.com/normal/5773448845ce6e5083b716f404a.png" TargetMode="External"/>
</Relationships>
```

but when I try to load this docx to php, it throw an exception like this 

```
Exception 'PhpOffice\PhpWord\Exception\InvalidImageException' with message ''

in /app/vendor/phpoffice/phpword/src/PhpWord/Element/Image.php:386

Stack trace:
#0 /app/vendor/phpoffice/phpword/src/PhpWord/Element/Image.php(139): PhpOffice\PhpWord\Element\Image->checkImage('zip://liepin_1....')
#1 [internal function]: PhpOffice\PhpWord\Element\Image->__construct('zip://liepin_1....')
#2 /app/vendor/phpoffice/phpword/src/PhpWord/Element/AbstractContainer.php(145): ReflectionClass->newInstanceArgs(Array)
#3 [internal function]: PhpOffice\PhpWord\Element\AbstractContainer->addElement('Image', 'zip://liepin_1....')
#4 /app/vendor/phpoffice/phpword/src/PhpWord/Element/AbstractContainer.php(112): call_user_func_array(Array, Array)
```

seams it try to unzip the remote url as image data and failed

**Comment by FBnil** [comment]
I DO see some code that should handle that case:
`./src/PhpWord/Element/Image.php`  in function setSourceType()
```
if (strpos($this->source, 'https') === 0) {
:
$this->sourceType = self::SOURCE_STRING;
```
in setFunctions() we see png is supported, and the exception should give a message, not an empty message:
`throw new InvalidImageException(sprintf('Invalid image: %s', $this->source));`

We also have that this passes in setSourceType():
`filter_var('https://image0.lietou-static.com/normal/5773448845ce6e5083b716f404a.png', FILTER_VALIDATE_URL)` 

it then does download the image (which also succeeded for me)
```
                $fileContent = file_get_contents($this->source);
                $this->source = $fileContent;
                $this->sourceType = self::SOURCE_STRING;
```

Thus, your action to check would be:
./src/PhpWord/Element/Image.php function checkImage()
```
    private function checkImage()
    {
        $this->setSourceType();

        // Check image data
        if ($this->sourceType == self::SOURCE_ARCHIVE) {
            $imageData = $this->getArchiveImageSize($this->source);
        } else if ($this->sourceType == self::SOURCE_STRING) {
            $imageData = $this->getStringImageSize($this->source);
        } else {
            $imageData = @getimagesize($this->source);
        }
// DIE AND DUMP (or similar) HERE YOUR IMAGE DATA and check why it is not an array....
var_dump($imageData); # try also $this->source
        if (!is_array($imageData)) {
            throw new InvalidImageException(sprintf('Invalid image: %s', $this->source));
        }

```
 
`./src/PhpWord/Writer/Word2007/Part/Rels.php:        $targetMode = ($type == 'hyperlink') ? 'External' : '';`

**Comment by yeluolei** [comment]
I am using php 7.1. Seams the code is in the develop branch. I am using the composer version v0.13.0. the newest version is not published into composer.

anyway, I will close this problem and try the develop branch, thank you ~

**Comment by yeluolei** [comment]
OK, I have try the develop branch, but he error message shows as bellow.
seams the source type detect is wrong. test  file attached.

[liepin_1.docx](https://github.com/PHPOffice/PHPWord/files/1420711/liepin_1.docx)



```

Exception 'PhpOffice\PhpWord\Exception\InvalidImageException' with message 'Invalid image: zip://liepin_1.docx#word/https://image0.lietou-static.com/img/569f31cb45ce9a6555837d7704a.png'

in /app/vendor/phpoffice/phpword/src/PhpWord/Element/Image.php:389
```

**Comment by FBnil** [comment]
@yeluolei Thank you for finding that bug. Your attachment seems to have personal data (not that I can read Chinese), so delete it or replace it with something that can be shared. At least remove the email inside it because webcrawlers will get that added to spam lists.

I'll work on it during the weekend.

**Comment by yeluolei** [comment]
no problem~ the attachment is just for you~

**Comment by FBnil** [comment]
Ok, the document now reads ok with this edit:

1. We make sure that getRels() keeps the [http|https|ftp|gopher]:// external link intact: 

function getRels() in `.\vendor\phpoffice\phpword\src\PhpWord\Reader`
```
            // Do not add prefix to link source
            if (!in_array($type, array('hyperlink')) && !preg_match('#^\w+://#', $target)) {
                $target = $targetPrefix . $target;
            }
```

2. We make sure that the external link does not reference a zip:

function readRun() in `.\vendor\phpoffice\phpword\src\PhpWord\Reader\Word2007`
```
            } elseif ($xmlReader->elementExists('w:pict', $domNode)) {
                $rId = $xmlReader->getAttribute('r:id', $domNode, 'w:pict/v:shape/v:imagedata');
                $target = $this->getMediaTarget($docPart, $rId);
                if (!is_null($target)) {
                    if (preg_match('#^\w+://#', $target)) {
                        $imageSource = $target;
                    } else {
                        $imageSource = "zip://{$this->docFile}#{$target}";
                    }
                    $parent->addImage($imageSource);
                }
```

However, your document also contains 
`<w:t xml:space="preserve">&crm</w:t>`
And you need to escape those first with htmlspecialchars(), like this (I think this is already fixed in dev / 0.14.0 with  Settings::isOutputEscapingEnabled() ):
`$section->addText(htmlspecialchars('&crm', ENT_COMPAT, 'UTF-8'));`

Or you will get this error:
```
    Problem: An XML parser returns the error “xmlParseEntityRef: noname”

    Cause: There is a stray ‘&’ (ampersand character) somewhere in the XML text eg. some text & some more text

    Solution:

        Solution 1: Remove the ampersand.
        Solution 2: Encode the ampersand (that is replace the '&' character with '& amp;' ). Remember to Decode when reading the XML text.
        Solution 3: Use CDATA sections (text inside a CDATA section will be ignored by the parser.) eg. <![CDATA[some text & some more text]]>

    Note: ‘&’ ‘<' '>‘ will all give problems if not handled correctly.
```

**Comment by yeluolei** [comment]
thanks very much! It's so detail. I have fixed this with my own solution just like yours. Actually I hope this can make phpword better~

**Comment by FBnil** [comment]
@yeluolei You are welcome. Good to see that the instructions were enough to get your application working.
Yes, I just made a patch for 0.14.0 https://github.com/PHPOffice/PHPWord/pull/1176 
I cleaned the code up a little so it looks more professional, but it still is the same solution.
