### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by Charius** [PHPOffice/PHPWord#1174]
So when there will be next release. Since now there are 100+ commits in develop branch and no release. It's sad.

**Comment by FBnil** [comment]
Charius, we do not have an official maintainer (if you want you can apply for that position). There are lots of patches, and they all need to be tested, marked as useful, marked as incomplete or missing functions, or missing testcases (which you can pull-request to those, before they get merged into PHPWord), etc. That work can be done by enthousiasts like us. For example: there are 3 versions of TemplateProcessor Images insertions. Which would you choose? Just go into the patches, test them, and comment on their usefulness, the name of the functions, the ideas to make it easier on the user later on, this way the patch gets better.

**Comment by Charius** [comment]
@FBnil thanks for the answer and information!

**Comment by Charius** [comment]
this issue related with #848 

So I close this one

**Comment by connerbw** [comment]
@FBnil 
>we do not have an official maintainer

What about this comment?
> https://github.com/PHPOffice/PHPWord/issues/948#issuecomment-305099226

I see @troosan in the dev branch. It would be nice to get some clarification. I'm starting to lose my confidence in this project.

**Comment by Charius** [comment]
@connerbw the situation is really interesting, thanks for your comment. Maybe @troosan or @FBnil will clarify this for all of us.

**Comment by FBnil** [comment]
I have updated my profile picture accordingly.

**Comment by troosan** [comment]
Hi, indeed, I'm not as volubile as @FBnil :-) (thanks for the support BTW)
Anyway, I'm trying to go through the PR (there are a lot) and integrating the ones that can easily be merged and that do not risk breaking to much things.

As you can see I updated the copyright to 2010-2017, so I'm still hoping to publish 0.14 as a Christmas present!

After that I guess we'll have to have a release dedicated to all the nice changes done on the TemplateProcessor. I'm a bit nervous about those changes as there is virtually 0 unit tests covering that part.

**Comment by Charius** [comment]
@troosan thanks for your response, glad to see your answer!
