### ISSUE TITLE
How to add array in setValue(template) with(or without) foreach???

### ISSUE THREAD

**Issue by Ru4slan** [PHPOffice/PHPWord#1191]
I have a variable $ _POST ['text'] (text texarea).
After, I'm trying to convert this into an array of strings:
$ Nl_char = "\ n";
$ Obr = explode ($ nl_char $ _ POST ['text']);

With foreach, I'm trying to add this array to the document:
foreach ($arr as $line) {
$document->SetValue('text',$line);
}

But when foreach was first executed, $ {text} in the document changed to the first line, and the other lines were not added to the document.
How to add this array strings in document???

**Comment by FBnil** [comment]
There is no `\n` in xml, it need to be converted to `<w:br/>` (the equivalent of shift+enter) first:   
```
$lines = $_POST['text']; 
$lines = preg_replace('~\R~u', '</w:t><w:br/><w:t>', $lines);
```
(`/\R/u` is the unicode enter, which matches both unix and windows enters).

Then, in your document, you have 1 single `${text}`, and thus, can only be filled with 1 substitution. Using the br substitution, you can now forget the foreach and just `$document->SetValue('text',$lines);` once.
This feature has been added in several TemplateProcessor forks. So it is coming (beginning next year).

**Comment by Ru4slan** [comment]
@FBnil 
Fatal error: Class 'Settings' not found in Z:\home\wbbb.ru\WWW\adds.php on line 40
Maybe, i use old version PHPWord?

**Comment by Ru4slan** [comment]
@FBnil 
Same error on lastest version.

**Comment by Ru4slan** [comment]
@FBnil 
it is working, but if in textarea symbols like <>, russian letters from file, need htmlspecialchars, but if i put htmlspecialchars, this not work(((

**Comment by Ru4slan** [comment]
Thanks.
This work with

$lines = $_POST['texts']; 
$lines=htmlspecialchars($lines); 
$lines = preg_replace('~\R~u', '</w:t><w:br/><w:t>', $lines); 
Settings::setOutputEscapingEnabled(false); 
$document->SetValue('text',$lines); 
Settings::setOutputEscapingEnabled(true);

**Comment by Ru4slan** [comment]
Work with

$lines = $_POST['texts']; 
$lines=htmlspecialchars($lines); 
$lines = preg_replace('~\R~u', '</w:t><w:br/><w:t>', $lines); 
Settings::setOutputEscapingEnabled(false); 
$document->SetValue('text',$lines); 
Settings::setOutputEscapingEnabled(true);

**Comment by FBnil** [comment]
updated my answer. You are right, the escape needs to be done manually if you disable it.

**Comment by Ru4slan** [comment]
@FBnil 
For space in begin of text, needs this:
$lines = preg_replace('~\R~u', '</w:t><w:br/><w:t>', $lines); -it's your example
$lines = preg_replace('~\R~u', '<w:t><w:br/></w:t>', $lines); -its working
Only one / replace. Ha ha hah))))

**Comment by FBnil** [comment]
be careful with that code, I think it produces invalid ooxml (which the document programs auto-fix while reading in the file). Test it out on MSWord AND OpenOffice to be sure that they grok (accept) it.
