### ISSUE TITLE
[Question] How to read a doc file and split into a new document

### ISSUE THREAD

**Issue by brayann** [PHPOffice/PHPWord#1193]
We are going to build a split document feature, where the user can choose from and to which pages he wants to split into a new document.
Can I accomplish that with this library?

Thanks!

**Comment by FBnil** [comment]
Not with out-of-the-box features at the moment. Nobody has written a full section cloner.
Also, there is no concept of start of page. Yes, there is a pagebreak, but for example, a very long table can have "keep paragraph text together" enabled and suddenly the whole cell is on the next page (so it is not a matter of counting vertical pt's, which by itself is hard).
The only viable way I see is to convert the docx to pdf, then manipulate the pages (which is easy), and stitch a new pdf together. But once in pdf, you stay in pdf or you lose the layout. 
Now, you can combine the things, for example, fetch the text from a centain page in the pdf, and "know" that text belongs to that page, then go back to the docx and use that to extract, or remove that text (which could be in a table).

Maybe I am short-sighted, but afaik, there is no easy way.

**Comment by brayann** [comment]
Thanks @FBnil, and sorry for the late reply, saw it just now.

We ended up just supporting PDF anyway, which is what you kind of suggested.

Thanks!
