### ISSUE TITLE
How to create new Doc page.

### ISSUE THREAD

**Issue by Joseph-NC** [PHPOffice/PHPWord#1194]
I will like to know what method creates new page in the document.
I just need to add short content to page one, create page two and do the same and so on.
Is this possible with **PHPWord**?

**Comment by FBnil** [comment]
You need to add a [pagebreak](http://phpword.readthedocs.io/en/latest/elements.html?highlight=page%20break)

Please look into the source code, it contains useful examples.
```
$section->addPageBreak();
```
