### ISSUE TITLE
Wrong dompdf writer

### ISSUE THREAD

**Issue by bunnyhu** [PHPOffice/PHPWord#1195]
The PDF export function with domPDF is bugged.  The phpword have an old connection file to the dompdf library. 
Please modify the **\phpoffice\phpword\src\PhpWord\Writer\PDF\DomPDF.php**

line35: `protected $includeFile = 'src/Autoloader.php';`
line52:  `$pdf = new \Dompdf\Dompdf();`

Please do not forget to set the PDF rendering engine, before You use PDF in the IOFactory!

```
\PhpOffice\PhpWord\Settings::setPdfRendererPath($_SERVER['DOCUMENT_ROOT'].'/vendor/dompdf/dompdf');
\PhpOffice\PhpWord\Settings::setPdfRendererName(\PhpOffice\PhpWord\Settings::PDF_RENDERER_DOMPDF);
$objWriter = \PhpOffice\PhpWord\IOFactory::createWriter($objReader, 'PDF'); 
```

**Comment by troosan** [comment]
@bunnyhu, did you try this with the development branch? This should be fixed already in the upcomming version.

**Comment by bunnyhu** [comment]
@troosan Hi, nop, I am using composer that is load the master, but the code is different in the development banch. Actually I cannot want to suggest using dev version to my client. Who know what is unstable the in the dev branch :) But nice to see, in the next version this problem will be solved official!
