### ISSUE TITLE
Call to undefined method PhpOffice\\Common\\XMLWriter::writeText()"

### ISSUE THREAD

**Issue by metallurgical** [PHPOffice/PHPWord#1197]
Got this error when parse data from database to ms word. I'm using `dev-develop` when installing.
Here is the command used to install the package `composer require  "phpoffice/phpword:dev-develop"`.

When i check the stacktrace log, it coming from this line of code `<my-project-folder>/vendor/phpoffice/phpword/src/PhpWord/Writer/Word2007/Element/Text.php:46`

**Comment by kaur58** [comment]
i switched back to commit c9350d3 and the problem was gone ("phpoffice/phpword": "dev-develop#c9350d3")

**Comment by metallurgical** [comment]
@kaur58 never thought about that. Seems like everything working fine now. Thanks for pointing it out.

**Comment by troosan** [comment]
was my mistake, it was fixed already

**Comment by metallurgical** [comment]
@troosan thanks for information.
