### ISSUE TITLE
How could I replace a var or a block into table section or image section

### ISSUE THREAD

**Issue by sunchenweb** [PHPOffice/PHPWord#1198]
I want read a word file as a template, and replace vars in template into image section or a table section.
     now I make it by TemplateProcessor.setValue function, and let replace=a xml string made myself. the result of docx have many warnings,however,It can be opened.
     Is there any other ways?

**Comment by FBnil** [comment]
The warnings are that LibreOffice/MSWord tries to autofix malformed xml.
There are a few patches around that provide image insertions, just check the [pull request ](https://github.com/PHPOffice/PHPWord/pulls) area (there are 3 independent implementations).
Tables are easily inserted by doing a replaceBlock() as that cuts nicely at w:p borders, just make sure your xml starts with w:p then w:table.

Remember: setValue() is only to set text, no newlines, no xml, so you will need to use blocks

**Comment by sunchenweb** [comment]
table replaced success,how about images
`
namespace App\Http\Controllers\Test;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use PhpOffice\PhpWord\IOFactory;
use PhpOffice\PhpWord\PhpWord;
use PhpOffice\PhpWord\TemplateProcessor;

class WordTestController extends Controller
{
    //
    public function trans(){
        $phpWordHandle = new PhpWord();
        $section = $phpWordHandle->addSection();
        $table = $section->addTable();
        for ($r = 1; $r <= 8; $r++) {
            $table->addRow();
            for ($c = 1; $c <= 5; $c++) {
                $table->addCell(1750)->addText("Row {$r}, Cell {$c}");
            }
        }
        $objWriter =  IOFactory::createWriter($phpWordHandle);
        $fullXml = $objWriter->getWriterPart('Document')->write();
        $TemplateProcessor = new TemplateProcessor(storage_path().'\word\template\222.docx');
        //dd($this->getBodyBlock($fullXml));
        $TemplateProcessor->replaceBlock('tag_999',$this->getBodyBlock($fullXml));
        $TemplateProcessor->saveAs(storage_path().'\word\report\test1.docx');
    }
    protected function getBodyBlock($string){
        if (preg_match('%(?i)(?<=<w:body>)[\s|\S]*?(?=</w:body>)%', $string, $regs)) {
            return $regs[0];
        } else {
            return '';
        }
    }
}
`

**Comment by FBnil** [comment]
for images, check out https://github.com/PHPOffice/PHPWord/pull/1084

**Comment by icy2003** [comment]
> table replaced success,how about images
> 
> ```
> namespace App\Http\Controllers\Test;
> use Illuminate\Http\Request;
> use App\Http\Controllers\Controller;
> use PhpOffice\PhpWord\IOFactory;
> use PhpOffice\PhpWord\PhpWord;
> use PhpOffice\PhpWord\TemplateProcessor;
> 
> class WordTestController extends Controller
> {
>     //
>     public function trans(){
>         $phpWordHandle = new PhpWord();
>         $section = $phpWordHandle->addSection();
>         $table = $section->addTable();
>         for ($r = 1; $r <= 8; $r++) {
>             $table->addRow();
>             for ($c = 1; $c <= 5; $c++) {
>                 $table->addCell(1750)->addText("Row {$r}, Cell {$c}");
>             }
>         }
>         $objWriter =  IOFactory::createWriter($phpWordHandle);
>         $fullXml = $objWriter->getWriterPart('Document')->write();
>         $TemplateProcessor = new TemplateProcessor(storage_path().'\word\template\222.docx');
>         //dd($this->getBodyBlock($fullXml));
>         $TemplateProcessor->replaceBlock('tag_999',$this->getBodyBlock($fullXml));
>         $TemplateProcessor->saveAs(storage_path().'\word\report\test1.docx');
>     }
>     protected function getBodyBlock($string){
>         if (preg_match('%(?i)(?<=<w:body>)[\s|\S]*?(?=</w:body>)%', $string, $regs)) {
>             return $regs[0];
>         } else {
>             return '';
>         }
>     }
> }
> ```

how to set "tag_999" in a <w:p> block, I tried your function and my variable is surrounded by <w:t>
