### ISSUE TITLE
addPreserveText in TextRun

### ISSUE THREAD

**Issue by dodlhuat** [PHPOffice/PHPWord#1199]
As I would need a footer with a logo on the left, and two lines of text on the right (while the second one would be page and number) I would need to add preserveText into a TextRun which seems to be impossible. Or do I get something wrong?
I tried to work with fields instead, but this is only causing an error to pop up.

**Comment by troosan** [comment]
with which version are you trying? Can you post your code with fields, this should work normally.

**Comment by troosan** [comment]
@dodlhuat did you manage to make it work? If so, can you close this issue?
