### ISSUE TITLE
something wrong when use replace_block

### ISSUE THREAD

**Issue by sunchenweb** [PHPOffice/PHPWord#1201]
This error was happend on office 2016.
When use replace_block in TemplateProcessor, it didn't work.And when I opened document.xml,find something like this.
```
<w:p w:rsidR="00197886" w:rsidRDefault="00197886" w:rsidP="00197886">
    <w:bookmarkStart w:id="0" w:name="_GoBack"/>
    <w:r>
        <w:t>${</w:t>
    </w:r>
    <w:proofErr w:type="spellStart"/>
    <w:r>
        <w:t>block_table</w:t>
    </w:r>
    <w:proofErr w:type="spellEnd"/>
    <w:r>
        <w:t>}</w:t>
    </w:r>
</w:p>
<w:p w:rsidR="00197886" w:rsidRDefault="00197886" w:rsidP="00197886">
    <w:r>
        <w:t>${/</w:t>
    </w:r>
    <w:proofErr w:type="spellStart"/>
    <w:r>
        <w:t>block_table</w:t>
    </w:r>
    <w:proofErr w:type="spellEnd"/>
    <w:r>
        <w:t>}</w:t>
    </w:r>
</w:p>
```
What shall I do to fix it?

**Comment by FBnil** [comment]
That seems to have  `${block_table}` EMPTY  `${/block_table}` and the blocks SHOULD have been replaced, but there is nothing inside the blocks to select. Do not worry about the tags being in separate w:t, this is "fixed" by fixBrokenMacros().

The regexp has proven to not be all too reliable (missing `\b` for example). Unfortunately, I have misplaced my fixed regexp.

If you need a solution fast, try my updated [TemplateProcessor](https://raw.githubusercontent.com/FBnil/PHPWord/templates/src/PhpWord/TemplateProcessor.php) (just rename the one in your ./vendor/ to .old and replace it with this one), else, could you create a small document and procedure how you make it
