### ISSUE TITLE
Table border not showing when generate docx from html

### ISSUE THREAD

**Issue by lvc2202** [PHPOffice/PHPWord#1208]
It's urgent, pls help me

**Comment by FBnil** [comment]
Your request is too terse. Version of php, version of phpword, platform etc.
Are you using 
` "phpoffice/phpword": "dev-master",` in your composer.json?
How do you style the tables? do you have a minimal html example?

**Comment by lvc2202** [comment]
Nevermine, I found the problem. It's because of the ckeditor auto generated <table border="1"> instead of <table style="border 1px solid black">. Thanks anyway ^_^
