### ISSUE TITLE
Bullet list and number styling didn't apply when generate docx.

### ISSUE THREAD

**Issue by lvc2202** [PHPOffice/PHPWord#1210]
I already put style="font-weight:bold;" but it's not working when generate it into docx.
Any idea ?

**Comment by FBnil** [comment]
Similar to https://github.com/PHPOffice/PHPWord/issues/1163  (contains do-it-yourself solution)
I do not have much time at the moment, but I'll try for a patch next month.

**Comment by lvc2202** [comment]
But I using addhtml function to do it. I mean I using the html coding to generate contents like this which has bullet list, table and so on.

**Comment by FBnil** [comment]
@lvc2202 Then it might be a good idea to list a small program on how you can reproduce the bug so somebody can run it and take a look at it, something like:

```php
Route::get('/test_bullet_html', function () {
        $phpWord = new \PhpOffice\PhpWord\PhpWord();
        $section = $phpWord->addSection();
        #$textBox = $phpWord->addT();
        $htmlStr = '<html><body><p><ul><li>one</li></ul></p></body></html>';
        HTMLParser::addHtml($section, $htmlStr, true);
        dd($section);

        $objWriter = \PhpOffice\PhpWord\IOFactory::createWriter($phpWord, 'Word2007');
        $objWriter->save(storage_path('app/public/letable.docx'));
        return response()->download(storage_path('app/public/letable.docx'))->deleteFileAfterSend(true);
});
```

**Comment by lvc2202** [comment]
Nevermine, it has been fixed by the commited code now.

**Comment by alexcodeZ** [comment]
Lo que uso yo para generar viñetas en una plantilla, es el siguiente código, espero que les sirva a las personas que empiecen a buscar esto nuevamente. 
`// datos de los productos
		$nombre_productos ="";
		foreach ($Detalle as $det){
			$nombre_productos = $nombre_productos."<w:p><w:pPr><w:pStyle w:val='OurStyle2'/></w:pPr><w:r><w:t xml:space='preserve'>". "• ".$det->nombre."</w:t></w:r></w:p>";
		}
$templateWord->setValue('nombre_productos',$nombre_productos);
`
