### ISSUE TITLE
Formatting in lists via addHtml

### ISSUE THREAD

**Issue by rkorebrits** [PHPOffice/PHPWord#1215]
We are having a few issues with formatting in lists. After seeing this issue: https://github.com/PHPOffice/PHPWord/issues/945 I updated composer to take from the `develop` branch, but we are still not able to get formatting in lists.

I don't know how the documents are actually built up and maybe it is not possible to have formatting in lists, but as the documents otherwise are able to be styled perfectly and it's possible in Word to style lists, I would assume that is would be doable?

# Expected Behavior

Ideally, lists with formatting (e.g. `<strong>`, `<em>`, `<br>`, etc.) would also be displayed like this in the Word output. Like this:

- **I am bolded.** 
   and I am not
- _I am italic_  and I am not

# Current Behavior

On the develop branch all formatting is stripped. On the 0.13 branch, formatted copy is removed completely. 

## Context

* PHP version: 7.1
* PHPWord version: 0.13/develop

**Comment by troosan** [comment]
@rkorebrits Indeed, that's a known issue with lists, the formatting is currently lost.
The only improvement in the develop branch is that at least the text is kept, whereas before it was not.

**Comment by rkorebrits** [comment]
Thanks @troosan 
Would this be something that might be added in the near future? Not sure what the impact there is..

**Comment by samimussbach** [comment]
I do not know your release policy but wouldn't this be a reason for a new release 0.13.1? People are loosing data quite subtly (at least if they use phpword as a kind of export).
Would it be possible to release a 0.13.1 with the fix that texts in lists are at least not silently vamishing?

**Comment by troosan** [comment]
0.14 will be release soon. I haven't had the time to work on parsing the list items styling.
Feel free to submit a pull request if you have a solution for it. I would be happy to review it and merge it to the main development branch!

**Comment by rkorebrits** [comment]
I'd love to spend time on this great project, but unfortunately I won't be able to in the foreseeable future. Thanks @troosan

**Comment by samimussbach** [comment]
Good news that 0.14 is near. I hope to find the time to work on a patch but I don't really understand yet what happens during the recursive parsing and the exact need for an extra Html::parseListItem()

**Comment by troosan** [comment]
fixed with #1239

**Comment by samimussbach** [comment]
I can confirm that your fix works with our data, Thank you!

**Comment by rkorebrits** [comment]
Also confimed
