### ISSUE TITLE
XML Parsing error; Location: Part: /word/document.xml, Line:0, Column:2

### ISSUE THREAD

**Issue by dvdutra** [PHPOffice/PHPWord#1216]
Hello,

I'm using this library to generate .docx documents from my php application. But I keep getting a XML error and can't open the document on Microsoft Office Word. The error is: XML Parsing error occurs; Location: Part: /word/document.xml, Line:0, Column:2.

I can't figure it out what is happening, already tried htmlspecialchars() on my html texts, but then the document won't come with the tables, paragraphs, images, etc. Just the plain code text and that's not what I need.

Does someone know how to fix it?

**Comment by troosan** [comment]
@dvdutra As the template asked, can you provide a sample code, or the generated document that fails to open.

Try to unzip the docx (rename it to *.zip) and check the content of the xml file.

**Comment by josh-oiknine** [comment]
I was getting this error when adding a row to my table but not adding any columns into that row. I would check that first.

**Comment by troosan** [comment]
No response
