### ISSUE TITLE
the name in the end tag of the element must match the element type in the start tag

### ISSUE THREAD

**Issue by luisorozcomlv** [PHPOffice/PHPWord#1218]
sorry, this is my first post on githb...

# Expected Behavior
Create a new document from another docx file using template processor

# Current Behavior

working fine, no error reportes durning script execution

# Failure Information

When i try to open the result docx file i got this error:

the name in the end tag of the element must match the element type in the start tag:

Location: Part: /word/document.xml Line 2: Column: 

## How to Reproduce

$template = new \PhpOffice\PhpWord\TemplateProcessor("dictamTpl.docx");            

foreach($onlyOneRow as $n => $c)
{
	
$c = xmlEntities($c);
$template->setValue($n, $c);
$template->setValue(strtoupper($n), $c); 
}   

$template->saveAs('result.docx'); 

## Context

* PHP version:
* PHPWord version: 0.13
PHP 5.6
CentOS 7
Dedicated Server

**Comment by luisorozcomlv** [comment]
I tried without any setValue, only reading and saving the document, but still got the same error.

**Comment by troosan** [comment]
@luisorozcomlv can you share the document (or any other document) that makes this fail?

**Comment by luisorozcomlv** [comment]
https://www.mlv.com.mx/downloads/Archive.zip

**Comment by troosan** [comment]
@luisorozcomlv I don't know if that's the cause of the issue but if you check the source (rename to dictamTpl.zip and unzip) you will see that the ${acciondenominada}, ${fechajuntaaclaratotia}, ... are split over multiple xml nodes.
This causes the replacement to fail. Fix this in the source document I'm pretty sure it will be OK.

**Comment by luisorozcomlv** [comment]
It works!. Thank you. BTW, i also change the isolated $ chars to it html entity.
