### ISSUE TITLE
Incorrect definition of bold text

### ISSUE THREAD

**Issue by ursaevandrey** [PHPOffice/PHPWord#1219]
`<w:b w:val="0"/>` don't display as bold text in MSWord, but when reading from docx file `Style\Font::isBold()` is `true`

* PHP version: 7.1.11
* PHPWord version: 0.14
![screenshot](https://user-images.githubusercontent.com/7485190/33789561-31469faa-dc9b-11e7-9a2b-8b9f6ec63b03.jpg)

**Comment by troosan** [comment]
indeed, problem is in PhpOffice\PhpWord\Reader\Word2007\AbstractPart->readStyleDef

as soon as the node exists it considers it to be true. It should actually check the value of the w:val attribute. It should only return `true`if the attribute is not 0 or false

**Comment by ursaevandrey** [comment]
@troosan Thank you for answer. I did my task another way (removed text formatting in MSWord). I didn't want modified code of your library, but I think this bugfix need to add in next version.
