### ISSUE TITLE
zendframework libs dependencies outdated

### ISSUE THREAD

**Issue by ywarnier** [PHPOffice/PHPWord#1224]
Hi team,

In composer.json, you are setting a relatively strict requirement on zendframework libs to be 2.4.*

https://github.com/PHPOffice/PHPWord/blob/7c256b53442ea0c229163216b27f362fa86199ba/composer.json#L37-L39

This prevents smooth inclusion of PHPWord in environments where version >2.4 are required. Is there any specific reason for that?

Would it be feasible to have a new stable release allowing for "~2.4" (all 2.* versions superior to 2.4) rather than "2.4.*"?

**Comment by ywarnier** [comment]
I see that the develop branch has it updated to 

https://github.com/ywarnier/PHPWord/blob/3e6745f14697d74b74e8d3ab9af670c8fad2ee3f/composer.json#L51-L52

But somehow the master branch and the latest stable release (now more than a year old) doesn't...

**Comment by troosan** [comment]
I’ll release 0.14 before the end of the year, so no need :-)

**Comment by ywarnier** [comment]
:+1:
