### ISSUE TITLE
HTML plain characters from DB to DOCX

### ISSUE THREAD

**Issue by henryseron** [PHPOffice/PHPWord#1229]
Hello Everybody,

I am modifying an e-commerce website. The product description is stored in the database as follow:

```
&#60;p&#62;Product description&#60;/p&#62;
```

As you can see above, the HTML code is stored as plain characters. When I take this info from the DB and use it to create the docx document, the text in the Word document is shown as HTML code:
```
<p>Product description</p>
```

I already tried with different functions: html_entity_decode, htmlentities, htmlspecialchars. Maybe I am using them in the wrong order or just I am doing it in the wrong way.

Any ideas how to convert those characters  to readable text in the Word document?

Thanks.

**Comment by troosan** [comment]
@henryseron please ask questions on [StackOverFlow](https://stackoverflow.com/questions/tagged/phpword)
GitHub is to report issues.

**Comment by troosan** [comment]
@henryseron have you tried 
```php
\PhpOffice\PhpWord\Shared\Html::addHtml($section, $html);
```

**Comment by henryseron** [comment]
@troosan I tried using \PhpOffice\PhpWord\Shared\Html::addHtml($section, $html); but the DB has no HTML code, so I got an error when I opened the docx file.

**Comment by henryseron** [comment]
@troosan I just solved the problem. I used \PhpOffice\PhpWord\Shared\Html::addHtml($section, html_entity_decode($html));
Thanks

**Comment by juniorriau** [comment]
@henryseron hi, can you share the detail? I new in PHP Office/PHPWord. i want wrote a word document from my web app

my code is
`$row = $this->Speech_model->get_by_id($id);
        
        $phpWord = new \PhpOffice\PhpWord\PhpWord();
        $section = $phpWord->addSection(array('paperSize' => 'A5'));
        // Adding Text element to the Section having font styled by default...

        /*
         * Note: it's possible to customize font style of the Text element you add in three ways:
         * - inline;
         * - using named font style (new font style object will be implicitly created);
         * - using explicitly created font style object.
         */

        // Adding Text element with font customized inline...
        $section->addText($row->title,
            array('name' => 'Times New Roman', 'size' => 12)
        );
   
     
        // Saving the document as OOXML file...
        $objWriter = \PhpOffice\PhpWord\IOFactory::createWriter($phpWord, 'Word2007');
        $objWriter->save($row->title.".docx");`

the html in $row->content, input from CKEditor

so where i can put the 
`\PhpOffice\PhpWord\Shared\Html::addHtml($section, html_entity_decode($row->content));`

thanks
