### ISSUE TITLE
Table attribute align center not working when convert from html to docx

### ISSUE THREAD

**Issue by lvc2202** [PHPOffice/PHPWord#1230]
I'm using ckeditor to generate some text for generate a docx.
When I used ckeditor to generate table, it shows as below:
`<table align="center" border="0" cellpadding="0" cellspacing="0" style="width:251px">`

The data can be output but the table can't align to center.

Pls help me, urgent.
Thank you.

**Comment by troosan** [comment]
@lvc2202 try with style="text-align: center"
currently only in dev-master version

**Comment by lvc2202** [comment]
style="text-align: center" is working but I want the whole table align to center of page and td contents maintain align to left. 
Text align is working in style attribute but align attribute itself is not working for table tag.
Is there any way to make the whole table align to center of the page?

**Comment by troosan** [comment]
@lvc2202 did you try setting the alignment on the parent paragraph?

**Comment by lvc2202** [comment]
```
<p style="text-align:center">
<table><tr><td>test</td></tr></table>
</p>
```
Tried before, getting error in the end because it doesn't allow table tag inside of the paragraph tag.
Ckeditor also auto correct the table tag inside the paragraph tag and seperate them out like below:
```
<p style="text-align:center"></p>
<table><tr><td>test</td></tr></table>
<p></p>
```

**Comment by lvc2202** [comment]
I noticed the code below is able to get the table attribute value but it doesn't apply the alignment attribute to the docx.
<table **align="center"** border="0" cellpadding="0" cellspacing="0" style="width:251px">

```
if ($attributes->getNamedItem('align') !== null) {
            $newElement->setAlignment($attributes->getNamedItem('align')->value);
}

use PhpOffice\PhpWord\SimpleType\Jc;
public function setAlignment($value)	
    {	
        if (Jc::isValid($value)) {
            $this->alignment = $value;	
        }		
        return $this;	
    }
```

**Comment by lvc2202** [comment]
Nevermine, I have solved it by changing the parseTable function.
Now if got any attribute in the table tag then it will get the attribute value and apply it in style.
```
private static function parseTable($node, $element, &$styles)
    {
        $attributes = $node->attributes;
        
        if ($attributes->getNamedItem('align') !== null) {
             $styles['table'] = array('align'=>$attributes->getNamedItem('align')->value);
        }
        $elementStyles = self::parseInlineStyle($node, $styles['table']);
        $newElement = $element->addTable($elementStyles);
        return $newElement;
    }
```

**Comment by troosan** [comment]
It's too late for release 0.14, but I'll try to include a fix for this in the next one

**Comment by lvc2202** [comment]
Thank you for your contribution. Looking forward to the next release.
