### ISSUE TITLE
addListItem bullet is NOT RTL on Word2007

### ISSUE THREAD

**Issue by mirr** [PHPOffice/PHPWord#1232]
```
<?php 
...

$section->addListItem('List Item 1', 0, array('rtl' => true), null, array('alignment' => \PhpOffice\PhpWord\SimpleType\Jc::END));
$section->addListItem('List Item 2', 0, array('rtl' => true), null, array('alignment' => \PhpOffice\PhpWord\SimpleType\Jc::END);
$section->addListItem('List Item 3', 0, array('rtl' => true), null, array('alignment' => \PhpOffice\PhpWord\SimpleType\Jc::END);
```

When saving to docx file, the list item is not displaying the bullet to RTL, instead it displays like this:
•   List Item 1
•   List Item 2
•   List Item 3

How can I display it like this one:
List Item 1    •
List Item 2    •
List Item 3    •

Thanks!

**Comment by troosan** [comment]
@mirr you need to set the bidirectional element ("bidi") to true
```php
$section->addListItem('List Item 1', 0, null, null, array('bidi' => true, 'alignment' => \PhpOffice\PhpWord\SimpleType\Jc::END));
$section->addListItem('List Item 2', 0, null, null, array('bidi' => true, 'alignment' => \PhpOffice\PhpWord\SimpleType\Jc::END));
```

**Comment by peterramsis** [comment]
@troosan  thanks

**Comment by Chetan-citrusbug** [comment]
I am using TOC to set indexing.
I have to make that doc as HEBREW, So I also need to make that bidirectional.
I have tried many thing but not working. Any Idea How to make that?
