### ISSUE TITLE
[solved] Sample_26_Html.php png type, image's color is black or gray

### ISSUE THREAD

**Issue by agang235** [PHPOffice/PHPWord#1234]
#This is:
- [x] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpword)

# Expected Behavior

Please describe the behavior you are expec

ting.

### Current Behavior

use Sample_26_Html.php

### Failure Information
color is error
Sample_26_Html.php inster png file, image's color is black or gray

### How to Reproduce
![phpword](https://user-images.githubusercontent.com/25738075/34463929-226e77fa-eea7-11e7-9a2e-74c62f18efa7.png)

Please provide a code sample that reproduces the issue.
This is the full code
```php
<?php
include_once 'Sample_Header.php';

// New Word Document
echo date('H:i:s') , ' Create new PhpWord object' , EOL;
$phpWord = new \PhpOffice\PhpWord\PhpWord();

$section = $phpWord->addSection();
$html = '<h1>Adding element via HTML</h1>';

            // http://tikuimgs.oss-cn-qingdao.aliyuncs.com/tikuimg/q_500004/e/12/14/01/fdba95731ac4.png success but black
            // http://tikuimgs.oss-cn-qingdao.aliyuncs.com/tikuimg/q_500014/a/09/05/38/a8bed5b3cc.gif success
            // http://tikuimgs.oss-cn-qingdao.aliyuncs.com/tikuimg/q_500004/e/12/15/58/7c8e2b8413ad.png success but gray
$html .= '
<img src="http://tikuimgs.oss-cn-qingdao.aliyuncs.com/tikuimg/q_500014/a/09/05/38/a8bed5b3cc.gif" style="vertical-align:middle;"/>
<img src="http://php.net/images/logos/php-med-trans-light.gif" style="vertical-align:middle;"/>
<img src="http://tikuimgs.oss-cn-qingdao.aliyuncs.com/tikuimg/q_500004/e/12/14/01/fdba95731ac4.png" style="vertical-align:middle;"/>
<img src="http://tikuimgs.oss-cn-qingdao.aliyuncs.com/tikuimg/q_500004/e/12/15/58/f184c399cd43.png" style="vertical-align:middle;"/>
<img src="http://tikuimgs.oss-cn-qingdao.aliyuncs.com/tikuimg/q_500004/e/12/15/58/7c8e2b8413ad.png" style="vertical-align:middle;"/>
';

\PhpOffice\PhpWord\Shared\Html::addHtml($section, $html, false, true);

// Save file
echo write($phpWord, basename(__FILE__, '.php'), $writers);
if (!CLI) {
    include_once 'Sample_Footer.php';
}


```

### Context

* PHP version: 5.5.38 
* PHPWord version: 0.14

**Comment by troosan** [comment]
This might be solved by PR #779
Could you check?

**Comment by agang235** [comment]
@troosan Think you very mach, and i test success for it 
![image](https://user-images.githubusercontent.com/25738075/34464614-d2f2e0ce-eec1-11e7-9d5f-1c30c085b95d.png)

**Comment by troosan** [comment]
Perfect, I’ll try to include this in the next release
