### ISSUE TITLE
Broken documentation link for API Documentation in readme.md

### ISSUE THREAD

**Issue by pink6440** [PHPOffice/PHPWord#1236]
This is:

- [x] a bug report
- [ ] a feature request
- [x] **not** a usage question
# Expected Behavior

When clicking on the API Documentation link : going to the documentation page

### Current Behavior

http://phpoffice.github.io/PHPWord/docs/master/ => Github Page not found

**Comment by troosan** [comment]
@pink6440 thanks, this documentation has indeed been retired. I removed the link
