### ISSUE TITLE
HTML parser does not parse col-xs-* attributes

### ISSUE THREAD

**Issue by rebbieboi** [PHPOffice/PHPWord#1241]
This is:

- [ ] a bug report
- [x] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpword)

# Expected Behavior

Please describe the behavior you are expecting.

### Current Behavior

What is the current behavior?

col-xs-* is not being followed so output format is not as expected

Please help provide information about the failure.

Generate .docx file using this sample code as a reference:
https://github.com/PHPOffice/PHPWord/blob/develop/samples/Sample_26_Html.php

Please provide a code sample that reproduces the issue.

```
<section>
	<div class="row">
    	<div class="col-xs-12" data-type="container-content">
        	<section data-type="component-photo">
    			<div class="photo-panel">
        		</div>
        	</section>
        </div>
    </div>
</section>
<section>
	<div class="row">
        <div class="col-xs-6" data-type="container-content">
    	    <section data-type="component-text"><p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Porro labore architecto fuga tempore omnis aliquid, rerum numquam deleniti ipsam earum velit aliquam deserunt, molestiae o<span style="color:#00FFFF;">fficiis mollitia accusantium suscipit fugiat esse magnam eaque cumque, iste corrupti magni? Illo dicta saepe, maiores fugit aliquid consequuntur aut, rem ex iusto dolorem molestias obcaecati eveniet vel voluptatibus recusandae illum, voluptatem! Odit est possimus nesciunt.</span></p>
			</section>
		</div>
        <div class="col-xs-6" data-type="container-content">
        	<section data-type="component-text"><h2><span style="color:#FF8C00;"><span style="font-family:comic sans ms,cursive;"><strong>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Porro labore architecto fuga tempore omnis aliquid, rerum numquam deleniti ipsam earum velit aliquam deserunt, molestiae officiis mollitia accusantium suscipit fugiat esse magnam eaque cumque, iste corrupti magni? Illo dicta saepe, maiores fugit aliquid consequuntur aut, rem ex iusto dolorem molestias obcaecati eveniet vel voluptatibus recusandae illum, voluptatem! Odit est possimus nesciunt.</strong></span></span></h2>
			</section>
		</div>
    </div>
</section>
```

### Context

* PHP version: 5.6
* PHPWord version: 0.14

**Comment by troosan** [comment]
Indeed, this is not implemented yet. To generate a table you currently have to use <table>, not <div>.

**Comment by rebbieboi** [comment]
No wonder I wasn't able to find any document relating to it. Will you be able to point me to your documentation for PDF to Word?

I'm having a hard time finding it. Or is it supported?

Thank you

**Comment by troosan** [comment]
we do not support parsing PDF to word.

**Comment by rebbieboi** [comment]
Thank you. I'll just find a way to convert div to table when converting to word.
