### ISSUE TITLE
Unit testing methods

### ISSUE THREAD

**Issue by vpratfr** [PHPOffice/PHPWord#1245]
This is:

- [ ] a bug report
- [x] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpword)

I was wondering if you had any recommendations about how we can go about testing the documents which are produced. Like asserting that the document contains some text, a table, etc.

**Comment by troosan** [comment]
There is nothing in the library itself, but if you check the test classes, you will find in tests/PhpWord/_includes class TestHelperDOCX
```php
        $doc = TestHelperDOCX::getDocument($phpWord, 'Word2007');
        $this->assertTrue($doc->elementExists('/w:document/w:body/w:p/w:r/w:rPr/w:u'));
        $this->assertEquals('single', $doc->getElementAttribute('/w:document/w:body/w:p/w:r/w:rPr/w:u', 'w:val'));
```
Maybe you can find some inspiration from that.
