### ISSUE TITLE
Image src as base64 is not working

### ISSUE THREAD

**Issue by rebbieboi** [PHPOffice/PHPWord#1246]
This is:

- [x] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpword)

# Expected Behavior

Should display the image

### Current Behavior

Image is not displayed

### Failure Information
 I get this errors instead:
Uncaught PhpOffice\PhpWord\Exception\InvalidImageException: Invalid image: data:image/jpeg;base64,/9j/4AAQSkZJRgABAgEAYABgAAD/7gAOQWRv.....

Please help provide information about the failure.

### How to Reproduce
I am using a base64 image

### Context

* PHP version: 7
* PHPWord version: 0.14

**Comment by troosan** [comment]
can you give a code sample that reproduces the issue?
I think you should strip out the first part of the string (data:image/jpeg;base64,) which is not part of the base64 encoded data.

**Comment by rebbieboi** [comment]
I had to change my approach since using base64 as an image source was not resource friendly. Though there seems to be a problem when img tag is not closed. Is there a fix for this instead or do I have to manually close the img tag which would be tricky for my part since the content is PHP generated.

**Comment by troosan** [comment]
@rebbieboi right now, as we are loading XML and not HTML, the tag needs to be closed as otherwise it is not valid XML.

**Comment by rebbieboi** [comment]
@troosan Thank you for that information. :) Last question if you don't mind. How can I set default dimensions for the content generated from an HTML source? Images tend to take a full 100% width meaning it won't sometimes fit.

**Comment by troosan** [comment]
when you addHTML, you add it to a container. I guess if you set a fixed with to that container the content should not be wider than that.

**Comment by padre** [comment]
@rebbieboi Have you been able to fix it?

 I have the same problem with img base64:

"Invalid image: data:image/png;base64,iVBORw0..."

**Comment by freretuc** [comment]
I've find better : No need to update Image.php & AbstractWriter.php
In the function parseImage in HTML.php
`    private static function parseImage($node, $element)`
`    {`
`        $style = array();`
`        $src = null;`
`        foreach ($node->attributes as $attribute) {`
`            switch ($attribute->name) {`
`                case 'src':`
`                    $src = $attribute->value;`
`                    if(preg_match('/^(.*base64,)/m', $src)) {`
`                      $src = base64_decode(preg_replace('/^(.*base64,)/m', '', $src));`
`                    }`
`                    break;`

**Comment by troosan** [comment]
@freretuc was this not fixed with #1382
