### ISSUE TITLE
 Failed to load a docx file

### ISSUE THREAD

**Issue by NewPoow** [PHPOffice/PHPWord#1250]
This is:

- [x] a bug report

# Expected Behavior

An error occurs when calling the function 
```php 
$phpWord->setDefaultParagraphStyle();
```
 in the "PhpOffice\PhpWord\Reader\Word2007\Styles.php" file at line 59 for missing an ``` $paragraphDefaultStyle ``` argument.

Please include this argument to fix the bug.

**Comment by troosan** [comment]
good catch
