### ISSUE TITLE
phpWord fails to load/read docx files created in office 365.

### ISSUE THREAD

**Issue by vickya1** [PHPOffice/PHPWord#1253]
This is:

- [x] a bug report
- [x] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpword)

A word document (.docx) created via the desktop will be resolved as a `document.xml`.  

Whereas a word document (.docx) created via office 365 will be resolved as `document22.xml`.

In function `TemplateProcessor::getMainPartName` returns the fixed name of `word/document.xml` which leads to `ZipArchive::getFromName` failing to get the file xml content.

Instead `TemplateProcessor::getMainPartName` could potentially use regex to cater `22` in the name incase this changes.

* PHP version: 5.6 & 7.1
* PHPWord version: 0.13 & 0.14

**Comment by troosan** [comment]
can you attach a sample document? I don't have an office 365 account.

**Comment by vickya1** [comment]
[Office365DocExample.docx](https://github.com/PHPOffice/PHPWord/files/1711559/Office365DocExample.docx)

**Comment by troosan** [comment]
Thanks, indeed, I guess the best way would be to read the file names from [Content_Types].xml instead of hardcoding it.
