### ISSUE TITLE
image width not set

### ISSUE THREAD

**Issue by nicdnepr** [PHPOffice/PHPWord#1254]
This is:

a bug report

# Expected Behavior

docx with table, one column with image with fixed width

### Current Behavior

image with full size

### How to Reproduce

Please provide a code sample that reproduces the issue.

```php
<?php
require __DIR__ . '/vendor/autoload.php';

$phpWord = new PhpWord();
        $section = $phpWord->addSection();
        \PhpOffice\PhpWord\Shared\Html::addHtml($section, '<table style="width:100%"><tr><td><img src="https://www.gettyimages.ca/gi-resources/images/Homepage/Hero/UK/CMS_Creative_164657191_Kingfisher.jpg" style="width: 20px;"/></td><td>text</td></tr></table>');

        $objWriter = \PhpOffice\PhpWord\IOFactory::createWriter($phpWord, 'Word2007');
        $objWriter->save($docx);
```

### Context

* PHP version: 7
* PHPWord version: 0.14

**Comment by sergeizelenyi** [comment]
maybe you can help set:

src/PhpWord/Style/Image.php
` $this->setUnit(self::UNIT_PX) instead of $this->setUnit(self::UNIT_PT);`

in the previous release there was : `px`
in 0.14 it could be a mistake: `pt`

P.S. translate.google :(

**Comment by troosan** [comment]
Indeed, this is due to the fix for #224
To fix this, try to change PhpWord/Shared/Html::parseImage and add the following in the case for width and height
```php
    $style['unit'] = \PhpOffice\PhpWord\Style\Image::UNIT_PX;
```
Please tell me if that fixes the issue.

**Comment by sergeizelenyi** [comment]
> Please tell me if that fixes the issue.

resolve in my case

**Comment by troosan** [comment]
@sergeizelenyi great, I'll include a fix in the next release

**Comment by simogeo** [comment]
It seems i still have a similar issue using phpWord v0.16

Please see : https://stackoverflow.com/questions/57867641/controling-image-size-with-addhtml-from-phpword-0-16-library

Any idea ?

**Comment by simogeo** [comment]
Please, any clue regarding this ?

**Comment by simogeo** [comment]
I expected php-word to interpret width value from `style` attribute. It seems, it is not the default behavior.

Actually, to solve my issue, I just remove my style attribute dynamically and add a `width` attribute to img tag using [SimpleHTMLDOM](https://simplehtmldom.sourceforge.io/manual.htm#section_access).
