### ISSUE TITLE
addHtml list items get incorrect paragraph space

### ISSUE THREAD

**Issue by rkorebrits** [PHPOffice/PHPWord#1260]
This is a bug report

# Expected Behavior

I'm expecting the same result as when create a Word doc from MS Word, i.e. no added space to list items be default.

### Current Behavior

When adding HTML containing a list (`ol`/`ul`) via `addHtml`, the list items get unnecessary spacing added to it. Looking at the code:

phpoffice/phpword/src/PhpWord/Shared/Html.php:437

    $listRun = $element->addListItemRun($data['listdepth'], $styles['list'], $styles['paragraph']);

It looks like the paragraph styles get added to the list items (which is wrong imo), resulting in:

![image](https://user-images.githubusercontent.com/3765592/35502707-81e1f004-04e6-11e8-97bc-b8d65c344e5d.png)

Whereas the correct output would be:

![image](https://user-images.githubusercontent.com/3765592/35502741-9edd8c5e-04e6-11e8-8b49-63abfb6b03ff.png)

It would be great if we could set global styles for list items, which I don't think is possible currently, so instead of applying `$styles['paragraph']`, we could apply `$styles['listItem']`

### Context

* PHP version: 7.1
* PHPWord version: dev-devlop

**Comment by troosan** [comment]
can you provide an example? Running the Sample_26_Html.php sample I do not have this extra spacing.

**Comment by rkorebrits** [comment]
From Sample 26, I just removed some stuff, I used this:

    public function runTest(){
        $phpWord = new \PhpOffice\PhpWord\PhpWord();
        $section = $phpWord->addSection();
        $html = '<h1>Adding element via HTML</h1>';
        $html .= '<ul><li>Item 1</li><li>Item 2</li><ul><li>Item 2.1</li><li>Item 2.1</li></ul></ul>';

        \PhpOffice\PhpWord\Shared\Html::addHtml($section, $html, false, false);
        // Save file

        $objWriter = \PhpOffice\PhpWord\IOFactory::createWriter(
            $phpWord, 'Word2007'
        );

        $file_path_docx = 'test_bullets.docx';

        $objWriter->save($file_path_docx);
    }

Results in 

![image](https://user-images.githubusercontent.com/3765592/35971808-172be360-0cd8-11e8-9ed1-45729ff17a9d.png)

in  MS Word

**Comment by troosan** [comment]
for me it results in 
![image](https://user-images.githubusercontent.com/6959414/36037052-dfb00972-0dbb-11e8-80e3-52591678187a.png)
I'm using latest dev-develop branch, and am using Word 2016

**Comment by rkorebrits** [comment]
Hmm weird, can you please send me your document and check mine:

[test_bullets.docx](https://github.com/PHPOffice/PHPWord/files/1715929/test_bullets.docx)

How come your fonts are so big? Is it zoomed in or is there any added styling?

**Comment by troosan** [comment]
@rkorebrits The problem seems to be the word version. When opening your document with word 2010 I get the same result as you, with word 2016 the spacing is fine. We'll have to investigate more to find out what is causing this.

**Comment by rkorebrits** [comment]
Thanks! I tried investigating myself and from what I saw, it seemed to me that paragraph styling was applied to lists. I will also try and find some time to see if I can investigate, I'd love to help out and contribute to this great project!

**Comment by kisabelle** [comment]
Just came to chime in to say that I'm seeing the same issue and wondering if it's caused by each list item being added to a separate list? 

The reason I'm wondering is that a paragraph style should only be added to the list not the individual list item, and it seems each list item is getting paragraph spacing (spaceBefore, spaceAfter). 

I also noticed that highlighting all the list items and toggling the "bullet list" option to turn them into regular text, then toggling the "bullet list option" again results in a correctly spaced list, when highlighted you can actually see that the spaceBefore is only applied on the first list item and spaceAfter is only on the last list item.

![screen shot 2018-09-28 at 11 51 39 am](https://user-images.githubusercontent.com/1544652/46227752-0034f400-c315-11e8-9dbb-95088a896368.png)
![screen shot 2018-09-28 at 11 51 47 am](https://user-images.githubusercontent.com/1544652/46227753-0034f400-c315-11e8-90a5-0a2f28ecdb22.png)
![screen shot 2018-09-28 at 11 51 53 am](https://user-images.githubusercontent.com/1544652/46227754-0034f400-c315-11e8-9f6b-95136efe61f6.png)

**Comment by diggamies** [comment]
> Just came to chime in to say that I'm seeing the same issue and wondering if it's caused by each list item being added to a separate list?
> 
> The reason I'm wondering is that a paragraph style should only be added to the list not the individual list item, and it seems each list item is getting paragraph spacing (spaceBefore, spaceAfter).
> 
> I also noticed that highlighting all the list items and toggling the "bullet list" option to turn them into regular text, then toggling the "bullet list option" again results in a correctly spaced list. Afterwards, while the text is highlighted you can actually see that the spaceBefore is only applied on the first list item and spaceAfter is only on the last list item.
> 
> ![screen shot 2018-09-28 at 11 51 39 am](https://user-images.githubusercontent.com/1544652/46227752-0034f400-c315-11e8-9dbb-95088a896368.png)
> 
> ![screen shot 2018-09-28 at 11 51 47 am](https://user-images.githubusercontent.com/1544652/46227753-0034f400-c315-11e8-90a5-0a2f28ecdb22.png)
> 
> ![screen shot 2018-09-28 at 11 51 53 am](https://user-images.githubusercontent.com/1544652/46227754-0034f400-c315-11e8-9f6b-95136efe61f6.png)

Yep, this is the exact same behaviour I get.

**Comment by PiklioBezGashti** [comment]
is this issue still not fixed ? i have same problem with spacing between li in ol is there anyway to remove this space because margin-top/bottom has no effect on this one

**Comment by Brian-Webb** [comment]
We are also experiencing this.

@rkorebrits , have you had any luck resolving this?

**Comment by rkorebrits** [comment]
> We are also experiencing this.
> 
> @rkorebrits , have you had any luck resolving this?

In the end we abandoned this way of generating files, but ended up using the template parser, this worked way better

**Comment by AlexGnatko** [comment]
Hi!

I've managed to solve this issue by copying the PhpOffice\PhpWord\Shared\Html class and creating my own "MyHtml" class. I guess it could also have been done by overloading some members of this class.

I wanted to add a new paragraph style called "li", but couldn't figure out how to do it.

So I just added some code plain code to the new class:

`protected static function parseListItem($node, $element, &$styles, $data)
    {
        $cNodes = $node->childNodes;
        if (!empty($cNodes)) {
            $styles['li']['spaceAfter'] = 0;
            if ($node->last) {
                $styles['li']['spaceAfter'] = 200;
            }
            $listRun = $element->addListItemRun($data['listdepth'], $styles['list'], $styles['li']);
            foreach ($cNodes as $cNode) {
                self::parseNode($cNode, $listRun, $styles, $data);
            }
        }
    }`

Also had to change this line is parseNode:
`$newElement = call_user_func_array(array('MyHtml', $method), $arguments);`

And finally added the ability to detect the last child node in parseChildNodes:

`protected static function parseChildNodes($node, $element, $styles, $data)
    {
        if ('li' != $node->nodeName) {
            $cNodes = $node->childNodes;
            if (!empty($cNodes)) {
                $lst = [];
                foreach ($cNodes as $n => $cNode) {
                    if ($element instanceof AbstractContainer || $element instanceof Table || $element instanceof Row) {
                        $lst[] = $cNode;
                    }
                }
                $last = count($lst) - 1;
                foreach ($lst as $n => $cNode) {
                    if ($last == $n) {
                        $cNode->last = true;
                    }
                    self::parseNode($cNode, $element, $styles, $data);
                }
            }
        }
    }`

This all works fine for me, the list looks great.

**Comment by AlexGnatko** [comment]
Aaaand... an even easier solution. Forget the "li" style:

```
    protected static function parseListItem($node, $element, &$styles, $data)
    {
        $cNodes = $node->childNodes;
        if (!empty($cNodes)) {
            if (!$node->last) {
                $styles['paragraph']['spaceAfter'] = 0;
            }
            $listRun = $element->addListItemRun($data['listdepth'], $styles['list'], $styles['paragraph']);
            foreach ($cNodes as $cNode) {
                self::parseNode($cNode, $listRun, $styles, $data);
            }
        }
    }
```

**Comment by AlexGnatko** [comment]
I don't know how to make pull requests, but here are some suggestions to the PHPWord developers:

Change this line of the Html.php class:
```
$newElement = call_user_func_array(array('PhpOffice\PhpWord\Shared\Html', $method), $arguments);
```
To:
```
$newElement = call_user_func_array(array(get_called_class(), $method), $arguments);
```
and then replace the parseChildNodes function with the one mentioned above.

This will enable people to extend the PhpOffice\PhpWord\Shared\Html with their own implementations of various HTML-rendering functions such as that parseListItem function.

**Comment by tmcreativeltd** [comment]
I've just found I simply only have to add the custom spaceAfter and spacing styles to parseListItem:

`protected static function parseListItem($node, $element, &$styles, $data)
    {
        $cNodes = $node->childNodes;
        if (!empty($cNodes)) {
            // ADDED
            $styles['paragraph']['spaceAfter'] = 30;
            $styles['paragraph']['spacing'] = 0;
            // --
            $listRun = $element->addListItemRun($data['listdepth'], $styles['list'], $styles['paragraph']);
            foreach ($cNodes as $cNode) {
                self::parseNode($cNode, $listRun, $styles, $data);
            }
        }
    }`
