### ISSUE TITLE
because of locale, float numbers are being written to XML with ',' instead of '.'

### ISSUE THREAD

**Issue by Cyrills** [PHPOffice/PHPWord#1268]
This is:

- [ ] a bug report

# Expected Behavior

Genereating any docx filw

### Current Behavior

Then I'm trying to open docx I got xml error by MS Word

### How to Fix

Problem in current locale. Because my locale has commas in float numbers and section style
write `<w:pgSz w:orient="portrait" w:w="11905,511811024" w:h="16837,795275591"/>`
in document.xml

using this code

```
$xmlWriter->writeAttribute('w:w', $style->getPageSizeW());
$xmlWriter->writeAttribute('w:h', $style->getPageSizeH());
```

So, to fix this problem I need to use:

```
->addSection([
      'pageSizeW' => str_replace(',','.',SectionStyle::DEFAULT_WIDTH),
      'pageSizeH' => str_replace(',','.',SectionStyle::DEFAULT_HEIGHT)
    ])

```

**Comment by troosan** [comment]
would calling the following before generating your document fix the issue?
```php
setlocale(LC_NUMERIC, '.');
```
you can reset it to whatever it was before after the document is generated.

**Comment by Trainmaster** [comment]
@troosan It should also be possible to override `writeAttribute()` in `XMLWriter` (Common):

```php
if (is_float($value)) {
    $value = json_encode($value);
}
return parent::writeAttribute($name, $value);
```

Another option would be `number_format()` but it has the downside that you must specify the number of decimals. Right now it seems that `json_encode()` is the best option to convert a float to string in a locale-independent manner.

**Comment by troosan** [comment]
@PHPOffice/phpcommon-team could I have your opinion on the following

The following correctly writes `<element attr="0.5"/>`
```
php -r '$xml = new \XMLWriter();$xml->openURI("php://output"); $xml->startElement("element");$xml->writeAttribute("attr", 0.5);$xml->endElement();echo $xml->flush();'
```
Whereas if your locale is printing decimals with a `,` instead of a `.`
```
php -r 'setlocale(LC_ALL, "fr_FR"); $xml = new \XMLWriter();$xml->openURI("php://output"); $xml->startElement("element");$xml->writeAttribute("attr", 0.5);$xml->endElement();echo $xml->flush();'
```
it will output `<element attr="0,5"/>`which is not recognised by by Word

**Comment by troosan** [comment]
@Progi1984 I guess you must have the same issue in other PHPOffice projects?
What do you think of @Trainmaster solution, can it be merged into the Common

**Comment by Progi1984** [comment]
@troosan I just check. 🆗 for me.
