### ISSUE TITLE
Section breaks with breakType => oddPage don't display correctly

### ISSUE THREAD

**Issue by zakkolar** [PHPOffice/PHPWord#1270]
This is:

- [ ] a bug report

# Expected Behavior

Specifying a section's "breakType" as "oddPage" should make sure that each section of the output document starts on an odd page, adding a blank page if necessary.

### Current Behavior

"breakType"->"oddPage" displays the same as "breakType"->"nextPage"; it just adds a single page break between sections regardless of the resulting page being odd or even

### How to Reproduce
```php
<?php
require __DIR__ . '/vendor/autoload.php';

$phpWord = new \PhpOffice\PhpWord\PhpWord();
$section = $phpWord->addSection(array('breakType' => 'oddPage'));
$section->addText("section 1");

$section2 = $phpWord->addSection(array('breakType' => 'oddPage'));
$section2->addText("section 2");

$section3 = $phpWord->addSection(array('breakType' => 'oddPage'));
$section3->addText("section 3");
```

This produces a document that is three pages long

### Context

* PHP version: 7.1.3
* PHPWord version: 0.14
* Word 16.9.1 on Mac

**Comment by troosan** [comment]
Indeed, according to https://support.office.com/en-us/article/insert-delete-or-change-a-section-break-0eeae2d6-b906-42d3-a1bd-7e77ca8ea1f3 it should

> Starts the new section on the next odd-numbered page. For example, if you insert an Odd Page Section Break at the end of page 3, the next section will start on page 5.

I'm also using word 2016 on Mac, and I'm having the same problem. I don't think this is a PhpWord error, but a word error. The break inserted by PhpWord is the correct one, it's just not working. Even when adding the break directly in Word it's not working.

**Comment by zakkolar** [comment]
Aha - thank you for clarifying that! I just checked and creating the break directly in Word doesn't work for me either.
