### ISSUE TITLE
Word2007 parser does not parse `<w:br/>` tags

### ISSUE THREAD

**Issue by reed-jones** [PHPOffice/PHPWord#1274]
This is:

- [X] a bug report
- [X] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpword)

# Expected Behavior

IOFactory::load($source) should not modify source

### Current Behavior

On Windows 10 IOFactory::load($source) is removing all lines following a "soft return" or newline that is created with "Shift+Enter"

#### Example:
This is line one `<shift+enter>`
This is line two `<shift+enter>`
This is line three `<enter>`
This is line four

#### Becomes:
This is line one
This is line four

### Failure Information

Using TemplateProcessor to update a document template, and saving that document works as expected. later however when the documented is loaded using IOFactory::load($source), all lines following a soft return aren't existing.

### How to Reproduce
```php
$templateProcessor = new \PhpOffice\PhpWord\TemplateProcessor($template);
$templateProcessor->setValue($keys, $values); 
$templateProcessor->saveAs($dest);

// Here the document is correct.

$document = \PhpOffice\PhpWord\IOFactory::load($dest);
$htmlWriter = new \PhpOffice\PhpWord\Writer\HTML($document);
$htmlWriter->save('broken_document.html');

// here the document is broken
```

```php
// this has the same broken result

$PHPWord = new \PhpOffice\PhpWord\Reader\Word2007();
$document = $PHPWord->load($template);
$htmlWriter = new \PhpOffice\PhpWord\Writer\HTML($document);
$htmlWriter->save('broken_document.html');
```

### Context

* PHP version: 7.2.0
* PHPWord version: 0.14.0

**Comment by troosan** [comment]
indeed, it seems the `<w:br/>` is not being parsed
