### ISSUE TITLE
When you read docx with image it can fail

### ISSUE THREAD

**Issue by PeuX** [PHPOffice/PHPWord#1280]
This is:

- [x] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpword)

# Expected Behavior

I want to open a docx that contain image.

### Current Behavior

i got an exception.

### Failure Information

When I try to open a docx that contain image , i get an error
```
InvalidImageException in Image.php line 385:
Invalid image: zip://C:\inetpub\wwwroot\test_phpWord\src\Report\Controllers/../../../data/templates_word/testFinal.docx#word/media/section_image1.png
```
but i know the image is in the docx (i extract it to verify)

### How to Reproduce

Please provide a code sample that reproduces the issue.

```php
<?php
require __DIR__ . '/vendor/autoload.php';

 $phpWord = \PhpOffice\PhpWord\IOFactory::load(__DIR__.'/../../../data/templates_word/testFinal.docx');

```

### Context

* PHP version: 7.1.1
* PHPWord version: 0.14

To correct this i change /PHPWord/Elment/image.php L.457
```
if ($zip->locateName($imageFilename) ) {...
```
To 
```
if ($zip->locateName($imageFilename) !== false) { ...
```

Thanks for your great work !

**Comment by troosan** [comment]
I did the exact same fix 2 days ago, it was already merged in dev-develop
https://github.com/PHPOffice/PHPWord/commit/e846602d1ebdab8603b8c8b7d1b69a0577d3f780
