### ISSUE TITLE
Colspan and rowspan not working on the HTML Writer

### ISSUE THREAD

**Issue by lnicorena** [PHPOffice/PHPWord#1283]
This is:

- [ ] a bug report

# Expected Behavior

To properly generate the colspan and rowspan properties, when loading a docx document containing tables (with merged cells) and convert it to html

### Current Behavior

The colspan and rowspan properties (loaded from tables in a docx ) are being ignored by the HTML Writer. I believe that by the other Writers too.

### Failure Information

When a table like this is loaded,

![screen shot 2018-02-15 at 15 02 49](https://user-images.githubusercontent.com/2575777/36269893-86615e02-1261-11e8-8afa-8264e8125aa5.png)

This is the html output:
![screen shot 2018-02-15 at 15 06 14](https://user-images.githubusercontent.com/2575777/36270137-1cd7b782-1262-11e8-974b-ae2e75402e71.png)

```html
<table>
<tbody><tr>
<td>
<p style="text-align: center; margin-top: 0; margin-bottom: 0;">A</p>
</td>
<td>
<p style="text-align: center; margin-top: 0; margin-bottom: 0;">B</p>
</td>
<td>
<p style="text-align: center; margin-top: 0; margin-bottom: 0;">C</p>
<p style="text-align: center; margin-top: 0; margin-bottom: 0;">R</p>
</td>
<td>
<p style="text-align: center; margin-top: 0; margin-bottom: 0;">D</p>
</td>
</tr>
<tr>
<td>
<p style="text-align: center; margin-top: 0; margin-bottom: 0;">Q</p>
</td>
<td>
<p>&nbsp;</p>
</td>
<td>
<p>&nbsp;</p>
</td>
</tr>
<tr>
<td>
<p style="text-align: center; margin-top: 0; margin-bottom: 0;">Z</p>
</td>
<td>
<p style="text-align: center; margin-top: 0; margin-bottom: 0;">E</p>
</td>
<td>
<p>&nbsp;</p>
</td>
</tr>
</tbody></table>
```

### How to Reproduce

```php
$template ='path/to/document.docx';
$phpWord = \PhpOffice\PhpWord\IOFactory::load($template);
$htmlWriter = new \PhpOffice\PhpWord\Writer\HTML($phpWord);
$htmlString = $htmlWriter->getContent();
print $htmlString;
```

### Context

* PHP version:  7.2.0
* PHPWord version: 0.13.0

**Comment by troosan** [comment]
I'm guessing the problem occurs when loading the document, not writing it.

**Comment by mattbolt** [comment]
While investigating a similar issue, I've noticed this is actually two separate issues. The first as @troosan indicates, is during the loading process (see #1291). The second seems that the HTML Writer completely ignores the gridSpan / vMerge cell styles.

For this reason i submitted the previously mentioned issue separately, as the HTML Writer does need to use the cell styles once they are being processed properly by the Reader.

**Comment by danilocarva9** [comment]
Did you guys manage to make **rowspan** work on Html? I have the latest version of Phpword, but I can't make it work...

Only colspan works.. :(
