### ISSUE TITLE
Footnote should be allowed within ListItemRun

### ISSUE THREAD

**Issue by rootpd** [PHPOffice/PHPWord#1287]
This is:

- [ ] a bug report
- [x] a feature request
- [x] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpword)

# Expected Behavior

Library should allow creating `Footnote` within `ListItemRun`.

### Current Behavior

`BadMethodCallException` is being thrown from `PhpOffice\PhpWord\Element\AbstractContainer`

### How to Reproduce

```php
<?php
require __DIR__ . '/vendor/autoload.php';

$phpWord = new \PhpOffice\PhpWord\PhpWord();
$section = $phpWord->addSection();
$liRun = $section->addListItemRun(0, ['listType' => \PhpOffice\PhpWord\Style\ListItem::TYPE_NUMBER]);
$liRun->addText('foo');
$fn = $liRun->addFootnote();
$fn->addText($footnote);
```

I've tried to comment the thrown exception. Generated word is valid and displaying correctly. This is solely to revise allowed containers for `footnote` container.

Thank you.

### Context

* PHP version: 7.1
* PHPWord version: 0.14

**Comment by troosan** [comment]
all you need to change is the AbstractContainer
```php
            'Footnote'      => array('Section', 'TextRun', 'Cell', 'ListItemRun'),
```
I'll create a PR for it.
