### ISSUE TITLE
Endnotes read in from Word Document don't match up with their elements

### ISSUE THREAD

**Issue by mattbolt** [PHPOffice/PHPWord#1293]
This is:

- [x] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpword)

# Expected Behavior

When loading a Word 2016 Document that contains endnotes, the endnote elements contain the correct associated endnote content.

### Current Behavior

In a word document that contains a <w:endnote> tag with w:type="continuationNotice" attribute, the end notes are all offset by one position also resulting in the content of the last endnote being dropped off entirely.

### Failure Information

The underlying Footnotes reader assumes the relationship between the w:id of the reference and the index of the footnote in the document are the same. This is not the case, and the Reader needs to use the w:id field from the endnoteReference / footnoteReference tags to match with the related content.

### Context

* PHP version: 7.1.9
* PHPWord version: 0.14

**Comment by mattbolt** [comment]
I have temporarily fixed this locally for myself by modifying the following files:

Reader\Word2007\AbstractPart.php
```php
if ($xmlReader->elementExists('w:footnoteReference', $domNode)) {
  // Footnote
  $wId = $xmlReader->getAttribute('w:id', $domNode, 'w:footnoteReference');
  $parent->addFootnote()->setRelationId($wId); //Added setRelationId
} elseif ($xmlReader->elementExists('w:endnoteReference', $domNode)) {
  // Endnote
  $wId = $xmlReader->getAttribute('w:id', $domNode, 'w:endnoteReference');
  $parent->addEndnote()->setRelationId($wId); // Added setRelationId
} ......
```

Reader\Word2007\Footnotes.php
```php
$element = null;
foreach ($collection as $item) {
    if (($this->collection === 'endnotes') && ($item instanceof Endnote)) {
        if ($item->getRelationId() == $id) {
            $element = $item;
            break;
        }
    } elseif (($this->collection === 'footnotes') && ($item instanceof Footnote)) {
        if ($item->getRelationId() == $id) {
            $element = $item;
            break;
        }
    }
}

// Avoid w:type "separator" and "continuationSeparator"
// Only look for <footnote> or <endnote> without w:type attribute
if (is_null($type) && isset($element)) {
```

**Comment by troosan** [comment]
@mattbolt can you please upload a sample word document, I did not manage to reproduce the issue you are discribing

**Comment by troosan** [comment]
@mattbolt never mind, I managed to write a test for it. I'll fix it.

**Comment by troosan** [comment]
@mattbolt please try the dev-develop version, this should be fixed
