### ISSUE TITLE
??? symbols after convert docx to pdf file 

### ISSUE THREAD

**Issue by shevardena** [PHPOffice/PHPWord#1296]
hello, im getting ??? symbols after convert docx to pdf file any ideas how to fix it?

**Comment by troosan** [comment]
any specifics? Can you post a code sample?

**Comment by moxetiale** [comment]
see screnshots ![image](https://user-images.githubusercontent.com/17551744/36860185-024e0f86-1d9a-11e8-8ecb-54dc112e41a5.png)
![image](https://user-images.githubusercontent.com/17551744/36860254-30dafa6c-1d9a-11e8-8dc7-907b873b5ffa.png)

actualy word file contains georgian alphabets and only that alphabets converted to ??? in pdf file, see word file screenshot 
![image](https://user-images.githubusercontent.com/17551744/36860289-46d9c37a-1d9a-11e8-9efa-9d6d9efbee43.png)

and finaly this is pdf file
![image](https://user-images.githubusercontent.com/17551744/36860631-47f25fe6-1d9b-11e8-9a97-db48a37dbcfd.png)

**Comment by troosan** [comment]
OK, but that's probably because the font you are using in the PDF does not support UTF-8.

**Comment by moxetiale** [comment]
Understand. How can i use another font before convert to pdf?

**Comment by troosan** [comment]
I'm not to familiar with the PDF libraries, but you can set the font on $xmlWriter->setFont('arial');
Also, did you try with other PDF libraries (mpdf or dompdf)?

**Comment by autaut03** [comment]
@moxetiale I'm very sory for the offtop, but what is your Atom color scheme called?

**Comment by moxetiale** [comment]
@troosan  no i did not try other libraries, i will try setFont thanks
@autaut03 One dark

**Comment by jkurowski** [comment]
I have same problem. My .docx file:

> Witam,
> na imię mam ${variableName} i jestem z Białogardu.

.pdf file:

> Witam,
> na imi? mam Jacek i jestem z Bia?ogardu.

And my php code:
```
			require_once LIBRARY_PATH.'/bootstrap.php';
			$phpWord = new \PhpOffice\PhpWord\PhpWord();

			$domPdfPath = realpath(VENDOR_PATH.'/dompdf/dompdf');
			\PhpOffice\PhpWord\Settings::setPdfRendererPath($domPdfPath);
			\PhpOffice\PhpWord\Settings::setPdfRendererName('DomPDF');
			
			$template = new \PhpOffice\PhpWord\TemplateProcessor(FILES_PATH.'/imie.docx');
			$template->setValue('variableName', 'Jacek');
			$template->saveAs(FILES_PATH.'/result.docx');
			
			//Load temp file
			$phpWord = \PhpOffice\PhpWord\IOFactory::load(FILES_PATH.'/result.docx');

			//Save it
			$xmlWriter = \PhpOffice\PhpWord\IOFactory::createWriter($phpWord , 'PDF');
			$xmlWriter->save(FILES_PATH.'/result.pdf'); 
```

Any suggestions?

**Comment by jacklove2run** [comment]
@troosan I have tried the dompdf, the same reasult. I will try $xmlWriter->setFont('arial') later.

**Comment by jkurowski** [comment]
$xmlWriter->setFont('arial') - dont work

**Comment by neverovski** [comment]
@jkurowski When **composer update** or **composer install**, **phpword\src\PhpWord\Writer\HTML\Part\Head.php** - will change.
Better: 
`
$fontStyle = new \PhpOffice\PhpWord\Style\Font();
$fontStyle->setName('DejaVu Sans, sans-serif');
`

**Comment by Davis-PHP** [comment]
Do you have a solution for the same problem?

**Comment by ideamk** [comment]
```
$fontStyleName = 'oneUserDefinedStyle';
$phpWord->addFontStyle(
    $fontStyleName,
    array('name' => 'DejaVu Sans', 'size' => 10)
);
```
Works for me. Fonts location in `/vendor/dompdf/dompdf/lib/fonts`, by default install from composer.

**Comment by SarahTrees** [comment]
Support question successfully answered.
Sample code works.
Issue can be marked as closed.
