### ISSUE TITLE
Can i ignore the check on "zxx" locale code ? 

### ISSUE THREAD

**Issue by mdeprezzo** [PHPOffice/PHPWord#1298]
This is:

- [x] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpword)

# Expected Behavior

Can i ignore the locale code check ? If don't in the default locale ?

### Current Behavior

For some file i got this error: **zxx is not a valid language code**

### Failure Information

```
zxx is not a valid language code
```

### How to Reproduce

I don't know, i'm converting a rtf file with libreoffice and then i try to read with phpword reader.

### Context

* PHP version: 7.1.13
* PHPWord version: 0.14

**Comment by troosan** [comment]
@mdeprezzo can you provide a dummy file that produces this error?

**Comment by mdeprezzo** [comment]
@troosan Sure i attach that file here
[romanzo.rtf.zip](https://github.com/PHPOffice/PHPWord/files/1770360/romanzo.rtf.zip)

**Comment by troosan** [comment]
@mdeprezzo I don't see where this zxx is coming from (I cannot find this string anywhere in the rtf document). You are reading the rtf file directly or transforming the rtf -> docx and then reading the docx? In which case, can you send me the docx file.

**Comment by mdeprezzo** [comment]
@troosan oh yep, i convert the rtf file to docx with libreoffice

**Comment by troosan** [comment]
@mdeprezzo I did the exact same thing, but nowhere in the docx I get zxx locale. Can you provide me with a docx document?

**Comment by mdeprezzo** [comment]
@troosan Before, i tried again to upload the rtf file, and after convert by libreoffice i check again the error.

**Comment by moromete** [comment]
I can confirm also that when you set on LibreOffice default language for documents as "[None]"
The docx files are generated with the following in word\styles.xml
<w:lang w:val="zxx" w:eastAsia="zh-CN" w:bidi="hi-IN"/>
![screenshot_20180726_155011](https://user-images.githubusercontent.com/3898548/43263466-05957a4c-90ec-11e8-954e-f0c73c467e82.png)
[zxx_locale.docx](https://github.com/PHPOffice/PHPWord/files/2231989/zxx_locale.docx)

**Comment by troosan** [comment]
very nice :-)
I'll remove the check then

**Comment by fhferreira** [comment]
+1
