### ISSUE TITLE
Illegal string offset 'alignment'

### ISSUE THREAD

**Issue by bowendai** [PHPOffice/PHPWord#1302]
when I  use the following code , the error info is  Illegal string offset 'alignment'
![image](https://user-images.githubusercontent.com/6072950/36955927-55a1d806-2066-11e8-87d3-03419dc29b1d.png)

so, i don't know how to deal with it? 
Can anyone help me？

```php
$phpWord = new \PhpOffice\PhpWord\PhpWord();
        $section = $phpWord->addSection();
        $html = '<h2 style="color: rgb(0, 0, 0);font-family: &#39;sans serif&#39;, tahoma, verdana, helvetica;font-style: normal;font-variant-ligatures: normal;font-variant-caps: normal;letter-spacing: normal;orphans: 2;text-indent: 0px;white-space: normal;widows: 2;word-spacing: 0px;-webkit-text-stroke-width: 0px;text-align: center">
    <span style="font-size: 16px"><strong>委 托 担 保 合 同</strong></span>
</h2>';
\PhpOffice\PhpWord\Shared\Html::addHtml($section, $html, false, false);
$phpWord->save('test.docx', 'Word2007');
```

**Comment by troosan** [comment]
That's because `<h2/>` is being added as a Heading, with a named style 'Heading2'.
Because of this inline styling cannot be added to it. I changed the code not to choke on this but any inline style will not be parsed.

**Comment by bowendai** [comment]
@troosan  If I want to set <h2/> to be center,what should i do?

**Comment by troosan** [comment]
You need to first define a style named Heading2
```php
$phpWord->addParagraphStyle('Heading2', array('alignment' => 'center'));
```
This will then be used by the heading. Do the same for h1, h3, h4 of course!

**Comment by gitstashgithub** [comment]
I got the same error by usinng

**Comment by bowendai** [comment]
@gitstashgithub  
I modified the function parseText of Html.php
`    private static function parseText($node, $element, &$styles)
    {
        $styles['font'] = self::recursiveParseStylesInHierarchy($node, $styles['font']);

        //alignment applies on paragraph, not on font. Let's copy it there
        if (isset($styles['font']['alignment'])) {
            
            if(is_array($styles['paragraph'])){
                
                $styles['paragraph']['alignment'] = $styles['font']['alignment'];
            }
        }

        if (is_callable(array($element, 'addText'))) {
            $element->addText($node->nodeValue, $styles['font'], $styles['paragraph']);
        }
    }`

**Comment by troosan** [comment]
@bowendai I did (almost) the exact same change in the current develop branch
