### ISSUE TITLE
Delete text from section

### ISSUE THREAD

**Issue by maba4891** [PHPOffice/PHPWord#1303]
Here's the thing: I create a phpword object and add sections and text. But before I write the object to the final docx document I need to look at the whole thing again and might have to make some changes (especially deleting text again). It would be nice to do this at the end because I have a lot of complex conditions on how to fill the object. 

Here is where I am so far:
```
// creating new object, adding section and texts
$phpWord = new \PhpOffice\PhpWord\PhpWord();
$section = $phpWord->createSection();
$section->addText("Text1");
$section->addText("Text2");

// .. continue filling the document based on complex conditions
```
The question now is: How can I delete elements???

Of course I can get the elements from $section via getElements():
```
// get all elements of the section
$section_elements = $section->getElements();
// delete one element from this array
unset($section_elements[1]);
```
But that only deletes the text from the $section_elements array and leaves the phpword object untouched. **So how can I delete elements from the phpword object itself before writing it to a docx file?**

Thanks!

**Comment by troosan** [comment]
please try out the dev-develop version?
I added a method to remove an element from a section
```php
        $section->removeElement($elementToRemove);
```
$elementToRemove can either be the element itself, or an integer representing the position in the elements array to remove.

**Comment by troosan** [comment]
@maba4891 BTW, you should use `$phpWord->addSection();` instead of `$phpWord->createSection();`
The later is deprecated!

**Comment by maba4891** [comment]
Thanks for the quick reaction! :+1:  I am busy with another urgent project right now but will have a look at it asap and will report back here :)

**Comment by hultberg** [comment]
@troosan Looking forward for the `removeElement` method.
