### ISSUE TITLE
Error in Joomla

### ISSUE THREAD

**Issue by stoomby** [PHPOffice/PHPWord#1308]
I have trying to use the library in Joomla. I have installed a custom module that includes phpWord but I get a fatal error.

```
<?php
use PhpOffice\PhpWord\Style\Font;
use PhpOffice\PhpWord\Style\Paragraph;
use PhpOffice\PhpWord\Style\IOFactory;

require_once 'phpWorld/bootstrap.php';
```

And the error is:
Fatal error: Class 'ZipArchive' not found in /home/public_html/vendor/phpoffice/phpword/src/PhpWord/Shared/ZipArchive.php on line 134

I haven't ever edited ZipArchive.php at all, and I don't see the reason why there you be any issue there.

**Comment by troosan** [comment]
That's because you do not have http://php.net/manual/en/class.ziparchive.php installed.
As an alternative (if you cannot install that php extension) you can try 
https://github.com/PHPOffice/PHPWord/blob/develop/docs/general.rst#zip-class
