### ISSUE TITLE
New line with templateProcessor

### ISSUE THREAD

**Issue by R-Benjamin** [PHPOffice/PHPWord#1311]
This is:

- [X ] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpword)

# Expected Behavior

$myString = "Test-X \n Test-Y"
`Test-X'
'Test-Y'

### Current Behavior

$myString = "Test-X \n Test-Y"
`Test-XTest-Y'

### Failure Information

When I use the template processor, I can't insert a new line with a string. 

### How to Reproduce

Please provide a code sample that reproduces the issue.

```php
<?php
$templateProcessor->setValue('txt_agent_detail_evalB#'.$i.'', "test1 \n test2");
?>
```

### Context

* PHP version: 7
* PHPWord version: 0.14

**Comment by troosan** [comment]
please check #838

**Comment by R-Benjamin** [comment]
`< w : b r / >\n` and `</w:t><w:br/><w:t>` don't work. the problem is the same.

**Comment by tongjuhua** [comment]
me too，if not use template < w : b r / >\n and </w:t><w:br/><w:t> can work well.
