### ISSUE TITLE
Bug on "line-height" style

### ISSUE THREAD

**Issue by celsowm** [PHPOffice/PHPWord#1317]
This is:

- [X] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpword)

### What you did

**estilo.htm:**

```
<p style="text-align: justify; text-indent: 70.9pt; line-height: 150%;">
Lorem ipsum lorem ipsum&nbsp;Lorem <strong>ipsum lorem</strong> ipsum Lorem 
ipsum lorem ipsum Lorem ipsum lorem ipsum Lorem ipsum lorem ipsum Lorem ipsum lorem
 ipsum Lorem ipsum lorem ipsum Lorem ipsum
 lorem ipsum Lorem ipsum lorem 
 ipsum Lorem ipsum lorem ipsum Lorem ipsum lorem ipsum Lorem ipsum lorem 
 ipsum .</p>
```

**test.php:**

```
$html = file_get_contents(WWW_ROOT . DS . 'estilo.htm');
$phpWord = new \PhpOffice\PhpWord\PhpWord();
$section = $phpWord->addSection();
\PhpOffice\PhpWord\Shared\Html::addHtml($section, $html);
$phpWord->save('estilo.docx');
```

### What happened
PHPWord generated a docx with 4 blank pages (https://ufile.io/9jyrv)

### What you expected to happen
A docx with only one page and a paragraph with 1.5 of line height

### Context

* PHP version: 7.0.10
* PHPWord version: dev

**P.S.**: text-identity works fine (without line-height)

**Comment by troosan** [comment]
That's because it expects the line-height as `1.5`, not `150%`.
I'll see if I can "translate"

**Comment by troosan** [comment]
fixed, please check develop branch

**Comment by celsowm** [comment]
Worked fine Thanks ! Now the only style used on CKeditor that I still need to translate to docx oasis is the margin-left
