### ISSUE TITLE
is it possible to only read a word file without convert it to any other format?

### ISSUE THREAD

**Issue by arunk9034** [PHPOffice/PHPWord#1323]
Hi, 
Let me know how can I read a word file using PHPWORD, without converting this file to other formats like HTML, pdf.

If it is, then let me know how can I do this.

Thanks

**Comment by pmingram** [comment]
/samples/Sample_11_ReadWord97.php
/samples/Sample_11_ReadWord2007.php

`$phpWord = \PhpOffice\PhpWord\IOFactory::load($source);`

**Comment by arunk9034** [comment]
With this code "$phpWord = \PhpOffice\PhpWord\IOFactory::load($source);" ,  i got an very large array, and can't able to understand how to use this array and echo only text that word file contain with proper word format.

Hope you understand my Query. @pmingram
