### ISSUE TITLE
Incorrect behavior when parsing html tag 'br'

### ISSUE THREAD

**Issue by GolDiV** [PHPOffice/PHPWord#1325]
This is:

- [x] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpword)

### Expected Behavior

When I use the tag `<br/>` in html string and parse it in phpword like addHtml('test1`<br/>`test2'), in MsWord I expect to recieve next:
'test1' (soft line break like 'shift+enter')
'test2'

### Current Behavior

But now it work as next:
'test1' (line break like 'enter')
'empty string'   (line break like 'enter')
'test2'

### Failure Information

An empty string is inserted because function 'parseLineBreak' in class 'html' do it ($element->addTextBreak();). If this function is made empty, then the extra line will disappear. However, where to replace line break to soft line break, I did not find

### How to Reproduce

Please provide a code sample that reproduces the issue.

```php
<?php
require __DIR__ . '/vendor/autoload.php';

$phpWord = new \PhpOffice\PhpWord\PhpWord();
$section = $phpWord->addSection();
$html ='test1<br/>test2';
\PhpOffice\PhpWord\Shared\Html::addHtml($section, $html, false, false);
```

### Context

* PHP version: 7.1
* PHPWord version: 0.15

**Comment by troosan** [comment]
Did you try the dev-develop version?

**Comment by GolDiV** [comment]
yes

**Comment by troosan** [comment]
If you parse the following it's fine
```html
<p>test1<br/>test2</p>
```

**Comment by apothan** [comment]
@troosan Is it expected that you use <p>...</p> around any HTML added this way? I am getting the same issue as OP. I do not use the paragraph because it creates formatting I do not want.

This seems to have been introduced in 0.14 because if I go back to 0.13 it does not happen.

**Comment by troosan** [comment]
I'll see if I can restore backward compatibility.
I guess I could automatically add a `<p>` if the root element is not a block element.
