### ISSUE TITLE
PHPword addradar chart with style (standard) not work!!!

### ISSUE THREAD

**Issue by LDKJJ** [PHPOffice/PHPWord#1326]
Hey i want to add a radar chart with standard type using PHPword i make ($xmlWriter->writeElementBlock('c:radarStyle', 'val', 'standard');) but is not work for me plz any answer thank you :)
like this => https://imgur.com/Qwqg3jj
Best regards saleh

**Comment by troosan** [comment]
please check Sample_32_Chart.php, you'll find all the examples you need

**Comment by LDKJJ** [comment]
i checked your example, the example its work but i make radarstyle with type standard is give me a marker a place the standard this is my need ;)

**Comment by troosan** [comment]
I'm afraid I do not understand what you need. Please post your code and I'll see if I understand better.
