### ISSUE TITLE
Align: justify and bold  breaks line instead of inline bold

### ISSUE THREAD

**Issue by eelco2k** [PHPOffice/PHPWord#1330]
This is:

- [x] a bug report
- [ ] a feature request

### Expected Behavior

```
<p>This is some long <b>bold text which should automatic split and go to next line</b> when align is set to 'justify', but it doesn't and this last part goes to third line.
```
### Current Behavior

The bold part (also when using ``<b> ...</b>``) will be put on a new line instead of inline in the text.

### How to Reproduce

```php

<?php
require __DIR__ . '/vendor/autoload.php';

$phpWord = new \PhpOffice\PhpWord\PhpWord();
$section = $phpWord->addSection();

$html = "This medical follow-up training commits itself to one <b>basic level 'efficiency of care'</b> to strive for every medical specialist where efficiency is part of daily work "; //example text

\PhpOffice\PhpWord\Shared\Html::addHtml($section, $html , false, false);

// Saving the document as OOXML file...
$objWriter = \PhpOffice\PhpWord\IOFactory::createWriter($phpWord, 'Word2007');

```

### Context

* PHP version: 7.1
* PHPWord version: 0.14

**Comment by troosan** [comment]
if you surround it with `<p>...</p>` its working fine

**Comment by eelco2k** [comment]
Perfect it works. Noticed you replied this fix also in other thread ;-) so i could try it out. Thanks for fast reply!

**Comment by troosan** [comment]
you're welcome. Other solution, if you cannot modify the HTML, you can first add add a TextRun to the section, then add the HTML to it.
