### ISSUE TITLE
How to read mathematical formulas from file docx and display to screen?

### ISSUE THREAD

**Issue by idist-hn** [PHPOffice/PHPWord#1331]
I dont know how to read mathematical formulas. Does it have Math Object?
Example:
![image](https://user-images.githubusercontent.com/21170584/38287248-ddeb9f86-37f3-11e8-8d46-fb468e3b8143.png)

**Comment by latincrow81** [comment]
+1 now im generating images but ideally it would be better to generate the actual word objects

**Comment by hungdang6676** [comment]
Hello guys, how can i do this? Can i make some change in reader classes or somewhere??

**Comment by et-muneeb** [comment]
any help regarding this?

**Comment by Ling1992** [comment]
+1

**Comment by mindfreak269** [comment]
any update?

**Comment by redrum0x** [comment]
update?

**Comment by Progi1984** [comment]
@idist-hn Could you give us a sample file, please ?

**Comment by redrum0x** [comment]
> @idist-hn @latincrow81 @mindfreak269 @Ling1992 @redrum0x @hungdang6676
> 
> Could you give us a sample file, please ?
![image](https://github.com/PHPOffice/PHPWord/assets/36562632/e01e7d9d-c462-439a-b32b-79818a5a5b80)


I am upload this test file to https://file.io/EEZ4y7sUXrrt

**Comment by Progi1984** [comment]
FYI : A Pull Request is in Progress : #2477
