### ISSUE TITLE
Add paging to a footer with addHtml

### ISSUE THREAD

**Issue by BohdanBursa** [PHPOffice/PHPWord#1346]
Is there a way to add paging to a footer with

`\PhpOffice\PhpWord\Shared\Html::addHtml($footer, $content,false, true);`

I know how to do it like this
`$footer->addPreserveText('Page {PAGE} of {NUMPAGES}.');`

but i would like to do it with
`
\PhpOffice\PhpWord\Shared\Html::addHtml($footer, $content, false, true);`

**Comment by troosan** [comment]
no, that's not possible. what you can do is add a TextRun to the footer, then add the HTML on that TextRun

**Comment by BohdanBursa** [comment]
Thanks for your response , but that's not what i wanted to do, i will do it without the html then
