### ISSUE TITLE
After setting lineHeight, how to make the text vertically centered?

### ISSUE THREAD

**Issue by HuPengCheng1994** [PHPOffice/PHPWord#1348]
After setting lineHeight, how to make the text vertically centered?

**Comment by troosan** [comment]
You'll need to set the same spacing before and after (spaceBefore and spaceAfter)

**Comment by HuPengCheng1994** [comment]
set number has no effect
`$section->addText("报告编号报告编号报告编号报告编号报告编号报告编号报告编号报告编号报告编号报告编号报告编号",['size'=>18],['spaceBefore ' => 200,'spaceAfter'=>200]);`

**Comment by troosan** [comment]
there is a space after spaceBefore ...
```php
$section->addText('Vertically centered text', array('size'=>18), array('lineHeigth' => 600,'spaceBefore' => 200,'spaceAfter'=>200));
```
