### ISSUE TITLE
How to make each page footer or header show according to the directory title？

### ISSUE THREAD

**Issue by HuPengCheng1994** [PHPOffice/PHPWord#1351]
Currently only the footer and page are set to the same for each page

help me

**Comment by troosan** [comment]
can you be a bit more specific, what do you mean with directory title?
Can you share a screenshot, a code sample of what you already have, ...

**Comment by HuPengCheng1994** [comment]
I want to make the header or footer of each page different.

**Comment by troosan** [comment]
The header and footer can be different per section.
You can also have a different header for even and odd pages.
Please check the documentation on how to do this: http://phpword.readthedocs.io/en/latest/containers.html#headers

**Comment by SomayaMomtaz** [comment]
You also can use style reference to change header according to special format

https://github.com/PHPOffice/PHPWord/issues/1349
