### ISSUE TITLE
Hey when use git clone: to download , i can't find the vendors folder nor the autoload.php file

### ISSUE THREAD

**Issue by wibgates** [PHPOffice/PHPWord#1353]
This is:

- [x] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpword)

### Expected Behavior

Please describe the behavior you are expecting.

### Current Behavior

What is the current behavior?

### Failure Information

Please help provide information about the failure.

### How to Reproduce

Please provide a code sample that reproduces the issue.

```php
<?php
require __DIR__ . '/vendor/autoload.php';

$phpWord = new \PhpOffice\PhpWord\PhpWord();
$section = $phpWord->addSection();
$section->...
```

### Context

* PHP version:
* PHPWord version: 0.14

**Comment by troosan** [comment]
you can find all about Composer here: https://getcomposer.org/

**Comment by wibgates** [comment]
thanks it worked with composer
