### ISSUE TITLE
.git folder is huge

### ISSUE THREAD

**Issue by czosel** [PHPOffice/PHPWord#1355]
I got a timeout when I was trying to install PHPWord with composer. It seems that the `.git` folder is huge:
```bash
$ du -h --max-depth=1
2.1M	./src
1.9M	./tests
144K	./docs
1.2M	./samples
336M	./.git
```
Can someone tell how this happened, and if there would be a chance to do some history-rewriting to slim the `.git` folder down?

If you like, this could also be considered a composer issue (see https://github.com/composer/composer/issues/3449).

**Comment by troosan** [comment]
I guess this could help
https://stackoverflow.com/questions/2116778/reduce-git-repository-size?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa

**Comment by czosel** [comment]
`git gc` is run automatically on remote git repos, so that doesn't help. This [answer on SO](https://stackoverflow.com/a/42544963/1743938) shows how to find the largest files in a git repo, which returns something like this in our case:
```
66d14527d422  3,8MiB coverage/develop/Writer/Word2007/Part/Theme.php.html
d5386d4c852b  3,8MiB coverage/develop/Writer/Word2007/Part/Theme.php.html
14eefc645832  3,8MiB coverage/develop/Writer/Word2007/Part/Theme.php.html
c6a6da8442c3  3,8MiB coverage/develop/Writer/Word2007/Part/Theme.php.html
e6d905ba0436  3,8MiB coverage/develop/Writer/Word2007/Part/Theme.php.html
0b04872ad4c1  3,9MiB coverage/develop/Writer/Word2007/Part/Theme.php.html
807796c3f422  3,9MiB coverage/develop/Writer/Word2007/Part/Theme.php.html
05c2d849df86  3,9MiB coverage/develop/Writer/Word2007/Part/Theme.php.html
27b093aa95bf  3,9MiB coverage/develop/Writer/Word2007/Part/Theme.php.html
41f9ce746399  3,9MiB coverage/develop/Writer/Word2007/Part/Theme.php.html
8924416f1a49  3,9MiB coverage/develop/Writer/Word2007/Part/Theme.php.html
bc53f5ed02fd  3,9MiB coverage/develop/Writer/Word2007/Part/Theme.php.html
c056639544a8  3,9MiB coverage/develop/Writer/Word2007/Part/Theme.php.html
f21cabd66869  3,9MiB coverage/develop/Writer/Word2007/Part/Theme.php.html
fdf5198467e7  3,9MiB coverage/develop/Writer/Word2007/Part/Theme.php.html
```
It seems that the massive `.git` folder is essentially filled with old coverage reports. I'd suggest running some filter-branch magic to get rid of them, what do you think @troosan?

**Comment by czosel** [comment]
Oh, looking at where those files are coming from reveals that this is a CI issue:
```
commit 04192091191069e2692f52f8b9eb5449da2ce5cc
Author: travis-ci <travis@travis-ci.org>
Date:   Wed Apr 18 07:11:36 2018 +0000

    PHPDocumentor (Travis Build: 1695  - Branch: develop)
```
So before we can clean up, we'd have to figure out how to avoid that the coverage reports are being added to the repo :smiley:

**Comment by troosan** [comment]
Indeed, I don't think there is much added value in keeping those code coverage reports and phpDocumentation.
Maybe we could track code coverage with https://github.com/marketplace/coveralls?
What do you think @Progi1984, does anybody check the content of the gh-pages anyway?

**Comment by czosel** [comment]
I didn't even find the gh-pages, are they supposed to be here?
http://phpoffice.github.io/PHPWord/docs/master/

**Comment by troosan** [comment]
The github pages were dropped a couple of months ago

https://help.github.com/articles/configuring-a-publishing-source-for-github-pages/

**Comment by Progi1984** [comment]
@troosan I agree to delete gh-pages and migrate to coveralls. I think doing the same thing for PHPPresentation.

**Comment by czosel** [comment]
@Progi1984 Awesome! I updated #1360 to include coveralls integration.
