### ISSUE TITLE
No show text

### ISSUE THREAD

**Issue by pavell86** [PHPOffice/PHPWord#1357]
Hello,
My document contain this sentence: **I sell a plot of 30 m2**. PHPWord show only text I sell a plot of, but no show 30 m2. Why ?

xml structure, which is in docx below
<w:smartTag w:uri="urn:schemas-microsoft-com:office:smarttags" w:element="metricconverter"><w:smartTagPr><w:attr w:name="ProductID" w:val="30 m2"/></w:smartTagPr>

Thank you

**Comment by troosan** [comment]
might be because of the `w:smartTag` node.
With which version did you try? can you please try with the dev-develop version?
