### ISSUE TITLE
Fatal error when trying to pass code from HTML to Create Word File

### ISSUE THREAD

**Issue by wnorales** [PHPOffice/PHPWord#1362]
Im getting the following Error Message and i dont understand why,i put the correct path for PHP office. 

<img width="848" alt="error message" src="https://user-images.githubusercontent.com/10760389/39494962-51da03c4-4d66-11e8-91e2-c6b95e8e55c1.PNG">
<img width="425" alt="html" src="https://user-images.githubusercontent.com/10760389/39494963-51e9230e-4d66-11e8-8304-b4939c525efe.PNG">
<img width="412" alt="php" src="https://user-images.githubusercontent.com/10760389/39494964-51fbca04-4d66-11e8-9001-2900c2b81f21.PNG">

**Comment by troosan** [comment]
Because your package is wrong, you put `PhpOffice\PhpWord\src\PhpWord\Shared\html` which is obviously wrong.
Should be `\PhpOffice\PhpWord\Shared\Html`
