### ISSUE TITLE
Adding images with TemplateProcessor

### ISSUE THREAD

**Issue by rkorebrits** [PHPOffice/PHPWord#1365]
I've spent quite a bit of time using the `TemplateProcessor` now, but I'm stuck on the adding of images. Is there a consensus on how to do this? I see there are several PRs, but none of them seem to have been merged. What I've tried so far:

1. I tested @FBnil 's suggestion in https://github.com/PHPOffice/PHPWord/issues/1079 to replace existing images, which works on itself, but I need more flexibility as it can only really work if you code against a particular document, whereas we will have loads of different templates with a variable number of images.

2. @ejn 's solution in https://github.com/PHPOffice/PHPWord/pull/1084 looked very promising, however it doesn't work for me, I get the following message when opening the document:
![image](https://user-images.githubusercontent.com/3765592/39698139-da6d1910-51f3-11e8-9451-97b9118e6ccb.png)
After clicking "ok" here, I get the option to "recover the contents", which works, but it's not a viable solution as we can't provide "broken" documents to our users.
The template: [empty.docx](https://github.com/PHPOffice/PHPWord/files/1979571/empty.docx)
The output: [CV_680989964_Test_Name_20180507-114821.docx](https://github.com/PHPOffice/PHPWord/files/1979574/CV_680989964_Test_Name_20180507-114821.docx)

3. https://github.com/PHPOffice/PHPWord/pull/1170 by @SailorMax works fine, however it's not possible to set the size of the image in the template variable which is something we'd need to be able to manage inside the templates.

What is the recommended way to do this (if there is any).

**Comment by SailorMax** [comment]
@rkorebrits PR #1170 now support image size options. Can you try it?

**Comment by rkorebrits** [comment]
I've managed to get EJNs version working and it's working like a charm for me. If I get time, I will try your PR also, thanks!

**Comment by rkorebrits** [comment]
Closing this ticket for now to reduce clutter. I think admin needs to make a call on which PR to use and merge as this is quite a big feature. EJNs feature worked perfect for me after applying this fix: https://github.com/PHPOffice/PHPWord/pull/1084#issuecomment-387050292 (due to filenames with full stops)
