### ISSUE TITLE
'Semicolon missing' in saved docx file

### ISSUE THREAD

**Issue by BBalazsJurgen** [PHPOffice/PHPWord#1367]
Dear Dev Team,

We are using PHPWord to generate a number of docx files - we are using PHPWord to generate the file from scratch, the main body of the document remains the same, and we are only changing certain elements like tables and parts of text in paragraphs.

Most of the documents generated work just fine, but a few seem to have issues. When trying to open a file, Word replies with the following message (rough translations, might not be accurate):

"We're sorry. We can't open the file [filename] because we found a problem with its contents."
Clicking "Details" provides us with the following information:
"Semicolon required. Location: Part: /word/document.xml, Line: 2, Column: 62564".

I have attached the file in question for reference.
[180509_Incero_KertEsOtthonobolt_AW_Teljesítés Igazolás.docx](https://github.com/PHPOffice/PHPWord/files/1988193/180509_Incero_KertEsOtthonobolt_AW_Teljesites.Igazolas.docx)

Please get back to us with anything you can find.

Kind regards,
BBalazs

**Comment by rkorebrits** [comment]
![image](https://user-images.githubusercontent.com/3765592/39856422-34454f6e-5430-11e8-9500-2d49f735d68a.png)

You need to escape ampersands. You can either use `htmlspecialchars` or `\PhpOffice\PhpWord\Settings::setOutputEscapingEnabled(true);`

**Comment by BBalazsJurgen** [comment]
Thanks for the speedy reply, the solution worked flawlessly.
