### ISSUE TITLE
Html tag css class not working in html to word

### ISSUE THREAD

**Issue by umairali** [PHPOffice/PHPWord#1375]
I am adding CSS class in HTML tag but CSS class not working only inline style is working please suggest anything.

class not working
```
<style type="text/css">
.pStyle 
{
  font-size:15px;
}
</style>

<p class="pStyle">Calculator</p>
```

inline style working
`<p style="font-family: calibri; font-size: 17px; color: #444444; font-weight: bold;">Calculator</p>`

**Comment by rkorebrits** [comment]
I highly doubt that the PHPWord would parse your CSS and apply styling, rather apply the styling inline yourself I think.

**Comment by Progi1984** [comment]
It's in progress : #2327
