### ISSUE TITLE
Add gitattributes

### ISSUE THREAD

**Issue by akarupt** [PHPOffice/PHPWord#1377]
This is:

- [ ] a bug report
- [X] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpword)

### Expected Behavior

When i run "composer update --no-dev" i espect that folder "samples" and "tests" and "docs" dont go to vendor folder.

### Current Behavior

The folders are going to the vendor folder

### Failure Information

Solution: add gitattributes
https://stackoverflow.com/questions/32795241/remove-unwanted-files-from-php-composer-dependencies

### How to Reproduce

Run Composer update --no-dev

### Context

* PHP version: 7.0
* PHPWord version: 0.14

**Comment by troosan** [comment]
@akarupt If I add this it will actually not be the `composer update --no-dev` that gets you the package without the extra files. A simple `composer update` will not download the samples, build, ... directories.

To get the samples you'll have to run `composer update --prefer-source`

**Comment by troosan** [comment]
done in 0.15
