### ISSUE TITLE
Empty file 7.2kb

### ISSUE THREAD

**Issue by inteclever** [PHPOffice/PHPWord#1379]
This is:
- [ ] **not** a usage question (ask them on https://ru.stackoverflow.com/questions/832042/phpword-%D0%BF%D1%83%D1%81%D1%82%D0%BE%D0%B9-%D1%84%D0%B0%D0%B9%D0%BB)

Hello!
Help me please.
Except Chrome Google in any browsers I receive an empty file ....

### How to Reproduce

Please provide a code sample that reproduces the issue.

```php
<?php
require __DIR__ . '/vendor/autoload.php';

$phpWord = new \PhpOffice\PhpWord\PhpWord();
$section = $phpWord->addSection();
$section->...

		$objWriter = \PhpOffice\PhpWord\IOFactory::createWriter($phpWord,'Word2007');
		header("Content-Description: File Transfer");
		header('Content-Disposition: attachment; filename="Shpora.doc"');
		header('Content-Type: application/vnd.openxmlformats-officedocument.wordprocessingml.document');
		header('Content-Transfer-Encoding: binary');
		header('Cache-Control: must-revalidate, post-check=0, pre-check=0');
		header('Expires: 0');
		$objWriter->save("php://output");

### Context

* PHP version: 5.6
* PHPWord version: 0.14

**Comment by inteclever** [comment]
header('Content-Disposition: attachment; filename="Shpora.docx"');

**Comment by troosan** [comment]
you can actually just do
```php
$phpWord->save('Shpora.doc', 'Word2007', true);
```

**Comment by inteclever** [comment]
The file does not help anyway empty. Its size is 7.2kb...

**Comment by troosan** [comment]
try to rename to zip, and check what's in it.

**Comment by inteclever** [comment]
troosan, it not help...
Make generate with method AddHtml it's work for Edge (Desktop. mobile), Google chrome (Desktop, mobile), Mozilla (Desktop, mobile - not trying), Yandex browser (Desktop - not trying, mobile - not working, generate just blank document). 
I wont solve this problem...
P.S. Sorry for my bad english.

**Comment by troosan** [comment]
please share the generated file, and maybe a bit of code.
