### ISSUE TITLE
Why generated .docx file is opening in compatibility mode

### ISSUE THREAD

**Issue by umairali** [PHPOffice/PHPWord#1381]
why docx is opening in compatibility mode. this compatibility mode creating many issue like table width and break the line when I open this document with mac pages and its showing all tables with zero width.

![345](https://user-images.githubusercontent.com/5318005/40422594-ec2ece64-5ea0-11e8-840b-ce2fcdf5f5dd.JPG)

<img width="706" alt="ertert" src="https://user-images.githubusercontent.com/5318005/40422765-5cffb946-5ea1-11e8-8859-a831dc0fafc8.png">

**Comment by troosan** [comment]
does this help?
http://phpword.readthedocs.io/en/latest/recipes.html#remove-compatibility-mode-text-in-the-ms-word-title-bar

**Comment by umairali** [comment]
thanks now it's not showing compatibility mode but still if i open this file to mac pages its showing tables in one row 

<img width="706" alt="ertert" src="https://user-images.githubusercontent.com/5318005/40465617-abee4c20-5f32-11e8-8323-0c1d756d0cce.png">
