### ISSUE TITLE
Allow to change sections?

### ISSUE THREAD

**Issue by hultberg** [PHPOffice/PHPWord#1384]
This is:

- [ ] a bug report
- [x] a feature request
- [x] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpword)

### Description

Hello. I have some code for changing an existing document and are adding a section at the end with a table. However, if the previous last section has not set the break type to `continuous`, the content I added gets added to a new page (as expected). I therefore wrote a small hack to change the internal sections array to modify the breaktype of the last section:

```php
<?php

// ...code to read and so on.

/**
 * @var PhpOffice\PhpWord\PhpWord $word
 */

$allSections = $word->getSections();
$allSections[count($allSections) - 1]->getStyle()->setBreakType('continuous');

// HACK:
$reflection = new \ReflectionClass(get_class($word));
$sectionsProperty = $reflection->getProperty('sections');
$sectionsProperty->setAccessible(true);
$sectionsProperty->setValue($word, $allSections);
```   

I therefore propose to add a method that either; allows to set a new Sections array or allows to modify a specific index. I'm looking into creating an PR, but I wanted to get some inputs on what you guys thought was the best method strategy to implement.

**Comment by troosan** [comment]
with the dev-develop version (future 0.15) you can actually get a specific section (by index)
```php
$phpWord->getSection(3);
```
Do you actually need to set back the list of sections? When you modify a section it modifies directly that instance, no need to replace.

**Comment by hultberg** [comment]
@troosan Indeed, verified by this short [3v4l snippet](https://3v4l.org/EBeXY). I'm awaiting the new release then. :-)
