### ISSUE TITLE
XMLWriter::writeAttribute() expects parameter 2 to be string, array given

### ISSUE THREAD

**Issue by temirfe** [PHPOffice/PHPWord#1409]
I have following error: XMLWriter::writeAttribute() expects parameter 2 to be string, array given in
phpoffice\phpword\src\PhpWord\Writer\Word2007\Style\Row.php line 47
```
if ($this->height !== null) {
            $xmlWriter->startElement('w:trHeight');
            $xmlWriter->writeAttribute('w:val', $this->height); //line 47
            $xmlWriter->writeAttribute('w:hRule', ($style->isExactHeight() ? 'exact' : 'atLeast'));
            $xmlWriter->endElement();
        }
```

**Comment by ThomasAKaestner** [comment]
@temirfe What caused the issue?

**Comment by esteveboix** [comment]
In my case, I had this:

`$summary->addListItem("list element", [0]);`

...in my document. Note the array as the second argument. This is wrong, I changed it to:

`$summary->addListItem("list element", 0);`

...and the error went away.

HTH,
Esteve

**Comment by azmilazizi1999** [comment]
In mine the error was at addCell line, it expects width and style parameter but i only passed style without assigning width. I changed it to from
`addCell($cellstyle)` to `addCell(null, $cellStyle)` and it went alright.

Try checking your stack trace, the involving element should be stated somewhere.
