### ISSUE TITLE
Fatal error: Cannot use 'Object' as class name as it is reserved 

### ISSUE THREAD

**Issue by chrisribe** [PHPOffice/PHPWord#1418]
This is:

- [x] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpword)

### Expected Behavior
Working "Sample 06 Footnote"

### Current Behavior
Php crash, not working.

### Failure Information

Fatal error: Cannot use 'Object' as class name as it is reserved in C:\cribe\GitHub\PHPWord\src\PhpWord\Element\Object.php on line 26

### How to Reproduce

Please provide a code sample that reproduces the issue.

Just run sample #6 page.
Build v0.14.0 with: 
composer require phpoffice/phpword

load samples with:
cd to samples dir and run php-S localhost:8000

### Context

* PHP version: 7.2.6
* PHPWord version: 0.14

**Comment by chrisribe** [comment]
Humm seems fixed on the develop branch any ETA on a release tag ?

**Comment by troosan** [comment]
anytime now, just need to find some time to finalise it

**Comment by troosan** [comment]
resolved with 0.15

**Comment by troosan** [comment]
resolved by #1185
