### ISSUE TITLE
application path changed, but phpword still remembers old path

### ISSUE THREAD

**Issue by daybreak10** [PHPOffice/PHPWord#1453]
This is a general help question regarding the storage of path information in phpword, composer, autoloader, bootstrap or associated files.   I am moving my application from my development server to my production server.  The /var/www/html/VTProtocol_test/.... is changing to /var/www/html/VTProtocol/.....

After moving the files and ensuring my config.php, VTProtocol.conf, autoloader.php, and bootstrap.php files were all correct for the right path for the new location, I get this error when the code attempts to generate the document -- it still remembers VTProtocol_test when pulling the image file.  I have searched every possible file under the /includes and /includes/vendor directories and cannot find a reference to this old directory.  I even reinstalled composer.  Any help would be greatly appreciated.  Thanks.

 PHP Fatal error:  Uncaught exception 'PhpOffice\\PhpWord\\Exception\\InvalidImageException' with message 'Invalid image: /var/www/html/VTProtocol_test/includes/stop-logo-words.png' in /var/www/html/VTProtocol/includes/vendor/phpoffice/phpword/src/PhpWord/Element/Image.php:385\nStack trace:\n#0 /var/www/html/VTProtocol/includes/vendor/phpoffice/phpword/src/PhpWord/Element/Image.php(140): PhpOffice\\PhpWord\\Element\\Image->checkImage()\n#1 [internal function]: PhpOffice\\PhpWord\\Element\\Image->__construct('/var/www/html/V...', Array)\n#2 /var/www/html/VTProtocol/includes/vendor/phpoffice/phpword/src/PhpWord/Element/AbstractContainer.php(144): ReflectionClass->newInstanceArgs(Array)\n#3 [internal function]: PhpOffice\\PhpWord\\Element\\AbstractContainer->addElement('Image', '/var/www/html/V...', Array)\n#4 /var/www/html/VTProtocol/includes/vendor/phpoffice/phpword/src/PhpWord/Element/AbstractContainer.php(111): call_user_func_array(Array, Array)\n#5 /var/www/html/VTProtocol/print_protocol_doc.php(317): PhpOffice\\PhpWord\\Element\\AbstractContainer in /var/www/html/VTProtocol/includes/vendor/phpoffice/phpword/src/PhpWord/Element/Image.php on line 385, referer: http://myserver.com/VTProtocol/get_protocols.php

Bootstrap.php is 
`<?php
/**
 * This file is part of PHPWord - A pure PHP library for reading and writing
 * word processing documents.
 *
 * PHPWord is free software distributed under the terms of the GNU Lesser
 * General Public License version 3 as published by the Free Software Foundation.
 *
 * For the full copyright and license information, please read the LICENSE
 * file that was distributed with this source code. For the full list of
 * contributors, visit https://github.com/PHPOffice/PHPWord/contributors. test bootstrap
 *
 * @see         https://github.com/PHPOffice/PHPWord
 * @copyright   2010-2017 PHPWord contributors
 * @license     http://www.gnu.org/licenses/lgpl.txt LGPL version 3
 */

$vendorDirPath = '/var/www/html/VTProtocol/includes/vendor';
if (file_exists($vendorDirPath . '/autoload.php')) {
    require $vendorDirPath . '/autoload.php';
} else {
    throw new Exception(
        sprintf(
            'Could not find file \'%s\'. It is generated by Composer. Use \'install --prefer-source\' or \'update --prefer-source\' Composer commands to move forward.',
            $vendorDirPath . '/autoload.php'
        )
    );
}`

autoload.php is:

`<?php

// autoload.php @generated by Composer

require_once __DIR__ . '/composer/autoload_real.php';

return ComposerAutoloaderInit59e6e1bd1ba8cea4765faf5a9a0f1d48::getLoader();
`

**Comment by troosan** [comment]
I guess you'll have to regenerate the autoload.
You can do this with 
```
composer dump-autoload
```
