### ISSUE TITLE
Can't read file .doc (MS Word 97) with utf-8 characters

### ISSUE THREAD

**Issue by nhatquang20** [PHPOffice/PHPWord#1454]
This is:

- [x] a bug report
 My .doc file has the following text: است که در زمان ساخت داده هائی در آن 
I use this code to read file:
`
$phpWord = \PhpOffice\PhpWord\IOFactory::load($source, 'MsDoc');

        $sections = $phpWord->getSections();

        foreach ($sections as $section) {
            foreach ($section->getElements() as $element) {
               $string = $element->gettext();
               echo $string;
               exit;
            }
        }
`
its return: '3* ©G /1 2E'F 3'.*
when i dump it, its return: "'\x063\x06*\x06 ©\x06G\x06 /\x061\x06 2\x06E\x06'\x06F\x06 3\x06'\x06.\x06*\x06 "
How could i read it and save to db?

**Comment by Progi1984** [comment]
@nhatquang20 Could you give us a sample file for testing, please ? Thank you

**Comment by LuongTranNguyen** [comment]
Hi Progi1984, 

Is this issue fixed yet? I use PHPOffice and have the same problem.

**Comment by KitKanWong** [comment]
same problem

**Comment by nevergone** [comment]
v0.17.0 tested and it have same problem.

Sample text for testing (text with hungarian special characters):

árvíztűrő tükörfúrógép
ÁRVÍZTŰRŐ TÜKÖRFÚRÓGÉP

**Comment by Progi1984** [comment]
@KitKanWong @nevergone @LuongTranNguyen Hi, Could you send me a file with this case, please, for analysis ?

**Comment by Progi1984** [comment]
@nhatquang20 @KitKanWong @nevergone @LuongTranNguyen 

This issue has been fixed by a maintainer in the PR #2664. You can help him by sponsoring him through [Github sponsors](https://github.com/sponsors/Progi1984).
