### ISSUE TITLE
Fatal error: Cannot use 'Object' as class name as it is reserved in C:\E\sites\fjl-b-php\vendor\phpoffice\phpword\src\PhpWord\Element\Object.php on line 26

### ISSUE THREAD

**Issue by bingxinranhuo** [PHPOffice/PHPWord#1457]
This is:

- [x] a bug report

run phpword/samples/index.php?Sample_04_Textrun.php
or
phpword/samples/index.php?Sample_06_Footnote.php

### Fatal error
```php
Fatal error: Cannot use 'Object' as class name as it is reserved in C:\E\sites\fjl-b-php\vendor\phpoffice\phpword\src\PhpWord\Element\Object.php on line 26
```

### Context

* PHP version:php 5.6
* PHPWord version: 0.15

**Comment by troosan** [comment]
@bingxinranhuo Are you sure you are using version 0.15? This class was renamed
