### ISSUE TITLE
Set Table Direction RTL 

### ISSUE THREAD

**Issue by mmasomi73** [PHPOffice/PHPWord#1549]
How to set table direction rtl?
it's my code:

```php
        $style = array('rtl' => true,
                       'name' => 'B Mitra',
                       'size' => 12);

        $borderStyle = array('borderSize' => 6,
                            'borderColor' => '000000');

        $table = $section->addTable($borderStyle);
        $cellHCentered = array('alignment' => \PhpOffice\PhpWord\SimpleType\Jc::CENTER);
        $cellHEnd = array('alignment' => \PhpOffice\PhpWord\SimpleType\Jc::END);
        $cellVCentered = array('valign' => 'center');
        $i = 0;

        //--------------= Questions Header
        $table->addRow();
        $cell = $table->addCell(500,$cellVCentered);
        $textrun = $cell->addTextRun($cellHCentered);
        $textrun->addText('ردیف', $style);

        $cell = $table->addCell(11000);
        $textrun = $cell->addTextRun($cellHEnd);
        $textrun->addText('سوالات', $style);

        $cell = $table->addCell(500,$cellVCentered);
        $textrun = $cell->addTextRun($cellHCentered);
        $textrun->addText('بارم', $style);
```

**Comment by troosan** [comment]
Isn't this what you are trying to produce?

![image](https://user-images.githubusercontent.com/6959414/50610758-68771100-0ed4-11e9-8190-43bd2577ab3c.png)

**Comment by mmasomi73** [comment]
No, it's exactly reversed, in rtl table columns arranged right to left; first column in right side and last column in left. One solution is arrange columns reverse, but not correct solution; 
![2019-01-03_09-59-00](https://user-images.githubusercontent.com/8652400/50625613-7bbec680-0f3e-11e9-914f-dcc2ee3a2818.png)

**Comment by troosan** [comment]
Oh I see, it's not only the text that should be RTL, it's also the column order.
Can you provide a simple document with just that so I can see the generated XML?

**Comment by troosan** [comment]
I have word 2017 for mac, and I don't seem to have this "table direction" option :-(
But I tried with LibreOffice, where the option is present.
It seems what we need is http://www.datypic.com/sc/ooxml/e-w_bidiVisual-1.html
I'll try to create a pull request for this.

**Comment by mmasomi73** [comment]
yes, Sure. 
[Questions (13).docx](https://github.com/PHPOffice/PHPWord/files/2723224/Questions.13.docx)
this file created with office 2013, and table is rtl.

**Comment by mmasomi73** [comment]
> I have word 2017 for mac, and I don't seem to have this "table direction" option :-(
> But I tried with LibreOffice, where the option is present.
> It seems what we need is http://www.datypic.com/sc/ooxml/e-w_bidiVisual-1.html
> I'll try to create a pull request for this.

Exactly, for rtl table use `<w:bidiVisual/>`

**Comment by troosan** [comment]
@mmasomi73 code has been merged to develop branch.
You can use it by defining the dependency version as "dev-develop"

**Comment by farzadjamshidi** [comment]
Hi @troosan 
how about RTL in table of content?

![Untitled](https://user-images.githubusercontent.com/46782998/65374264-31809f80-dc9d-11e9-9043-049fb64687a4.png)
