### ISSUE TITLE
ParseStyle for border-color

### ISSUE THREAD

**Issue by Gllrm0** [PHPOffice/PHPWord#1551]
In HTML Writer for tables, I trying set style [border-color](https://github.com/PHPOffice/PHPWord/blob/b54f39169e1facb67b4b8cd533812c8fc06dd61a/src/PhpWord/Shared/Html.php#L586-L588) property, but the parseStyle()  should be 
```php
case 'border-color':
 $styles['borderColor'] = trim($cValue, '#');
 break;
```
actually 
```php
case 'border-color':
 $styles['color'] = trim($cValue, '#');
 break;
```

**Comment by troosan** [comment]
Indeed, you are right, actually 'color' does not do anything, should have been bgColor to set the background color.
Ideally we should even be able to parse
```
border-color: red green blue pink;
```
to 
```php
$styles['borderTopColor'] = 'red';
$styles['borderRightColor'] = 'green';
$styles['borderBottomColor'] = 'blue';
$styles['borderLeftColor'] = 'pink';
```
