### ISSUE TITLE
A tag without href causes error in Rels

### ISSUE THREAD

**Issue by 10types** [PHPOffice/PHPWord#1562]
The following causes an error "Invalid parameters passed" in Rels

`HTMLParser::addHtml($section,'<a title="Link to Foo">Foo</a>',false);`

The link above is nonsense logically (no href and no name makes it pointless in HTML) but it's still valid HTML. The lack of href causes an exception rather than (for example) rendering it as unlinked text.

**Comment by branchard** [comment]
The following code also causes an error:
`HTMLParser::addHtml($section,'<a href="#">Foo</a>',false);`

**Comment by santerref** [comment]
Here is a patch I am using to make this working:

```
diff --git a/src/PhpWord/Shared/Html.php b/src/PhpWord/Shared/Html.php
index 4e8dc17..0633f47 100644
--- a/src/PhpWord/Shared/Html.php
+++ b/src/PhpWord/Shared/Html.php
@@ -813,7 +813,11 @@ class Html
         }
         $styles['font'] = self::parseInlineStyle($node, $styles['font']);
 
-        if (strpos($target, '#') === 0) {
+        if(empty($target)) {
+          $target = '#';
+        }
+
+        if (strpos($target, '#') === 0 && strlen($target) > 1) {
             return $element->addLink(substr($target, 1), $node->textContent, $styles['font'], $styles['paragraph'], true);
         }
```
