### ISSUE TITLE
Vector images in phpWord

### ISSUE THREAD

**Issue by landerdominguez** [PHPOffice/PHPWord#1576]
Hi!

I have done an application using phpWord to get my company manuals, but I have an issue with vector images. Engineering area gives me the images in vector format (wmf/emf) and I can't add them to the manuals.

I have tried to convert to png, but I loose a lot of image quality. 

Is there any option to add these kind of images?

Thanks in advance.

**Comment by mynukeviet** [comment]
Up

**Comment by Progi1984** [comment]
Duplicate of #1480
