### ISSUE TITLE
How to download the latest version of PHPWord ?

### ISSUE THREAD

**Issue by lvc2202** [PHPOffice/PHPWord#1580]
Hi all, may I know where to download the latest PHPWord version because I tried clicked on clone or download then it download as old version file. Urgent.

Thanks

**Comment by Progi1984** [comment]
@lvc2202 You can download it with Composer (https://packagist.org/packages/phpoffice/phpword).

The documentation is here : https://github.com/PHPOffice/PHPWord#installation
