### ISSUE TITLE
Dead link in Contributing.md

### ISSUE THREAD

**Issue by ahiijny** [PHPOffice/PHPWord#1582]
In [CONTRIBUTING.md](https://github.com/PHPOffice/PHPWord/blob/edd9617c03888ce4dd2e28c2fcacfad98194f4fc/CONTRIBUTING.md), there's a link that no longer works:

> [Here](https://phpunit.de/presentations.html) you can find PHPUnit best practices and additional information on effective unit testing, which helps us making PHPWord better day to day.

Looking at past web archive snapshots, the "Learn from presentations" link disappeared from the front page of https://phpunit.de/ sometime in [December 2017](http://web.archive.org/web/20171211112139/https://phpunit.de/) (not sure why).

Web archive still has an archived version of that page though: http://web.archive.org/web/https://phpunit.de/presentations.html

**Comment by troosan** [comment]
thanks, I changed the text
