### ISSUE TITLE
HTML Code for Page-Break

### ISSUE THREAD

**Issue by Gzim** [PHPOffice/PHPWord#1601]
This is:

- [x] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpword)

### Expected Behavior

Hi, I just want to generate a simple page break in my DOCX Word Document while using HTML.

### Current Behavior

The different HTML Codes I am using doesn't work.

### How to Reproduce

This is the HTML code I am using. but it does not work! What html code would be accepted to get a pagebreak?

```
<p style="page-break-after: always;">a</p>
```

### Context

* PHP version: 7.1
"phpoffice/phpword": "v0.16.*"

**Comment by Gzim** [comment]
@troosan sorry for directly ping you on this issue, but I have seen in the other issues that you might be the one who can help or give me some hint.

I have seen the write() function for page break on file ..\vendor\phpoffice\phpword\src\PhpWord\Writer\Word2007\Element\PageBreak.php would be the right one to solve my issue

but I don't know how I can call it in my HTML code.

do I have to extend the file ..\vendor\phpoffice\phpword\src\PhpWord\Shared\Html.php so that the style page-break-.. : always; can be rendered or what should I do? if yes: how?

I would appreciate very much some hint or solution because it's difficult to solve it with my low-level programming skills.

thanks beforehand and regards,
gzim

**Comment by Gzim** [comment]
Solved it myself:

If you interested in the solution follow this steps:

1. write following code-statement in your html to force a pagebreak
`<pagebreak></pagebreak>`

extend ..\vendor\phpoffice\phpword\src\PhpWord\Shared\Html.php 
a) 
```
        // Node mapping table
        $nodes = array(
          // $method        $node   $element    $styles     $data   $argument1      $argument2
....
            'pagebreak' => array('PageBreak',   null,   $element,   $styles,    null,   null,           null),
        );
```


b) 
```
   /**
     * Parse page break
     *
     * @param \PhpOffice\PhpWord\Element\AbstractContainer $element
     */
    private static function parsePageBreak($element)
    {
        $element->addPageBreak();
    }
```

**Comment by fahrenheit9** [comment]
Any update on this missing feature ?

**Comment by Yeleup** [comment]
It works for me

`<p style="page-break-after:always;"></p>
`
