### ISSUE TITLE
Invalid link on contributing.md

### ISSUE THREAD

**Issue by jchristlieb** [PHPOffice/PHPWord#1614]
This is:

- [x ] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpword)

### Expected Behavior

A valid link to the suggested best practice with PHPUnit

### Current Behavior

404 page

### Failure Information

Please help provide information about the failure.

### How to Reproduce

1) visit `contributing.md`
https://github.com/PHPOffice/PHPWord/blob/master/CONTRIBUTING.md
2) go the **test your code** section and click on the anchor *here* which tries to open the following page: https://phpunit.de/presentations.html

### Context

* PHP version:
* PHPWord version: 0.14

**Comment by ahiijny** [comment]
I also raised this issue here: https://github.com/PHPOffice/PHPWord/issues/1582

Looks like this was fixed in develop but it hasn't been merged into master yet: https://github.com/PHPOffice/PHPWord/commit/81af913a66d7c508ad2337b2763cbd0c05e106de
