### ISSUE TITLE
samples directory not installed when using composer

### ISSUE THREAD

**Issue by kenrbnsn** [PHPOffice/PHPWord#1626]
This is:

- [x] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpword)

### Expected Behavior

Please describe the behavior you are expecting.

When installing using composer there should be a samples directory as described in the documentation.

I used the command:
composer require phpoffice/phpword

### Current Behavior

What is the current behavior?

The samples directory is missing as can be seen by the output of these commands

$ pwd
/var/www/testphpoffice.sand-box.site/public_html/web/vendor/phpoffice

$ ls -l
total 12
drwxr-xr-x 4 apache apache 4096 May  3 11:12 common
drwxr-xr-x 6 apache apache 4096 May  3 14:16 phppresentation
drwxr-xr-x 3 apache apache 4096 May  3 11:12 phpword

$ ls -l phpword
total 120
-rw-r--r-- 1 apache apache  1123 Dec 29 19:35 bootstrap.php
-rw-r--r-- 1 apache apache 33003 Dec 29 19:35 CHANGELOG.md
-rw-r--r-- 1 apache apache  3242 Dec 29 19:35 composer.json
-rw-r--r-- 1 apache apache  2410 Dec 29 19:35 CONTRIBUTING.md
-rw-r--r-- 1 apache apache 35147 Dec 29 19:35 COPYING
-rw-r--r-- 1 apache apache  7651 Dec 29 19:35 COPYING.LESSER
-rw-r--r-- 1 apache apache   688 Dec 29 19:35 LICENSE
-rw-r--r-- 1 apache apache   363 Dec 29 19:35 phpword.ini.dist
-rw-r--r-- 1 apache apache  9466 Dec 29 19:35 README.md
-rw-r--r-- 1 apache apache   649 Dec 29 19:35 sonar-project.properties
drwxr-xr-x 3 apache apache  4096 Dec 29 19:35 src

### Failure Information

Please help provide information about the failure.
See above

### How to Reproduce
Install using composer

### Context

* PHP version:
$ php -v
PHP 7.2.18 (cli) (built: Apr 30 2019 15:26:52) ( NTS )

* PHPWord version: v0.16.0 (30 dec 2018)

**Comment by troosan** [comment]
Indeed, the samples are not part of the package when installing as a composer dependency.
This is because it is defined in `.gitattributes` as `export-ignore`
The solution is to either
- checkout the code.
- run composer with `--prefer-source` (not tested ...)
