### ISSUE TITLE
Call to undefined method PhpOffice\PhpWord\TemplateProcessor::cloneRowAndSetValues()

### ISSUE THREAD

**Issue by kunoSchlonz** [PHPOffice/PHPWord#1632]
This is:

- [x] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpword)

### Expected Behavior

i try to use this function,
but its not in the release 0.16 

### Current Behavior

What is the current behavior?

### Failure Information

Please help provide information about the failure.

### How to Reproduce

Please provide a code sample that reproduces the issue.

```php
<?php
require __DIR__ . '/vendor/autoload.php';

$phpWord = new \PhpOffice\PhpWord\PhpWord();
$section = $phpWord->addSection();
$section->...
```

### Context

* PHP version:
* PHPWord version: 0.16

**Comment by troosan** [comment]
indeed it's not, you'll have to wait for 0.17, or use the develop version

**Comment by yoedusvany** [comment]
I have installed dev-master version and I have the same error

**Comment by smadrom** [comment]
> I have installed dev-master version and I have the same error

dev-develop
