### ISSUE TITLE
Cannot save/write file

### ISSUE THREAD

**Issue by JulyanoF** [PHPOffice/PHPWord#1663]
When I try to save file of document, I get this error: 
`Warning: ZipArchive::close(): Failure to create temporary file: Permission denied in vendor/phpoffice/phpword/src/PhpWord/Shared/ZipArchive.php on line 163`
My code is this:
```
require 'vendor/autoload.php';
$html = file_get_contents('template.html');
$phpWord = new \PhpOffice\PhpWord\PhpWord();
$section = $phpWord->addSection();
\PhpOffice\PhpWord\Shared\Html::addHtml($section, $html, false, false);
$objWriter = \PhpOffice\PhpWord\IOFactory::createWriter($phpWord, 'Word2007');
$objWriter->save('test.xlsx');
```
I'm running in Ubuntu 18.04 x64 PHP 7.2 and this project is inside apache's folder (/var/www/html/myproject).
I already tried to change entire folder permissions to 0755 and owner to www-data:www-data and myuser:www-data and I got same error

**Comment by liborm85** [comment]
Unrelated to phpword. Problem is in your permissions/privileges.

**Comment by cristianmattar** [comment]
I have the same problem, my permissions are correct, I changed everything to 777, even the vendor for testing, and the error remained. I even tried using the fopen function and everything is correct. It's something with phpworld

**Comment by cristianmattar** [comment]
After a lot of research I got the solution with the commands below. I hope it helps someone

chcon -R -t httpd_sys_content_t /var/www/html/directory_to_write
chcon -R -t httpd_sys_rw_content_t /var/www/html/directory_to_write
