### ISSUE TITLE
Docx to PDF images and styles lost

### ISSUE THREAD

**Issue by shedh** [PHPOffice/PHPWord#1684]
Hi,

Using the following code the temp file has images and the styles but once converted to pdf images and styles are lost

`$phpWord = new \PhpOffice\PhpWord\PhpWord();`
`$rendererLibraryPath = '../composer/vendor/tecnickcom/tcpdf';`
`\PhpOffice\PhpWord\Settings::setPdfRendererPath($rendererLibraryPath);`
`\PhpOffice\PhpWord\Settings::setPdfRendererName('TCPDF');`
`$templateProcessor = new \PhpOffice\PhpWord\TemplateProcessor('./docs/PurchaseOrderTemplate.docx');`
`$templateProcessor->setImageValue('logo', './docs/sigtext.png');`
`$templateProcessor->saveAs('./docs/temp/temp2.docx');`

`$temp = \PhpOffice\PhpWord\IOFactory::load('./docs/temp/temp2.docx');`

`$xmlWriter = \PhpOffice\PhpWord\IOFactory::createWriter($temp , 'PDF');`
 `$xmlWriter->save('./docs/results/sampledocument.pdf', TRUE);`

**Comment by geoffwasham** [comment]
I am also experiencing this issue. I started using PHPWord specifically because the documentation indicated I could use it to hydrate Word docs and then convert them to PDF.

Please update/comment as to the status of this feature.

**Comment by geoffwasham** [comment]
@gpstiip88 Thanks for the suggestion. I've looked into that one, just not a good fit for my web server.

Would love to hear a response from PhpOffice/PhpWord developers.

**Comment by m1stermanager** [comment]
also experiencing this issue. absolutely cannot/will not run word on my servers for something like unoconv to work. not awesome that this is the "standard" php word/office lib?

**Comment by AlanHdz** [comment]
Also experiencing this issue, any updates?

**Comment by AlanHdz** [comment]
also experiencing this issue, any updates?

**Comment by m1stermanager** [comment]
our solution was to make sure that openoffice was available to the app, write the docx, convert to pdf, do whatever w/ the pdf bytes, cleanup temp docx and pdf
