### ISSUE TITLE
How Can I Insert Chart In Tempate ?

### ISSUE THREAD

**Issue by GodShuning** [PHPOffice/PHPWord#1700]
###it is not useful

$asset_industry_distribute_chart = new Chart("pie",["制造业","工业","金融业","农业"],[12,23,45,23]);
$asset_industry_distribute_chart->getStyle()->setWidth(Converter::inchToEmu(2.5))->setHeight(Converter::inchToEmu(2));
$asset_industry_distribute_chart->getStyle()->setShowGridX(false);
$asset_industry_distribute_chart->getStyle()->setShowGridY(false);
$asset_industry_distribute_chart->getStyle()->setShowAxisLabels(false);
$templateProcessor->setComplexBlock('a', $asset_industry_distribute_chart);

**Comment by KingComp** [comment]
...and Image
