### ISSUE TITLE
PHPWord Document Protection

### ISSUE THREAD

**Issue by ashjamieson1** [PHPOffice/PHPWord#1721]
Hi,

I'm wanting to make parts of my word document read-only.  The recipe in the documentation (https://phpword.readthedocs.io/en/latest/general.html#document-protection) states to use the following:

$documentProtection = $phpWord->getSettings()->getDocumentProtection();
$documentProtection->setEditing(DocProtect::READ_ONLY);
$documentProtection->setPassword('myPassword');

When I add the lines to my generation script I get an error:

Fatal error: Class 'DocProtect'

From my composer.json file I'm using version 0.16.0

  "require": {
    "phpoffice/phpword": "^0.16.0"
  }

The document generates fine with the lines removed.  Is this an issue with this version or am I not doing something correctly?

thanks.

**Comment by ashjamieson1** [comment]
It would appear that the documentation is incorrect.  Instead of :

$documentProtection->setEditing(DocProtect::READ_ONLY);

I changed it to:

$documentProtection->setEditing(PhpOffice\PhpWord\SimpleType\DocProtect::READ_ONLY);

With this I can now set the entire document to READ_ONLY but this isn't what I want to be able to achieve.    In my generation script I am looping through HTML content from MySQL and adding each row as a section using \PhpOffice\PhpWord\Shared\Html::addHtml.  How can I set some sections to be read-only whilst allowing editing with track changes in others?

thanks.

**Comment by ashjamieson1** [comment]
This is the code that I have tried:


if ($row_TemplateSection['template_section_title'] == "Services Description"){
                                $stmtDocumentOffering = $genDocx->getDocumentOffering($document_in);

                                while ($row_Offering = $stmtDocumentOffering->fetch(PDO::FETCH_ASSOC)){
                                        extract($row_Offering);

                                        // Loop through the quanity of the particular offering
                                        $offCount=1;
                                        while ($offCount <= $row_Offering['quantity']) {
                                                $msg .= "entering offering loop (".$row_Offering['offering_name']." #".$offCount.")</br>";
                                                $msg .= "Protected</br>";

                                                $filecontents .= $content;
                                                \PhpOffice\PhpWord\Shared\Html::addHtml($section, $content, false, false);
                                                $documentProtection = $phpWord->getSettings()->getDocumentProtection();
                                                $documentProtection->setEditing(PhpOffice\PhpWord\SimpleType\DocProtect::READ_ONLY);
                                                $documentProtection->setPassword('123456');

                                                $offCount++;
                                        }

                                }

                        }else{
                                $filecontents .= $content;
                                \PhpOffice\PhpWord\Shared\Html::addHtml($section, $content, false, false);
                                $documentProtection = $phpWord->getSettings()->getDocumentProtection();
                                $documentProtection->setEditing(PhpOffice\PhpWord\SimpleType\DocProtect::TRACKED_CHANGES);
                        }

**Comment by mtagliab** [comment]
@ashjamieson1 when you tried this
```php
$documentProtection->setEditing(DocProtect::READ_ONLY);
```

did you imported `PhpOffice\PhpWord\SimpleType\DocProtect`? Because your fix is just defining the whole namespace for `DocProtect` instead of importing it.
