### ISSUE TITLE
 How to set the height of the row?

### ISSUE THREAD

**Issue by AntonioTellez** [PHPOffice/PHPWord#1759]
Hello, I am making a table, but all the rows have the same height and I want to make them smaller than they are, I have changed the height parameter when I add a row, but it only works if the value I set is greater than "standard height", but if I try to add a row with a small value, it does not work and the result is a "standard height" row as shown in the image below

![table](https://user-images.githubusercontent.com/58046583/69366209-7607c780-0c5b-11ea-99b5-1924d895b1c4.jpg)

How can I set the height of the row to get a table next where the height of the row is more adjusted to the text?

![table ok](https://user-images.githubusercontent.com/58046583/69366483-12ca6500-0c5c-11ea-9c1e-9be98d674659.jpg)

**Comment by lalop** [comment]
the row is defined when adding the row https://phpword.readthedocs.io/en/latest/elements.html?highlight=addRow#tables

**Comment by SaidkhojaIftikhor** [comment]
Same for me :/

**Comment by ytilotti** [comment]
Hi. Your answer isn't here #223 ?
