### ISSUE TITLE
Abandoned package zendframework/zend-escaper

### ISSUE THREAD

**Issue by Houbsi** [PHPOffice/PHPWord#1797]
### Describe the Bug

Package zendframework/zend-escaper is abandoned, you should avoid using it. Use laminas/laminas-escaper instead.

### Steps to Reproduce

Simply install or update via composer update/composer install

### Expected Behavior

It shouldn't warn for an abandoned package

### Current Behavior

Showing the following warning:
Package zendframework/zend-escaper is abandoned, you should avoid using it. Use laminas/laminas-escaper instead.

### Context

Please fill in your environment information:

- PHP Version: 7.4.1
- PHPWord Version: 0.17.0

**Comment by mbardelmeijer** [comment]
Is there any progress on this?

**Comment by MusaZhou** [comment]
I met the same issue, but the warning changed to error, like below:
_Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for phpoffice/phpword 0.17.0 -> satisfiable by phpoffice/phpword[0.17.0].
    - phpoffice/phpword 0.17.0 requires zendframework/zend-escaper ^2.2 -> no matching package found._

**Comment by eigan** [comment]
This issue should not have been closed. 

@Houbsi Your PR have several issues that you should look into if you would like to have it merged.

**Comment by Houbsi** [comment]
@eigan It's like my first real PR, and i have not enough knowledge about what i need to do to fix the testing. :(

**Comment by sambenne** [comment]
The fix looks correct, it just needs pulling in as the new library appears to be the same but maintained by a new person or group.
