### ISSUE TITLE
how I can convert a phpword template to pdf without losing page format

### ISSUE THREAD

**Issue by FZMOUOMINE** [PHPOffice/PHPWord#1840]
Hey, Can someone help me to convert my phpword template to pdf without losing my docs style, I try DomPDF, MPDF and TCPDF and no one gives me the result that I want

**Comment by ozilion** [comment]
Hi, 

On windows server system installed LibbreOffice beyond Microsoft Office and using code below converting saved teplate .docx file to .pdf file 

`
$tempLibreOfficeProfile = sys_get_temp_dir() . "\\LibreOfficeProfile" . rand(100000, 999999);
            $komut = '"C:\\Program Files\\LibreOffice\\program\\soffice.exe" "-env:UserInstallation=file:///' . str_replace("\\", "/", $tempLibreOfficeProfile) . '" --headless --convert-to pdf "' . $wordfile . '" --outdir "' . $_SESSION['ASETPATH'] . '"';
            exec($komut);
`
This code works as you open file in LibreOffice and save as pdf file but it's all in background.

**Comment by FZMOUOMINE** [comment]
Hey,
Well I use libreOffice and office-converter, you'll find below the steps to convert word file to pdf.
1- install libreOffice from http://www.libreoffice.org/
2- add  'C:\Program Files\LibreOffice\program' to the System environment path.
3 - install office-converter from https://github.com/ncjoes/office-converter
4- update file OfficeConverter.php (set the $bin attribute to 'soffice' in constructor instead of 'libreoffice' line 27 AND at line 233 i change the 'export' to 'set')
5- add this code to your php file 
<?php
// if you are using composer, just use this
use NcJoes\OfficeConverter\OfficeConverter;

$converter = new OfficeConverter('test-file.docx', 'path-to-outdir');
$converter->convertTo('output-file.pdf'); //generates pdf file in same directory as test-file.docx

?>

And finally hope you enjoy it :smiley:

**Comment by iamasafkhan** [comment]
what if I have doc file. not docx

$converter = new OfficeConverter('test-file.doc', 'path-to-outdir');

**Comment by allestaire** [comment]
Try this method, got only got box character, seems like, it does not read font

**Comment by phamquocbuu** [comment]
> Hey, Well I use libreOffice and office-converter, you'll find below the steps to convert word file to pdf. 1- install libreOffice from http://www.libreoffice.org/ 2- add 'C:\Program Files\LibreOffice\program' to the System environment path. 3 - install office-converter from https://github.com/ncjoes/office-converter 4- update file OfficeConverter.php (set the $bin attribute to 'soffice' in constructor instead of 'libreoffice' line 27 AND at line 233 i change the 'export' to 'set') 5- add this code to your php file
> 
> ```
> <?php
> // if you are using composer, just use this
> use NcJoes\OfficeConverter\OfficeConverter;
> 
> $converter = new OfficeConverter('test-file.docx', 'path-to-outdir');
> $converter->convertTo('output-file.pdf'); //generates pdf file in same directory as test-file.docx
> ?>
> ```
> 
> And finally hope you enjoy it 😃

If the PDF layout is broken, the issue might be with the conversion from DOCX to HTML or the rendering of HTML to PDF. To improve the process, you can use `libreoffice` for more accurate conversion from DOCX to PDF. `libreoffice` can be called via command line from PHP, ensuring better preservation of formatting.

Here's how you can do it:

1. **Install LibreOffice**:
   Ensure you have LibreOffice installed on your server. You can install it using the following command:

   ```sh
   sudo apt-get install libreoffice
   ```

2. **Use PHP to call LibreOffice for conversion**:
   Use PHP to execute a command that converts the DOCX file to PDF using LibreOffice.

Here is the PHP script:

```php
<?php
function convertDocxToPdf($docxFilePath, $outputDir)
{
    // Ensure the output directory exists
    if (!is_dir($outputDir)) {
        mkdir($outputDir, 0777, true);
    }

    // Define the output file path
    $pdfFilePath = $outputDir . '/' . pathinfo($docxFilePath, PATHINFO_FILENAME) . '.pdf';

    // Command to convert DOCX to PDF using LibreOffice
    $command = 'libreoffice --headless --convert-to pdf --outdir ' . escapeshellarg($outputDir) . ' ' . escapeshellarg($docxFilePath);

    // Execute the command
    exec($command, $output, $returnVar);

    // Check if the conversion was successful
    if ($returnVar == 0) {
        return $pdfFilePath;
    } else {
        return false;
    }
}

// Usage example
$docxFilePath = 'path/to/your/document.docx';
$outputDir = 'path/to/output/directory';
$pdfFilePath = convertDocxToPdf($docxFilePath, $outputDir);

if ($pdfFilePath) {
    echo 'PDF created successfully: ' . $pdfFilePath;
} else {
    echo 'Failed to create PDF.';
}
?>
```

**Comment by warcooft** [comment]
> export

Thank you, it works! does this work on vps servers?

**Comment by warcooft** [comment]
@FZMOUOMINE Thank you, it works! does this work on vps servers?
