### ISSUE TITLE
Undefined type 'PhpOffice\PhpWord\PhpWord'.

### ISSUE THREAD

**Issue by lluck42** [PHPOffice/PHPWord#1854]
composer require phpoffice/phpword

touch main.php
```
<?
require_once "vendor/autoload.php";
$phpWord = new \PhpOffice\PhpWord\PhpWord();
```
error:
Undefined type 'PhpOffice\PhpWord\PhpWord'.

**Comment by liborm85** [comment]
I'm test your steps, and it works without problems (only enabled short_open_tag is required, see https://stackoverflow.com/a/2185331)

**Comment by lluck42** [comment]
thanks, I can see that. and now it works.

> I'm test your steps, and it works without problems (only enabled short_open_tag is required, see https://stackoverflow.com/a/2185331)
