### ISSUE TITLE
Package zendframework/zend-escaper is abandoned

### ISSUE THREAD

**Issue by arce701** [PHPOffice/PHPWord#1874]
### Describe the Bug

The PHPWord plugin package is abandoned, we have the warning in the console.
"Package zendframework/zend-escaper is abandoned, you should avoid using it. Use laminas/laminas-escaper instead."

### Context

Please fill in your environment information:

 PHP Version:  7.3
- PHPWord Version: 0.17.0

**Comment by lkppo** [comment]
Should be fixed by PR #1844
