### ISSUE TITLE
New line into cell.

### ISSUE THREAD

**Issue by aidam400** [PHPOffice/PHPWord#1880]
Is here any way how to write more that one line into table cell?

Input text:
![print](https://user-images.githubusercontent.com/12350154/84029530-d873ab80-a992-11ea-9885-78716dccfab6.png)

Result:
![result](https://user-images.githubusercontent.com/12350154/84029544-dc9fc900-a992-11ea-8e82-a3d12bbb16d5.png)

Should looks like:
![Should looks like](https://user-images.githubusercontent.com/12350154/84029775-3d2f0600-a993-11ea-854d-2c1c48468769.png)

**Comment by Yavro** [comment]
Yes, it is possible. You can use separate addText() calls. Something like this:
```
$table->addRow();
$cell = $table->addCell(30);
$cell->addText('First line.');
$cell->addText('Second line.');
```

**Comment by aidam400** [comment]
Thanks
