### ISSUE TITLE
afterSpace has not any effect in table

### ISSUE THREAD

**Issue by ghost** [PHPOffice/PHPWord#1884]
What am I doing wrong?
Code:
![image](https://user-images.githubusercontent.com/12350154/84651861-e84b3c80-af0a-11ea-9d60-3f94de0bfbd7.png)

Result:
![image](https://user-images.githubusercontent.com/12350154/84651556-7541c600-af0a-11ea-96ff-63c1d3093266.png)

Expected result:
![image](https://user-images.githubusercontent.com/12350154/84651646-96a2b200-af0a-11ea-80c9-2a67b902eb7b.png)

**Comment by mrcnpdlk** [comment]
It is different between using styles for table/cell/paragraph.
You can read the documentation or (better) look the used classes. For example:
`PhpOffice\PhpWord\Style\Table`, `PhpOffice\PhpWord\Style\` & `PhpOffice\PhpWord\Style\Paragraph`

In my opinion you should set `spaceAfter` property for Paragraph style not for Table style. Table style doesnt have this property.

**Comment by volhardend** [comment]
hey! I fixed it doing this: 
```
$phpWord->setDefaultParagraphStyle(
	array(
		'alignment' => \PhpOffice\PhpWord\SimpleType\Jc::BOTH,
		'spaceAfter' => \PhpOffice\PhpWord\Shared\Converter::pointToTwip(0),
		'spacing' => 120,
	)
);
```
