### ISSUE TITLE
Corrupted Doc xmlParseEntityRef: no name

### ISSUE THREAD

**Issue by SylvanoTombo** [PHPOffice/PHPWord#1898]
### Describe the Bug
The generated doc is corrupted, giving SaxException: [word/document.xml line 2]: xmlParseEntityRef: no name

### Steps to Reproduce

I don't know exactly what's going on but i have a word template and change all variables inside the template and generate a new doc.
```php
<?php
        $phpword = new TemplateProcessor($file);

        foreach ($phpword->getVariables() as $variable)
        {
            $phpword->setValue('${' . $variable .'}',array_key_exists($variable, $information) ? $information[$variable] : '');
        }

        $phpword->saveAs($filename);

        $this->createFolderForGeneratedContractIfNotExists($fullFilePath);

        rename($filename, $fullFilePath);
```
- PHP Version: 7.2
- PHPWord Version: "^0.17.0"

**Comment by SylvanoTombo** [comment]
This is problem related to escaping("&", "<")..For those who encounter the same problem, a better solution is to add the following line of code before you do anything with the word document:
```php
<?php

      PhpOffice\PhpWord\Settings::setOutputEscapingEnabled(true);
      ....
```

This will automatically escape any problematic characters.

**Comment by thibaut-decherit** [comment]
I have the same issue, `PhpOffice\PhpWord\Settings::setOutputEscapingEnabled(true);` does not resolve it, I still get that error because a variable is replaced by a string containing `&`.

I tried adding that line before then after `$phpword = new TemplateProcessor($file);`, no change.
