### ISSUE TITLE
How to get Auto-numbering docx to html?

### ISSUE THREAD

**Issue by BoldErdene1221** [PHPOffice/PHPWord#1911]
![SharedScreenshot](https://user-images.githubusercontent.com/50978688/88866461-5f2f6100-d23d-11ea-8a25-daa394266f3d.jpg)
Left side input
Right side output
Code:
`<?php

require_once './vendor/autoload.php';

$fileTmp = './test03.docx';

$phpWord = \PhpOffice\PhpWord\IOFactory::load($fileTmp);

$objWriter = \PhpOffice\PhpWord\IOFactory::createWriter($phpWord, 'HTML');

$objWriter->save('test4.html');

?>`

**Comment by Surenkhordorj** [comment]
.

**Comment by Surenkhordorj** [comment]
.

**Comment by mleppik** [comment]
Currently I don't think you can - looking at the source of HTML ListItem writer:
https://github.com/PHPOffice/PHPWord/blob/develop/src/PhpWord/Writer/HTML/Element/ListItem.php#L43

It is just a Paragraph element.

**Comment by BoldErdene1221** [comment]
> Currently I don't think you can - looking at the source of HTML ListItem writer:
> https://github.com/PHPOffice/PHPWord/blob/develop/src/PhpWord/Writer/HTML/Element/ListItem.php#L43
> 
> It is just a Paragraph element.

Ok, thank you
