### ISSUE TITLE
Tempate - Modify checkbox value

### ISSUE THREAD

**Issue by poitierjohan** [PHPOffice/PHPWord#1929]
Hi,
I have in my template *.docx an input type CheckBox.
But, I want to modify this value for my final document.
Is that possible ?
Actually, i use a Wingdings text.
Thank you for your answers...

**Comment by ozilion** [comment]
Hi,

As i commented your previous issue here [https://github.com/PHPOffice/PHPWord/issues/1791#issuecomment-569919076](url)  you can modify state of checkbox in your teamplates. Also you can use my modifed TemplateProcessor.php file it's for v0.17 so no need to change your file if you are using latest version. And sending an example template docx includes several checkboxes that i use.

[template.docx](https://github.com/PHPOffice/PHPWord/files/5179286/template.docx)

[TemplateProcessor.zip](https://github.com/PHPOffice/PHPWord/files/5179283/TemplateProcessor.zip)

**Comment by poitierjohan** [comment]
Hi,

Thank you for your answer.
I try your code, bu I have an symfony error :

Cannot autowire service "App\Controller\TemplateProcessor": argument
"$documentTemplate" of method "__construct()" is type-hinted "string", you
should configure its value explicitly.

I use PhpWord V0.17 ; Symfony 4.4

Do you have a solution ?

Thank you !

Le dim. 6 sept. 2020 à 11:01, Özcan ARSLAN <notifications@github.com> a
écrit :
