### ISSUE TITLE
& in $replace string using TemplateProcessor->setValue($search, $replace) corrupts .docx files

### ISSUE THREAD

**Issue by yoieh** [PHPOffice/PHPWord#1942]
### Describe the Bug

Using a `&` character in a $replace string of the `setValue($search, $replace)` function creates a corrupt .docx file.

### Steps to Reproduce

```php

<?php
require __DIR__ . '/vendor/autoload.php';

$templateProcessor = new TemplateProcessor("template.docx");
$templateProcessor->setValue("placeholder", "Foo & bar"); // <========== cant use & character
$templateProcessor->saveAs("name.docx");

```
Then try to open the file in word.

### Expected Behavior

The character needs escaping or not allowed and a error should be thrown.

### Current Behavior

It creates a corrupted .docx's file and cant be open in word.

### Context

Please fill in your environment information:

Using it in a projekt with lumen but it should not make any difference.

- php: ^7.2
- phpoffice/phpword: ^0.17.0
- laravel/lumen-framework: ^6.0

**Comment by liborm85** [comment]
Special characters need escape.
Example:
```php
$templateProcessor = new TemplateProcessor("template.docx");
$xmlEscaper = new \PhpOffice\PhpWord\Escaper\Xml();
$templateProcessor->setValue("placeholder", $xmlEscaper->escape("Foo & bar"));
$templateProcessor->saveAs("name.docx");
```

Or enable escaping everywhere:
```php
\PhpOffice\PhpWord\Settings::setOutputEscapingEnabled(true);
```
