### ISSUE TITLE
Package zendframework/zend-escaper is abandoned, you should avoid using it. Use laminas/laminas-escaper instead.

### ISSUE THREAD

**Issue by hulang** [PHPOffice/PHPWord#1944]
Use laminas/laminas-escaper instead.

**Comment by liborm85** [comment]
Fixed in PR https://github.com/PHPOffice/PHPWord/pull/1946

**Comment by hulang** [comment]
@liborm85 The question is when to merge。。。

**Comment by liborm85** [comment]
I don't know... I don't have permissions to merge this project... It's to @troosan or @Progi1984.
