### ISSUE TITLE
Supported PHP version

### ISSUE THREAD

**Issue by stephanvierkant** [PHPOffice/PHPWord#1948]
I see this library still supports very old versions of PHP. What's this library's policy around this? PhpSpreadsheet doesn't support PHP <7.2.

I think we should follow PHP's supported versions list: https://www.php.net/supported-versions.php

Still supporting 7.1 already is a stupid idea, still supporting PHP 5 is insane.

**Comment by liborm85** [comment]
Older PHP versions no longer need support, I agree with drop. If someone uses old versions of PHP they usually don't update libraries.

Support PHP 7.2+ versions sounds reasonable. I could work on it, but I'm not the maintainer of this repo and do not have any rights. That must be decided by @troosan.

**Comment by stephanvierkant** [comment]
I can create a PR if agreed. Let's add it to README.md that PHPOffice only supports [Supported Versions](https://www.php.net/supported-versions.php).

**Comment by stephanvierkant** [comment]
Nevermind.
