### ISSUE TITLE
PHP 8

### ISSUE THREAD

**Issue by MrElLeRm** [PHPOffice/PHPWord#1979]
Hello, when you plan include php8 support? I'm trying to install this lib to my project, but installation was rejected ...(((

**Comment by liborm85** [comment]
I prepared PR https://github.com/PHPOffice/PHPWord/pull/1946, now we are waiting to @troosan for merge.

**Comment by michaljusiega** [comment]
Friendly ping @troosan - let's release `0.18.0` version please ;)

**Comment by shaoqi** [comment]
when you plan include php8.0.1 support?

**Comment by liborm85** [comment]
Support for PHP 8.0 is prepared id master. We pending to release... Can only @troosan

**Comment by stephanvierkant** [comment]
We should consider this package unmaintained if there is just on maintainer. Anyone interesting in creating/maintaining a fork? I'd hoped PHPOffice (as an organisation) would take responsibility, but they won't: https://github.com/PHPOffice/PhpSpreadsheet/issues/1765

**Comment by liborm85** [comment]
I hope we don't have to create a fork.

**Comment by stephanvierkant** [comment]
I hope so too, but we're waiting for a PHP 8 release for 4 months now. What happens in case of a security issue?

**Comment by michaljusiega** [comment]
Yesterday, @troosan was active in this repo :)

**Comment by troosan** [comment]
Yes I am!
Sorry for the delay. Will prepare the release ASAP.

**Comment by stephanvierkant** [comment]
Do you still want to maintain this package in the future?
