### ISSUE TITLE
Read entire file

### ISSUE THREAD

**Issue by kvovadis** [PHPOffice/PHPWord#1997]
Hello,
When i tried to open docx file with PHPWord and then export it to HTML atleast 30% of document data missing. Can you help me figure it out ?
Thanks in advance.
Mark

**Comment by liborm85** [comment]
Any example of issue?

**Comment by kvovadis** [comment]
require_once('Vendor\autoload.php');

$source = 'test.docx';

$phpWord = \PhpOffice\PhpWord\IOFactory::load($source, 'Word2007');
$htmlWriter = new \PhpOffice\PhpWord\Writer\HTML($phpWord);
$htmlWriter->save('test.html');

**Comment by kvovadis** [comment]
Oh.. I think i found solution.. in my Word file were "bullet points" which cannot be parsed. When i removed everything works.
