### ISSUE TITLE
Replacing laminas/laminas-zendframework-bridge without providing its functionality breaks packages

### ISSUE THREAD

**Issue by mussbach** [PHPOffice/PHPWord#2028]
### Describe the Bug
In f2516b08b146da9b2be6 (#1946) was introduced that this package replaces `laminas/laminas-zendframework-bridge`. I do not really understand why this package should be replaced by phpword, which is especially weird as newly required `laminas/laminas-escaper` itself requires `laminas/laminas-zendframework-bridge`

In my opinion #1946 breaks setups where other libraries need `laminas/laminas-zendframework-bridge`. I am a bit hesitating, as no one else seems to have this problem. Perhaps anybody could help me to understand, what happens here?

### Steps to Reproduce

Install phpword 0.18 in a setup with a package requiring the bridge. Then call anything.

### Expected Behavior

Nothing should break

### Current Behavior

A fatal error occurs `Attempted to load class "ClassGenerator" from namespace "Zend\Code\Generator".
Did you forget a "use" statement for e.g. "Laminas\Code\Generator\ClassGenerator"`

### Context

Please fill in your environment information:

- PHP Version: 7.3
- PHPWord Version:  0.18

**Comment by liborm85** [comment]
Package `laminas/laminas-zendframework-bridge` is replaced/removed because PHPWord uses new `Laminas` namespace and bridge for deprecated `Zend` namespace is not required.

**Comment by mussbach** [comment]
Yes, of course, fair enough, but why does composer.json claims that phpword replaces the bridge via
`"replace": {
        "laminas/laminas-zendframework-bridge": "*"
    }, `

**Comment by damienlaguerre** [comment]
I'm agree with @mussbach, the replacement breaks compatibility with other packages that need it.
In my case, the problem appears with Drupal.

**Comment by mussbach** [comment]
@troosan would you mind checking this and perhaps publish a version 0.18.1?  Otherwise we could unfortunately not install version 0.18 at all

**Comment by damienlaguerre** [comment]
While waiting for the fix, you can use an alias as a workaround: https://getcomposer.org/doc/articles/aliases.md

**Comment by mussbach** [comment]
Thank you @damienlaguerre, this is a good idea
