### ISSUE TITLE
PHPWord generated documents have a border around images in LibreOffice Writer

### ISSUE THREAD

**Issue by prescriptionlifeline** [PHPOffice/PHPWord#2031]
### Describe the Bug

PHPWord generated documents have a border around images in LibreOffice Writer. This border is not present in Microsoft Word and I do not want it to be present

### Steps to Reproduce

Please provide a code sample that reproduces the issue.

```php
<?php
require __DIR__ . '/vendor/autoload.php';

use \PhpOffice\PhpWord\PhpWord;

$PHPWord = new PhpWord();
$section = $PHPWord->createSection();
$section->addImage('logo.png');

$PHPWord->save('test.docx', 'Word2007');
```
For the purposes of this demo I used https://www.google.com/images/branding/googlelogo/2x/googlelogo_color_272x92dp.png as the local logo.png.

### Expected Behavior

This is how it looks in Microsoft Word:

![image](https://i.stack.imgur.com/Cdtpv.png)

### Current Behavior

This is how it looks in LibreOffice Writer:

![image](https://i.stack.imgur.com/x76D9.png)

LibreOffice Writer _is_ perfectly capable of showing images in Word documents without borders. Case in point: it does so with documents created with Microsoft Word 2019 and with documents it generates itself.

### Context

Please fill in your environment information:

- PHP Version: 7.4.9
- PHPWord Version: 0.18.0
- Microsoft Word: 2019
- LibreOffice Writer: 7.0.1.3

Here are the files:

[PHPWord 0.18.0 generated document](https://github.com/PHPOffice/PHPWord/files/6084147/phpword.docx)
[Microsoft Word 2019 generated document](https://github.com/PHPOffice/PHPWord/files/6084161/microsoft.docx)
[LibreOffice Writer 7.0.1.3 generated document](https://github.com/PHPOffice/PHPWord/files/6084210/libreoffice.docx)

**Comment by prescriptionlifeline** [comment]
Here's the word/document.xml that Microsoft Word 2019 produced:

https://pastebin.com/U6nRZ8WC

Here's the word/document.xml that PHPWord 0.18.0 produced:

https://pastebin.com/7dYUHrtj

Here's the word/document.xml that LibreOffice 7.0.1.3 produced:

https://pastebin.com/faWmmdZr

I note that only PHPWord uses `v:data` or `v:imageshape`.

**Comment by madeingnecca** [comment]
I can confirm this issue.

**Comment by kamilmmach** [comment]
I've created a PR #2021 that solves this issue

**Comment by madeingnecca** [comment]
Patched Phpword using the PR's patch and it worked great, thanks.
