### ISSUE TITLE
How to dynamically output multiple tables in a template?

### ISSUE THREAD

**Issue by phptools** [PHPOffice/PHPWord#2065]
![image](https://user-images.githubusercontent.com/12751078/115195899-e3a27680-a121-11eb-8d36-2df7f6c46063.png)

**Comment by phptools** [comment]
$count = count($productList);
        // clone block
        $templateProcessor->cloneBlock('productions', $count, true, true);

        // set block
        foreach ($productList as $key => $value) {
            $search = 'fundInfo#' . ($key + 1);
            $table = $this->getTable($value);
            
            $templateProcessor->setComplexBlock($search, $table);
        }

**Comment by jorge-koki** [comment]
Hello, could you give more details about this? What does the function $this->getTable($value);
