### ISSUE TITLE
PHP8 support

### ISSUE THREAD

**Issue by simivar** [PHPOffice/PHPWord#2105]
### Is your feature request related to a problem? Please describe.

Currently, PHPWord is installable on PHP8 but the tests fail to run as it's installed with PHPUnit 4.8.36 which uses `each()` function removed from PHP in version 8. 

### Describe the solution you'd like

We have to allow PHPUnit of version `^8.0|^9.0` so we can run tests on PHP8 but... in version 8 return types were added so we have to as well remove support for PHP lower than 7.1.

- [ ] require PHPUnit >= 8.0
- [ ] require PHP >= 7.1

**Comment by liborm85** [comment]
PHP 8.0 is supported with following two hacks.

PHPUnit 8 is installed on PHP 8.0 now with this hack:
https://github.com/PHPOffice/PHPWord/blob/0.18.2/.github/workflows/ci.yml#L46-L47

And tests are transformed with this hack:
https://github.com/PHPOffice/PHPWord/blob/0.18.2/.github/workflows/ci.yml#L55-L63

After drop support PHP 5.x, 7.0 and 7.1 in library can be rewritten to a clean solution.
