### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by siwinski** [PHPOffice/PHPWord#211]
What is the license for this library?  [composer.json lists "LGPL-3.0+"](https://github.com/PHPOffice/PHPWord/blob/b937786cfd4c53eb272f703769b80a1023698c9e/composer.json#L11) but the files list LGPL v2.1 (see below)

$ grep -r '@license' PHPWord-b937786cfd4c53eb272f703769b80a1023698c9e
PHPWord-b937786cfd4c53eb272f703769b80a1023698c9e/src/PhpWord/Style/Tabs.php: \* @license    http://www.gnu.org/licenses/old-licenses/lgpl-2.1.txt    LGPL
PHPWord-b937786cfd4c53eb272f703769b80a1023698c9e/src/PhpWord/Style/TOC.php: \* @license    http://www.gnu.org/licenses/old-licenses/lgpl-2.1.txt    LGPL
PHPWord-b937786cfd4c53eb272f703769b80a1023698c9e/src/PhpWord/Style/Font.php: \* @license    http://www.gnu.org/licenses/old-licenses/lgpl-2.1.txt    LGPL
PHPWord-b937786cfd4c53eb272f703769b80a1023698c9e/src/PhpWord/Style/Image.php: \* @license    http://www.gnu.org/licenses/old-licenses/lgpl-2.1.txt    LGPL
PHPWord-b937786cfd4c53eb272f703769b80a1023698c9e/src/PhpWord/Style/Paragraph.php: \* @license    http://www.gnu.org/licenses/old-licenses/lgpl-2.1.txt    LGPL
PHPWord-b937786cfd4c53eb272f703769b80a1023698c9e/src/PhpWord/Style/Cell.php: \* @license    http://www.gnu.org/licenses/old-licenses/lgpl-2.1.txt    LGPL
PHPWord-b937786cfd4c53eb272f703769b80a1023698c9e/src/PhpWord/Style/ListItem.php: \* @license    http://www.gnu.org/licenses/old-licenses/lgpl-2.1.txt    LGPL
PHPWord-b937786cfd4c53eb272f703769b80a1023698c9e/src/PhpWord/Style/Row.php: \* @license    http://www.gnu.org/licenses/old-licenses/lgpl-2.1.txt    LGPL
PHPWord-b937786cfd4c53eb272f703769b80a1023698c9e/src/PhpWord/Style/Table.php: \* @license    http://www.gnu.org/licenses/old-licenses/lgpl-2.1.txt    LGPL
PHPWord-b937786cfd4c53eb272f703769b80a1023698c9e/src/PhpWord/Style/Tab.php: \* @license    http://www.gnu.org/licenses/old-licenses/lgpl-2.1.txt    LGPL
PHPWord-b937786cfd4c53eb272f703769b80a1023698c9e/src/PhpWord/Section/Text.php: \* @license    http://www.gnu.org/licenses/old-licenses/lgpl-2.1.txt    LGPL
PHPWord-b937786cfd4c53eb272f703769b80a1023698c9e/src/PhpWord/Section/Object.php: \* @license    http://www.gnu.org/licenses/old-licenses/lgpl-2.1.txt    LGPL
PHPWord-b937786cfd4c53eb272f703769b80a1023698c9e/src/PhpWord/Section/Footer/PreserveText.php: \* @license    http://www.gnu.org/licenses/old-licenses/lgpl-2.1.txt    LGPL
PHPWord-b937786cfd4c53eb272f703769b80a1023698c9e/src/PhpWord/Section/Image.php: \* @license    http://www.gnu.org/licenses/old-licenses/lgpl-2.1.txt    LGPL
PHPWord-b937786cfd4c53eb272f703769b80a1023698c9e/src/PhpWord/Section/Footer.php: \* @license    http://www.gnu.org/licenses/old-licenses/lgpl-2.1.txt    LGPL
PHPWord-b937786cfd4c53eb272f703769b80a1023698c9e/src/PhpWord/Section/ListItem.php: \* @license    http://www.gnu.org/licenses/old-licenses/lgpl-2.1.txt    LGPL
PHPWord-b937786cfd4c53eb272f703769b80a1023698c9e/src/PhpWord/Section/Footnote.php: \* @license    http://www.gnu.org/licenses/old-licenses/lgpl-2.1.txt    LGPL
PHPWord-b937786cfd4c53eb272f703769b80a1023698c9e/src/PhpWord/Section/TextRun.php: \* @license    http://www.gnu.org/licenses/old-licenses/lgpl-2.1.txt    LGPL
PHPWord-b937786cfd4c53eb272f703769b80a1023698c9e/src/PhpWord/Section/PageBreak.php: \* @license    http://www.gnu.org/licenses/old-licenses/lgpl-2.1.txt    LGPL
PHPWord-b937786cfd4c53eb272f703769b80a1023698c9e/src/PhpWord/Section/Header.php: \* @license    http://www.gnu.org/licenses/old-licenses/lgpl-2.1.txt    LGPL
PHPWord-b937786cfd4c53eb272f703769b80a1023698c9e/src/PhpWord/Section/Settings.php: \* @license    http://www.gnu.org/licenses/old-licenses/lgpl-2.1.txt    LGPL
PHPWord-b937786cfd4c53eb272f703769b80a1023698c9e/src/PhpWord/Section/TextBreak.php: \* @license    http://www.gnu.org/licenses/old-licenses/lgpl-2.1.txt    LGPL
PHPWord-b937786cfd4c53eb272f703769b80a1023698c9e/src/PhpWord/Section/Link.php: \* @license    http://www.gnu.org/licenses/old-licenses/lgpl-2.1.txt    LGPL
PHPWord-b937786cfd4c53eb272f703769b80a1023698c9e/src/PhpWord/Section/Table/Cell.php: \* @license    http://www.gnu.org/licenses/old-licenses/lgpl-2.1.txt    LGPL
PHPWord-b937786cfd4c53eb272f703769b80a1023698c9e/src/PhpWord/Section/Table/Row.php: \* @license    http://www.gnu.org/licenses/old-licenses/lgpl-2.1.txt    LGPL
PHPWord-b937786cfd4c53eb272f703769b80a1023698c9e/src/PhpWord/Section/Table.php: \* @license    http://www.gnu.org/licenses/old-licenses/lgpl-2.1.txt    LGPL
PHPWord-b937786cfd4c53eb272f703769b80a1023698c9e/src/PhpWord/Section/Title.php: \* @license    http://www.gnu.org/licenses/old-licenses/lgpl-2.1.txt    LGPL
PHPWord-b937786cfd4c53eb272f703769b80a1023698c9e/src/PhpWord/IOFactory.php: \* @license    http://www.gnu.org/licenses/old-licenses/lgpl-2.1.txt    LGPL
PHPWord-b937786cfd4c53eb272f703769b80a1023698c9e/src/PhpWord/TOC.php: \* @license    http://www.gnu.org/licenses/old-licenses/lgpl-2.1.txt    LGPL
PHPWord-b937786cfd4c53eb272f703769b80a1023698c9e/src/PhpWord/Template.php: \* @license    http://www.gnu.org/licenses/old-licenses/lgpl-2.1.txt    LGPL
PHPWord-b937786cfd4c53eb272f703769b80a1023698c9e/src/PhpWord/Section.php: \* @license    http://www.gnu.org/licenses/old-licenses/lgpl-2.1.txt    LGPL
PHPWord-b937786cfd4c53eb272f703769b80a1023698c9e/src/PhpWord/PhpWord.php: \* @license    http://www.gnu.org/licenses/old-licenses/lgpl-2.1.txt    LGPL
PHPWord-b937786cfd4c53eb272f703769b80a1023698c9e/src/PhpWord/Autoloader.php: \* @license    http://www.gnu.org/licenses/old-licenses/lgpl-2.1.txt    LGPL
PHPWord-b937786cfd4c53eb272f703769b80a1023698c9e/src/PhpWord/Writer/ODText/WriterPart.php: \* @license    http://www.gnu.org/licenses/old-licenses/lgpl-2.1.txt    LGPL
PHPWord-b937786cfd4c53eb272f703769b80a1023698c9e/src/PhpWord/Writer/ODText/Manifest.php: \* @license    http://www.gnu.org/licenses/old-licenses/lgpl-2.1.txt    LGPL
PHPWord-b937786cfd4c53eb272f703769b80a1023698c9e/src/PhpWord/Writer/ODText/Content.php: \* @license    http://www.gnu.org/licenses/old-licenses/lgpl-2.1.txt    LGPL
PHPWord-b937786cfd4c53eb272f703769b80a1023698c9e/src/PhpWord/Writer/ODText/Styles.php: \* @license    http://www.gnu.org/licenses/old-licenses/lgpl-2.1.txt    LGPL
PHPWord-b937786cfd4c53eb272f703769b80a1023698c9e/src/PhpWord/Writer/ODText/Mimetype.php: \* @license    http://www.gnu.org/licenses/old-licenses/lgpl-2.1.txt    LGPL
PHPWord-b937786cfd4c53eb272f703769b80a1023698c9e/src/PhpWord/Writer/ODText/Meta.php: \* @license    http://www.gnu.org/licenses/old-licenses/lgpl-2.1.txt    LGPL
PHPWord-b937786cfd4c53eb272f703769b80a1023698c9e/src/PhpWord/Writer/IWriter.php: \* @license    http://www.gnu.org/licenses/old-licenses/lgpl-2.1.txt    LGPL
PHPWord-b937786cfd4c53eb272f703769b80a1023698c9e/src/PhpWord/Writer/Word2007/WriterPart.php: \* @license    http://www.gnu.org/licenses/old-licenses/lgpl-2.1.txt    LGPL
PHPWord-b937786cfd4c53eb272f703769b80a1023698c9e/src/PhpWord/Writer/Word2007/DocProps.php: \* @license    http://www.gnu.org/licenses/old-licenses/lgpl-2.1.txt    LGPL
PHPWord-b937786cfd4c53eb272f703769b80a1023698c9e/src/PhpWord/Writer/Word2007/Footnotes.php: \* @license    http://www.gnu.org/licenses/old-licenses/lgpl-2.1.txt    LGPL
PHPWord-b937786cfd4c53eb272f703769b80a1023698c9e/src/PhpWord/Writer/Word2007/DocumentRels.php: \* @license    http://www.gnu.org/licenses/old-licenses/lgpl-2.1.txt    LGPL
PHPWord-b937786cfd4c53eb272f703769b80a1023698c9e/src/PhpWord/Writer/Word2007/Document.php: \* @license    http://www.gnu.org/licenses/old-licenses/lgpl-2.1.txt    LGPL
PHPWord-b937786cfd4c53eb272f703769b80a1023698c9e/src/PhpWord/Writer/Word2007/Footer.php: \* @license    http://www.gnu.org/licenses/old-licenses/lgpl-2.1.txt    LGPL
PHPWord-b937786cfd4c53eb272f703769b80a1023698c9e/src/PhpWord/Writer/Word2007/FootnotesRels.php: \* @license    http://www.gnu.org/licenses/old-licenses/lgpl-2.1.txt    LGPL
PHPWord-b937786cfd4c53eb272f703769b80a1023698c9e/src/PhpWord/Writer/Word2007/Rels.php: \* @license    http://www.gnu.org/licenses/old-licenses/lgpl-2.1.txt    LGPL
PHPWord-b937786cfd4c53eb272f703769b80a1023698c9e/src/PhpWord/Writer/Word2007/Styles.php: \* @license    http://www.gnu.org/licenses/old-licenses/lgpl-2.1.txt    LGPL
PHPWord-b937786cfd4c53eb272f703769b80a1023698c9e/src/PhpWord/Writer/Word2007/Header.php: \* @license    http://www.gnu.org/licenses/old-licenses/lgpl-2.1.txt    LGPL
PHPWord-b937786cfd4c53eb272f703769b80a1023698c9e/src/PhpWord/Writer/Word2007/Base.php: \* @license    http://www.gnu.org/licenses/old-licenses/lgpl-2.1.txt    LGPL
PHPWord-b937786cfd4c53eb272f703769b80a1023698c9e/src/PhpWord/Writer/Word2007/ContentTypes.php: \* @license    http://www.gnu.org/licenses/old-licenses/lgpl-2.1.txt    LGPL
PHPWord-b937786cfd4c53eb272f703769b80a1023698c9e/src/PhpWord/Writer/RTF.php: \* @license    http://www.gnu.org/licenses/old-licenses/lgpl-2.1.txt    LGPL
PHPWord-b937786cfd4c53eb272f703769b80a1023698c9e/src/PhpWord/Writer/Word2007.php: \* @license    http://www.gnu.org/licenses/old-licenses/lgpl-2.1.txt    LGPL
PHPWord-b937786cfd4c53eb272f703769b80a1023698c9e/src/PhpWord/Writer/ODText.php: \* @license    http://www.gnu.org/licenses/old-licenses/lgpl-2.1.txt    LGPL
PHPWord-b937786cfd4c53eb272f703769b80a1023698c9e/src/PhpWord/HashTable.php: \* @license    http://www.gnu.org/licenses/old-licenses/lgpl-2.1.txt    LGPL
PHPWord-b937786cfd4c53eb272f703769b80a1023698c9e/src/PhpWord/Style.php: \* @license    http://www.gnu.org/licenses/old-licenses/lgpl-2.1.txt    LGPL
PHPWord-b937786cfd4c53eb272f703769b80a1023698c9e/src/PhpWord/Reader/IReader.php: \* @license    http://www.gnu.org/licenses/old-licenses/lgpl-2.1.txt    LGPL
PHPWord-b937786cfd4c53eb272f703769b80a1023698c9e/src/PhpWord/Reader/AbstractReader.php: \* @license    http://www.gnu.org/licenses/old-licenses/lgpl-2.1.txt    LGPL
PHPWord-b937786cfd4c53eb272f703769b80a1023698c9e/src/PhpWord/Reader/Word2007.php: \* @license    http://www.gnu.org/licenses/old-licenses/lgpl-2.1.txt    LGPL
PHPWord-b937786cfd4c53eb272f703769b80a1023698c9e/src/PhpWord/DocumentProperties.php: \* @license    http://www.gnu.org/licenses/old-licenses/lgpl-2.1.txt    LGPL
PHPWord-b937786cfd4c53eb272f703769b80a1023698c9e/src/PhpWord/Footnote.php: \* @license    http://www.gnu.org/licenses/old-licenses/lgpl-2.1.txt    LGPL
PHPWord-b937786cfd4c53eb272f703769b80a1023698c9e/src/PhpWord/Media.php: \* @license    http://www.gnu.org/licenses/old-licenses/lgpl-2.1.txt    LGPL
PHPWord-b937786cfd4c53eb272f703769b80a1023698c9e/src/PhpWord/Settings.php: \* @license    http://www.gnu.org/licenses/old-licenses/lgpl-2.1.txt    LGPL
PHPWord-b937786cfd4c53eb272f703769b80a1023698c9e/src/PhpWord/Shared/Font.php: \* @license    http://www.gnu.org/licenses/old-licenses/lgpl-2.1.txt    LGPL
PHPWord-b937786cfd4c53eb272f703769b80a1023698c9e/src/PhpWord/Shared/XMLWriter.php: \* @license    http://www.gnu.org/licenses/old-licenses/lgpl-2.1.txt    LGPL
PHPWord-b937786cfd4c53eb272f703769b80a1023698c9e/src/PhpWord/Shared/Drawing.php: \* @license    http://www.gnu.org/licenses/old-licenses/lgpl-2.1.txt    LGPL
PHPWord-b937786cfd4c53eb272f703769b80a1023698c9e/src/PhpWord/Shared/String.php: \* @license    http://www.gnu.org/licenses/old-licenses/lgpl-2.1.txt    LGPL
PHPWord-b937786cfd4c53eb272f703769b80a1023698c9e/src/PhpWord/Shared/ZipStreamWrapper.php: \* @license    http://www.gnu.org/licenses/old-licenses/lgpl-2.1.txt    LGPL
PHPWord-b937786cfd4c53eb272f703769b80a1023698c9e/src/PhpWord/Exceptions/Exception.php: \* @license    http://www.gnu.org/licenses/old-licenses/lgpl-2.1.txt    LGPL
PHPWord-b937786cfd4c53eb272f703769b80a1023698c9e/src/PhpWord/Exceptions/InvalidImageException.php: \* @license    http://www.gnu.org/licenses/old-licenses/lgpl-2.1.txt    LGPL
PHPWord-b937786cfd4c53eb272f703769b80a1023698c9e/src/PhpWord/Exceptions/InvalidObjectException.php: \* @license    http://www.gnu.org/licenses/old-licenses/lgpl-2.1.txt    LGPL
PHPWord-b937786cfd4c53eb272f703769b80a1023698c9e/src/PhpWord/Exceptions/UnsupportedImageTypeException.php: \* @license    http://www.gnu.org/licenses/old-licenses/lgpl-2.1.txt    LGPL
PHPWord-b937786cfd4c53eb272f703769b80a1023698c9e/src/PhpWord/Exceptions/InvalidStyleException.php: \* @license    http://www.gnu.org/licenses/old-licenses/lgpl-2.1.txt    LGPL

_NOTE: Information was taken from commit [b937786cfd](https://github.com/PHPOffice/PHPWord/tree/b937786cfd4c53eb272f703769b80a1023698c9e) which was the latest commit at the time this issue was submitted._

**Comment by Herz3h** [comment]
Is there any plan to change the license of PhpWord to MIT or similar permissive license like PhpSpreadsheet did  ?

**Comment by cleeev** [comment]
Are there any news on a possible license change to e.g. MIT? I'm currently evaluating the options for a new project and it would definitely need a more permissive license.

It would also be very helpful to know whether this is totally out of question, but since PhpSpreadsheet made the move I'd love to see PhpWord make the change as well!

**Comment by mkazakov** [comment]
Is there a plan for changing the license of PhpWord to MIT?

**Comment by Cruiser13** [comment]
+1 for MIT :-)

**Comment by Herz3h** [comment]
Any news on this ?
