### ISSUE TITLE
HTML text-align style not working when using addHtml()

### ISSUE THREAD

**Issue by BrainforgeUK** [PHPOffice/PHPWord#2115]
### Describe the Bug

HTML text-align style not working.

### Steps to Reproduce

PHP
$phpWord = new \PhpOffice\PhpWord\PhpWord();
$section = $phpWord->addSection();
\PhpOffice\PhpWord\Shared\Html::addHtml($section, $html);

header('Content-Type: application/octet-stream');
header('Content-Disposition: attachment;filename="test.docx"');

$objWriter = \PhpOffice\PhpWord\IOFactory::createWriter($phpWord, 'Word2007');
$objWriter->save('php://output');

HTML
&lt;h1 style="line-height: 23px;text-align: center;font-size: 20px;"&gt;Chapter 27&lt;/h1&gt;

### Expected Behavior

Text to be centred.
Also text-align:right no recognised.

### Current Behavior

Text is left aligned

### Context

- PHP Version: 7.4
- PHPWord Version: Both Libre Office 7.1.4 and online https://office.com

**Comment by BrainforgeUK** [comment]
Found this does not work either - no indentation or italic text
... am I doing something wrong?

&lt;p style="padding-left: 50px;padding-right: 50px;font-style: italic;"&gt;' . trim($matches[1]) . '&lt;/p&gt;

Using these did not work either &lt;center&gt; and &lt;i&gt;

BUT found &lt;sup style="vertical-align: super;"sup&gt;ABCsup&lt;/sup&gt; worked
While &lt;span style="vertical-align: super;"&gt;ABC&lt;/span&gt; did not work.

**Comment by BrainforgeUK** [comment]
For text-align in h1 tags use a p tag instead.
Not ideal as that breaks the link to style Header 1.

**Comment by OussamaKhoubran** [comment]
Any news about this issue, the alignment is not applied on all the heading!
