### ISSUE TITLE
Convert to PDF

### ISSUE THREAD

**Issue by CheeseTastisch** [PHPOffice/PHPWord#2139]
Hey

When I want to convert a Word document into a PDF document, the content is taken with it, but the style is not.
I am using dompdf.

This is my code:

```
\PhpOffice\PhpWord\Settings::setPdfRendererName(\PhpOffice\PhpWord\Settings::PDF_RENDERER_DOMPDF);
\PhpOffice\PhpWord\Settings::setPdfRendererPath('../vendor/dompdf/dompdf');

$reader = \PhpOffice\PhpWord\IOFactory::load('test.docx');

$writer = \PhpOffice\PhpWord\IOFactory::createWriter($reader, 'PDF');
$writer->save('test.pdf');
```

Thanks for your help.

WORD:
![grafik](https://user-images.githubusercontent.com/56408700/132812680-67a31d6e-5b3e-4272-8d68-14ae436297e9.png)

PDF:
![grafik](https://user-images.githubusercontent.com/56408700/132812839-ef14eec3-339c-41dd-89dc-70f6245b53af.png)

**Comment by Jack-ST94** [comment]
This seems more an issue related to dompdf rather then phpword. That said, I had the same issue when trying to convert Word documents to PDF, so I ended up using libreoffice. It's a lengthy process for long documents, but it preserves style and pagination.

**Comment by abuzer** [comment]
@CheeseTastisch, where you able to resolve the issue? Any hint?

**Comment by mspiderv** [comment]
@CheeseTastisch Did you try to use mPDF renderer isntead?

```
$ composer require mpdf/mpdf
```

```
$phpWord = ...;

\PhpOffice\PhpWord\Settings::setPdfRendererName(\PhpOffice\PhpWord\Settings::PDF_RENDERER_MPDF);
\PhpOffice\PhpWord\Settings::setPdfRendererPath('/path/to/your/vendor/mpdf/mpdf');

$writer = \PhpOffice\PhpWord\IOFactory::createWriter($phpWord, 'PDF');
$writer->save('document.pdf');
```

**Comment by brunocerq** [comment]
I have the same issue.
I have tried with MPDF like suggested by @mspiderv but the result is the same, page is generated but all styling is lost.
I'm searching for alternatives.

**Comment by allestaire** [comment]
Got the same issue, style are lost upon convertion

**Comment by blessedjasonmwanza** [comment]
I think [Office converter](https://github.com/ncjoes/office-converter) might be an ideal solution for specifically converting word to pdf docs.
