### ISSUE TITLE
Support Apple's .pages format

### ISSUE THREAD

**Issue by Mouke** [PHPOffice/PHPWord#2190]
### Is your feature request related to a problem? Please describe.

I'm trying to create a text processor file into PDF convertor (so that my app users may upload .docx et related formats to my app without having to convert into PDF). Currently, your library doesn't seem to support Apple's .pages format (the HTML formated has an empty <body> tag).

### Describe the solution you'd like

Being able to pass a .pages document to the HTML writer.

### Describe alternatives you've considered

Searching for an alternate library that would support that format. Or just tell my users "Apple Pages is not supported".

### Additional context

I'm posting that request because i didn't see anything about that among the issues, past and current. If somebody is already trying to work on it, i'm willing to give a hand. I'm also willing to try to do it myself.

**Comment by MarkBaker** [comment]
Unfortunately I don't believe that any of Apple's proprietary formats (pages, numbers, etc) are publicly available; so it would require reverse engineering

**Comment by Mouke** [comment]
I have try to see a bit for myself how those formats work. Unlike the currently supported formats, Apple doesn't rely on XML but on .iwa files, which are compiled. This makes the all process much more complicated.

I will not try to support apple's format on my app, end of story :).
