### ISSUE TITLE
How to specify the color of the legend in the chart?

### ISSUE THREAD

**Issue by yinbug** [PHPOffice/PHPWord#2191]
How to specify the color of the legend in the chart?
I tried the line chart and the column chart according to the example and can't set the legend color.

**Comment by q97585248** [comment]
Maybe
`$chart->getStyle()->setColors( array( 'FFFFFF', '000000', 'FF0000', '00FF00', '0000FF' ) );`
But i  was tested has no effect on radar charts

**Comment by yinbug** [comment]
Thank you for your guidance
