### ISSUE TITLE
Output docx empty file with "<" in content

### ISSUE THREAD

**Issue by lhbao88** [PHPOffice/PHPWord#2215]
### Describe the Bug

When the html content has the character "<", the output file is empty.

### Steps to Reproduce

```php
<?php
require "../../WORD/autoload.php";
$pw = new \PhpOffice\PhpWord\PhpWord();
$section = $pw->addSection();
$html = '1 < 2';
\PhpOffice\PhpWord\Settings::setOutputEscapingEnabled(true);
\PhpOffice\PhpWord\Shared\Html::addHtml($section,$html, false, false);
$pw->save("filename.docx", "Word2007");
```
### Context

- PHP Version: 7.4
- PHPWord Version:  0.18.3

**Comment by raybon-lee** [comment]
`<w:t>>XUG0080TKJPC01319<</w:t>`  In fact，the title is `>XUG0080TKJPC01319<`   ，The generated docx is parsed into an xml file, so, the file cannot be opened

**Comment by raybon-lee** [comment]
set pre  `Settings::setOutputEscapingEnabled(true);`    Applicable to templates and generated word, convert its special characters into html characters
