### ISSUE TITLE
Loaded word file it's content not saving in pdf.

### ISSUE THREAD

**Issue by janmoes96** [PHPOffice/PHPWord#2244]
Hi there,
`
		\PhpOffice\PhpWord\Settings::setPdfRendererPath('src/Controller/PhpWord/lib/dompdf/autoload.inc.php');
		\PhpOffice\PhpWord\Settings::setPdfRendererName('DomPDF');	
		
		$phpWord = \PhpOffice\PhpWord\IOFactory::load($url, 'Word2007');

		$dirname = pathinfo($url, PATHINFO_DIRNAME);

		$filename = time().'.pdf';
		
		$xmlWriter = \PhpOffice\PhpWord\IOFactory::createWriter($phpWord , 'PDF');

		$test = $xmlWriter->save($dirname.'/'.$filename);
		var_dump($test);`

I have this code that allowes me to load a word file. I can see it's content when I dump `$phpWord`, it also creates a pdf file. But the content isn't loaded inside. Instead when you open the pdf, it says something about being corrupt, or couldn't load

**Comment by Progi1984** [comment]
@janmoes96 Hi, Could you send me a file with error, for analyzing it, please ?

**Comment by janmoes96** [comment]
@Progi1984 not needed anymore, I think I fixed it like a week later maybe, can't remember, it's been like 2 year haha

**Comment by Progi1984** [comment]
@janmoes96 Sorry. Maintainer is not a paid job.
