### ISSUE TITLE
How to save lines from "textarea"?

### ISSUE THREAD

**Issue by raxvell** [PHPOffice/PHPWord#2276]
Now all text from "textarea" is saved as just solid text. How can I make the text stay in lines?

`<textarea id="program_description" name="program_description" placeholder="Program description"></textarea>`

`$program_description = $_POST['program_description'];
 
$document->setValue('program_description', $program_description);`

**Comment by TactiFail** [comment]
I actually had the exact same problem yesterday, and I fixed it based off this comment:

https://github.com/PHPOffice/PHPWord/issues/553#issuecomment-757552317

I ended up doing the following in my controller:

```php
public function process_newline_text($string)
{
	$lines = explode("\n", $string);
	$textrun = new TextRun();
	$textrun->addText(array_shift($lines));
	foreach ($lines as $line) {
		$textrun->addTextBreak();
		$textrun->addText(htmlspecialchars($line));
	}
	return $textrun;
}

$templateProcessor = new TemplateProcessor('template.docx');

$templateProcessor->setComplexValue(
	'someField',
	$this->process_newline_text($paragraph)
);

```

The `htmlspecialchars()` is optional, but needed in my situation. I tried to use the setting (I forget which it is) to auto-escape but it did not work for me.
