### ISSUE TITLE
setValue deleting breaklines

### ISSUE THREAD

**Issue by Szmit2** [PHPOffice/PHPWord#2323]
### Describe the Bug

When I use "$document->setValue('TRESC_UMOWY', $tresc_umowy['zasady']);" and save the file, phpword deletes all breaklines in $tresc_umowy['zasady']. How can I prevent that?

### Steps to Reproduce

$tresc_umowy['zasady'] = "
a) loremipsum lorem ipsum
b) lorem ipsum lorem ipsum
"
$document->setValue('TRESC_UMOWY', $tresc_umowy['zasady']);

### Expected Behavior

In word document I expected:

a) loremipsum lorem ipsum
b) lorem ipsum lorem ipsum

### Current Behavior

What I got:
a) loremipsum lorem ipsumb) lorem ipsum lorem ipsum

### Context

Please fill in your environment information:

- PHP Version: 7.2
- PHPWord Version:

**Comment by xpolter** [comment]
Hello

Use str_replace(PHP_EOL, '<w:br/>', $value)

**Comment by lebuhorskiy** [comment]
#2522

**Comment by Progi1984** [comment]
Fixed by #2522
