### ISSUE TITLE
Deprecated: Return type of PhpOffice

### ISSUE THREAD

**Issue by kitechij** [PHPOffice/PHPWord#2324]
### Describe the Bug
in joomla 4.2.5 version

Deprecated: Return type of PhpOffice\PhpWord\Shared\XMLWriter::writeAttribute($name, $value) should either be compatible with XMLWriter::writeAttribute(string $name, string $value): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in F:\XAMPP\htdocs\jml4251\vendor\phpoffice\phpword\src\PhpWord\Shared\XMLWriter.php on line 174

Please fill in your environment information:

- PHP Version: 8.1
- PHPWord Version: 18.3

**Comment by PowerKiKi** [comment]
Fixed in v1.0.0 (via 91416e48ac4bf320fb4c0949ed238d80e94ee41c)
