### ISSUE TITLE
Stop using `develop` branch ?

### ISSUE THREAD

**Issue by PowerKiKi** [PHPOffice/PHPWord#2326]
@Progi1984, I'd like to suggest to entirely drop the `develop` branch, and instead have only a single long-lived branch `master`. All developments can happen in short-lived "feature branch". Since we extensively use PRs already this is already very natural, and only tested PR are merged into `master`. Then `master` can be released whenever it needs to.

Dropping `develop` has the advantage of reduce maintenance noise. When cutting a release, there is nothing to merge anymore, so there isn't any risk of conflicts or merge mistakes. I believe it is also easier for infrequent contributors, because they only have to worry about a single remote branch.

We've been working this way in PhpSpreadsheet for years now, and it was really an improvement for us.

I'll take care of the transition if you agree. What do you think ?

**Comment by Progi1984** [comment]
@PowerKiKi Good idea :+1: I approve it.

**Comment by PowerKiKi** [comment]
Fixed in https://github.com/PHPOffice/PHPWord/commit/d2c6b9f7903e0918bd4119e7d349a5544530689a
