### ISSUE TITLE
Header doesn't start at the top of page

### ISSUE THREAD

**Issue by BackNot** [PHPOffice/PHPWord#2366]
### Describe the Bug

Header is not set to the start of the page. It seems to have a margin which i can't remove.

### Steps to Reproduce

```php
<?php

$phpWord = new \PhpOffice\PhpWord\PhpWord();
$section = $phpWord->addSection();
$header = $section->addHeader();
$header->addText("Header");

```

### Expected Behavior

I expected header to start at the top.

<img width="1262" alt="Screenshot 2023-01-03 at 11 20 37" src="https://user-images.githubusercontent.com/37146282/210961867-5e96fe71-ff2c-4ffa-bb4f-b6ac1a29e8b4.png">

### Context

- PHP Version: 8.1
- PHPWord Version: 1.0

**Comment by MarkBaker** [comment]
Pages have borders in MS Word; and the content for a page is within the page Borders; that includes a page header

![image](https://user-images.githubusercontent.com/770298/211687320-712db078-69dd-4f1f-a1e8-7dfbce63747c.png)

You should be able to set the margins for any section using the [sectionStyle](https://phpword.readthedocs.io/en/latest/containers.html#sections)

**Comment by MarkBaker** [comment]
In addition to the margins, MS Word also has settings for the distance from the top of the page to the Header (and from the bottom of the page to the footer).

![image](https://user-images.githubusercontent.com/770298/212857114-cfc9b190-7a1a-486f-8a83-9c7a60f1d7a4.png)

To render the header at the very top of the page, both the top margin and the header height have to be set to zero.

```php
$phpWord = new \PhpOffice\PhpWord\PhpWord();
$pageMargins = ['marginTop' => 0,
                'marginLeft' => 0,
                'marginRight' => 0,
                'marginBottom' => 0,
                'headerHeight' => 0,
                'footerHeight' => 0,
];
$section = $phpWord->addSection($pageMargins);
$header = $section->addHeader();
$header->addText("HEADER TEXT");
$section->addText("BODY TEXT");
```

![image](https://user-images.githubusercontent.com/770298/212859856-e7288f1c-8ee3-4242-9c88-e38574026306.png)

**Comment by BackNot** [comment]
Thanks, it works that way. I am closing the issue.
