### ISSUE TITLE
fix(phpunit): tests are not successful anymore due to a missing method

### ISSUE THREAD

**Issue by nxtpge** [PHPOffice/PHPWord#2403]
### Describe the Bug

PHPUnit tests with PHP above or equal to version 8.1 are not successful anymore preventing contributions (pull requests) to be validated.

It is caused by the fact that PHPUnit misses the `PHPUnit\Framework\TestCase::setOutputCallback()` method which was available in version [9.6](https://github.com/sebastianbergmann/phpunit/blob/0da2376003743c901b54aa2e7dae3d9dd49edf8c/src/Framework/TestCase.php#L1440) but removed in [10.1](https://github.com/sebastianbergmann/phpunit/blob/e0e14a6eb10e2f94ef87dbd943953b324f11a53e/src/Framework/TestCase.php).

### Steps to Reproduce

- Follow the 5 steps of the ["Getting started" section](https://github.com/PHPOffice/PHPWord/blob/master/CONTRIBUTING.md#getting-started) of the contributing guidelines
- Run :

```shell
composer test-no-coverage
```

### Expected Behavior

Tests are successful.

### Current Behavior

Command's output:

```shell
There were 4 errors:

1) PhpOffice\PhpWordTests\PhpWordTest::testSave
Error: Call to undefined method PhpOffice\PhpWordTests\PhpWordTest::setOutputCallback()

/path/to/repository/PHPWord/tests/PhpWordTests/PhpWordTest.php:125

2) PhpOffice\PhpWordTests\Writer\ODTextTest::testSavePhpOutput
Error: Call to undefined method PhpOffice\PhpWordTests\Writer\ODTextTest::setOutputCallback()

/path/to/repository/PHPWord/tests/PhpWordTests/Writer/ODTextTest.php:106

3) PhpOffice\PhpWordTests\Writer\RTFTest::testSavePhpOutput
Error: Call to undefined method PhpOffice\PhpWordTests\Writer\RTFTest::setOutputCallback()

/path/to/repository/PHPWord/tests/PhpWordTests/Writer/RTFTest.php:107

4) PhpOffice\PhpWordTests\Writer\Word2007Test::testSetGetUseDiskCaching
Error: Call to undefined method PhpOffice\PhpWordTests\Writer\Word2007Test::setOutputCallback()

/path/to/repository/PHPWord/tests/PhpWordTests/Writer/Word2007Test.php:172
```

### Context

- PHP Version: 8.1.18
- PHPWord Version: 1.0.0
- PHPUnit Version: 10.1.3

**Comment by PowerKiKi** [comment]
Fixed by https://github.com/PHPOffice/PHPWord/pull/2404
