### ISSUE TITLE
Is it possible to use this lib to convert docx files to pdf?

### ISSUE THREAD

**Issue by insinfo** [PHPOffice/PHPWord#2411]
Is it possible to use this lib to convert docx files to pdf?

**Comment by cavasinf** [comment]
Using [domPDF](https://github.com/dompdf/dompdf)

```php
// Locate DomPDF vendor
$dompdfPath = $vendorDirPath . '/dompdf/dompdf';

// Set renderer settings
\PhpOffice\PhpWord\Settings::setPdfRenderer(\PhpOffice\PhpWord\Settings::PDF_RENDERER_DOMPDF, $domPdfPath);

// Load docx
$phpWord = \PhpOffice\PhpWord\IOFactory::load($docxPath);

// Write into PDF
$xmlWriter = \PhpOffice\PhpWord\IOFactory::createWriter($phpWord, 'PDF');
```

For better result you can use [unoserve](https://github.com/unoconv/unoserver) that use libreoffice libs directly

**Comment by insinfo** [comment]
in the end I ended up installing libreoffice on the production debian server and using headless to convert docx to PDF, having to install libreoffice on the server for that is pretty bad but at the moment I haven't seen another library that does this in order to preserve the layout, do this without needing libre office just with pure php would be wonderful
