### ISSUE TITLE
Unable to open Word file

### ISSUE THREAD

**Issue by sadhana98** [PHPOffice/PHPWord#2424]
Hi Team,
I am using PHPWord in one of our tool. But unfortunately word document that downloaded using phpword is not opening if the content has & in it, But We should not replace & with **and**
Please suggest any solution.
Thanks,
Sadhana

**Comment by solarsilk** [comment]
try: `$string = htmlspecialchars($string);`

**Comment by sadhana98** [comment]
Thanks a lot @solarsilk, It works fine.
