### ISSUE TITLE
TemplateProcessor bug on SetValue with "&"

### ISSUE THREAD

**Issue by samuel-lujan** [PHPOffice/PHPWord#2441]
### Describe the Bug
When I'm using the TemplateProcessor to change some values on my docx template and the value that I'll set on the place at the ${varaiable} has the char & it brokes the document

### Steps to Reproduce

Please provide a code sample that reproduces the issue.

```php
<?php
require __DIR__ . '/vendor/autoload.php';

$phpWord = new \PhpOffice\PhpWord\PhpWord();

$template = public_path('files/mytemplate.docx');

$word = new TemplateProcessor($template);


$word->setValue('company_name', "Geat&Greater");
```

### Expected Behavior
on the document that I save on my folder it was expected to be with the company name Geat&Greater

### Context

Please fill in your environment information:

- PHP Version: 8.1
- PHPWord Version: "phpoffice/phpword": "^0.18.3",
- Laravel 9

**Comment by samuel-lujan** [comment]
![image](https://github.com/PHPOffice/PHPWord/assets/17858893/b58dc9fe-e735-4e29-ab24-27e4b1fd8172)

**Comment by thomasb88** [comment]
setValue change the data in the xml files of the Word File.
You should replace & by the corresponding xml entity, that is to say
&amp;
I would say.
I guess it should be automatized for all specific xml entities in TemplateProcessor.php

**Comment by thomasb88** [comment]
It seems its should be done in the code there

if (Settings::isOutputEscapingEnabled()) {
            $xmlEscaper = new Xml();
            $replace = $xmlEscaper->escape($replace);
        }

but it seems to be false by default...

**Comment by thomasb88** [comment]
So i would try
Settings::setOutputEscapingEnabled(true);

**Comment by samuel-lujan** [comment]
But from where import this Settings?

**Comment by thomasb88** [comment]
You're welcome -)
