### ISSUE TITLE
Can't read the section heading , only  read and return the text in section, replace section with new line<br>

### ISSUE THREAD

**Issue by malyk-waqar** [PHPOffice/PHPWord#2486]
### Steps to Reproduce

Please provide a code sample that reproduces the issue.

 $phpWord = IOFactory::load($wordFile);
            $wordText = '';

            foreach ($phpWord->getSections() as $section) {
                $elements = $section->getElements();
                $numElements = count($elements);

                foreach ($elements as $key => $element) {
                    if ($element instanceof \PhpOffice\PhpWord\Element\TextRun) {
                        foreach ($element->getElements() as $textElement) {
                            if ($textElement instanceof \PhpOffice\PhpWord\Element\Text) {
                                $wordText .= $textElement->getText();
                            }
                        }
                    } elseif ($element instanceof \PhpOffice\PhpWord\Element\Text) {
                        $wordText .= $element->getText();
                    }

                    // Add a line break if it's not the last element in the section.
                    if ($key < $numElements - 1) {
                        $wordText .= PHP_EOL;
                    }
                }
            }
            $formattedText = $wordText;

### Current Behavior

What is the current behavior?

### Context

Please fill in your environment information:

- PHP Version:
- PHPWord Version:

**Comment by lebuhorskiy** [comment]
To add a line break you need to pass `</w:t><w:br/><w:t>` instead `PHP_EOL`
I saw this in #2522 
I hope this will be added in the next version

**Comment by Progi1984** [comment]
Fixed in #2522
