### ISSUE TITLE
Impossible to read ODT file previously saved by PHPWord as ODText

### ISSUE THREAD

**Issue by ligoo** [PHPOffice/PHPWord#2493]
### Describe the Bug

Returning an empty array of element when trying to read an ODT file that has been saved by PHPWord previously.

### Steps to Reproduce

```php
<?php
require __DIR__ . '/vendor/autoload.php';

// Save
$phpWord = new \PhpOffice\PhpWord\PhpWord();
$section = $phpWord->addSection();
$section->addText('days');
$section->addText('monday');
$section->addText('tuesday');
$writer = \PhpOffice\PhpWord\IOFactory::createWriter($phpWord, 'ODText');
$writer->save('example.odt');

// Load
$reader = IOFactory::createReader('ODText');
$document = $reader->load('example.odt');

dd($document); // dd() laravel sugar but the idea is to inspect $document
```

### Expected Behavior

Should return an array of PhpOffice\PhpWord\Element

### Current Behavior

returns [] in $document->getSection(0)->elements

### Leads
The library can properly read this (that is coming from libre office when creating a document saved as .odt file):
```xml
 <office:body>
  <office:text>
   <text:p text:style-name="P1">days</text:p>
   <text:p text:style-name="P1">monday</text:p>
   <text:p text:style-name="P1">tuesday</text:p>
  </office:text>
 </office:body>
```

but cannot read this (that is coming from the library when saving as .odt):
```xml
 <office:body>
  <office:text>
   <text:section text:style-name="Sect1" text:name="Section1">
    <text:p text:style-name="P1"/>
    <text:p text:style-name="Standard">days</text:p>
    <text:p text:style-name="Standard">monday</text:p>
    <text:p text:style-name="Standard">tuesday</text:p>
   </text:section>
  </office:text>
 </office:body>

```

### Context

Please fill in your environment information:

- PHP Version: 8.2
- PHPWord Version: 1.1.0

**Comment by oleibman** [comment]
FWIW, the document prepared by save appears to be valid; the problem does not lie with Writer/Odt. On the other hand, Reader/Odt has some gaps. At a minimum, Reader/ODText/Content has no support for `text:section` and `text:span` tags, and needs those.
