### ISSUE TITLE
Release 0.12.0

### ISSUE THREAD

**Issue by ivanlanin** [PHPOffice/PHPWord#255]
- [x] Wait that all tickets assigned to [Milestone 0.12.0](https://github.com/PHPOffice/PHPWord/issues?milestone=11&state=open) are closed
- [x] Create the next milestone
- [x] Pull Request from develop to master
- [x] Update the Changelog with date of day
- [x] Release with content from the Changelog.md
- [ ] Tweet the release

**Comment by RomanSyroeshko** [comment]
Hi @Progi1984. You can release the current version (0.12.0) when you are ready with #288.

I suggest 0.13.0 as the next PHPWord version.

Happy New Year!

**Comment by Progi1984** [comment]
Hi @RomanSyroeshko, I move the #288 to 0.13.0.

Happy new year, too for you and all the @PHPOffice/phpword-team !

**Comment by Progi1984** [comment]
PR #460 !

**Comment by Progi1984** [comment]
Tweet : https://twitter.com/Progi1984/status/551313383468044289

**Comment by RomanSyroeshko** [comment]
@Progi1984, could you please tweet also [here](https://twitter.com/phpword)?

**Comment by Progi1984** [comment]
@RomanSyroeshko Done : 
- For PHPWord : https://twitter.com/PHPWord/status/551729935904432128
- For PHPOffice : https://twitter.com/PHPOffice
