### ISSUE TITLE
Version 1.2.0 - Xml parsing error because of "&" char

### ISSUE THREAD

**Issue by helderneves91** [PHPOffice/PHPWord#2553]
### Describe the Bug

I have a word that has variables to be replaced. If the text has an **&**, the word is created with errors, giving the error xml parsing error.
![xml parser](https://github.com/PHPOffice/PHPWord/assets/11777337/b1095dc8-b779-41d1-8880-1400a0db5026)

### Steps to Reproduce

Please provide a code sample that reproduces the issue.

```php
<?php
// Load template into PhpOffice\PhpWord
$template = Storage::disk('orbiapps_sgc')->path('templates/'.$template->file);
$template = new TemplateProcessor($template);

// Replace data
$template->setValue('myname', 'test1 & test2');

// Save a worked copy of the template
$template->saveAs(storage_path('temporary/'.$exportable_file_name));
```

### Context

Please fill in your environment information:

- PHP Version: 8.1
- PHPWord Version: 1.2.0

**Comment by romcrew** [comment]
You need to enable the escape characters feature. Don't know why it is not enabled by default.
In vendor\phpoffice\phpword\src\PhpWord\Settings.php set outputEscapingEnabled to true and it should work.

**Comment by helderneves91** [comment]
> You need to enable the escape characters feature. Don't know why it is not enabled by default. In vendor\phpoffice\phpword\src\PhpWord\Settings.php set outputEscapingEnabled to true and it should work.

Ahh ok, I get it. After searching the docs I found that it's desabled by default for backward compatibility.
We should not mess with vendor folders.

Since I build a template variable with ```$template = new TemplateProcessor($template);``` , is there any way to define the escaping to true?

Thanks
