### ISSUE TITLE
MsDoc reader borks up central europen encoding

### ISSUE THREAD

**Issue by verybigelephants** [PHPOffice/PHPWord#2565]
### Describe the Bug

Hello, when trying to read a .doc file with central european characters (file example here [srncik.zip](https://github.com/PHPOffice/PHPWord/files/14139698/srncik.zip) ) the reader messes up all the diacritics

### Steps to Reproduce

```php
                        $type_word_reader = IOFactory::createReader('MsDoc');
			$text = "";

			$word = $type_word_reader->load($working_file_path);
			foreach($word->getSections() as $section){
				$els = $section->getElements();
				foreach ($els as $el) {			
					$class = get_class($el);
					if (method_exists($class, 'getText')) {
						//i have tried everything, nothing works
						 // \PhpOffice\PhpWord\Shared\Text::toUTF8($el->getText());
						// \ForceUTF8\Encoding; Encoding::fixUTF8($el->getText())); 
						$text .= $el->getText()."\n";
					} else {
						$text .= "\n";
					}
				}
			}
                       file_put_contents('test.log',  $text);
```

### Expected Behavior

not mess up the characters

### Current Behavior

messing up the characters

### Context

Please fill in your environment information:

- PHP Version: 8.2
- PHPWord Version: ^1.2

**Comment by Progi1984** [comment]
@verybigelephants 

This issue has been fixed by a maintainer in the PR #2664. You can help him by sponsoring him through [Github sponsors](https://github.com/sponsors/Progi1984).
