### ISSUE TITLE
Incorrect variable naming conventions

### ISSUE THREAD

**Issue by l4nos** [PHPOffice/PHPWord#2586]
Not so much a bug, as it probablly still "Works".

But poor naming convention used, the headerIndex is reused for footers when it shoud be footerIndex.

TemplateProcessor class line numbers are below.

<img width="1525" alt="image" src="https://github.com/PHPOffice/PHPWord/assets/31861108/7e323a8e-eab2-4888-b5d4-18ec650e6526">

**Comment by Progi1984** [comment]
@efpapado issue has been fixed by a maintainer. You can help him by sponsoring him through [Github sponsors](https://github.com/sponsors/Progi1984).
