### ISSUE TITLE
setValue Multi-Line Value

### ISSUE THREAD

**Issue by martindavis** [PHPOffice/PHPWord#268]
Thank you for the amazing library! This has made my life much easier!

I am using your library to automatically fill out a packing slip. In order to make it easier to maintain and change, I am loading a Word Document as a Template, and then using `setValue()` to update variables. The template I am using has a lot of formatting and I would really prefer to avoid doing it in code if at all possible. It would also make it practically impossible for non-coders to update the template.

The issue I'm having is that I need to insert a multi-line replacement in several places (address, order notes, etc). Are there any plans to implement this in the future? Or am I missing another way to solve this problem, such as XSLT?

I could extend the Template Class with a `setValueForPartMulti()` and if I understand Word's Format correctly, my xml would need to look like the following:

```
 <w:r>
  <w:t>Hello</w:t>
  <w:br/>
  <w:t>world</wt>
</w:r>
```

Could I simply have my custom function `preg_replace('\r\n', '<w:br/>', $value)`? Would any issues arise from doing this?

**Comment by AndyWaters** [comment]
Both of these lines worked for me.

$replace = preg_replace('~\R~u', '</w:t><w:br/><w:t>', $replace);
$replace = preg_replace('~(*BSR_ANYCRLF)\R~', '< w : b r / >', $replace);

However, I had to add into TemplateProcessor.php at line 352 because of a later version.

Thanks Andy

**Comment by kuamatzin** [comment]
Not working for me!

Any suggestions? 

protected function setValueForPart($documentPartXML, $search, $replace, $limit)
    {
        if (substr($search, 0, 2) !== '${' && substr($search, -1) !== '}') {
            $search = '${' . $search . '}';
        }

        if (!String::isUTF8($replace)) {
            $replace = utf8_encode($replace);
        }

        //Lines added
        $replace = preg_replace('~\R~u', '/w:t', $replace);
        $replace = preg_replace('~(*BSR_ANYCRLF)\R~', '< w : b r / >', $replace);

        // Note: we can't use the same function for both cases here, because of performance considerations.
        if (self::MAXIMUM_REPLACEMENTS_DEFAULT === $limit) {
            return str_replace($search, $replace, $documentPartXML);
        } else {
            $regExpDelim = '/';
            $escapedSearch = preg_quote($search, $regExpDelim);
            return preg_replace("{$regExpDelim}{$escapedSearch}{$regExpDelim}u", $replace, $documentPartXML, $limit);
        }
    }

And i'm using it: $document->setValue("hello", "hello \n world"));

**Comment by maninderx** [comment]
@kuamatzin 

Did you get it to work? Where did you put the code?

**Comment by kuamatzin** [comment]
@maninderx No yet =(

**Comment by smandpartners-sipuni** [comment]
@kuamatzin
this worked for me
`
		
		    //Lines added
			$replace = preg_replace('~\R~u', '</w:t><w:br/><w:t>', $replace);
`

**Comment by maninderx** [comment]
@smandpartners-sipuni Thank you. This works.

> `//Lines added
    $replace = preg_replace('~\R~u', '</w:t><w:br/><w:t>', $replace);`

**Comment by mhollander** [comment]
I also found that this line works in setValueForPart():

`$replace = preg_replace('~\R~u', '</w:t><w:br/><w:t>', $replace);`

I put the line at the beginning of the function in v0.13.

Is there a reason that this hasn't been imported into the actual codebase?

**Comment by FBnil** [comment]
@mhollander In version 0.13.0, the setValue('label',"value\nwith\multiline") works for me (linux PHP7 0.13.0). Can you verify or explain to me what does not work?

**Comment by mhollander** [comment]
@FBnil Thank you for looking into this and picking off some of the issues with this project.

I'm using 0.13.0 with PHP Version 7.0.22-0ubuntu0.16.04.1

I just reverted my version of PHPWord to not have my addtion and this still doesn't work.  I am doing a setValue(setValue('label',"value\nwith\nmultiline") and I get "value\nwith\nmultiline" in the actual substitution.  If I have literal newlines in my text string, I have the same problem.

**Comment by FBnil** [comment]
@mhollander  Ok, you are right, it is not PHPWord that add the w:br, it is LibreOffice that automatically fixes it after opening it. I'll do some tests if MSOffice doesn't mind the absence of revision id's (https://blogs.msdn.microsoft.com/brian_jones/2006/12/11/whats-up-with-all-those-rsids/).
I also checked shift-enter (a way to add multiline, in say, a bullet point without going into a new bulletpoint, need to test all at the office. New testcase for the multiline are written and pass.

**Comment by marios88** [comment]
Had exactly the same problem
Libreoffice: displays the files correctly probably by fixing the wrong code on the fly
Ms Office: everything is on a single line

Solutions provided here do the trick, see attached file for a simple extension class that applies the fix

[Phptemplate_withnewline.php.txt](https://github.com/PHPOffice/PHPWord/files/1780769/Phptemplate_withnewline.php.txt)

**Comment by dennisvandenende** [comment]
It seems the solution of @marios88 was not implemented yet, but the error still exists. After adding the code from the Phptemplate_withnewline.php.txt it works like a charm for me.

**Comment by ThBM** [comment]
I used the solution from @FBnil which seems to work fine.

Below is the extended class I use :

```php
use PhpOffice\PhpWord\TemplateProcessor;

class VTemplateProcessor extends TemplateProcessor
{
    protected function setValueForPart($search, $replace, $documentPartXML, $limit)
    {
        // Shift-Enter
        if (is_array($replace)) {
            foreach ($replace as &$item) {
                $item = preg_replace('~\R~u', '</w:t><w:br/><w:t>', $item);
            }
        } else {
            $replace = preg_replace('~\R~u', '</w:t><w:br/><w:t>', $replace);
        }

        return parent::setValueForPart($search, $replace, $documentPartXML, $limit);
    }
}
```
