### ISSUE TITLE
Use Mergefields in template

### ISSUE THREAD

**Issue by totpero** [PHPOffice/PHPWord#272]
Is more correct to use Mergefields  to set the values int template because Mergefields  keep the text format and is more easy to create template and modify.
Is possible to add this feature?
Here is some references:
http://www.codeproject.com/Articles/38575/Fill-Mergefields-in-docx-Documents-without-Microso
http://www.add-in-express.com/creating-addins-blog/2013/09/06/working-with-word-templates/
http://vivekcek.wordpress.com/2012/08/25/create-a-word-document-from-a-template-using-c-mail-merge/

**Comment by dlwatersuk** [comment]
Any progress with this? I'm also interested in this feature but don't know too much about how Word documents are formatted

**Comment by magicleader** [comment]
Any update? Alternatively, is there a way to be able to replace a block of text (or table, image, ...) even after merging the template with the data? I wish to keep the starting reference keys of the template on the resulting word document to be able to edit it again.
