### ISSUE TITLE
default value checked on checkbox

### ISSUE THREAD

**Issue by ahrinal** [PHPOffice/PHPWord#281]
hii all.
i want to create a checkbox with a default value checked in one of that like this
![untitled](https://cloud.githubusercontent.com/assets/7554027/3293264/26bda93a-f599-11e3-9096-6650684c0cce.png)

so, is there any function to do that?? 
thanks so much..

**Comment by sunildora94** [comment]
Use this to add the checked checkbox to the word document,
`$table = $section->addTable();
$cell = $table->addRow()->addCell(1000);

$textrun = $cell->addTextRun();
$textrun->addFormField('checkbox');
$textrun->addText('D');

$textrun = $cell->addTextRun();
$textrun->addFormField('checkbox')->setValue('<w:sym w:font="Wingdings" w:char="F0FE"/>');
$textrun->addText('B');`

This did work for me, hope this will help you guys. :)
