### ISSUE TITLE
no outline textbox

### ISSUE THREAD

**Issue by ahrinal** [PHPOffice/PHPWord#296]
sorry for easy question. 
i want to get a text box with no outline or no border. 
i tried adding that code 
 'borderSize' => 0 , 'borderSize' => false.
but it doesn't work. 
what should I do??.
thank you

**Comment by imagemap788** [comment]
> it looks like the css code 😆 . why didn't i thought like that. btw thank you kang ivan 😄





https://pedro-morrisjs.github.io/gridsome-plugin/
