### ISSUE TITLE
Missing image when convert to pdf file

### ISSUE THREAD

**Issue by nata-ax** [PHPOffice/PHPWord#306]
I have problem in pdf when I running the code which contain image, the image not show in pdf file. Can you help me to fix this problem? Thanks for helping.

**Comment by markcoenradie** [comment]
Same issue here. Images are rendered correctly in the docx, but they're not in the PDF :'(

**Comment by troosan** [comment]
fixed with PR #1074

**Comment by anujak20** [comment]
Same issue. image not display in pdf

**Comment by quadrogod** [comment]
If images miss after convert xls to pdf [i use mpdf writer]

Problem: file converts xls > html -> pdf
When create html, all links writes as zip://

pdf writer can't read zip://image_url_to_xls_file#media/image_resource.png
"mpdf file contains an invalid stream. only http, https, file streams are allowed"

Just create your writer class with fix, and use it.

use PhpOffice\PhpSpreadsheet\Writer\Pdf\Mpdf as OriginalMpdf;
class Mpdf extends OriginalMpdf
{
    private $_embedImagesFixRollback;

    private function applyImageFix()
    {
        $this->isPdf = false;
        $this->_embedImagesFixRollback = $this->getEmbedImages();
        $this->setEmbedImages(true);
    }

    private function rollbackImageFix()
    {
        $this->isPdf = true;
        $this->setEmbedImages($this->_embedImagesFixRollback);
    }

    /**
     * Save Spreadsheet as html to variable.
     *
     * @return string
     */
    public function generateHtmlAll()
    {
        $this->applyImageFix();
        $html = parent::generateHtmlAll();
        $this->rollbackImageFix();
        return $html;;
    }
}
