### ISSUE TITLE
Using table tag in HTML Reader produces no output

### ISSUE THREAD

**Issue by EK1771** [PHPOffice/PHPWord#324]
**Sample Code:**

```
$phpWord = new \PhpOffice\PhpWord\PhpWord();

$section = $phpWord->addSection();

$html = '<table><tr><td>test</td></tr></table>';

\PhpOffice\PhpWord\Shared\Html::addHtml($section, $html);

$objWriter = \PhpOffice\PhpWord\IOFactory::createWriter($phpWord, 'Word2007');
$objWriter->save('test.docx');
```

**Expected Output:**

Table with one cell containing the word "test".

**Actual Output:**

Blank

From stepping through the code quickly, the issue seems to be caused by the following if condition in parseChildNodes():

```
if ($element instanceof AbstractContainer) {
    self::parseNode($cNode, $element, $styles, $data);
}
```

Commenting out the if condition then allows for the sample code above to produce the expected output.

**Comment by matteomoretti** [comment]
Any news? The bug still occours

**Comment by phpnets** [comment]
by using \PhpOffice\PhpWord\Shared\Html::addHtml($section, $html)  we can interpret html to word. Can we set alignment options for this output (such as align right/left/both) ?

**Comment by garethellis36** [comment]
@mogilvie are you able to share your complete and working `Html` class with modifications? I'm trying it myself but when I try and apply it to an updated sample (as below), I get an error when it tries to write because of the objects is null.

```php
 $html .= '<table><thead><tr><th>Header of column 1</th><th>Header of column 2</th></tr></thead>';
$html .= '<tbody><tr><td>Row 1 for column 1</td><td>Row 1 for column 2</td></tr></tbody></table>';
```

**Comment by mogilvie** [comment]
I'll post the full class tonight, but in the meantime, is the error caused by the switch statement not having any code to be executed for case: 'skiphead'?

**Comment by garethellis36** [comment]
@mogilvie I doubt that - it should fall through to the 'skipTbody' case because there's no break statement. I don't fully understand how this works but I *assumed* that thead would need to be handled in the same way as tbody.

**Comment by mogilvie** [comment]
@garethellis36 Agree re skipThead. Is the parseTable function returning the $newElement? It's cut off from the sample html class.

**Comment by mogilvie** [comment]
Html.php uploaded as a text file. It was working as of Jan 2015.

[Html.txt](https://github.com/PHPOffice/PHPWord/files/119668/Html.txt)

**Comment by surindersinghva** [comment]
Thank you, this is very very helpful. The embedded table is printing like charm now. I am still stuck with an embedded nested list, if you can help. There are two issues, 1. List item not printing if <strong> tag is used, 2. Nested list not printing with or without <strong> tags. Here's what I have: <p>The following list has all the information.</p><ol><li><strong>Item 1</strong><ol><li><strong>Nested Item 1</strong></li><li>Nested Item 2</li></ol></li></ol><p>List ends here.</p>

Thank you

**Comment by arrabal** [comment]
@mogilvie Your Html.php works ok, thanks for your work. I had to comment line 61,         $dom->save('/var/www/vhosts/specshaper.com/DOM.xml'); //@TODO Delete Debug

However, the table is generated without borders, even if a set a big "border" value in <table> tag.

Will these fixes be integrated in the main branch?

**Comment by arivanbastos** [comment]
This issue still occurs.

**Comment by danilocarva9** [comment]
How to cellspacing and cellpadding on Html table? It's not working :(
