### ISSUE TITLE
wrappingStyle not working as expected (docx writer, 0.11.1)

### ISSUE THREAD

**Issue by fhaubner** [PHPOffice/PHPWord#325]
Hi,

I have some problems using wrappingStyle in the latest Version of PHPWord. I made a very small example and to me it looks like a problem close to the writer.

``` php
$section = $PHPWord->createSection();
$section->addText("some text");
$image = $section->addImage('../path/to/Image.jpg', array('wrappingStyle' => 'square'));
$section->addText("some more text");
$section->addText("Image Wrapping Style:");
$section->addText($image->getStyle()->getWrappingStyle());
$objWriter = \PhpOffice\PhpWord\IOFactory::createWriter($PHPWord, 'Word2007');
```

The getWrappingStyle method always returns the correct wrappingStyle I set for the image. But the wraping style in the exported document for the image always stays inline.

Thanks in advance and best regards
Florian

**Comment by rajeshbabu54** [comment]
Hello everyone,
I want to add some images and text to existing docx in phpword.I tried with the following code but it is not showing correct.

include_once 'Sample_Header.php';
// New Word document
$name = basename(FILE, '.php');
$source = DIR . "/resources/{$name}.docx";
//$phpWord = new \PhpOffice\PhpWord\PhpWord();
$phpWord1 = \PhpOffice\PhpWord\IOFactory::load($source);
$document = $phpWord1->loadTemplate($source);
$document->saveAs('temp.docx');
$phpWord = \PhpOffice\PhpWord\IOFactory::load('temp.docx'); 
$section = $phpWord->addSection();
$section->addText(htmlspecialchars('Local image without any styles:'));
$section->addImage('resources/_mars.jpg');
$section->addTextBreak(2);
$source = 'http://php.net/images/logos/php-med-trans-light.gif';
$section->addText(htmlspecialchars("Remote image from: {$source}"));
$section->addImage($source);
$xmlWriter = \PhpOffice\PhpWord\IOFactory::createWriter($phpWord , 'Word2007');
$xmlWriter->save('result1234566.docx');

Please send me the code. Please help me out from this problem

Thank you

Rajesh babu
