### ISSUE TITLE
setValue "&" Error 

### ISSUE THREAD

**Issue by Andy-Man** [PHPOffice/PHPWord#333]
Hello,
i'm using PHPWord for templates and it works really good but when i try to write "&" char, generated document won't open.

```php
$document->setValue('OBJ-EX-15', ' Johnson & Johnson');
```
same as
```php
$document->setValue('OBJ-EX-15', ' Johnson&Johnson');
```
Have anyone same bug?

**Comment by GMTA** [comment]
Please see the following issues for a more detailed insight on this topic:
* #401 
* #514

I am positive that you will be able to solve the issue using the information provided above. Good luck!

**Comment by RomanSyroeshko** [comment]
https://github.com/PHPOffice/PHPWord/issues/671#issuecomment-231520458.
