### ISSUE TITLE
Laravel wrapper?

### ISSUE THREAD

**Issue by vadimwe** [PHPOffice/PHPWord#347]
Is any laravel 4x wrapper for your awesome work?

**Comment by shad0wfir3** [comment]
Have you ended up creating a wrapper yet? Im looking at using the library in L5, but still haven't found a package for Laravel to do this.

**Comment by vadimwe** [comment]
Noup, sorry. I used plain PHPWord package as I remember.

**Comment by Progi1984** [comment]
Sorry, it's not the goal of the library.
