### ISSUE TITLE
Source code migration to 5.4 features

### ISSUE THREAD

**Issue by ghost** [PHPOffice/PHPWord#355]
PHP developers [announced](http://php.net/archive/2014.php#id2014-08-14-1) end of life of PHP 5.3. Since now the minimal supported version is 5.4. We should plan migration to PHP 5.4.

Migration guide from PHP 5.3.x to PHP 5.4.x could be found [here](http://php.net/manual/en/migration54.php).

**Comment by Progi1984** [comment]
PHPWord is not anymore compatible PHP 5.4.
