### ISSUE TITLE
Editing an existing doc/docx file. 

### ISSUE THREAD

**Issue by Akhileshvk** [PHPOffice/PHPWord#357]
Is it possible to edit a existing doc/docx file dynamically using PhpWord (add varying header and footer in all pages which is my requirement). If not can anyone give me some suggestions.

Thanks

**Comment by anglo-tech** [comment]
it is not working for doc files

$document = \PhpOffice\PhpWord\IOFactory::load('my.doc');

PHP Error[2]: ZipArchive::getFromName(): Invalid or unitialized Zip object
    in file /var/www/m/www/protected/extensions/phpword/PHPWord/Shared/ZipArchive.php at line 198
#0 /var/www/m/www/protected/extensions/phpword/PHPWord/Shared/ZipArchive.php(198): ZipArchive->getFromName()
#1 /var/www/anglo/www/protected/extensions/phpword/PHPWord/Shared/XMLReader.php(59): PhpOffice\PhpWord\Shared\ZipArchiv
->getFromName()
#2 /var/www/m/www/protected/extensions/phpword/PHPWord/Reader/Word2007.php(144): PhpOffice\PhpWord\Shared\XMLReader
>getDomFromZip()
#3 /var/www/m/www/protected/extensions/phpword/PHPWord/Reader/Word2007.php(109): PhpOffice\PhpWord\Reader\Word2007-
getRels()
#4 /var/www/m/www/protected/extensions/phpword/PHPWord/Reader/Word2007.php(42): PhpOffice\PhpWord\Reader\Word2007->
eadRelationships()
#5 /var/www/m/www/protected/extensions/phpword/PHPWord/IOFactory.php(73): PhpOffice\PhpWord\Reader\Word2007->load()

**Comment by wdog** [comment]
absolute path!

**Comment by ankitcodefarm** [comment]
I am working on the same issue and still after giving absolute path still it's not working

**Comment by TheSpectroMx** [comment]
@ankitcodefarm apparently it doesn't work with '.doc'. If your file has that extension try to update to '.docx', in my use case it worked like this.
