### ISSUE TITLE
Question about Word 2 PDF

### ISSUE THREAD

**Issue by hregis** [PHPOffice/PHPWord#375]
Hello
it's possible to read a docx and convert to pdf ?
i try and i have this error:
Error: Cannot add PreserveText in Cell

Thanks

**Comment by RomanSyroeshko** [comment]
Hi, @hregis. Do you have any news for us? :wink:

**Comment by dellert** [comment]
use unoconv for exporting doc to pdf https://github.com/alchemy-fr/PHP-Unoconv
