### ISSUE TITLE
Numbered List restart / reset

### ISSUE THREAD

**Issue by alpha1125** [PHPOffice/PHPWord#402]
#291 <ol start="50"> quivalent? thread was helpful... but it causes an issue with Word itself.

The code in #291 works, as it should display...  It's been working fine for my needs, until yesterday.  It failed a use case where when the outputted Word document needed to be globally styled.

Since I am giving a new style name, every time I need to start a new list; I cannot use Word to apply the intended format across the whole document.  Since one is called "alpha" and the other is called "beta".  When you have hundreds of these... it becomes pretty tedious.  I have two options, figure out how PHPWord can reset numbered lists, OR, write a VBA macro to do what I need it to do... I prefer the earlier option.

The psuedo code I believe should be as follows:

``` PHP
$phpWord->addNumberingStyle(
    'alphanum',
    array('type' => 'multilevel', 'levels' => array(
        array(
            'format' => 'decimal', 'text' => '%1.',
            'left' => 360, 'hanging' => 360, 'tabPos' => 360),
        )
    )
);

$section->addText('Alpha');
$section->addListItem('List Item 1', 0, null, 'alphanum');
$section->addListItem('List Item 2', 0, null, 'alphanum');
$section->addListItem('List Item 3', 0, null, 'alphanum');

// Something to this effect:
$section->listItemCounterReset('alphanum', 0);

$section->addText('Second List, with the first item restarted at 1');
$section->addListItem('List Item restart at 1', 0, null, 'alphanum');
$section->addListItem('List Item 2', 0, null, 'alphanum');
$section->addListItem('List Item 3', 0, null, 'alphanum');
```

The idea would be to have some sort of functionality like so:

``` php
/**
 * @param string $listStyle list style name
 * @param int $depth depth to reset, default 0;
 */
function listItemCounterReset($listStyle, $depth=0){
    listItemCounterSet($listStyle, $depth, 0);
}

/**
 * @param string $listStyle
 * @param int $depth
 * @param mixed $value alphanum, value to reset to.
 */
function listItemCounterSet($listStyle, $depth=0, $value=0){
    // code to reset values.
}
```

I've tried Style::resetStyles(), and it does set the style... but everything else as well.

Anyone got a solution to this?

**Comment by mapyourproperty** [comment]
We disagree that this is a non-issue.  The numerical listing should absolutely restart in Word.  PHPWord does not restart the "sublisting" in a docx format in Microsoft Word.  So for example, it should list 1. a. b. c. 2. a b., but instead it print out list "1. a. b. c. 2. d. e. f".  As a startup, we use PHPWord to print out list for different regulation policy and this is definitely a bug we really support fixing.  We have been developing code for 12 months using PHPWord and run into this issue alot.  Any support we can provide, please tell us but we only two people (frontend developer & business)

**Comment by alpha1125** [comment]
I worked around this, by starting a new list with the microtime stamp as it's name for each new listing being started.  There was no method()/function() to restart.

**Comment by mapyourproperty** [comment]
So this is a bug with a poor work around (which we ID also).  We can reactivate back to BUG from closed?

**Comment by BonnieDoug** [comment]
My personal workaround was as the list's are processed within a foreach() loop I simply used the $key as a name:

        foreach($lists as $key => $listItem){
           $this->word->addNumberingStyle("list$key", array("format"=>"decimal", "restart"=>true));
           foreach($listItem as $item){
               $section->addListItem($item, 0, null, "list".$key);
           }
        }

**Comment by brutalcrozt** [comment]
@BonnieDoug Clever solutions :heart_eyes:

**Comment by eweso** [comment]
Okay guys, I have a bugfix and will pull a request in 3 weeks, after my holiday. I can show you, how I fixed it. By the way, I will also pull a request for a better HTML Parser, which is traversing through DOM and supports classes. I need to add support for table and images, then it's complete.

You have to modify following files: 

- PhpOffice\PhpWord\Element\AbstractContainer
- PhpOffice\PhpWord\Style\ListItem

Attached you will find the working, but not fully tested, classes.
[ListItemBugfix.zip](https://github.com/PHPOffice/PHPWord/files/1849874/ListItemBugfix.zip)
