### ISSUE TITLE
Error with addHtml() and "&"

### ISSUE THREAD

**Issue by skurty** [PHPOffice/PHPWord#406]
Hi,

I'm trying to create a doc:

> $phpWord = new \PhpOffice\PhpWord\PhpWord();
> $section = $phpWord->addSection();
> \PhpOffice\PhpWord\Shared\Html::addHtml($section, $content);
> $objWriter = \PhpOffice\PhpWord\IOFactory::createWriter($phpWord, 'Word2007');
> $objWriter->save('...');

where $content contains a string with a "&".

I get this error:

> Warning:  DOMDocument::loadXML(): xmlParseEntityRef: no name in Entity, line: 1 in PhpOffice/PhpWord/Shared/Html.php on line 55
> Notice:  Trying to get property of non-object in PhpOffice/PhpWord/Shared/Html.php on line 129
> Notice:  Trying to get property of non-object in PhpOffice/PhpWord/Shared/Html.php on line 169
> Notice:  Trying to get property of non-object in PhpOffice/PhpWord/Shared/Html.php on line 170

I've tried to replace the & by &amp; but same error. If I remove it, no problem.

I'm using the last version of PHPWord.

Thank you

**Comment by chrispen** [comment]
Hi
I am new to PHPWord and  trying to create a doc. I am running PHP 5.6.0 and using latest PHPWord but the document is not created when there is an & and or &amp. I am getting illegal name character error. 
This is part of my code:
//html text
$results = $key['data'][COMPPERSCOPY];
		\PhpOffice\PhpWord\Shared\Html::addHtml($section,$results);

It is working fine when i remove & and &amp. Please help me.
Thank you.

**Comment by jr-cobweb** [comment]
For anyone else encountering this issue, In later versions (0.13 onwards?) you can turn on output escaping which fixes the issue:

Settings::setOutputEscapingEnabled(true)

**Comment by DucCodefactory** [comment]
\PhpOffice\PhpWord\Settings::setOutputEscapingEnabled(true);
