### ISSUE TITLE
Add a Checkbox to a template

### ISSUE THREAD

**Issue by cbloss** [PHPOffice/PHPWord#425]
Hello! 

Loving the power behind PHPWord by the way!! 

I was wondering if there's a way to add a checkbox to a template. I've seen how to do it to a new document, but what about a template? I thought about going the Wingding symbol route, but haven't been able to figure out how to change font styles on a template (well besides opening it up in word and changing the font styles there, but Wingdings..well the symbols don't translate well. 

Can anyone give an tips?

Thanks!

**Comment by yowrosales** [comment]
Still waiting

**Comment by ozilion** [comment]
At least if we can set value of checkbox in template, would be great, too!

**Comment by ozilion** [comment]
I've tried PHPDocx template features. They have function named thickChecboxes to set value of specified checkboxes in templates. Here is the sample code from their trial pro package.

<?php

//path to the CreateDocx class within your PHPDocX installation
require_once '../../../classes/CreateDocx.inc';

$docx = new CreateDocxFromTemplate('../../files/Checkbox.docx');
$docx->setLanguage('tr_TR');

$variables = array('check1' => 1, 'check2' => 0, 'check3' => 1);
$docx->tickCheckboxes ($variables);

$docx->createDocx('example_tickCheckboxes_1');

This function uses variable entered in help string field of checkbox and working like a charm as we expected too :+1: :)

I don't know if already PHPWord has similar feature but may be we can also implement such a way. I could use PHPDocx to check checkboxes but it takes so long time to process. As an example with PHPWord i can finish a job in 10 seconds, with PHPDocx it takes around 2 min and i tested without using tickCheckbox function.

**Comment by Blue-QAQ** [comment]
用setValue把关键字替换成xml代码
//1 or 0  
class checkbox{
    public  function value($value)
    {
        if ($value){
            return '<w:sdt><w:sdtPr><w:rPr><w:rFonts w:eastAsia="华文仿宋" w:hint="eastAsia" /><w:sz w:val="21" /></w:rPr><w:id w:val="-310866052" /><w15:appearance w15:val="hidden" /><w14:checkbox><w14:checked w14:val="1" /><w14:checkedState w14:val="0052" w14:font="Wingdings 2" /><w14:uncheckedState w14:val="00A3" w14:font="Wingdings 2" /></w14:checkbox></w:sdtPr><w:sdtContent><w:r><w:rPr><w:rFonts w:eastAsia="华文仿宋" w:hint="eastAsia" /><w:sz w:val="21" /></w:rPr><w:sym w:font="Wingdings 2" w:char="F052" /></w:r></w:sdtContent></w:sdt>';
        }
        else{
            return '<w:sdt><w:sdtPr><w:rPr><w:rFonts w:eastAsia="华文仿宋" w:hint="eastAsia" /><w:sz w:val="21" /></w:rPr><w:id w:val="-310866052" /><w15:appearance w15:val="hidden" /><w14:checkbox><w14:checked w14:val="1" /><w14:checkedState w14:val="0052" w14:font="Wingdings 2" /><w14:uncheckedState w14:val="00A3" w14:font="Wingdings 2" /></w14:checkbox></w:sdtPr><w:sdtContent><w:r><w:rPr><w:rFonts w:eastAsia="华文仿宋" w:hint="eastAsia" /><w:sz w:val="21" /></w:rPr><w:sym w:font="Wingdings 2" w:char="F0A3" /></w:r></w:sdtContent></w:sdt>';
        } 
    }
}

**Comment by Progi1984** [comment]
Fixed by #2509
