### ISSUE TITLE
Get a blank word document

### ISSUE THREAD

**Issue by smroczek** [PHPOffice/PHPWord#434]
$PHPWord = new PHPWord();
$document = $PHPWord->loadTemplate('./documents/invoice1.docx');
$section = $PHPWord->createSection();
$section->addText( $invname);
$section->addText( $organization_link_record['organization_link_address_1'] );
$section->addText( $organization_link_record['organization_link_address_2'] );
if (!empty( $organization_link_record['organization_link_address_3'])) 
{$section->addText( $organization_link_record['organization_link_address_3'] );}
if (!empty( $organization_link_record['organization_link_address_4'])) 
{$section->addText( $organization_link_record['organization_link_address_4'] );}
$$section->addText($city);
$document->save('invoice/'.$invoicedoc);

what am i doing wrong?

**Comment by alpha1125** [comment]
Late to the party... but here's the answer you probably didn't want.
You can't do that, unless you nest it somewhere to have it possibly replaceBlock() a ${tag} with a block.

"It is not possible to directly add new OOXML elements to the template file being processed, but it is possible to transform main document part of the template using XSLT" -- Source: http://phpword.readthedocs.org/en/latest/templates-processing.html
