### ISSUE TITLE
Alignment footer PreserveText

### ISSUE THREAD

**Issue by ottena** [PHPOffice/PHPWord#45]
Alignment of the PreserveText can only be done by entering an emty fontstyle array.
Leaving out the fontsyle array will result in left alignment of the text.

**Comment by pawansharma13** [comment]
Hi Ivanlanin,

How can we add addPreserveText method in section. I want to add indexing in my doc file with page number.
************************
Exp :
title 1        5
title 2        10
title 3        15
title 4        15
title 5        16
************************


Plz help

Thanks
Pawan Sharma
