### ISSUE TITLE
Inconsistent Text Escaping

### ISSUE THREAD

**Issue by lrobert** [PHPOffice/PHPWord#470]
I noticed after release 0.12.0 that my documents no longer open because there is inconsistent escaping. The erorr I get is the same as Issue #401. However I noticed that the ListItem element [ListItem.php#L60](https://github.com/PHPOffice/PHPWord/blob/master/src/PhpWord/Element/ListItem.php#L60) adds text this way:

```php
$this->textObject = new Text(String::toUTF8($text), $fontStyle, $paragraphStyle);
```

whereas the text element doesn't escape anything. Shouldn't this be left up to the user to handle escaping in all cases?

**Comment by RomanSyroeshko** [comment]
Yep, @lrobert, all escaping must be done outside of the library. One of the reasons is to avoid multiple escaping of the same text.

**Comment by lrobert** [comment]
I mixed up escaping and encoding. Currently the ListItem encodes UTF-8 but doing just addText() does not. I'm just trying to figure out if it's intended to be this way or if I should a submit a PR to clean it up

**Comment by RomanSyroeshko** [comment]
Thanks, @lrobert. I can performe an investigation, but only at weekend. I will really appreciate any additional information upon the problem.

**Comment by RomanSyroeshko** [comment]
Hi, @lrobert. I double-checked the changes, and it seems all is working as intended. Do you still have any questions or experience any issues up on this?
