### ISSUE TITLE
Unreadable content

### ISSUE THREAD

**Issue by tskkh** [PHPOffice/PHPWord#482]
Hi,
I am using PHPWord in my web application. First it really works fine but after I update my composer,
I still export it but the content is unreadable like this : 

  PK########�JSFP_O��;###<######word/media/section_image1.png<�#p&]#.�ƶm�N�ض5�m۞ض��m��Ll���ϩs�jWu��^ս�Z#�W���$#,.,##@��#S##@#�#�Р��#~�##�#i1a5Ϝ�#��_��#mς'�ق�#G#��[���ٗe(#�2(E�j��{���d���#�V&#���(ٗ�\�###�Tѷ���#oN?#���#��#���#��(� hr�̷:}���5#�#tU9�#�|�O3���s��R����3��y��

**Comment by RomanSyroeshko** [comment]
Hi @tskkh.

Sorry, what did you do?

**Comment by tskkh** [comment]
Hi,
I use PHPWord to download document as word office.

**Comment by RomanSyroeshko** [comment]
I meant "What did you do with composer"? You updated composer itself or you updated version of PHPWord?

**Comment by tskkh** [comment]
I updated composer only.
It seems there is the problem on header because it works fine for saving, but not working for downloading. 
This is my header for download using phpword:

**Comment by RomanSyroeshko** [comment]
The file breaks after download? Will it be readable if you download it with some tools and not with your PHP code?
