### ISSUE TITLE
Shared with PHPOffice

### ISSUE THREAD

**Issue by Progi1984** [PHPOffice/PHPWord#485]
Some parts of PHPOffice projects are recurrents :
* graphs in OpenXML
  * https://github.com/PHPOffice/PHPExcel/blob/develop/Classes/PHPExcel/Writer/Excel2007/Chart.php#L125
  * https://github.com/PHPOffice/PHPWord/blob/master/src/PhpWord/Writer/Word2007/Part/Chart.php
  * https://github.com/PHPOffice/PHPPowerPoint/blob/master/src/PhpPowerpoint/Writer/PowerPoint2007/Chart.php#L374
* convert between drawing units :
  * https://github.com/PHPOffice/PHPExcel/blob/develop/Classes/PHPExcel/Shared/Drawing.php#L38
  * https://github.com/PHPOffice/PHPWord/blob/master/src/PhpWord/Shared/Drawing.php#L17
  * https://github.com/PHPOffice/PHPPowerPoint/blob/master/src/PhpPowerpoint/Shared/Drawing.php#L27
* and so on...

The idea would be to create a package (PHPOfficeShared or PHPOffice or...) which permits to group useful functions in one place for improving all projects.

Poke teams : 
* @PHPOffice/phpexcel-team 
* @PHPOffice/phppowerpoint-team 
* @PHPOffice/phpword-team

**Comment by MarkBaker** [comment]
Would also apply to components like the OLE Reader/Writer, and also to some document-level elements like DocumentProperties and parts of DocumentSecurity

**Comment by MarkBaker** [comment]
Useful in a separate repository when dependencies can be managed via composer, but harder for doing a non-composer build of all components

**Comment by Progi1984** [comment]
@MarkBaker Exactly for OLE and DocumentProperties. 

Ah ! Composer save our lives :p
May be the solution will be an autoload (not in the case where we use Composer) for loading PHPExcel & PhpOfficeShared ?

**Comment by MarkBaker** [comment]
Namespacing would be a godsend there, but that requires forcing the minimum version requirement to PHP 5.3.0.... which is all to the good as well, as it means guaranteed SPL in PHP core, closures, etc

**Comment by Progi1984** [comment]
@MarkBaker Actually, the minimal support is :
* 5.2.0 for PHPExcel
* 5.3.0 for PHPPowerPoint
* 5.3.3 for PHPWord

**Comment by RomanSyroeshko** [comment]
+1 for separate subproject in PHPOffice family managed by Composer. So we can depend other projects on it. I would call it ``Common`` (``\PhpOffice\Common``). ``Shared`` is not a good name, because this term is used in OOXML (there are so called shared objects). So, to avoid confusion, we should choose a different name.

As regards PHP version, I suggest starting with at least 5.3. PHPOffice will use the lib when got PHP upgraded.

**Comment by Progi1984** [comment]
@RomanSyroeshko Good idea for ``Common`` ;)
I agree with you for PHPExcel.

**Comment by Progi1984** [comment]
Done with https://packagist.org/packages/phpoffice/common
