### ISSUE TITLE
PHP conversion - is it possible or not at this time?

### ISSUE THREAD

**Issue by donquick** [PHPOffice/PHPWord#488]
Hi - I'm using this code to first save my file as docx whihc works and then save it as PDF whihc throws an error:  here is the code:

```
// Saving the document as DOCX file...
$objWriter = \PhpOffice\PhpWord\IOFactory::createWriter($phpWord, 'Word2007');
$fullpathdocx = '..\orders\word\\'.$orderfromdb.'.docx';
$objWriter->save($fullpathdocx);

$objWriter = \PhpOffice\PhpWord\IOFactory::createWriter($phpWord, 'PDF');
//$fullpathdocx = '..\orders\pdf\\'.$orderfromdb.'.pdf';
$objWriter->save('willitwork.pdf');
```

The error is 'PDF rendering library or library path has not been defined.'
Thanks for any help.  Best regards,

**Comment by mdemori** [comment]
hi, 
you have to configure the  phpword.ini, under /vendor/phpoffice/phpword/ you will find a  phpword.ini.dist, rename it to  phpword.ini and edit to reflect your needed.

hope it help
