### ISSUE TITLE
Sample_12_HeaderFooter.php error

### ISSUE THREAD

**Issue by SSchwaiger** [PHPOffice/PHPWord#495]
To display the text centered, the second parameter is wrong. It should be

$footer->addPreserveText(htmlspecialchars('Page {PAGE} of {NUMPAGES}.'), **null,** array('align' => 'center'));

**Comment by RomanSyroeshko** [comment]
Fixed in ``develop`` branch. Will be released in scope of v0.13.0.

Thanks for the bug report.
