### ISSUE TITLE
Add ability to manage header & footer height

### ISSUE THREAD

**Issue by JillElaine** [PHPOffice/PHPWord#5]
The code to do this is here: http://phpword.codeplex.com/discussions/316726
Here is the related 'workitem' on the phpWord site: http://phpword.codeplex.com/workitem/35

**Comment by jcnolan** [comment]
Note, successfully tested in V0.13.0 to place 8.5" x 11" graphic as watermark as micro-perf template.  

       $PidPageSettings = array(
                'headerHeight'=> \PhpOffice\PhpWord\Shared\Converter::inchToTwip(.2),
                'footerHeight'=> \PhpOffice\PhpWord\Shared\Converter::inchToTwip(.2),
                'marginLeft'  => \PhpOffice\PhpWord\Shared\Converter::inchToTwip(.75),
                'marginRight' => \PhpOffice\PhpWord\Shared\Converter::inchToTwip(.75),
                'marginTop'   => 0,
                'marginBottom'=> 0,
            );

            $section = $this->phpword->createSection($PidPageSettings);
            $header = $section->addHeader();

            $foo = array(
                'width'            => \PhpOffice\PhpWord\Shared\Converter::inchToPixel(8.5),
                'height'           => \PhpOffice\PhpWord\Shared\Converter::inchToPixel(11),
                'positioning'      => \PhpOffice\PhpWord\Style\Image::POSITION_ABSOLUTE,
                'posHorizontal'    => \PhpOffice\PhpWord\Style\Image::POSITION_HORIZONTAL_CENTER,
                'posHorizontalRel' => \PhpOffice\PhpWord\Style\Image::POSITION_RELATIVE_TO_PAGE,
                'posVerticalRel'   => \PhpOffice\PhpWord\Style\Image::POSITION_RELATIVE_TO_PAGE,
            );

            if ($fName) $header->addWatermark($fName, $foo); // $fName would be your 8.5" x 11" image

Was using PHPWord to create documents to be printed on micro-perforated card stock and was placing a scan of the template as a watermark for debugging purposes and required a .2" header / footer. The following proceeding code worked but ALL values needed to be set to create a properly working document.
