### ISSUE TITLE
Unable to read doc (Word 97) file

### ISSUE THREAD

**Issue by KevinMercury** [PHPOffice/PHPWord#503]
The error was shown when I try to read .doc file

 Undefined property: PhpOffice\PhpWord\Shared\OLERead::$documentSummaryInformation in D:\xampp\htdocs\seniorProjectFile\PHPWord\src\PhpWord\Reader\MsDoc.php on line 144

**Comment by z01d** [comment]
I'm having the same problem.

**Comment by meganos** [comment]
I have this problem too.

**Comment by Ciloe** [comment]
I have the same problem too. Your website say the same :

http://www.devlez.com/demos/docWordExcel/vendor/phpoffice/phpword/samples/Sample_11_ReadWord97.php

**Comment by Ciloe** [comment]
Any advance for this error ?

**Comment by Alsciende** [comment]
This bug is nearly one year old, and a one-line Pull Request has been submitted (https://github.com/PHPOffice/PHPWord/pull/612). Is this project not maintained anymore?

**Comment by Progi1984** [comment]
@Alsciende This project is not dead. But we are for each PHPOffice project, one developer with a life and a work beside, so we work on issue on our free time.

Poke @MarkBaker & @RomanSyroeshko

**Comment by Alsciende** [comment]
I'm sorry I was rude. Your work is deeply appreciated and saves me a lot of headaches! I'm glad to know that the project is still being maintained and the bugs looked at.

**Comment by RomanSyroeshko** [comment]
Wow, so many people here! :smile: I'll try to find some time for that this weekend. Thanks.

**Comment by RomanSyroeshko** [comment]
Merged. Enjoy and have a nice weekend.
