### ISSUE TITLE
Impossible to open /results/Sample_07_TemplateCloneRow.docx (windows only)

### ISSUE THREAD

**Issue by AshSat** [PHPOffice/PHPWord#532]
Hello,

I have a problem with templates, using a WAMP server.
I don't have any issue with the same process with a LAMP server.

It's a LOCAL application, NOT on the internet.
Word documents have been tested with LibreOffice and OpenOffice, same results.

I'm working with the Sample_07_TemplateCloneRow example.
With Linux :
It works perfectly, 
I can open the file via http://...., but it is a "read only" version (that's fine, but NOT what I need)
I can open, read and modify the "/results/Sample_07_TemplateCloneRow.docx" file in his folder (direct access in the folder)

With Windows 7 (I tried with 2 different computers, same issue)
I can open the file via http://, it works but it's NOT what I need !
I can save the document in my "downloads" folder. After that, I can open the new document but it is NOT what I need neither !

I CANNOT open the "c:/[...]/results/Sample_07_TemplateCloneRow.docx", the file is "corrupted" (access denied) but it IS this one I need to open !

After many, many, many tests, I found a way to open those files :
right-click on the file -> Properties -> Security -> Modify -> Add a user -> I added my windows "username" (my OS is in french, i'm not quite sure with the english labels !)

and then, it works, I can open my "c:/[...]/results/Sample_07_TemplateCloneRow.docx"
It works, but it's really not an easy way for a daily use.

Templates (07 & 23) are the only ones who makes troubles.
IE, "/results/Sample_06_Footnote.docx" didn't need any manipulation before beeing open and have no owner neither.
I have no problem with other generated files with or without PHPWord, only with those using TemplateProcessor.

I do not understand what's the problem and think a little bit ironic to have rights/permissions issues with windows...

Has someone a solution with this issue ?
How can I solve it ?

Without this problem, PHPWord is awesome !

Windows 7 64bits
Wamp Server 2.5
Apache 2.4.9 (Win 32)
php 5.5.12
PHPWord Master 0.12.0

**Comment by RomanSyroeshko** [comment]
Hi @AshSat,
Which tool do you open *.docx files with?

**Comment by RomanSyroeshko** [comment]
Hi @AshSat,
Which LibreOffice version did you try?

**Comment by RomanSyroeshko** [comment]
Any news, @AshSat?

**Comment by AshSat** [comment]
Hi,
Sorry, I didn't your messages.
I tried with LibreOffice 4.3 and OpenOffice 4.1.1

I didn't see any issue with the temp dir.

Open those 2 documents are the only issues. Thanks a lot !

**Comment by RomanSyroeshko** [comment]
Do you experience the issue with the samples only, or it appears each time you use ``TemplateProcessor``?

**Comment by AshSat** [comment]
Each time I use TemplateProsessor.
With my own samples AND with the original samples.

**Comment by RomanSyroeshko** [comment]
Which temp dir do you use with PHPWord, default?

**Comment by AshSat** [comment]
yes, the default one.

**Comment by RomanSyroeshko** [comment]
By default, PHPWord uses OS's temp dir. ``TemplateProcessor`` copies the provided template into it, performs the transformations you want and saves the result in a new place.

My assumption is that something may happen with file permissions during the trip. So, please, create your own dir somewhere you definetely has enough permissions and give it to PHPWord as temp dir. Maybe this will help.

By the way, I use Windows 7 too and can't reproduce the problem. Possibly this is because I work under account with administrator's privileges.

**Comment by andrew-kzoo** [comment]
I cannot comment directly to your exact setup. However, I have had ongoing troubles with temporary files and temporary folders when using PHPWord (not just for templates). I concur that creating and using your own temp folder avoids many problems.

**Comment by AshSat** [comment]
I tried and it works !
It was the problem, you were right !
I created my own temporary dir and the problem is solved !

Thank you very much ! Have a very nice day !

**Comment by RomanSyroeshko** [comment]
Hi @AshSat,
I tried to reproduce your problem to find a remedy and no luck.

Could you, please, switch back to the default temp dir, then add ``chmod($fileName, 0666);`` after ``rename`` command in ``TemplateProcessor::saveAs``, and let me know if it helps?

Thanks.

**Comment by AshSat** [comment]
Hi Roman,
I did it, but it doesn't work. 
(I have tried that too before asking my question here, but I did it again, exactly as you ask and it doesn't work).

**Comment by RomanSyroeshko** [comment]
Okay, another attempt. :smile: What happens if you copy the file from it's location (``c:/[...]/results/Sample_07_TemplateCloneRow.docx``) to another location using Windows Explorer and try to open it then? You'll got the same error or no?

**Comment by RomanSyroeshko** [comment]
@AshSat, are you still there?

**Comment by kumfo** [comment]
@RomanSyroeshko I also have a broblem,I can't create pdf file.why?

**Comment by RomanSyroeshko** [comment]
@kumfo, how this is connected with the issue?

**Comment by AshSat** [comment]
Hi Roman,
Sorry, I'm late, but I'm here.
I made a copy of the document on my desktop and I can open it. It works with no error.

**Comment by RomanSyroeshko** [comment]
If we assume that your desktop resides on the same volume (``C:``), [Windows retains original file permissions](https://support.microsoft.com/en-us/kb/310316). It means that the problem is not in file permissions. Our experiment with ``chmod($fileName, 0666)`` confirms that.

So, I can suppose that the problem hides somewhere in file path. Can you reveal full file path? Maybe it's simply too long?

**Comment by AshSat** [comment]
Hi,
The real path is : c:\test\www\PHPWorld-master\samples\

For now, the only solution working is to create a temporary dir.

**Comment by RomanSyroeshko** [comment]
The path looks OK. :disappointed:

Your Windows temp dir is in its default location?

**Comment by AshSat** [comment]
Yes, it's sad... and my windows temp dir is in its default location.(sorry)
I know it's frustrating, BUT, the problem is really solved with a temporary dir (in PHPWord) and it's very simple to do. 
Adding a simple line in the FAQ will help those who have the same issue.
I really thank you for your time and your help ! I'm happy to help if you have other ideas !

**Comment by RomanSyroeshko** [comment]
No pain, no gain. :-) 

How many Windows users are involved? I use the same user to run Apache, PHP, LibreOffice, everything. It belongs to Administrators, and all the environment was installed under this account. What about you?

**Comment by AshSat** [comment]
the same... I'm the only user, no other account. All the environment was installed under this account too.

**Comment by RomanSyroeshko** [comment]
You know, I even installed WAMP Server, but it didn't help. It just works. :disappointed: 

Could you, please, post here output of main samples page (see ``http://localhost/PHPWorld-master/samples/``) from ``Requirement check`` section?

**Comment by AshSat** [comment]
Requirement check:
    PHP 5.3.3 ... passed
    PHP extension XML ... passed
    Temp folder "C:\windows\TEMP" is writable ... passed
    PHP extension ZipArchive (optional) ... passed
    PHP extension GD (optional) ... passed
    PHP extension XMLWriter (optional) ... passed
    PHP extension XSL (optional) ... passed

The keys :
BuildLabEx 7601.18798.amd64fre.win7sp1_gdr.150316-1654
CurrentVersion 6.1
EditionID Professional

I hope it helps :)

**Comment by RomanSyroeshko** [comment]
Nope. Mine is "7601.18869.amd64fre.win7sp1_gdr.150525-0603". Home Basic edition.

I'll try to find a PC with clean Windows installation. Maybe I customized something on my own laptop and successfully forget about that...

**Comment by RomanSyroeshko** [comment]
@AshSat, I got it reproduced on clean installation of Windows 8.1. Will try to reproduce.

**Comment by AshSat** [comment]
I'm happy you can reproduce the problem !
It's a little strange to be happy when you have a bug ;)

**Comment by RomanSyroeshko** [comment]
@AshSat, tell me, please, one more thing about your environment. What's the value of your ``JAVA_HOME`` system variable? :smirk:

**Comment by AshSat** [comment]
Sorry, I haven't seen your message :(
I try that soon !

**Comment by RomanSyroeshko** [comment]
Well done, partner! :+1:

**Comment by xarisavee** [comment]
Hi. I think I'm having the same problem. I got this:

 Uncaught exception 'PhpOffice\PhpWord\Exception\CopyFileException' with message 'Could not copy 'filename.docx' file to 'C:\xx\xx\AppData\Local\Temp\Php2E68.tmp'.' in C:\xampp\htdocs\lyrics\PHPWord-master\src\PhpWord\TemplateProcessor.php:

How do I "create your own dir somewhere you definetely has enough permissions and give it to PHPWord as temp dir"?
