### ISSUE TITLE
How to get the word document page?

### ISSUE THREAD

**Issue by kumfo** [PHPOffice/PHPWord#539]
I have a word document,now,I want to get number of pages in a Word document.What the phpword function can I use?

**Comment by RafKacz** [comment]
There is no function to get the current page number. The only way is to use "addPreserveText" like:
<code>
$footer->addPreserveText('Page {PAGE} of {NUMPAGES}.');
</code>

The documents you are programming with phpword are declarative. So you declare how the document should be structured and then an application, like Mircosoft Word, creates a view of this declaration.

When you add content like a textrun with a text that is two pages long, phpword doesn't programmatically know anything about the length.

**Comment by kumfo** [comment]
Thank you very much.
