### ISSUE TITLE
Create password protected docx file

### ISSUE THREAD

**Issue by kasinau** [PHPOffice/PHPWord#546]
Hi, I want to create a docx file from a template and protect it to be able to open only entering a password.
Is it possible with PHPWord or no?
Thank you!

**Comment by DsXack** [comment]
:+1: 
It no possible now(

https://github.com/PHPOffice/PHPWord/blob/3f136501b3dfea94766a704e17782c8a942a7b9b/src/PhpWord/Metadata/Protection.php#L25

**Comment by troosan** [comment]
no, that's not possible. you can only make a document (or parts of it only) read-only.
Forbidding to open a document is much more difficult than that as the whole document needs to be encrypted.

**Comment by devjob** [comment]
I have not protected template Word document.
I need to edit it and then to set protection with password to avoid changes.
How could I do it?
