### ISSUE TITLE
TemplateProcessor, some values are not replaced (incl. debug)

### ISSUE THREAD

**Issue by kaystrobach** [PHPOffice/PHPWord#548]
Given you have word document, with placeholders like ```${some.object.path}``` any change in any place of the document can add some xml inside the brackets of the placeholder.

```
$template = new \PhpOffice\PhpWord\TemplateProcessor($this->templatePath);
throw  new \Exception(print_r($template->getVariables(), TRUE));
```

gives f.e. the following array

```
[0] => student.aktenzeichen
[1] => student.registraturSba
[2] => student.kontakt.vorname
[3] => st</w:t></w:r><w:r><w:t>u</w:t></w:r><w:r><w:t>dent.kontakt.nachname
[4] => student.kontakt.strasse
[5] => st</w:t></w:r><w:r><w:t>u</w:t></w:r><w:r><w:t>dent.kontakt.hausnummer
[6] => student.kontakt.plz
[7] => student.kontakt.ort
[8] => student.kontakt.nachname
```

```3``` and ```5``` will never be replaced as they are screwed up by word :cry: as i use getVariables to obtain real object pathes from my domain model i used strip_tags to transform it into a useable object path again.

But neither giving the broken values ```3``` / ```5``` to set values gives a successfull replacement ... any idea? my current approach is to digg deeper into the ```setValueForPart``` function and understand what you do with value cleaning ...

**Comment by kaystrobach** [comment]
the following workaround makes the replacement a lot more robust for me!

current workaround:

```
		$variables = $template->getVariables();

		foreach ($variables as $variable) {
			if (strpos($variable, '.')) {
				list($object, $path) = explode('.', strip_tags($variable), 2);
				if (isset($this->variables[$object])) {
					$value = $this->resolve($this->variables[$object], $path);
					$template->setValue($variable, $value);
					$template->setValue(strip_tags($variable), $value);

					$this->logger->log('WordView Variable: ' . $variable . ' = ' . $value, LOG_DEBUG);
				}
			}
		}

		$this->logger->log('WordView leftovers', LOG_DEBUG, print_r($template->getVariables(), TRUE));
```

mean i do 2 replacements per document, one with the xml tags included and one with the xml removed with strip tags ... this makes it a little more robust for me, IMHO this should be fixed with some kind of mapping table, as the correct areas are detected.

**Comment by RomanSyroeshko** [comment]
Fixed.
