### ISSUE TITLE
RTL Support and font style issue

### ISSUE THREAD

**Issue by dorvega** [PHPOffice/PHPWord#558]
First, this is a very good library.
Second: I've got two issues with RTL

<ol>
<li> I'm trying to implement style in Hebrew document as following:
<br>
<code>$section = $phpWord->addSection();<br>
$mainTitle = $section->addTextRun(array('align' => 'center'));<br>
$mainTitle->addtext(htmlspecialchars('כותרת ראשית'),array('rtl' => true, 'size' => 25, 'bold' => true, 'underline' => 'single'));<br>
</code>
<br>
but the bold attribute doesn't work.</li>
<br>
<li>I'm trying to define style like this:
<br>
<code>
$textFontStyle = array('rtl' => true);
$phpWord->addFontStyle('textFontStyle', $textFontStyle);<br>
$textParagraphStyle = array('align' => 'right');<br>
$phpWord->addParagraphStyle('textParagraphStyle', $textParagraphStyle);<br>
$personalInfo = $section->addTextRun('textParagraphStyle');<br>
$personalInfo->addText(
    htmlspecialchars('שם:', ENT_COMPAT, 'UTF-8'), 'textParagraphStyle', 'textFontStyle'
);<br>
$personalInfo->addText(
    htmlspecialchars(' '.$_POST['first_name'].' '.$_POST['last_name'] , ENT_COMPAT, 'UTF-8'), 'textParagraphStyle', 'textFontStyle'
);<br>
</code>
<br>
But, the RTL is not working.</li>
</ol>

<p>can someone can help me with that?</p>

**Comment by itamar-Cohen** [comment]
hey,

after reading all the source files i found the answer
don't use ['align'=>'center/right']
use 
['alignment'=>'center/right']

**Comment by dorvega** [comment]
Thank you Itamar, I'll check this out.
