### ISSUE TITLE
Unwanted changes made while trying to edit a docx file.

### ISSUE THREAD

**Issue by mayankitt** [PHPOffice/PHPWord#566]
I wrote some code to edit documents through phpWord. But the changes didn't take effect and there were some unwanted changes. When I tried to simply load the file into the buffer and save it to the disk without making any changes to the document, the changes still persisted.
The code I used:

```
$source = "demoFile.docx";
$phpWordObj = \PhpOffice\PhpWord\IOFactory::load($source);

$objWriter = \PhpOffice\PhpWord\IOFactory::createWriter($phpWordObj, 'Word2007');
$objWriter->save('demoFileUpdate.docx');
```

The screenshots of the original and updated files are given below:
![demoFile.docx screenshot](http://i.stack.imgur.com/FWMZr.png)

![demoFileUpdate.docx screenshot](http://i.stack.imgur.com/RaYC2.png)

A detailed explaination of my problem can be seen [here](http://stackoverflow.com/questions/31130331/undesired-changes-while-editing-a-docx-document-with-phpword)

Hope to resolve this at the earliest.

**Comment by Progi1984** [comment]
@mayankitt Your screenshots and files are not anymore available. Could you update them for analyzing this issue ?

**Comment by mayankitt** [comment]
Hi @Progi1984 it's been a few years now and I no longer have access to the screenshots, I think we can close the issue. Thank you for following up even after almost a decade.
