### ISSUE TITLE
Code is not completly download 

### ISSUE THREAD

**Issue by kushal555** [PHPOffice/PHPWord#575]
I am downloading Code but some files are missing. I tried 3 or 4 times but still face same problem. Actually i want sample code for chart So i do it manually, But still face problem 
<pre>Fatal error: Call to undefined method PhpOffice\PhpWord\Element\Section::addChart() in C:\xampp\htdocs\PHPWord-0.10.0\samples\Sample_32_Chart.php on line 22</pre>
Please provide me full code and if you give me some guide line for put a chart in word template for a particular place then its really so helpful for me

**Comment by Max840** [comment]
Are you using PHPWord 0.10.0? Because the support for basic charts was added in [version 0.12.0](https://github.com/PHPOffice/PHPWord/releases/tag/0.12.0)

**Comment by kushal555** [comment]
Thank you very much @Max840 . Actually its my mistake because i am integrated it in Codeigniter  Framework and there is left some issue me. :)

**Comment by Max840** [comment]
No problem! :)

**Comment by RomanSyroeshko** [comment]
Thanks for help, @Max840.
