### ISSUE TITLE
Templates delete placeholders/unused tags

### ISSUE THREAD

**Issue by markthebro** [PHPOffice/PHPWord#593]
Hi everybody!
Is it possible to delete placeholders when using templates/filling out templates? I mean, i can replace the ${variable} with '' in the PHP code, but i want to delete the whole line. i dont want to have white unused space...

thanks in regard
mark

ps.: sry that my englisch sucks...

**Comment by narekps** [comment]
@markthebro You have found a solution?

**Comment by markthebro** [comment]
@narekps Yep, I'm using the phpdocx framework now.
