### ISSUE TITLE
Clone Block more times

### ISSUE THREAD

**Issue by fishwolf** [PHPOffice/PHPWord#598]
cloneBlock method doesn't work if i run more times.

[code]
$templateProcessor->setValue('Planet', htmlspecialchars('Venus'));
$templateProcessor->cloneBlock('CLONEME', 1);

$templateProcessor->setValue('Planet', htmlspecialchars('Mercury'));
$templateProcessor->cloneBlock('CLONEME', 1);

$templateProcessor->setValue('Planet', htmlspecialchars('Venus'));
$templateProcessor->cloneBlock('CLONEME', 1);

OR

$templateProcessor->cloneBlock('CLONEME', 3);

$templateProcessor->setValue('Planet#1', htmlspecialchars('Venus'));
$templateProcessor->setValue('Planet#2', htmlspecialchars('Mercury'));
$templateProcessor->setValue('Planet#3', htmlspecialchars('Venus'));

[/code]

![template23](https://cloud.githubusercontent.com/assets/4223458/9405014/7f746fe2-47f4-11e5-97ed-2768e740013f.jpg)

**Comment by Gadeoli** [comment]
Today has someway to do that (some kind of mult block)?
 v.0.16.0

`$templateProcessor->setValue('Planet', htmlspecialchars('Venus'));
$templateProcessor->cloneBlock('CLONEME', 1);

$templateProcessor->setValue('Planet', htmlspecialchars('Mercury'));
$templateProcessor->cloneBlock('CLONEME', 1);

$templateProcessor->setValue('Planet', htmlspecialchars('Venus'));
$templateProcessor->cloneBlock('CLONEME', 1);`

**Comment by Gadeoli** [comment]
Today has someway to do that (some kind of mult block)?
v.0.16.0

``$templateProcessor->setValue('Planet', htmlspecialchars('Venus'));
$templateProcessor->cloneBlock('CLONEME', 1);

$templateProcessor->setValue('Planet', htmlspecialchars('Mercury'));
$templateProcessor->cloneBlock('CLONEME', 1);

$templateProcessor->setValue('Planet', htmlspecialchars('Venus'));
$templateProcessor->cloneBlock('CLONEME', 1);``

**Comment by Gadeoli** [comment]
Today has someway to do that (some kind of mult block)?
v.0.16.0

`
$templateProcessor->setValue('Planet',` htmlspecialchars('Venus'));
$templateProcessor->cloneBlock('CLONEME', 1);

$templateProcessor->setValue('Planet', htmlspecialchars('Mercury'));
$templateProcessor->cloneBlock('CLONEME', 1);

$templateProcessor->setValue('Planet', htmlspecialchars('Venus'));
$templateProcessor->cloneBlock('CLONEME', 1);
`
