### ISSUE TITLE
Undefined property: PhpOffice\PhpWord\Shared\OLERead::$documentSummaryInformation

### ISSUE THREAD

**Issue by jaberu** [PHPOffice/PHPWord#610]
I cannot read Ms Word 97 because of the message above.

I think the problem is related to the OLERead class (line 58) where the documentSummaryInformation was renamed to docSummaryInfos. However the PhpOffice\PhpWord\Reader\MsDoc (line 144) still reads the old property what is not existing anymore.

**Comment by RomanSyroeshko** [comment]
See #503.
