### ISSUE TITLE
Disallow PHPWord to break table rows between pages 

### ISSUE THREAD

**Issue by matasarei** [PHPOffice/PHPWord#64]
Hello! How to configure it?

![one](https://f.cloud.github.com/assets/6638367/2206302/6fbcf1c8-995e-11e3-8ba1-b456311f1326.PNG)

![two](https://f.cloud.github.com/assets/6638367/2206304/71698360-995e-11e3-9f92-51c63b946870.PNG)

**Comment by ahmed-bhs** [comment]
@ivanlanin I'm using $templateProcessor->cloneRow() and my table is already drawed under my template, cloneRow does not contain that options :/
