### ISSUE TITLE
addLine is generating a diagonal line

### ISSUE THREAD

**Issue by geoff-maddock** [PHPOffice/PHPWord#643]
This seems to be a very simple case, but I can't determine why it's generating a diagonal rather than a horizontal line

```
$sectionStyle = array( 'marginLeft' => 200, 'marginRight' => 200);
$section = $phpWord->addSection($sectionStyle);

$fontStyleHeader =  array('name' => 'Arial', 'size' => 28 );
$fontStyleHeaderRed = array('color' => 'ff0000', 'name' => 'Arial', 'size' => 28 );
$phpWord->addTitleStyle(1, $fontStyleHeader, array('marginLeft' => 20));
$section->addTitle('Table of Contents', 1);

// relevant section here, just included above to show context
$lineStyle = array('weight' => 10, 'width' => 1000, 'color' => '000000');
$section->addLine($lineStyle);
```

Results in what you see in the attached image.
![horizontal](https://cloud.githubusercontent.com/assets/55493/10593387/5afbd3f0-7691-11e5-93a6-6bb93e466fef.jpg)

**Comment by boebi** [comment]
I have similar issues myself, whatever sort of line I try to create it always shows up diagonal as well. Can't get to my code right now but wanted to quickly add that you're not an isolated case.

**Comment by Oluwafemikorede** [comment]
same with me, dont know if you have any way with it

**Comment by webmaxer** [comment]
Hello. Set
`'height' => 0,`

**Comment by jaguaryang** [comment]
so late,you can try points parameter,
$header->addShape(
      'line',
      array(
        'points' => '-5000,0 10000,0',
        'outline' => array(
          'color' => '#999999',
          'weight' => 3,
          'width' => 1000
        ),
      )
    );

**Comment by manuelph** [comment]
Just set height too 0

$section->addLine(['weight' => 4, 'width' => 600, 'height' => 0]);
