### ISSUE TITLE
Docx version is broken after upgrading to latest develop branch

### ISSUE THREAD

**Issue by oliverhuynh** [PHPOffice/PHPWord#645]
I got below error after upgrading to latest develop branch. Not sure what's going wrong. It can work if I revert to previous version (July 2014). Any hints to fix this?
Check this screencast to see the issue: http://screencast.com/t/dwZPeyzV2o

**Comment by RomanSyroeshko** [comment]
Hi @oliverhuynh,
Why do you use `develop`? Did you try `v0.12.1` which is in `master`?
