### ISSUE TITLE
(total) pagecount outside footer?

### ISSUE THREAD

**Issue by boebi** [PHPOffice/PHPWord#647]
I am adding a simple pagecount in my footer with:

$footer->addPreserveText("Page {PAGE} of {NUMPAGES}");

This works perfectly fine. Now my issue is, is there ANY way to get the total amount of pages anywhere outside the footer?
I understand that phpword works declarative and that Office or any other program will parse whatever is in the document to generate a view but why can we only count pages in the footer?

At the end of my document I need to include how many pages there are (in text, for legal reasons) and this is the only issue I have right now. If there is no way to use the {NUMPAGES} outside the footer, would there be any alternative ways?

**Comment by troosan** [comment]
PreserveText can be added to a section, so you should be able to add the {NUMPAGES} anywhere.
You can also use addField('NUMPAGES', $properties) which will allow you to pass in properties on how to format the number. check PhpOffice\PhpWord\Element\Field for possible properties.

**Comment by Techbrunch** [comment]
For people running into the same issue:

```php
$textRun = $section->addTextRun();
$textRun->addField('NUMPAGES');
$textRun->addText(' pages');
```

Using `$section->addPreserveText('{NUMPAGES}');` did not work for me.
