### ISSUE TITLE
Word 2013 error

### ISSUE THREAD

**Issue by michaelachrisco** [PHPOffice/PHPWord#662]
When I am downloading from an action such as: 

    $file = 'letter.docx';
    header("Content-Description: File Transfer");
    header('Content-Disposition: attachment; filename="' . $file . '"');
    header('Content-Type: application/vnd.openxmlformats-officedocument.wordprocessingml.document');
    header('Content-Transfer-Encoding: binary');
    header('Cache-Control: must-revalidate, post-check=0, pre-check=0');
    header('Expires: 0');
    $xmlWriter = \PhpOffice\PhpWord\IOFactory::createWriter($phpWord, 'Word2007');
    return $xmlWriter->save("php://output");

I get an error:
![capture](https://cloud.githubusercontent.com/assets/398491/11198509/fd9fe40e-8c79-11e5-8e61-30904e2390e8.PNG)

Ill try to get a more complete code sample. 

This download action was working on LibreOffice but not Word 2013.

**Comment by Progi1984** [comment]
@michaelachrisco Could you give us your document to find the error ? Thanks

**Comment by michaelachrisco** [comment]
I simplified this further:

```php
  public function generate_letter($id){
   // Model::find($id)
    $phpWord = new \PhpOffice\PhpWord\PhpWord();
    foreach($members as $member){
    
    $firstPageText = "";
    $secondPageText = "";
    $thirdPageText = "" ;
    $defaultStyle = ['name' => 'Calibri', 'size' => 12];
    $section = $phpWord->createSection();
    // $section->addImage('../resources/assets/Buisness.jpg', array('width' => 306, 'height' => 102, 'align' => 'center'));
    // $section->addTextBreak(2);
    //
    // $section->addText(htmlspecialchars($firstPageText), $defaultStyle);
    // $footer = $section->addFooter();
    //
    // $footer->addPreserveText(htmlspecialchars('footer text | footer address', ENT_COMPAT, 'UTF-8'), null, array('align' => 'center', 'size' => 8, 'name'=>'Perpetua'));
    // $section->addPageBreak();
    // $section->addText($secondPageText, $defaultStyle);
    // $section->addPageBreak();
    // $section->addText($thirdPageText, $defaultStyle);
    // $section->addPageBreak();
    }
    $file = 'sample_letter.docx';
    header("Content-Description: File Transfer");
    header('Content-Disposition: attachment; filename="' . $file . '"');
    header('Content-Type: application/vnd.openxmlformats-officedocument.wordprocessingml.document');
    header('Content-Transfer-Encoding: binary');
    header('Cache-Control: must-revalidate, post-check=0, pre-check=0');
    header('Expires: 0');
    $xmlWriter = \PhpOffice\PhpWord\IOFactory::createWriter($phpWord, 'Word2007');
    return $xmlWriter->save("php://output");
  }
```

[sample_letter.docx](https://github.com/PHPOffice/PHPWord/files/36930/sample_letter.docx)

**Comment by michaelachrisco** [comment]
Huh....I just looked at the contents of the file as an plain text file and phpdebugbar injects itself into the document. Ill turn off the extension and see if that fixes the issue.

**Comment by michaelachrisco** [comment]
Looks like it was a config issue with phpdebugbar and not this package. \Debugbar::disable(); within the master controller was not working. Thanks for the help!

**Comment by xpyctum** [comment]
Actualy.
