### ISSUE TITLE
Images not rendered correctly on LibreOffice

### ISSUE THREAD

**Issue by xprt64** [PHPOffice/PHPWord#667]
The images are not rendered correctly (at least on LibreOffice), they get enlarged by a few millimeters and thus get fuzzy. I resolved the issue by modifying the width and height attributes from pixels to points in `PHPWord_Writer_Word2007_Base::_writeImage()` like this:

``` php
$objWriter->writeAttribute('style', 'width:'.(0.75 * $width).'pt;height:'.(0.75*$height).'pt');
```

Environment: Linux version 3.16.0-4-amd64 (debian-kernel@lists.debian.org) (gcc version 4.8.4 (Debian 4.8.4-1) ) #1 SMP Debian 3.16.7-ckt11-1+deb8u6 (2015-11-09)

**Comment by michaelachrisco** [comment]
Which version of LibreOffice are you using? Can you upload a sample doc? I may have ran into this bug before.

**Comment by xprt64** [comment]
Version: 4.3.3.2
Build ID: 430m0(Build:2)

The code I posted on is about an old version of PhpWord but the bug is
still there in the last stable version.

2015-11-27 15:28 GMT+02:00 michael chrisco <notifications@github.com>:

> Which version of LibreOffice are you using? Can you upload a sample doc? I
> may have ran into this bug before.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/PHPOffice/PHPWord/issues/667#issuecomment-160139836>.
>



-- 
Best regards,
Constantin Galbenu,
Tel: +40728247366
Skype: xprt64

**Comment by michaelachrisco** [comment]
Ill take a look on my side when I get a chance. If memory serves, the issue has something to do with the GD extension. http://php.net/manual/en/book.image.php

The offender might have something to do with the image element: https://github.com/PHPOffice/PHPWord/blob/develop/src/PhpWord/Element/Image.php

I know I was testing on MS Word and the stretching was happening.

**Comment by xprt64** [comment]
It's not about GD, the image is fine in the docx file and the dimensions
are correct on the docx/word/document.xml; it's just about LibreOffice
rendering: if the unit is pixel then it get streched as if LibreOffice
ignores the unit and uses points anyway.
The solution that worked for me was to use points as unit in the resulting
docx file.

2015-11-27 15:48 GMT+02:00 michael chrisco <notifications@github.com>:

> Ill take a look on my side when I get a chance. If memory serves, the
> issue has something to do with the GD extension.
> http://php.net/manual/en/book.image.php
>
> The offender might have something to do with the image element:
> https://github.com/PHPOffice/PHPWord/blob/develop/src/PhpWord/Element/Image.php
>
> I know I was testing on MS Word and the stretching was happening.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/PHPOffice/PHPWord/issues/667#issuecomment-160143882>.
>



-- 
Best regards,
Constantin Galbenu,
Tel: +40728247366
Skype: xprt64

**Comment by samsullivan** [comment]
Blurry for me too, even in MS Word.

**Comment by samsullivan** [comment]
I found out this is only on images from remote URLs, rather than a local path. I've changed my code from:
```
$section->addImage($url);
```

To:
```
$logoPath = '/tmp/image.png';
file_put_contents($logoPath, file_get_contents($url));
$section->addImage($logoPath);

// Remove temporary local file after rendering Word2007
unlink($logoPath);
```

Not a great solution, but it works for now! FYI, rendering of the image looked fine (before this solution) on any file type other than Word2007.

**Comment by michaelachrisco** [comment]
Huh that's a strange one....any indication why a remote URL would stretch
an image?
What was the URL if you don't mind posting?

**Comment by samsullivan** [comment]
It's in quite a big tech stack using private AWS images to create custom reports, so I made an example for you using Google's logo. Something crazier than just bad quality happened...

Here's the sample code:
```
$document = new \PhpOffice\PhpWord\PhpWord();

$url = 'https://www.google.com/images/branding/googlelogo/2x/googlelogo_color_272x92dp.png';
$path = '/tmp/image.png';
file_put_contents($path, file_get_contents($url));

$document->addSection()->addImage($url);
$document->addSection()->addImage($path);

$file = \PhpOffice\PhpWord\IOFactory::createWriter($document, 'Word2007');
$file->save('/tmp/document.docx');
```

Here's the result:
![screenshot from 2016-04-06 17 16 58](https://cloud.githubusercontent.com/assets/3789442/14334572/eee5e56a-fc1a-11e5-8b6e-f0a50fea8ef0.png)

Also, I noticed that JPGs were much better quality -- if not perfect. You can see if you use the above example with [this image](http://ichef-1.bbci.co.uk/news/660/cpsprodpb/17A21/production/_85310869_85310700.jpg). So, my bug (not sure if it's related to OP, honestly...let me know if I should open a new ticket), is narrowed to Word2007/PNG/remote.

**Comment by samsullivan** [comment]
I've figured out why this bug exists (and it does take place in `Element\Image`, but the root has to do with the GD extension). I expanded on my above test:

```
$document = new \PhpOffice\PhpWord\PhpWord();

$url = 'https://www.google.com/images/branding/googlelogo/2x/googlelogo_color_272x92dp.png';
$path = '/tmp/image.png';

$contents = file_get_contents($url);
file_put_contents($path, $contents);

$image = imagecreatefromstring($contents);
imagepng($image, str_replace('image', 'image-2', $path));

$image = imagecreatefromstring($contents);
imagesavealpha($image, true);
imagepng($image, str_replace('image', 'image-3', $path));

// Remotely; PHPWord uses imagepng() to get contents; FAIL
$document->addSection()->addImage($url);

// Local; PHPWord just opens the file; SUCCESS
$document->addSection()->addImage($path);

// Local w/imagepng(); FAIL
$document->addSection()->addImage(str_replace('image', 'image-2', $path));

// Local w/imagesavealpha(); SUCCESS
$document->addSection()->addImage(str_replace('image', 'image-3', $path));

$file = \PhpOffice\PhpWord\IOFactory::createWriter($document, 'Word2007');
$file->save('/tmp/document.docx');
```

It looks like PHPWord doesn't use [`imagesavealpha($image, true)`](http://php.net/manual/en/function.imagesavealpha.php) when saving the remote PNG files, and there for the data in said PNG files gets all screwy.

We need to find a way to work this into `Element\Image`...I can do a PR after I'm done getting this big project completed (since for right now downloading the image locally works just fine for me).

**Comment by michaelachrisco** [comment]
Sounds good to me.
I had thought that the GD extension might have had something to do with the
error. Thanks for the writeup!

**Comment by samsullivan** [comment]
I've opened a PR for this, Michael. Didn't test it with the HTML writer (which seems to use a different method), but everything looks good and it does fix the Word2007 issue.
