### ISSUE TITLE
Special Characters, cause xml problems

### ISSUE THREAD

**Issue by rhousham** [PHPOffice/PHPWord#671]
Hi when using the template processor and the setName function e.g
Saving as a doc file.
 
            $templateProcessor = new \PhpOffice\PhpWord\TemplateProcessor($template);
            $templateProcessor->setValue('SOMETEXT',$text);
           $templateProcessor->saveAs($file);

You need to htmlspecialchars the $text because otherwise if it contains a & or presumably other special chars this will break the file and you cannot open it. (unless you want to go through the faff of turning into a zip file, finding the & in the document.xml and changing it to & a m p; ! )

So hence
                   
           $text = htmlspecialchars($text);

above it is required

**Comment by GMTA** [comment]
Please see the following issues for a more detailed insight on this topic:
* #401 
* #514

I am positive that you will be able to solve the issue using the information provided above. Good luck!

**Comment by RomanSyroeshko** [comment]
Hi, @rhousham.
This is resolved in scope of #483. The changes are currently available in `develop` branch.

Thanks for the feedback.
