### ISSUE TITLE
can't align center vertically with the text 

### ISSUE THREAD

**Issue by ter987** [PHPOffice/PHPWord#672]
I used phpword plugin to create word files in my project ,but I have a problem that the paragraph didn't align center ,for example :
![11](https://cloud.githubusercontent.com/assets/15172109/11464902/0e742c36-976f-11e5-8586-7913f68befab.png)

But I want like this :
![22](https://cloud.githubusercontent.com/assets/15172109/11464911/1d356410-976f-11e5-9f50-2b2a0611598e.png)

My codes:
$textrun = $section->createTextRun(array('widowControl'=>'true'));
$textrun->addText('There is a',array('size'=>13));
$textrun->addImage('563803062838d1446511366.gif');
$textrun->addText('whick is a',array('size'=>13));

**Comment by DannydeJong** [comment]
Is the image itself not too high?

**Comment by ter987** [comment]
![center-text-vertically-word-2013-4](https://cloud.githubusercontent.com/assets/15172109/11835192/6eb01434-a40d-11e5-89c8-6e74c61a0819.jpg)

I mean，the word 2010 have a function that can align center vertically ,like the image ,  and does phpword have this function ?

**Comment by darfk3d3** [comment]
I'm interested into this too. Actually phpword support this?

**Comment by troosan** [comment]
indeed, this does not seem to be implemented. 
http://www.datypic.com/sc/ooxml/e-w_vAlign-1.html
Need to write the following in PhpOffice\PhpWord\Writer\Word2007\Style\Section
```xml
<w:sectPr>
<w:vAlign w:val="center"/>
</w:sectPr>
```

**Comment by xcephpdev** [comment]
Hi,

How we we add this in the Section.php File
<w:sectPr>
<w:vAlign w:val="center"/>
</w:sectPr>


THIS IS FROM THE FILES:
  // Page size & orientation
        $xmlWriter->startElement('w:pgSz');
        $xmlWriter->writeAttribute('w:orient', $style->getOrientation());
        $xmlWriter->writeAttribute('w:w', $style->getPageSizeW());
        $xmlWriter->writeAttribute('w:h', $style->getPageSizeH());
        $xmlWriter->endElement(); // w:pgSz

And which tag will be used to set the value dynamically.
