### ISSUE TITLE
Font Paragraph

### ISSUE THREAD

**Issue by kelly806** [PHPOffice/PHPWord#682]
Hey,
I use the font paragraph as follow:
$phpWord = new \PhpOffice\PhpWord\PhpWord();
$header26 = array('size' => 26, 'bold' => true);
$phpWord->addParagraphStyle('fPara', array('alignment' => 'right'));
$section = $phpWord->addSection();
$section->addText(htmlspecialchars('test', ENT_COMPAT, 'UTF-8'), $header26, 'fPara');

and the font paragraph can't work.
Someone can help me?
Thanks!!

**Comment by troosan** [comment]
fixed in 0.14
