### ISSUE TITLE
Unable to install using composer

### ISSUE THREAD

**Issue by mhollander** [PHPOffice/PHPWord#694]
I used the composer dependency in README.md and tried to use composer to install, but am getting an error:

...
~/htdocs/test$ sudo php /opt/bitnami/php/bin/composer.phar install
Loading composer repositories with package information
Installing dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.
  Problem 1
    - The requested package phpoffice/phpword could not be found in any version, there may be a typo in the pack
age name.
Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> for more details.
Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.
...

I tried adding a minimum-stability flag of "dev" to my composer.json file, but that didn't help either.

This is my composer.json file:
...
{                                                                                                               
    "minimum-stability": "dev",                                                                                 
    "require": {                                                                                                
           "phpoffice/phpword": "0.13.*"                                                                        
    }                                                                                                           
}                                                                                                               
...

I'm sorry if I'm being a bonehead and this is really simple.  I'm new to composer.

I'm running debian.

Thank you for any help you can give.

**Comment by ssanders** [comment]
I got it to install using ```"~0.12"```. I’m not sure there’s even a .13 yet.

https://github.com/janhohner/PHPWord/commit/95271f9463c6e85731c20c4d1800f6b61803d8e1 quotes instructions that uses ```"dev-master"```.
But it suggests instead to try ```composer require phpoffice/phpword```.

The README Composer instructions are variously incorrect.

**Comment by mhollander** [comment]
Thank you.  I used dev-master and it worked.  But is that really correct?  README.md should probably be updated by someone that knows more about composer and phpword.

**Comment by RomanSyroeshko** [comment]
Answered [here](https://github.com/PHPOffice/PHPWord/pull/699).
