### ISSUE TITLE
Table of contents numbers missing 

### ISSUE THREAD

**Issue by kemar-stpatrick876** [PHPOffice/PHPWord#707]
I have an issue where my TOC is being generated without the page numbers, 

![image](https://cloud.githubusercontent.com/assets/7540322/12438524/9f96a434-bef5-11e5-8a73-568435634236.png)

can someone help me with this, thanks in advance

**Comment by ramiro174** [comment]
me to

**Comment by geoff-maddock** [comment]
It's going to take somebody taking on the issue, because it doesn't seem like any of the previous developers are following up on these issues.  I'm going to see if I can't figure it out soon.

**Comment by v-man** [comment]
Is there any update for the page numbers missing issue of TOC?  I encounter the similar problem like the following attachment show.
![66ee tmp](https://cloud.githubusercontent.com/assets/17559605/13563725/35d64928-e47f-11e5-9ea0-17e82c54e96c.png)

**Comment by danyamasadeh** [comment]
Is there any update for the page numbers missing issue of TOC?

**Comment by arrabal** [comment]
Still waiting for updates on this issue. It would be great to have numbers in the TOC

**Comment by Worst45** [comment]
+1, still waiting too (in v0.13.0) :)

**Comment by sianto1997** [comment]
Can't you implement a loop at the end of the document which detects on which pages the titles are, and then add those page numbers to the TOC? I'll try it myself, and if it works I will post it here.

**Comment by heretreeli** [comment]
in fact, it's a little effect. Toc will arraise page number after print it as paper

**Comment by scalco19** [comment]
Someone was able to put page numbers in TOC?

**Comment by Venkatasivareddyavula** [comment]
Can any one find solution for this?

**Comment by yjfvictor** [comment]
This issue has been open for one year and a half. Is there anybody going to solve this problem?

**Comment by rramirezbrown** [comment]
Hello, I've experienced the same issues, does anybody know if it has been solved?

**Comment by troosan** [comment]
can anybody post a code sample of the issue?
What's sure is that we cannot set the page number as we do not know it when building the document. What you can do is once you open the document, update the fields. Word will then recompute the page numbers.

**Comment by troosan** [comment]
what you can do to force word to recompute all fields is set updateFields to true
```php
$phpWord->getSettings()->setUpdateFields(true);
```

**Comment by fgali** [comment]
Where can I get an example code on how to make a table of contents?

**Comment by troosan** [comment]
@fgali in the samples
Sample_17_TitleTOC.php

**Comment by fgali** [comment]
The solution you give for the toc numbers is useful for me when I am on my local server on windows but not when I upload it to the hoting.

**Comment by fgali** [comment]
Any suggestions? troosan.

**Comment by troosan** [comment]
I fail to see the difference between your local server and your remote hosting.
Care to elaborate?

**Comment by yangdevt** [comment]
addTOC is being generated without the page numbers still,
Is this solved?

**Comment by HuPengCheng1994** [comment]
$phpWord->getSettings()->setUpdateFields(true);

**Comment by chaitanyagubbala** [comment]
Unable to display page number even after setUpdateFields set to true.

**Comment by ttde1** [comment]
We´ve been able to reproduce and fix this issue. 
You have to active the 
$phpWord->getSettings()->setUpdateFields(true);
configuration and please replace the following file, with the file attached. 

While the MacOS Word is able to reference to a page number using the element´s name, the Windows Word is only able to load the very page number using the element´s id. 

File location:
/phpword/phpoffice/phpword/src/PhpWord/Writer/Word2007/Element/TOC.php

[TOC.php.zip](https://github.com/PHPOffice/PHPWord/files/3358782/TOC.php.zip)

**Comment by yoedusvany** [comment]
Hi, I replaced the file, but I have the issue yet.

**Comment by larryb-redflare** [comment]
@troosan 
> I fail to see the difference between your local server and your remote hosting.
> Care to elaborate?

2019 Issue still occurs; file works fine with flag set when generated locally; when file is downloaded from an internet site, TOC is not updated. I suspect it is an interaction between the MS Word Protected view conflicting with the flag that demands the document is updated when it is opened.

As this is a "rendering" issue, and so a restriction Word is placing on the file, there is probably not a way to fix this in PHPWord.



![2019-09-26 21_18_50-CustomRiskReport (14) docx  -  Protected View - Word](https://user-images.githubusercontent.com/32716618/65722100-73498580-e0a3-11e9-8580-fa83b24e908c.png)

**Comment by larryb-redflare** [comment]
@troosan 

> I fail to see the difference between your local server and your remote hosting.
> Care to elaborate?

The issue (and still occurring in 2019) is if you generate the file with PHP locally and open from a local disk it prompts you to update the file when you open. Generate the file from a web hosted page and when the file opens, Word displays a protected message saying are you sure you want to trust people on the internet, and even when you say yes i trust people on the internet and it allows you to edit the file, the prompt on open that occurs for locally generated files, does not happen and so the TOC remains with no page numbers, requiring a manual update.

I believe the problem is 
![2019-09-26 21_18_50-CustomRiskReport (14) docx  -  Protected View - Word](https://user-images.githubusercontent.com/32716618/65723014-66c62c80-e0a5-11e9-8800-f900c0178a81.png)

I also don't think there is a way to fix in PHPWord, as essentially you would need to set a flag - saying trust me, I'm a good actor on the internet and so running a "macro" is safe; but clearly if PHPWord provided just such a flag, how would we know some bad people would not also set the flag?

So the fix works for files served from trusted locations, but files from untrusted locations do not auto update on open.

**Comment by zhaomengxue7** [comment]
> 
> 
> @troosan
> 
> > I fail to see the difference between your local server and your remote hosting.
> > Care to elaborate?
> 
> The issue (and still occurring in 2019) is if you generate the file with PHP locally and open from a local disk it prompts you to update the file when you open. Generate the file from a web hosted page and when the file opens, Word displays a protected message saying are you sure you want to trust people on the internet, and even when you say yes i trust people on the internet and it allows you to edit the file, the prompt on open that occurs for locally generated files, does not happen and so the TOC remains with no page numbers, requiring a manual update.
> 
> I believe the problem is
> ![2019-09-26 21_18_50-CustomRiskReport (14) docx - Protected View - Word](https://user-images.githubusercontent.com/32716618/65723014-66c62c80-e0a5-11e9-8800-f900c0178a81.png)
> 
> I also don't think there is a way to fix in PHPWord, as essentially you would need to set a flag - saying trust me, I'm a good actor on the internet and so running a "macro" is safe; but clearly if PHPWord provided just such a flag, how would we know some bad people would not also set the flag?
> 
> So the fix works for files served from trusted locations, but files from untrusted locations do not auto update on open.


 I have exactly the same problem ， Has it been solved

**Comment by HuPengCheng1994** [comment]
我不太理解你想问什么问题？我的英文能力不是很好。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年9月6日(星期一) 下午4:33
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [PHPOffice/PHPWord] Table of contents numbers missing  (#707)






@特罗索

我看不到本地服务器和远程主机之间的区别。
能详细说一下吗

问题是（在 2019 年仍然会发生）如果你用PHP在本地和从本地磁盘打开时，它会提示您更新文件。从一个 web 托管页面生成文件，当文件打开时， Word 会显示一条受保护的消息，表示您确定要信任互联网上的人，即使你说是的，我相信人在互联网上，它允许你编辑文件，提示在打开发生的本地生成的文件，不会发生，因此 TOC 仍然没有页码，需要手动更新。

我认为问题在于


我也不认为有一种方法可以修复 PHP Word ，因为本质上你需要设置一个标志-说相信我，我是一个很好的演员在互联网上，所以运行一个“宏”是安全的；很明显，如果 PHP Word 提供了这样一个标志，我们怎么知道一些坏人不会也设置这个标志呢？

因此，修复工作的文件服务，从可信的位置，但文件从不受信任的位置不自动更新打开。

我也有同样的问题，已经解决了吗？

—
你收到这个是因为你评论了。
直接回复此邮件，在 GitHub 上查看或取消订阅.
GitHub Mobile 上的分流通知监督办或机器人.

**Comment by zhaomengxue7** [comment]
You can try the following two ways to solve it 
1、 Set windows file Security 
2、 Generate files into a compressed package， It can be displayed normally after decompression

**Comment by rahuldev1818** [comment]
$phpWord->getSettings()->setUpdateFields(true);

**Comment by rahuldev1818** [comment]
Use this code to update content fields
`$phpWord->getSettings()->setUpdateFields(true);`

**Comment by rahuldev1818** [comment]
```php
$phpWord->getSettings()->setUpdateFields(true);
```
