### ISSUE TITLE
Cannot install phpword version 0.13

### ISSUE THREAD

**Issue by Sohorev** [PHPOffice/PHPWord#713]
composer require phpoffice/phpword 0.13.0

./composer.json has been created
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package phpoffice/phpword could not be found in any version, there may be a typo in the package name.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> for more details.

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

**Comment by publiux** [comment]
0.13 doesn't exist as a release yet. Master is still at .12x. If you need to use this branch, use dev-develop in composer.json.

**Comment by Sohorev** [comment]
ok
