### ISSUE TITLE
How to change the text direction by phpword?

### ISSUE THREAD

**Issue by ter987** [PHPOffice/PHPWord#728]
For example : 
This is a Left to Righ
I want to change it to :
![qq 20160215143018](https://cloud.githubusercontent.com/assets/15172109/13041261/b273f772-d3f0-11e5-9951-0d0442b6fd11.png)

**Comment by ctissier** [comment]
Hi, same question here, did you find a solution ?

**Comment by jjasoncool** [comment]
is there exists any other options about chinese text direction? (e.g. btLr, tbRl)
because there more option in word GUI but I don't know how to find the code.

![image](https://user-images.githubusercontent.com/24731867/51827707-f8b64380-2324-11e9-9e10-6fc86daa6fc1.png)

Thanks!!
