### ISSUE TITLE
PHP7: Cannot use ..\Shared\String as String because 'String' is a special class name

### ISSUE THREAD

**Issue by egon12** [PHPOffice/PHPWord#730]
I'm using php7 and get this error when try Sample_11_ReadWord2007.php got this error

`Cannot use PhpOffice\PhpWord\Shared\String as String because 'String' is a special class name in /home/egon/Programming/www/PhpWordExperiment/vendor/phpoffice/phpword/src/PhpWord/Style/AbstractStyle.php on line 20`

If it isn't ready yet, would you please mention it in Readme.md

Thank you.

**Comment by cookieguru** [comment]
Mentioned many, [many times](https://github.com/PHPOffice/PHPWord/issues?q=String)

**Comment by egon12** [comment]
Oh Sorry, not carefuly search the issues when write this. Will close this issues.. Thanks.
