### ISSUE TITLE
PHP 7 Compability

### ISSUE THREAD

**Issue by iget-master** [PHPOffice/PHPWord#732]
Hi,

I'm migration an application to PHP7 and find out that PHPWord is incompatible because of some class names (String now is taken by PHP as a special class name), giving some erros like:

```
Cannot use PhpOffice\PhpWord\Shared\String as String because 'String' is a special class name
```

Is there any chance of this being fast fixed?

**Comment by flogr** [comment]
Hi,
i've seen this fix is already part of the 0.13.0 release, but is there a chance we get a bugfix release a bit sooner, @RomanSyroeshko ? Can't update my 0.12.* version with composer to 0.13.* since it's not released yet ...
thx

**Comment by iget-master** [comment]
Yes, I've seen that this was fixed on `develop` branch, but no releases yet, and I can't put something at production using the develop branch.

**Comment by RomanSyroeshko** [comment]
@flogr, try like that.
```
{
    "require": {
       "phpoffice/phpword": "dev-develop"
    }
}
```
I can't call `develop` branch ready for production now. So, use it at your own risk.

**Comment by iget-master** [comment]
@RomanSyroeshko Does v0.13.0 has any release date?

**Comment by flogr** [comment]
Thanks @RomanSyroeshko, i'll go with that in the meantime!! May i also ask when a release for v0.13.0 is planned?

**Comment by RomanSyroeshko** [comment]
`v0.13.0` will be released when I resolve all of its issues (if nothing really extraordinary happens). I work alone on the project for a long time and can't plan anything. :disappointed: 

`v0.13.0` contains refactoring of alignment-related functionality, so it's better to wait while PHPWord enthusiasts test it. :smirk:

**Comment by iget-master** [comment]
@RomanSyroeshko

I've seen that you are working alone on this. Some time ago I've made some PR that was never read, so I assumed that this project was abbandoned.

If this help, I can solve some issues to speed up the process, but I can't waste my time fixing something thay may not be used...

I'm free to help, just tell me what you need! :)

**Comment by francythacker** [comment]
Sollution 1:
I renamed class String to Stringg in entire phpword library and this works for me with php7 and older version of php too..

Sollution 2:
or one can use by giving alias to string class like
use PhpOffice\PhpWord\Shared\String as POString;

And now use POString as mentioned below.

public function setText($text)
{
$this->text = POString::toUTF8($text);
return $this;
}
This can also works fine

**Comment by troosan** [comment]
@francythacker or you can just use the latest version 0.14

**Comment by arcodeiglesia** [comment]
> Sollution 1:
> I renamed class String to Stringg in entire phpword library and this works for me with php7 and older version of php too..
> 
> Sollution 2:
> or one can use by giving alias to string class like
> use PhpOffice\PhpWord\Shared\String as POString;
> 
> And now use POString as mentioned below.
> 
> public function setText($text)
> {
> $this->text = POString::toUTF8($text);
> return $this;
> }
> This can also works fine

Thank you very very much!!!
The solution 1 that you suggest save my life.
PhpWord was working fine in Xampp 5.6.38. But few weeks ago I received the order to update to Xampp 7.2.14...
It was terrible. Our application mainly does Word documents with the data that we save in MySql BD. All the documents stopped working with the update. It has been several weeks of unsuccessful tests for it to work again and we were not getting it.
But then you appear with the solution!!!
You have become my heroine

**Comment by francythacker** [comment]
> > Sollution 1:
> > I renamed class String to Stringg in entire phpword library and this works for me with php7 and older version of php too..
> > Sollution 2:
> > or one can use by giving alias to string class like
> > use PhpOffice\PhpWord\Shared\String as POString;
> > And now use POString as mentioned below.
> > public function setText($text)
> > {
> > $this->text = POString::toUTF8($text);
> > return $this;
> > }
> > This can also works fine
> 
> Thank you very very much!!!
> The solution 1 that you suggest save my life.
> PhpWord was working fine in Xampp 5.6.38. But few weeks ago I received the order to update to Xampp 7.2.14...
> It was terrible. Our application mainly does Word documents with the data that we save in MySql BD. All the documents stopped working with the update. It has been several weeks of unsuccessful tests for it to work again and we were not getting it.
> But then you appear with the solution!!!
> You have become my heroine

Pleasure is all mine :-)

**Comment by ekohendratno** [comment]
> Hi,
> 
> I'm migration an application to PHP7 and find out that PHPWord is incompatible because of some class names (String now is taken by PHP as a special class name), giving some erros like:
> 
> ```
> Cannot use PhpOffice\PhpWord\Shared\String as String because 'String' is a special class name
> ```
> 
> Is there any chance of this being fast fixed?

try my branch https://github.com/ekohendratno/phpWord support for php5 and php7

**Comment by creativia** [comment]
I tried to make these modifications for the operation, but it did not work for me.
Is there a corrected version online?
