### ISSUE TITLE
PhpWord on Linux

### ISSUE THREAD

**Issue by cloud450** [PHPOffice/PHPWord#733]
Hi !

I try to use PHPWord on Linux Centos, but it not works.
On Windows OS, I have no problem.
I download PHPWord package from github.

All is Ok 
Requirement check:

    PHP 5.3.3 ... passed
    PHP extension XML ... passed
    Temp folder "c:\Temp" is writable ... passed
    PHP extension ZipArchive (optional) ... passed
    PHP extension GD (optional) ... passed
    PHP extension XMLWriter (optional) ... passed
    PHP extension XSL (optional) ... passed

I must make a particular configuration on Linux ?
Thanks for any help

**Comment by iget-master** [comment]
What exactly does not work?

**Comment by cloud450** [comment]
The document is not generated in the «results» directory
Thank you for your help

**Comment by iget-master** [comment]
1. Are you using the correct directory separator? Linux uses `/` and windows uses `\`.
2. Do your results directory have write permission for your webserver user?

**Comment by cloud450** [comment]
Thank you iget-master!
The problem was the permission of results directory.
Once again, thank you, problem solved.
