### ISSUE TITLE
PHP 7: Cannot use PhpOffice\PhpWord\Shared\String as String because 'String' is a special class name

### ISSUE THREAD

**Issue by btaens** [PHPOffice/PHPWord#736]
The String class name is occupied in base PHP 7, therefore the class `String` throws an error.

**Comment by fisharebest** [comment]
Duplicate of #642, #730, #732, etc.

Already fixed, but not released, so specify `"php-office/php-word": "dev-develop"` in your composer.json

**Comment by garethellis36** [comment]
When is the release due? I do not particularly want to use a develop branch release in production.

**Comment by MrMitch** [comment]
any news on this ?

**Comment by MicBehrens** [comment]
This should be prioritized.

**Comment by kehh** [comment]
This is included in https://github.com/PHPOffice/PHPWord/releases/tag/v0.13.0

**Comment by agwidarsito** [comment]
Is this included in a more stable release other than dev-develop?

**Comment by clemens-tolboom** [comment]
This works for v0.13.0.

@agwidarsito I myself cannot use develop version with Drupal but you can pin a dev version too using a commit version

```
"require": {
        "phpoffice/phpword": "dev-develop#fd156bf12a6d"
}
```

**Comment by agwidarsito** [comment]
@clemens-tolboom Awesome, good to know. Thanks! :)
