### ISSUE TITLE
Install via composer.json not working

### ISSUE THREAD

**Issue by bpineda** [PHPOffice/PHPWord#741]
According to the instructions, one way to install it on a project is to include it in the composer.json file like

`"phpoffice/phpword": "v0.13.*"`

However, if I do that, I get the error

> - The requested package phpoffice/phpword could not be found in any version, there may be a typo in the package name.

I looked for the package in packagist and was unable to find it. Should I add another repository to my composer installation?

**Comment by bpineda** [comment]
My bad, I did find it in packagist, but the version there has not been updated. Sorry about that.

**Comment by lorenzulrich** [comment]
The problem seems to be that only dev-master is in Packagist instead of all tags.
