### ISSUE TITLE
where is "src/PhpWord/Autoloader.php"

### ISSUE THREAD

**Issue by mskies** [PHPOffice/PHPWord#745]
I'm trying install by "Manual install", and use Git  installed phpword, but I can't find the Autoloader.php in src/PhpWord.
help, thanks.

**Comment by trinvh2** [comment]
You must use "composer install --prefer-source" in order to creating Autoload.php in /vendor folder

**Comment by mskies** [comment]
@trinvh2 thinkyou.

**Comment by valcosoftj** [comment]
would be nicer if it was included in the github, not everybody wants to use composer
