### ISSUE TITLE
How download the produced file automatically ?

### ISSUE THREAD

**Issue by cloud450** [PHPOffice/PHPWord#749]
Hello !

I try this code : 
$templateProcessor = new \PhpOffice\PhpWord\TemplateProcessor('Template.docx');
$templateProcessor->setValue('date', $date);
$file = 'HelloWorld.docx';
header("Content-Description: File Transfer");
header('Content-Disposition: attachment; filename="' . $file . '"');
header('Content-Type: application/vnd.openxmlformats-officedocument.wordprocessingml.document');
header('Content-Transfer-Encoding: binary');
header('Cache-Control: must-revalidate, post-check=0, pre-check=0');
header('Expires: 0');
$xmlWriter = \PhpOffice\PhpWord\IOFactory::createWriter($templateProcessor , 'Word2007');
$xmlWriter->save("php://output");

But I can't download it, I have a corrupted file.

Thank your for your help

**Comment by pv451** [comment]
Try to comment headers and look in browser what you actually getting. It seems that your code thows some warning or notices.

**Comment by R1sen** [comment]
Anyway i got a corrupted file. Code:
// Save File
             $objWriter = PHPWord_IOFactory::createWriter($PHPWord, 'Word2007');
             $objWriter->save(ROOT.'/temp/document.docx');

            $contentType = 'Content-type: application/vnd.openxmlformats-officedocument.wordprocessingml.document;';
            $objWriter->save(ROOT.'/temp/document.docx');

            header ( "Expires: Mon, 1 Apr 1974 05:00:00 GMT" );
            header ( "Last-Modified: " . gmdate("D,d M YH:i:s") . " GMT" );
            header ( "Cache-Control: no-cache, must-revalidate" );
            header ( "Pragma: no-cache" );
            header ( $contentType );
            header ( "Content-Disposition: attachment; filename=".ROOT.'/temp/document.docx');
            readfile(ROOT.'/temp/document.docx');

**Comment by pv451** [comment]
@R1sen In headers you should give only file name, not the whole path.
```php
header ( "Content-Disposition: attachment; filename=".'document.docx');
```

**Comment by R1sen** [comment]
Thanks!

2016-03-30 8:43 GMT+03:00 pv451 <notifications@github.com>:

**Comment by mcprogrammernew** [comment]
Hello !
This is my code:

$fileName = 'Determina.docx';
$templateProcessor = new \PhpOffice\PhpWord\TemplateProcessor(public_path('/doc/'.$fileName));
$templateProcessor->setValue('subject', $tender);

$templateProcessor->saveAs(public_path('results/'.$fileName)); 
	 
$contentType = 'Content-type: application/vnd.openxmlformats-officedocument.wordprocessingml.document';	 	
header ( "Expires: Mon, 1 Apr 1974 05:00:00 GMT" );
header ( "Last-Modified: " . gmdate("D,d M YH:i:s") . " GMT" );
header ( "Cache-Control: no-cache, must-revalidate" );
header ( "Pragma: no-cache" );
header ( $contentType );
header ( "Content-Disposition: attachment; filename=".$fileName);
readfile(public_path('results/'.$fileName)); 

When I open the downloaded file it says " problems in content". Then "Detected unreadable content. Retrieve document content? If the document is from a reliable source, click YES".
I click YES and the doc is open with its content. 

What is my error? Could anyone help me?
thank you in advance.

**Comment by femilopsy** [comment]
Below works for me with Laravel 5:
`$file_dir = $template_upload_dir.DIRECTORY_SEPARATOR.'filename.docx';
    $tags = array();
    if (file_exists($file_dir)) {
        $templateProcessor = new TemplateProcessor($file_dir);
        $tags = $templateProcessor->getVariables();
        $replace = array(''); 
        $templateProcessor->setValue($tags, $replace);
        $save_file_name = $fullname.'-'.$inv_code.'-'.date('YmdHis').'.docx';
        $templateProcessor->saveAs($save_file_name);
        return response()->download($save_file_name)->deleteFileAfterSend(true);
    }`
Hope it helps someone!!!

**Comment by ramonbello** [comment]
This is my code and it works

<?php
$nombreUsuario = $this->session->userdata('nombreUsuario');
$cabecera = $empresaSeleccionada[0]->nombre_completo;
$direccionEmpresa = $empresaSeleccionada[0]->direccion;
$telefonoEmpresa = $empresaSeleccionada[0]->telefono;
$estudiante = $certificado[0]->estudiante;
$estudianteCedula = $certificado[0]->cedula_estudiante;
$estudianteCurso = $certificado[0]->curso;
$estudianteParelelo = $certificado[0]->paralelo;
$periodo = $certificado[0]->periodo;
$fechaActual = date("Y-m-d");
$fechaEmision = FormatearFecha($fechaActual);
include_once APPPATH . '/vendor/autoload.php';
$templateProcessor = new \PhpOffice\PhpWord\TemplateProcessor(APPPATH . '/views/matricula/sindicato/PlatillaCertificado.docx');
$templateProcessor->setValue('cabecaraCertificado', $cabecera);
$templateProcessor->setValue('nombreEstudiante', $estudiante);
$templateProcessor->setValue('cedulaEstudiante', $estudianteCedula);
$templateProcessor->setValue('periodoEstudiante', $periodo);
$templateProcessor->setValue('fechaEmision', $fechaEmision);
$templateProcessor->setValue('direccionEmpresa', $direccionEmpresa);
$templateProcessor->setValue('telefonoEmpresa', $telefonoEmpresa);
$templateProcessor->setValue('nombreUsuario', $nombreUsuario);
$templateProcessor->setValue('estudianteCurso', $estudianteCurso);
$templateProcessor->setValue('estudiantePractica', $estudianteParelelo);
$nombreArchivo = $estudiante . ".docx";
$templateProcessor->saveAs("certificados/CERTIFICADO-" . $nombreArchivo);
header("Content-disposition: attachment;filename=CERTIFICADO-" . $nombreArchivo . " ; charset=iso-8859-1");
echo file_get_contents("certificados/CERTIFICADO-" . $nombreArchivo);

**Comment by JHGarrett** [comment]
> Hello !
> This is my code:
> 
> $fileName = 'Determina.docx';
> $templateProcessor = new \PhpOffice\PhpWord\TemplateProcessor(public_path('/doc/'.$fileName));
> $templateProcessor->setValue('subject', $tender);
> 
> $templateProcessor->saveAs(public_path('results/'.$fileName));
> 
> $contentType = 'Content-type: application/vnd.openxmlformats-officedocument.wordprocessingml.document';
> header ( "Expires: Mon, 1 Apr 1974 05:00:00 GMT" );
> header ( "Last-Modified: " . gmdate("D,d M YH:i:s") . " GMT" );
> header ( "Cache-Control: no-cache, must-revalidate" );
> header ( "Pragma: no-cache" );
> header ( $contentType );
> header ( "Content-Disposition: attachment; filename=".$fileName);
> readfile(public_path('results/'.$fileName));
> 
> When I open the downloaded file it says " problems in content". Then "Detected unreadable content. Retrieve document content? If the document is from a reliable source, click YES".
> I click YES and the doc is open with its content.
> 
> What is my error? Could anyone help me?
> thank you in advance.

I am having this issue now 4 years later. Any chance you know the solution???

**Comment by per2mn** [comment]
I found a solution in [readfile doc](https://www.php.net/manual/en/function.readfile.php) https://www.php.net/manual/en/function.readfile.php
 
```php
header('Content-Description: File Transfer');
header('Content-Type: application/octet-stream');
header('Content-Disposition: attachment; filename="' . basename($filename) . '"');
header('Expires: 0');
header('Cache-Control: must-revalidate');
header('Pragma: public');
header('Content-Length: ' . filesize($filename));
readfile($filename);
exit;
```
Ensure that the path for filename is correct.

Late answer but I hope it will help someone.
