### ISSUE TITLE
PhpWord evenPage() and oddPage() methods aren't working

### ISSUE THREAD

**Issue by Globax** [PHPOffice/PHPWord#751]
Hy, i use your awesome library PhpWord, but i have one problem with addHeader().

if i use this

``` php
$section = $phpWord->addSection([
        'marginTop' => PHPWordConverter::cmToTwip(0.75),
        'marginBottom' => PHPWordConverter::cmToTwip(2),
        'marginLeft' => PHPWordConverter::cmToTwip(3),
        'marginRight' => PHPWordConverter::cmToTwip(2)
    ]
);

$header = $section->addHeader();
$header->addText(htmlspecialchars('Header', ENT_COMPAT, 'UTF-8'), null);
```

i have "Header" on each page, id i add firtsPage() method

``` php
$header = $section->addHeader();
$header->firstPage();
$header->addText(htmlspecialchars('Header', ENT_COMPAT, 'UTF-8'), null);
```

i have "Header" on first page, thats works good, but if i use evenPage() method

``` php
$header = $section->addHeader();
$header->evenPage();
$header->addText(htmlspecialchars('Header', ENT_COMPAT, 'UTF-8'),
```

i have nothing, why?

But i realy need oddPage() method, how i can get it works?

**Comment by artuomvproskunin** [comment]
Hy, its work, but need some magic:
````
$footer = $section->addFooter(Header::AUTO);
$footer->addPreserveText('{PAGE}', null, ['align' => 'right']);

$footerEven = $section->addFooter(Header::EVEN);
$footerEven->addPreserveText('{PAGE}');
````
After this open ready document and in "work with headers" set checkbox "different headers for odd and even pages"

**Comment by Globax** [comment]
Hmm, looks like
`$section->addHeader(Header::FIRST);`
set checkbox automatically for Different First Page, but
`$section->addHeader(Header::EVEN);`
not, seems like the bug

Anyway thank you very much :)

**Comment by jaff521** [comment]
I used the codes given by artuomvproskunin to make different page footers, but failed, will you have a new solution??

**Comment by troosan** [comment]
The following PR #981 fixes this issue
