### ISSUE TITLE
Line breaks

### ISSUE THREAD

**Issue by slash66672** [PHPOffice/PHPWord#756]
Hi, we are working with phpWord to create a document from a html code.

The html code is stored in a database with tags as  &lt;br&gt; and &lt;b&gt;. The question is how we achieve these same styles generated in the docx file?

We try to replace the tags <br> by: \ n \ r \ n <w: br> and not the line break is generated. We have a html code like this:

```
<b>Item:</b> 123 <br>Count: ABC
<table>
  <tr>
    <td>April 2nd 2016</td>
    <td> Day 6 - Exploring the east<br/>
      <br/>
      In the morning ....<br/>
      <br/>
      <br/>
      Science and relaxation<br/>
      Take a tour....<br/>
      <br/>
      Nature walk<br/>
      Accompanied...<br/></td>
  </tr>
</table>
```

We use the addHtml function but this does not work. This is the code:

```
$phpWord = new \PhpOffice\PhpWord\PhpWord();

$section = $phpWord->addSection();
$html = '<b>Item:</b> 123 <br>Count: ABC
<table>
  <tr>
    <td>April 2nd 2016</td>
    <td> Day 6 - Exploring the east<br/>
      <br/>
      In the morning ....<br/>
      <br/>
      <br/>
      Science and relaxation<br/>
      Take a tour....<br/>
      <br/>
      Nature walk<br/>
      Accompanied...<br/></td>
  </tr>
</table>';

\PhpOffice\PhpWord\Shared\Html::addHtml($section, $html);
```

But when we try to open the file in MS Word it tells us an error message: Error opening file.

We want to know how to replace the line break for MS Word understands.

Thank you

**Comment by Ryuzakix3** [comment]
Open the Html.php (**PhpWord\Shared\Html.php**) go to the parseNodes function and add the line to the nodes array.

`'br'		=> array("TextBreak",	null,	$element,	null,		null,	null,			null),`

Now just copy the function and past to the end of the file

`	private static function parseTextBreak( $element )
	{
		$element->addTextBreak(1, null, null);
		
		return null;
	}
	`

**Comment by newbro** [comment]
The cause of the problem is the html tags. You may try using php function `strip_tags` to sanitize the data first.

**Comment by lcdservices** [comment]
We are running into this issue as well. strip_tags is not a solution -- we want the line breaks as denoted by the <br /> tags. Anyone find a solution to this?

**Comment by troosan** [comment]
`<br/>`tags should be parsed (since version 0.14 anyway).
Can you post a sample html code that does not work for you please?

**Comment by lcdservices** [comment]
we actually realized it was because our copy of the library was a bit outdated. once we updated it the break tags were parsed properly.

**Comment by reimax** [comment]
test example slash66672 and not work Line breaks.

**Comment by manchenkoff** [comment]
In version 0.16.0 also doesn't work, I tried to use both <br/> and <br> in HTML string
