### ISSUE TITLE
Have any ideas how to Insert MathML into document?

### ISSUE THREAD

**Issue by webquail** [PHPOffice/PHPWord#761]
Have any ideas how to Insert MathML or LaTex formula into document?

**Comment by r3sist** [comment]
Is it possible now somehow? :)

**Comment by latincrow81** [comment]
right now i use wkhtmltoimage to generate the formulas aside and then add them to the doc, but it would be way better if there was a math obj :blush

**Comment by Progi1984** [comment]
FYI : A Pull Request is in Progress : #2477
