### ISSUE TITLE
bug:Invalid style value: chineseCountingThousand  Options:bullet,decimal,upperRoman,lowerRoman,upperLetter,lowerLetter

### ISSUE THREAD

**Issue by hangzhoubison** [PHPOffice/PHPWord#777]
Thank you that we can provide such a good open source project, I encountered a little problem in the use of the process, please help. THX

i'm loading a doc file  and i hope  the doc file generate a html format file  
this is my code

```
    if(!file_exists($path_word)){
    throw new \Exception("file path error");
}
if(file_exists($path_html=str_replace(array('docx','doc'), 'html', $path_word))){
    return ;
}
require_once C('APPLICATION_DIR').DIRECTORY_SEPARATOR.'Home/Libs/PhpWord/Autoloader.php';
\PhpOffice\PhpWord\Autoloader::register();

// Creating the new document...
//$phpWord = new \PhpOffice\PhpWord\PhpWord();

//Load temp file
$phpWord = \PhpOffice\PhpWord\IOFactory::load($path_word); 
//Save it
$xmlWriter = \PhpOffice\PhpWord\IOFactory::createWriter($phpWord , 'HTML');
$xmlWriter->save($path_html);
```

but fail  !
bug:
exception file name D:\Projects\Verification\W\Application\Home\Libs\PhpWord\Style\AbstractStyle.php

line 287

exception info  Invalid style value: chineseCountingThousand Options:bullet,decimal,upperRoman,lowerRoman,upperLetter,lowerLetter

**Comment by troosan** [comment]
fixed in 0.14
