### ISSUE TITLE
Euro sign does not render in Word

### ISSUE THREAD

**Issue by redanser** [PHPOffice/PHPWord#780]
When I use the basic example to generate a Euro sign, I get a square in my Word file. However, if I copy the text and paste it in another program, the Euro sign shows up just fine, so somewhere it still is the right sign, it only doesn't show up in Word. If I type a Euro sign in the word doc itself, it also shows, so it's not the font either. 

What am I doing wrong?

I used this code: 

```php
<?php require_once **DIR** . '/PhpWord/Autoloader.php';
\PhpOffice\PhpWord\Autoloader::register();

$phpWord = new \PhpOffice\PhpWord\PhpWord();

$section = $phpWord->addSection();
$section->addText("€");

// Saving the document as OOXML file...
$objWriter = \PhpOffice\PhpWord\IOFactory::createWriter($phpWord, 'Word2007');
$objWriter->save('helloWorldEURO.docx');
?>
```

**Comment by pxom** [comment]
This works for me:
$fa_euro     = html_entity_decode('&#xf153;', 0, 'UTF-8');
$section->addText(utf8($fa_euro));

Hope it helps!
