### ISSUE TITLE
Can not lock/protect header from edit

### ISSUE THREAD

**Issue by dragmecom** [PHPOffice/PHPWord#785]
So I noticed that the PHPWord lib has virtually everything but the lock mechanism from Word, that allows for you to password lock paragraphs or exclusively the header and footer from being able to be edited. 

Right now it maintains locks when edited, but it can not create locks, unless I am missing something. 

Would be great if you could add this patch/feature.

**Comment by troosan** [comment]
this has been implemented in version 0.14.
See https://github.com/PHPOffice/PHPWord/blob/develop/docs/general.rst#document-protection
