### ISSUE TITLE
composer issue

### ISSUE THREAD

**Issue by xcopy** [PHPOffice/PHPWord#786]
I try to install `PHPOffice/PHPWord` via Composer as mentioned in README

``` json
{
    "require": {
       "phpoffice/phpword": "v0.13.*"
    }
}
```

But weird,

``` shell
$ composer install
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package phpoffice/phpword v0.13.* exists as phpoffice/phpword[0.10.0, 0.10.1, 0.11.0, 0.11.1, 0.12.0, 0.7.0, 0.8.0, 0.8.1, 0.9.0, 0.9.1, dev-develop, dev-master, v0.12.1] but those are rejected by your constraint.
```

Looks like releases `v0.13.*` does not exists. Or, am I missing something?

**Comment by pv451** [comment]
https://github.com/PHPOffice/PHPWord/releases

**Comment by xcopy** [comment]
@pv451 so, where is `v0.13.x`?

**Comment by pv451** [comment]
Obviously there is no v0.13.x yet. I suppose this is a mistake in readme.

**Comment by xcopy** [comment]
Yeah, I guess so
22 апр. 2016 г. 11:50 пользователь "pv451" <notifications@github.com>
написал:
