### ISSUE TITLE
Add footnote reference multiple times

### ISSUE THREAD

**Issue by zajca** [PHPOffice/PHPWord#790]
Hi,
It's possible to reference footnote multiple times?

I was looking for way how to do it and din't find any.

Also, I was looking how to remove number from footnote and use asterisk or something. I docs is only reference to `superScript` in fontStype but when I set it to `false` nothing happen.

**Comment by jordankaiser** [comment]
Thanks for the great library!!!

This is something I'd like to do as well. Examples follow.

**Current Implementation**

The big gray dog<sup>1</sup> is fast.
The small gray dog<sup>2</sup> is slow.

1 A friendly canine.
2 A friendly canine.

-------

**Desired Implementation**

The big gray dog<sup>1</sup> is fast.
The small gray dog<sup>1</sup> is slow.

1 A friendly canine.

**Comment by troosan** [comment]
Do you manage to this in Word?

**Comment by jordankaiser** [comment]
I think I see where you're going. I cannot do this in Word. I would guess the functionality of the library may be limited to the functionality of Word. Thanks for the response!
