### ISSUE TITLE
&lt; in addHTML

### ISSUE THREAD

**Issue by sleker78** [PHPOffice/PHPWord#791]
#Hi,
Great application - thanks.
There is a problem when you have `&lt;` in string:
```
$html='<p>something &lt; something </p>;
\PhpOffice\PhpWord\Shared\Html::addHtml($section, $html);
```

It'll break the xml structure for docs. Possible solution is to change addHTML method:
```
 // Load DOM
        $dom = new \DOMDocument();
        $dom->preserveWhiteSpace = true;
        $dom->loadXML($html,LIBXML_NOCDATA);
```

With this replacement user can send `<![CDATA[_lt_]]>` instead of `&lt;` like this:
```
$html='<p>something <![CDATA[_lt_]]> something </p>;
\PhpOffice\PhpWord\Shared\Html::addHtml($section, $html);
```

and it'll work ok.

Maybe there is some better solution but this will work for now.

Thanks

**Comment by RomanSyroeshko** [comment]
https://github.com/PHPOffice/PHPWord/issues/671#issuecomment-231520458.
