### ISSUE TITLE
Not PHP 7  compatible

### ISSUE THREAD

**Issue by schnuti** [PHPOffice/PHPWord#800]
The String class has to change name. It's used internally by PHP 7.

**Comment by mmarinero** [comment]
It's fixed in the develop branch, but there isn't a tagged release with the changes yet.

**Comment by schnuti** [comment]
Geat! Thanks, I'll try to find what tou changed it to,,

**Comment by Einenlum** [comment]
:+1:

**Comment by MicBehrens** [comment]
This should be prioritized.

**Comment by dmnk** [comment]
according to the last comment in #835 its fixed with #839 and both issues should be closed.

**Comment by troosan** [comment]
fixed in 0.14
