### ISSUE TITLE
Cannot find archive file / no such file or directory when opening template file

### ISSUE THREAD

**Issue by m-bosman** [PHPOffice/PHPWord#801]
When trying to open a template file through either templateprocessor or the load method, an exception is thrown. CopyFileException for the templateprocessor. Using version 0.12.0 due to not being able to install with composer. What am I doing wrong?

```
require_once dirname(__FILE__) . '/../classes/PhpOffice/src/PhpWord/Autoloader.php';
PhpOffice\PhpWord\Autoloader::register();
$templateProcessor = new \PhpOffice\PhpWord\TemplateProcessor('PhpOffice/PhpWord/test.docx');
//$phpWord = \PhpOffice\PhpWord\IOFactory::load('test.docx');
```

**Comment by JonasPardon** [comment]
What happened with this issue? Currently experiencing the same problem and can't find any online resources of people fixing this.

**Comment by marie1st** [comment]
Probably it could be permission to the folder of your application, chmod 777 [folder name]
