### ISSUE TITLE
addHtml to cell

### ISSUE THREAD

**Issue by ikerib** [PHPOffice/PHPWord#815]
Hi,

I need to create a 2 column document (same text but diferent language in each column). I generated the html and tried with 
`\PhpOffice\PhpWord\Shared\Html::addHtml($section, $html);`

witch works with small text but my text is very large. 

I checked the [21 Sample](https://github.com/PHPOffice/PHPWord/blob/develop/samples/Sample_21_TableRowRules.php) but there is no addHtml method for a cell. Is there any way to append html to a cell? something like this:

```
$table1 = $section->addTable(array('cellMargin' => 0, 'cellMarginRight' => 0, 'cellMarginBottom' => 0, 'cellMarginLeft' => 0));
$table1->addRow(3750);  
$cell1 = $table1->addCell(null, array('valign' => 'top', 'borderSize' => 30, 'borderColor' => 'ff0000'));
$cell1->addHtml('<p>lorem ipsum</p>');
$cell2 = $table1->addCell(null, array('valign' => 'top', 'borderSize' => 30, 'borderColor' => 'ff0000'));
$cell2->addHtml('<p>lorem2 ipsum2</p>');
```

**Comment by troosan** [comment]
instead of passing $section to the addHTML method, try to pass the $cell.
Like this
```php
\PhpOffice\PhpWord\Shared\Html::addHtml($cell1, '<p>lorem ipsum</p>');
```
