### ISSUE TITLE
Having an error while saving template as PDF

### ISSUE THREAD

**Issue by miniven** [PHPOffice/PHPWord#816]
I use a template (word document) and after replacing variables I save it as .docx
Then I try to load this file and to make it as pdf

`$phpWord = \PhpOffice\PhpWord\IOFactory::load('../docs/' . $new_contract_num . '/contract.docx');
        $xmlWriter = \PhpOffice\PhpWord\IOFactory::createWriter($phpWord, 'PDF');
    $xmlWriter->save('../docs/' . $new_contract_num . '/contract.pdf');`

And I get an error:

`Fatal error: Uncaught exception 'PhpOffice\PhpWord\Exception\Exception' with message 'PDF rendering library or library path has not been defined.' in C:\OpenServer\domains\infoproject\public\vendor\phpoffice\phpword\src\PhpWord\Writer\PDF.php:49 Stack trace: #0 C:\OpenServer\domains\infoproject\public\vendor\phpoffice\phpword\src\PhpWord\IOFactory.php(34): PhpOffice\PhpWord\Writer\PDF->__construct(Object(PhpOffice\PhpWord\PhpWord)) #1 C:\OpenServer\domains\infoproject\public\partials\generate.php(135): PhpOffice\PhpWord\IOFactory::createWriter(Object(PhpOffice\PhpWord\PhpWord), 'PDF') #2 {main} thrown in C:\OpenServer\domains\infoproject\public\vendor\phpoffice\phpword\src\PhpWord\Writer\PDF.php on line 49`

How to solve this?

**Comment by miniven** [comment]
I also tried to save as html and RTF and it worked correctly

**Comment by wqj97** [comment]
me too~

**Comment by rinkesh-prajapat** [comment]
me to

**Comment by troosan** [comment]
You need to tell PhpWord which PDF library to use. For instance
```php
        $rendererName = Settings::PDF_RENDERER_DOMPDF;
        $rendererLibraryPath = realpath('/../vendor/dompdf/dompdf');
        Settings::setPdfRenderer($rendererName, $rendererLibraryPath);
```
