### ISSUE TITLE
& and Special Characters, cause xml problems

### ISSUE THREAD

**Issue by pascaldls** [PHPOffice/PHPWord#818]
Struggle with this for one day before finding a solution 

For \PhpOffice\PhpWord\Shared\Html::addHtml 

line 238 private static function parseText  

i have added the following to slolve the problem 
`$element->addText( "<![CDATA[" . $node->nodeValue . "]]>" , $styles['font'], $styles['paragraph']);`

this make the text be valid xml 

Sorry for creating new bug for but i feel like sharing 
Special Characters, cause xml problems #671

**Comment by RomanSyroeshko** [comment]
https://github.com/PHPOffice/PHPWord/issues/671#issuecomment-231520458.
