### ISSUE TITLE
Page break for ODT

### ISSUE THREAD

**Issue by Issamatonis** [PHPOffice/PHPWord#824]
Hello,

i'm trying to generate docx and odt files. addPageBreak() work with docx, but not with ODT, i have all the content in the same page

**Comment by cookiekiller** [comment]
Same for me with 0.13 and dev branch.

**Comment by cookiekiller** [comment]
It's actually not even implemented for the ODT writer. That's the problem, it's not a bug, it's a missing feature, the ODT writer lacks of a lot features.

**Comment by cookiekiller** [comment]
@Issamatonis did you find any workaround?

**Comment by Issamatonis** [comment]
@cookiekiller : i used WORD to create the content than ODT to save the file: 

$word = new \PhpOffice\PhpWord\PhpWord();
$section = $word->addSection(array('orientation'=>'portrait'));

-- section content--

$nom_du_fichier_odt = "nom_fichier.odt";
$objWriter = \PhpOffice\PhpWord\IOFactory::createWriter($word, 'ODText');            
$objWriter->save($chemin . $nom_du_fichier_odt );

**Comment by cookiekiller** [comment]
@Issamatonis thanks for your answer, I implemented pagebreak meanwhile and created a pullrequest: https://github.com/PHPOffice/PHPWord/pull/863
