### ISSUE TITLE
Catchable error with ContentTypes::writeContentType()

### ISSUE THREAD

**Issue by NZasepa** [PHPOffice/PHPWord#833]
Hey there, 

I'm working on a project for an agency client. We've developed a system to generate product instructions via specific questions and answers. 

The problem is that I'm stucked on getting and error from PHPWord. 

> Catchable fatal error: Argument 1 passed to PhpOffice\PhpWord\Writer\Word2007\Part\ContentTypes::writeContentType() must be an instance of PhpOffice\Common\XMLWriter, instance of PhpOffice\PhpWord\Shared\XMLWriter given, called in /home/users/mp/public_html/beiko/wp-content/plugins/ic-warranty-grant/vendor/phpoffice/phpword/src/PhpWord/Writer/Word2007/Part/ContentTypes.php on line 71 and defined in /home/users/mp/public_html/beiko/wp-content/plugins/ic-warranty-grant/vendor/phpoffice/phpword/src/PhpWord/Writer/Word2007/Part/ContentTypes.php on line 87

My word file generating script is almost 1:1 with the documentation, so it's not an issue with my code. 

Best regards

**Comment by troosan** [comment]
I guess this does not happen anymore as the XMLWriter from PhpWord\Shared does not exist anymore?
