### ISSUE TITLE
Cannot align text

### ISSUE THREAD

**Issue by Vayel** [PHPOffice/PHPWord#834]
Hi,

I'm using PHPWord 12.1 but I don't manage to align text. The following code generates bold text but aligned to the left:

```
<?php
date_default_timezone_set('Europe/Paris');
require_once 'vendor/autoload.php';

$phpWord = new \PhpOffice\PhpWord\PhpWord();

// New portrait section
$section = $phpWord->addSection();

// Simple text
$section->addTitle('Welcome to PhpWord', 1);
$section->addText('Hello World!');

// Two text break
$section->addTextBreak(2);

// Define styles
$section->addText('Centered', array('bold' => true), array('alignment' => 'center'));

// Save file
$objWriter = \PhpOffice\PhpWord\IOFactory::createWriter($phpWord, 'Word2007');
$objWriter->save('sample.docx');

$objWriter = \PhpOffice\PhpWord\IOFactory::createWriter($phpWord, 'ODText');
$objWriter->save('sample.odt');

$objWriter = \PhpOffice\PhpWord\IOFactory::createWriter($phpWord, 'HTML');
$objWriter->save('sample.html');
```

Thanks

**Comment by aslubsky** [comment]
use
`$section->addText('some text', [], [
        'align' => \PhpOffice\PhpWord\Style\Alignment::ALIGN_CENTER
 ]);`

**Comment by Vayel** [comment]
Thanks!

However, it does not work for ODText format, only for Word2007 (I use LibreOffice 5).

**Comment by lythanhngodev** [comment]
$table->addCell(6500)->addText("Text", [], ['align' => \PhpOffice\PhpWord\Style\Cell::VALIGN_CENTER ]);

**Comment by venkata-koatiah** [comment]
Currently  I am Struggling for alignment in phpword (0.14.0) .I am Not able to do perform align left,right, center. But for alignment Justify  i am using this code it's working for me 

$phpWord->setDefaultParagraphStyle(
            array(
                'align'      => 'both',
                'spaceAfter' => \PhpOffice\PhpWord\Shared\Converter::pointToTwip(12),
                'spacing'    => 120,
                )
            );


i want to know  alignment ( left,right, center ) . code If anybody knows please let me know

**Comment by troosan** [comment]
please check https://phpword.readthedocs.io/en/latest/styles.html#paragraph

**Comment by troosan** [comment]
@mcabanatan please check Sample_09_Tables.php, there's an example there

**Comment by mcabanatan** [comment]
HI @troosan,

My above code came from Sample_09_Tables.php which doesnt work. I'm opening the word in word2013.

Regards

**Comment by troosan** [comment]
This is what I'm getting (word 2016 for mac)
![image](https://user-images.githubusercontent.com/6959414/40204292-5166158a-5a28-11e8-9ff2-0aa344cbcbaa.png)

**Comment by mcabanatan** [comment]
Well that works perfect! I don't know why it doesn't work on mine(word2013). Can I have the code you use to generate the word file?

Thanks in advance!

**Comment by troosan** [comment]
@mcabanatan That's exactly from **Sample_09_Tables.php**

**Comment by luizz** [comment]
@mcabanatan set space in $tableCenterValignText
```
$tableCenterValignText = array(
	'spaceBefore'=>0,
	'spaceAfter'=>0,
	'alignment' => \PhpOffice\PhpWord\SimpleType\Jc::CENTER, 
	'align' => \PhpOffice\PhpWord\Style\Cell::VALIGN_CENTER
);
```

**Comment by Tamn9208** [comment]
$section->addText('Centered', array('bold' => true), array('align' => 'center'));

**Comment by Stream3rPixel** [comment]
$section->addText("Center", array('bold' => true, "size"=>25), array('align' => 'center'));
