### ISSUE TITLE
PHP7 not support

### ISSUE THREAD

**Issue by dillongod** [PHPOffice/PHPWord#835]
int  php7, we cann't define a class named String.

**Comment by aslubsky** [comment]
+1 same problem
Cannot use PhpOffice\PhpWord\Shared\String as String because 'String' is a special class name

**Comment by mlinuxgada** [comment]
That issue is addressed several times, like [here](https://github.com/PHPOffice/PHPWord/issues?q=String). 
Guys, can you fix it, because its not quite wise to switch to "dev-develop" on a production server.

**Comment by mlinuxgada** [comment]
Already commited pull request [here #839 ](https://github.com/PHPOffice/PHPWord/pull/839). 
Now its up to the devs to accept it.

**Comment by DemianD** [comment]
"Already fixed, but not released, so specify "php-office/php-word": "dev-develop" in your composer.json"

- @fisharebest

**Comment by MicBehrens** [comment]
This should be prioritized.

**Comment by lukepolo** [comment]
Version 13 has it, and has been released

**Comment by John2013** [comment]
I renamed String to Stringg manualy and everything works on PHP7

**Comment by troosan** [comment]
already fixed in 0.14

**Comment by francythacker** [comment]
I renamed class String to Stringg in entire phpword library and this works for me with php7 and older version of php too..
