### ISSUE TITLE
TOC Missing Page# Resolution

### ISSUE THREAD

**Issue by James-1234** [PHPOffice/PHPWord#844]
There have been a number of unresolved issues previously raised on the TOC not showing page numbers. This appears to be caused by Word not 'updating' the TOC when the doc is opened. If you right click and 'update' - then the page numbers do show. The resolution to this issue appears to be finding a way to 'trick' Word into doing an 'update' when the doc is opened. Any ideas anyone ? 
Thanks

**Comment by INHack20** [comment]
+1 I'm having the same issue.

**Comment by scalco19** [comment]
Any solution?

**Comment by INHack20** [comment]
Hello, I solved it on windows using the "com_dotnet" library, this is not a final solution nor official, we hope and can solve that bug in the library.

$extension = "com_dotnet";

if (extension_loaded($extension)) {

    #Instantiate the spreadsheet component.
    $excel = new COM("Word.application") or die("Could not initialise Object.");
    // set it to 1 to see the MS Word window (the actual opening of the document)
    $excel->Visible = 0;
    // recommend to set to 0, disables alerts like "Do you want MS Word to be the default .. etc"
    $excel->DisplayAlerts = 0;
    // open the word 2007-2013 document 
    $excel->Documents->Open($source);
    $tableNum = $excel->ActiveDocument->TablesOfContents()->Count;
    for ($i = 1; $i <= $tableNum; $i++) {
        $excel->ActiveDocument->TablesOfContents($i)->UpdatePageNumbers();
    }
    $excel->ActiveDocument->SaveAs($destination);
    $excel->ActiveDocument->Close(0);
    $excel->Quit(0);
    // clean up
    unset($excel);

} else {
    throw new \RuntimeException("Debe cargar la extension en windows de extension=php_com_dotnet.dll");
}

**Comment by deepakgup** [comment]
@INHack20 Do we have a good fix for the issue?

**Comment by troosan** [comment]
you can force word to update fields with the following:
```php
$phpWord = new \PhpOffice\PhpWord\PhpWord();
$phpWord->getSettings()->setUpdateFields(true);
```

**Comment by chrisribe** [comment]
> you can force word to update fields with the following:
> 
> ```
> $phpWord = new \PhpOffice\PhpWord\PhpWord();
> $phpWord->getSettings()->setUpdateFields(true);
> ```

Does not work in office 365, you have to manually select all then hit F9
:(
