### ISSUE TITLE
Release v0.14.0

### ISSUE THREAD

**Issue by RomanSyroeshko** [PHPOffice/PHPWord#848]
- [x] Wait that all tickets assigned to [Milestone v0.14.0](https://github.com/PHPOffice/PHPWord/milestone/17) are closed.
- [x] Create the next milestone & the release ticket.
- [x] Set date of the release in `CHANGELOG.md`.
- [x] Create and merge PR from correspondent branch to `master`.
- [x] Close the milestone.
- [x] Publish the release.
- [x] Tweet the release [@PHPWord](https://twitter.com/PHPWord).

**Comment by morgunder** [comment]
@RomanSyroeshko any idea when 0.14.0 might be coming out?

**Comment by RomanSyroeshko** [comment]
Hi @morgunder,
Unfortunately I do not maintain the library anymore.

Poke @Progi1984.

**Comment by Progi1984** [comment]
@morgunder We are currently looking for a long term maintainer for this library (#948). @MarkBaker is busy with PhpSpreadsheet & me with PhpPresentation.

**Comment by morgunder** [comment]
@RomanSyroeshko @Progi1984 wow.  didn't realize that - might be readme worthy.  looking at the 0.14 milestone there don't seem to be that many issues.  seems like it might be a small project to push this across the finish line.  or do you see undocumented work that needs to be processed?
