### ISSUE TITLE
installing via composer - failing

### ISSUE THREAD

**Issue by josina08** [PHPOffice/PHPWord#852]
![image](https://cloud.githubusercontent.com/assets/8400694/17435381/130e2ad0-5b19-11e6-9cbe-1529d3cf0c7e.png)

**Comment by ozilion** [comment]
Hi, just go head to the link given and create your token in github and run installer again.

**Comment by josina08** [comment]
doesnt work...tried it many times

**Comment by josina08** [comment]
![image](https://cloud.githubusercontent.com/assets/8400694/17436346/fcaf11cc-5b1e-11e6-8058-0cc84c0d1373.png)

**Comment by josina08** [comment]
fixed was able to install
changed composer timeout to 200 as below

$ COMPOSER_PROCESS_TIMEOUT=2000 composer update --prefer-dist --no-dev
