### ISSUE TITLE
Is there any plan to support OMML or MathML?

### ISSUE THREAD

**Issue by xueliangliang** [PHPOffice/PHPWord#860]
Understand that OMML and MathML specs are quite complex, but if we use third party tool to author MathML,  the PHPWord library just open an API to load the MathML and convert the MathML using Office's own mathml2ooml.xls,  during exporting phase,  it directly insert into the final document.xml. In this case, the implementation effort should be much less. Anyone can verify whether the idea is achievable? And which files I should look into?

**Comment by xueliangliang** [comment]
I did a intrusive hacking approach via patch 

PhpWord/Writer/Word2007/Element/Text.php
PhpWord/Element/Text.php

For MathsML, it will just directly call

`$xmlWriter->writeRaw($this->getText($element->getText()));`

It has achieved my original intention, I will see how to make an more elegant patch from here.

**Comment by lengyuan** [comment]
Hi Xueliangliang, could you please share more details on the hacking approach? Thanks

**Comment by r3sist** [comment]
+1, it would be nice

**Comment by xueliangliang** [comment]
What kind of details do you need? `mathml2ooml.xls` can be found in Office folder, from there you can create MathML to OOML. and use `$xmlWriter->writeRaw` to insert the OOML into word directly.

**Comment by xueliangliang** [comment]
https://stackoverflow.com/questions/14041009/algorithm-or-code-for-converting-omml-to-mathml

**Comment by r3sist** [comment]
@xueliangliang Conversion is not a problem. For those who need:

```php
$xml = new DOMDocument;
$xml->loadXML($mathmlString);
$xsl = new DOMDocument;
$xsl->load('mml2omml.xsl'); // This could be found in MSOffice installation
$processor = new XSLTProcessor;
$processor->importStyleSheet($xsl);
$ommlString = $processor->transformToXML($xml);
```

I just couldn't find $xmlWriter object or couldn't use $xmlWriter->writeRaw method. I have active *word* and *section* objects and I would like to write that section texts and math expressions.

```
$word = new \PhpOffice\PhpWord\PhpWord();
$wordSection = $word->addSection();
```

Thank you for your comment!

**Comment by xueliangliang** [comment]
You need looking into 

`PhpWord/Writer/Word2007/Element/Text.php`,
`PhpWord/Element/Text.php`

 to create a customised element yourself to inject the raw omml. You can not use the existing exposed API to achieve it. 

And unzip a word with Math Equations, and check the actual output of the OMML, it is not a trivial task.

**Comment by eduardobreno** [comment]
> You need look into
> 
> `PhpWord/Writer/Word2007/Element/Text.php`,
> `PhpWord/Element/Text.php`
> 
> to create a customised element yourself to inject the raw omml. You can not use the existing exposed API to achieve it.
> 
> And unzip a word with Math Equations, and check the actual output of the OMML, it is not a trivial task.

Hi ,@xueliangliang , can you provide a example of how you inject raw omml ?

**Comment by xueliangliang** [comment]
For the latest version , it doesn't require any hacking, the following code is working as I expected.


`<?php
require_once 'bootstrap.php';

// Creating the new document...
$phpWord = new \PhpOffice\PhpWord\PhpWord();

/* Note: any element you append to a document must reside inside of a Section. */

// Adding an empty Section to the document...
$section = $phpWord->addSection();

$xml = new DOMDocument;
$xml->loadXML('<math xmlns="http://www.w3.org/1998/Math/MathML"><mroot><mi>x</mi><mn>4</mn></mroot></math>');
$xsl = new DOMDocument;
$xsl->load('./mathml2omml.xsl'); // This could be found in MSOffice installation
$processor = new XSLTProcessor;
$processor->importStyleSheet($xsl);
$omml = $processor->transformToXML($xml);
$t_omml = new DOMDocument;
$t_omml->loadXML($omml);
$omml = $t_omml->saveXML($t_omml->documentElement);    //Remove XML Version tag
echo $omml;
$section->addText($omml);


// Saving the document as OOXML file...
$objWriter = \PhpOffice\PhpWord\IOFactory::createWriter($phpWord, 'Word2007');
$objWriter->save('helloWorld.docx');`

**Comment by eduardobreno** [comment]
@xueliangliang , it worked! Thanks for your help.

**Comment by mandala21** [comment]
I try this code but i have error this error:
PHP Warning:  XSLTProcessor::importStylesheet(): compilation error: file /home/lucas/source/supercev/mathml2omml.xsl line 8 element stylesheet in Psy Shell code on line 1

You can send the mathml2omml.xsl file?

**Comment by mandala21** [comment]
I make this code but my docx is generate empty

**Comment by hungdang6676** [comment]
> For the latest version , it doesn't require any hacking, the following code is working as I expected.
> 
> ```
> <?php
> require_once 'bootstrap.php';
> 
> // Creating the new document...
> $phpWord = new \PhpOffice\PhpWord\PhpWord();
> 
> /* Note: any element you append to a document must reside inside of a Section. */
> 
> // Adding an empty Section to the document...
> $section = $phpWord->addSection();
> 
> $xml = new DOMDocument;
> $xml->loadXML('<math xmlns="http://www.w3.org/1998/Math/MathML"><mroot><mi>x</mi><mn>4</mn></mroot></math>');
> $xsl = new DOMDocument;
> $xsl->load('./mathml2omml.xsl'); // This could be found in MSOffice installation
> $processor = new XSLTProcessor;
> $processor->importStyleSheet($xsl);
> $omml = $processor->transformToXML($xml);
> $t_omml = new DOMDocument;
> $t_omml->loadXML($omml);
> $omml = $t_omml->saveXML($t_omml->documentElement);    //Remove XML Version tag
> echo $omml;
> $section->addText($omml);
> 
> 
> // Saving the document as OOXML file...
> $objWriter = \PhpOffice\PhpWord\IOFactory::createWriter($phpWord, 'Word2007');
> $objWriter->save('helloWorld.docx');
> ```
i can transform them to math type in word, but how can i concat some string together the formular? For example: "Give a fomular <math xmlns="http://www.w3.org/1998/Math/MathML"><mroot><mi>x</mi><mn>4</mn></mroot></math> please choose correct answer?"

**Comment by bhavink21** [comment]
@xueliangliang 
can you share this mathml2omml.xsl file with me?

**Comment by xueliangliang** [comment]
> @xueliangliang @hungdang6676
> 
> hello,
> in my case i m getting an error of "XSLTProcessorNot Found".
> can anyone help me with it?

install xsl extension.

**Comment by bhavink21** [comment]
@xueliangliang 
Not being able to do so.
could you guide me how to do so, or share a link of how to install it?

**Comment by hungdang6676** [comment]
> @xueliangliang @hungdang6676
> 
> hello,
> in my case i m getting an error of "XSLTProcessorNot Found".
> can anyone help me with it?

Hi there,
i copied XSTLTProcessor from new version of PHPWord

**Comment by bhavink21** [comment]
> > @xueliangliang @hungdang6676
> > hello,
> > in my case i m getting an error of "XSLTProcessorNot Found".
> > can anyone help me with it?
> 
> Hi there,
> i copied XSTLTProcessor from new version of PHPWord

I have recently installed PHPWORD in my code but not being able to find XSLTProcessor.

**Comment by xueliangliang** [comment]
> > Hi there,
> > i copied XSTLTProcessor from new version of PHPWord
> 
> I have recently installed PHPWORD in my code but not being able to find XSLTProcessor.
It is a PHP extension: https://www.php.net/manual/en/class.xsltprocessor.php

**Comment by xueliangliang** [comment]
@hungdang6676 

```php
$textrun = $section->addTextRun();
$textrun->addText("HELLO:");
$textrun->addText($omml);
$textrun->addText("WORLD!");
```

You can embed the formula with your normal text.

**Comment by bhavink21** [comment]
> For the latest version , it doesn't require any hacking, the following code is working as I expected.
> 
> ```
> <?php
> require_once 'bootstrap.php';
> 
> // Creating the new document...
> $phpWord = new \PhpOffice\PhpWord\PhpWord();
> 
> /* Note: any element you append to a document must reside inside of a Section. */
> 
> // Adding an empty Section to the document...
> $section = $phpWord->addSection();
> 
> $xml = new DOMDocument;
> $xml->loadXML('<math xmlns="http://www.w3.org/1998/Math/MathML"><mroot><mi>x</mi><mn>4</mn></mroot></math>');
> $xsl = new DOMDocument;
> $xsl->load('./mathml2omml.xsl'); // This could be found in MSOffice installation
> $processor = new XSLTProcessor;
> $processor->importStyleSheet($xsl);
> $omml = $processor->transformToXML($xml);
> $t_omml = new DOMDocument;
> $t_omml->loadXML($omml);
> $omml = $t_omml->saveXML($t_omml->documentElement);    //Remove XML Version tag
> echo $omml;
> $section->addText($omml);
> 
> 
> // Saving the document as OOXML file...
> $objWriter = \PhpOffice\PhpWord\IOFactory::createWriter($phpWord, 'Word2007');
> $objWriter->save('helloWorld.docx');
> ```
@xueliangliang @hungdang6676 
hey there I have used the same code as yours but I am unable to print mixtures of formulas and text.

Example:-

> <p><math xmlns="http://www.w3.org/1998/Math/MathML"><mfrac bevelled="true"><mi>a</mi><mi>b</mi></mfrac></math> Some Normal Text Goes Here </p>

this was the math type after conversion the string is as given below.

> 

> <p><m:oMath xmlns:m="http://schemas.openxmlformats.org/officeDocument/2006/math" xmlns:mml="http://www.w3.org/1998/Math/MathML"><m:f><m:fPr><m:type m:val="skw"/></m:fPr><m:num><m:r><m:t>a</m:t></m:r></m:num><m:den><m:r><m:t>b</m:t></m:r></m:den></m:f></m:oMath> Some Normal Text Goes Here </p>

Now I need to insert this text inside a word file using PHPWORD but the file gets corrupted.

**Comment by jjtorres2002** [comment]
@xueliangliang  @hungdang6676

Thanks for the code snippet! It partially works for me. It shows a math equation in the word document when I open it, with the fourth root symbol well placed, but with an empty placeholder in the argument (a blank square). 

![empty place holder](https://user-images.githubusercontent.com/77021157/103686528-b9132000-4f6d-11eb-99c8-9375f002afe6.png)

Any idea why would this be happening? I use Word 2007, and I have MathType installed?

Thanks in advance for any guidance or pointers

**Comment by xueliangliang** [comment]
```php
<?php
require_once 'bootstrap.php';

// Creating the new document...
$phpWord = new \PhpOffice\PhpWord\PhpWord();

/* Note: any element you append to a document must reside inside of a Section. */

// Adding an empty Section to the document...
$section = $phpWord->addSection();


$textrun = $section->addTextRun();
$textrun->addText("Please find the equivalent expression for ");
$textrun->addText(mathml2omml('<math xmlns="http://www.w3.org/1998/Math/MathML"><msup><mi>x</mi><mn>2</mn></msup><mo>-</mo><msup><mi>y</mi><mn>2</mn></msup></math>'));
$textrun->addText(" below:");
$textRunA = $section->addTextRun();
$textRunA->addText("A. ");
$textRunA->addText(mathml2omml('<math xmlns="http://www.w3.org/1998/Math/MathML"><mfenced><mrow><mi>x</mi><mo>-</mo><mi>y</mi></mrow></mfenced><mfenced><mrow><mi>x</mi><mo>+</mo><mi>y</mi></mrow></mfenced></math>'));
$textRunB = $section->addTextRun();
$textRunB->addText("B. ");
$textRunB->addText(mathml2omml('<math xmlns="http://www.w3.org/1998/Math/MathML"><msup><mfenced><mrow><mi>x</mi><mo>-</mo><mi>y</mi></mrow></mfenced><mn>2</mn></msup></math>'));


// Saving the document as OOXML file...
$objWriter = \PhpOffice\PhpWord\IOFactory::createWriter($phpWord, 'Word2007');
$objWriter->save('helloWorld.docx');


function mathml2omml($mathml) {
        $xml = new DOMDocument;
        $xml->loadXML($mathml);
        $xsl = new DOMDocument;
        $xsl->load('./mathml2omml.xsl'); // This could be found in MSOffice installation
        $processor = new XSLTProcessor;
        $processor->importStyleSheet($xsl);
        $omml = $processor->transformToXML($xml);
        $t_omml = new DOMDocument;
        $t_omml->loadXML($omml);
        $omml = $t_omml->saveXML($t_omml->documentElement);    //Remove XML Version tag
        return $omml;
}
```
Mix normal text with mathml.

**Comment by nandaks** [comment]
@xueliangliang How can be read Mathtype from docx file using PhpWord? When i tried to convert in pdf it shows me
<Object: word/embeddings/oleObject1.bin>

@xueliangliang I have searched lots of tickets and blogs. But did not get any solution. Please help me

I am sharing docx file, please have a look. 
[qq.docx](https://github.com/PHPOffice/PHPWord/files/7795599/qq.docx)

**Comment by yangweijie** [comment]
https://www.runoob.com/html/html5-mathml.html

**Comment by Yolver** [comment]
How to mix html with mathml?
I used HTML::addHtml() method and addText() method, but there is no expect effect.
please help me.

**Comment by frozenade** [comment]
How to do the opposite? Extract Word Equation to MathML?

**Comment by nguyenvanlongBG** [comment]
@nandaks  I am also having the same problem as you. Have you been able to solve this problem? I am also having the same problem as you. Have you been able to solve this problem?

**Comment by redrum0x** [comment]
Has anyone managed to extract it?

**Comment by Progi1984** [comment]
@yangweijie @xueliangliang @r3sist @eduardobreno @frozenade @lucus-lee @lucasres @redrum0x @hungdang6676 @Yolver 

Hello there, please, could you give us some files with math equations to analyze it and create a pull request ?

**Comment by Progi1984** [comment]
File from @redrum0x  [test+php.docx](https://github.com/PHPOffice/PHPWord/files/12665268/test%2Bphp.docx)

**Comment by Progi1984** [comment]
FYI : A Pull Request is in Progress : #2477

**Comment by pwN04** [comment]
i am getting
<mml:math xmlns:mml="http://www.w3.org/1998/Math/MathML" xmlns:m="http://schemas.openxmlformats.org/officeDocument/2006/math"/> in my docx only this line print every time a code run on my laravel project... please help

> <?php
> require_once 'bootstrap.php';
> 
> // Creating the new document...
> $phpWord = new \PhpOffice\PhpWord\PhpWord();
> 
> /* Note: any element you append to a document must reside inside of a Section. */
> 
> // Adding an empty Section to the document...
> $section = $phpWord->addSection();
> 
> 
> $textrun = $section->addTextRun();
> $textrun->addText("Please find the equivalent expression for ");
> $textrun->addText(mathml2omml('<math xmlns="http://www.w3.org/1998/Math/MathML"><msup><mi>x</mi><mn>2</mn></msup><mo>-</mo><msup><mi>y</mi><mn>2</mn></msup></math>'));
> $textrun->addText(" below:");
> $textRunA = $section->addTextRun();
> $textRunA->addText("A. ");
> $textRunA->addText(mathml2omml('<math xmlns="http://www.w3.org/1998/Math/MathML"><mfenced><mrow><mi>x</mi><mo>-</mo><mi>y</mi></mrow></mfenced><mfenced><mrow><mi>x</mi><mo>+</mo><mi>y</mi></mrow></mfenced></math>'));
> $textRunB = $section->addTextRun();
> $textRunB->addText("B. ");
> $textRunB->addText(mathml2omml('<math xmlns="http://www.w3.org/1998/Math/MathML"><msup><mfenced><mrow><mi>x</mi><mo>-</mo><mi>y</mi></mrow></mfenced><mn>2</mn></msup></math>'));
> 
> 
> // Saving the document as OOXML file...
> $objWriter = \PhpOffice\PhpWord\IOFactory::createWriter($phpWord, 'Word2007');
> $objWriter->save('helloWorld.docx');
> 
> 
> function mathml2omml($mathml) {
>         $xml = new DOMDocument;
>         $xml->loadXML($mathml);
>         $xsl = new DOMDocument;
>         $xsl->load('./mathml2omml.xsl'); // This could be found in MSOffice installation
>         $processor = new XSLTProcessor;
>         $processor->importStyleSheet($xsl);
>         $omml = $processor->transformToXML($xml);
>         $t_omml = new DOMDocument;
>         $t_omml->loadXML($omml);
>         $omml = $t_omml->saveXML($t_omml->documentElement);    //Remove XML Version tag
>         return $omml;
> }
> Mix normal text with mathml. I also attached the generated docx file.
> 
> [helloWorld.docx](https://github.com/PHPOffice/PHPWord/files/6134980/helloWorld.docx)

**Comment by josdejong** [comment]
The document `helloWorld.docx` attached to https://github.com/PHPOffice/PHPWord/issues/860#issuecomment-798480408 works fine in MS Office, however, the formulas do not show up in for example OpenOffice, Google Docs, or Office 365 in the browser. When creating a DOCX file with a formula using say OpenOffice, I can open the document in other applications and the formula works everywhere.

How can I make inserted `<m:oMath>...</m:oMath>` formulas working in other applications too?
