### ISSUE TITLE
ZF2 support is now broken.

### ISSUE THREAD

**Issue by jarrettj** [PHPOffice/PHPWord#865]
Hi,

Good day.

I'm using PHPWord with ZF2 and PHP 7. So I've encountered issue https://github.com/PHPOffice/PHPWord/issues/736. Now I need to upgrade to v0.13.0. 

But I can't do that, because PHPWord requires 3 zendframework pacakges that are on version 2.4._. ZF2 version 2.5._ uses the same package but requires version 2.5.\* though.

```
"require": {
        "php": ">=5.7",
        "phpoffice/phpword": "v0.13.0",
        "zendframework/zendframework": "2.*"
    }
```

Any help/workaround will be much appreciated.

Cheers.

**Comment by cookiekiller** [comment]
Cheers dude, I had same problem, but downgrading from 2.5 to 2.4 wasn't a huge problem. The changes are minimal.

**Comment by jarrettj** [comment]
Thanks @cookiekiller.

**Comment by Vargson** [comment]
But it should support ZF2.5* and also ZF3.0. There some changes, but there are minimal for PHP Word. Downgrading a framework can't be the solution.

**Comment by jarrettj** [comment]
Agreed @Vargson :) I don't have the time to fork/fix though. Patiently waiting for an update instead.

**Comment by dmnk** [comment]
thx for fixing this one. do you have an idea how long it's usually taking till such minor changes get merged? (as i'd need this now ;) )

**Comment by aight8** [comment]
Should definitely work with zf3 too

**Comment by marcomenzel** [comment]
Are there any known ZF2.5 related issues?

**Comment by Jorgemunive** [comment]
Hi, is there any news about compatibility with ZF2.5 or ZF3?

**Comment by troosan** [comment]
please use version 0.14
