### ISSUE TITLE
Embed WMF or SVG?

### ISSUE THREAD

**Issue by mraspe** [PHPOffice/PHPWord#878]
Hello,

is it possible to embed WMF (or SVG) in word documents with PHPWord?

Best regards
Mario

**Comment by thevel** [comment]
Same here PHPWord is good for generating word docx, 
but support for svg seems missing ( need it for importing generated graphs)

**Comment by tobwen** [comment]
Same here, but EMF would be better, since you can embedd EPS into EMF.

**Comment by larjohn** [comment]
I hacked around with Image.php and found out it was not that hard to embed emf or svg files. We just need a typical getimagesize alternative.

**Comment by tobwen** [comment]
> I hacked around with Image.php and found out it was not that hard to embed emf or svg files. We just need a typical getimagesize alternative.

Why not go the hard way, render to temporary raster, getimagesize and use this?

**Comment by landerdominguez** [comment]
> I hacked around with Image.php and found out it was not that hard to embed emf or svg files. We just need a typical getimagesize alternative.

Could you share how did you get it?

**Comment by tobwen** [comment]
@mraspe
Why was this closed?

**Comment by gaby64** [comment]
> 
I dont see the changes on your repo of PHPWord, could you push to it to share?

**Comment by gaby64** [comment]
> @mraspe Why was this report closed? Is there a fix?

Here you go, I made the fix, couldn't wait on @larjohn 

https://github.com/gaby64/PHPWord/tree/add-svg-emf-wmf

sudo apt install emf2svg php-curl php-imagick php-gd php-gmagick
composer require imagine/imagine
