### ISSUE TITLE
 MsDoc - Czech language support

### ISSUE THREAD

**Issue by petrknap** [PHPOffice/PHPWord#881]
Hello,

is it possible to add/fix Czech language support? **There is problem with national characters.** I prepared simple test which demonstrates what is wrong, [you can found it here](https://gist.github.com/petrknap/c76e94d61374da52690bdefe43497768).

```
c76e94d61374da52690bdefe43497768$ php czech_language_support.phpt 
Warning: assert(): Expected that 'PYília ~lueou' is equal to 'Příliš žluťoučký kůň pěl ďábelské ódy' failed in /tmp/c76e94d61374da52690bdefe43497768/czech_language_support.phpt on line 17
```

**Comment by Progi1984** [comment]
@petrknap

This issue has been fixed by a maintainer in the PR #2664. You can help him by sponsoring him through [Github sponsors](https://github.com/sponsors/Progi1984).
