### ISSUE TITLE
Install via Composer

### ISSUE THREAD

**Issue by Selion05** [PHPOffice/PHPWord#883]
Hey, 

I'm getting the following error

`C:\xampp\htdocs\phpword>composer  require phpoffice/phpword
Using version ^0.13.0 for phpoffice/phpword
./composer.json has been created
Loading composer repositories with package information
Updating dependencies (including require-dev)

Installation failed, deleting ./composer.json.

  [Composer\Downloader\TransportException]
  The "http://packagist.org/p/zendframework/zend-stdlib%24b8f7372485e8d7e912367b959244e4b50297149b12759f2edb5cdc7b27a845d0.json" file could not be downloaded: failed to open stream: HTTP reque
  st failed!
I tried the url in the browser and it worked! Any advice how to resolve this issue?

**Comment by troosan** [comment]
That looks like a composer issue, not PHPWord
