### ISSUE TITLE
Missing Page numbers in TOC

### ISSUE THREAD

**Issue by akshuam** [PHPOffice/PHPWord#891]
Hi All, I am using PHPWord to generate a word document. In that document i am generating TOC. The TOC is coming without page numbers and I have to manually update the table. This should be done automatically. Please help me to display page numbers in TOC.

Thanks in advance

**Comment by six-days** [comment]
i think it does not support page numbers

**Comment by heretreeli** [comment]
at version 0.12.1 can generate page numbers, latest version last page numbers ,hh

**Comment by scalco19** [comment]
I have the same problem, some solution?

**Comment by troosan** [comment]
You can use the following to force Word to update all fields
```php
$phpWord = new \PhpOffice\PhpWord\PhpWord();
$phpWord->getSettings()->setUpdateFields(true);
```
