### ISSUE TITLE
PHPWord added paragraphs after all comma

### ISSUE THREAD

**Issue by caiovncius** [PHPOffice/PHPWord#905]
Hello,

I'm using PHPWord, and for all formats I write my template, the PHPWord adds new paragraphs after a comma. This acontence with all the commas. Example:

Template: 

``` text
 Hello, how are you?
```

Output: 

```
Hello
,how are you?
```

How to resolve this question? Its a bug, or some setting?

**Comment by troosan** [comment]
@caiovncius are you still having this issue?
The following works fine for me
```php
$phpWord = new \PhpOffice\PhpWord\PhpWord();

$section = $phpWord->addSection();
$section->addText("Hello, how are you?");
```

**Comment by caiovncius** [comment]
Hi, yes. I'm having this issue yet.

**Comment by troosan** [comment]
Can you post a code sample? Does the code I posted work for you?

**Comment by troosan** [comment]
@caiovncius please try with latest dev-master (or wait for 0.14).
