### ISSUE TITLE
Paragraph indents

### ISSUE THREAD

**Issue by mburton603** [PHPOffice/PHPWord#913]
Indents don't appear to work. I have (for example) the following php statements:
$tabStop = (int)round(PhpOffice\PhpWord\Shared\Font::inchSizeToTwips(0.5));
$tabs = array($tabStop);
$docObj->addParagraphStyle('lhba', array('align'=>'left', 'spaceBefore'=>0, 'spaceAfter'=>0, 'spacing'=>0, 'hanging'=>$tabStop, 'indent'=>$tabStop, 'lineHeight'=>1, 'tabs'=>$tabs));
$docPara = $docSect->addTextRun('lhba');
$docPara->addText("(a)\tThis is a test", 'm11');
The text "This is a test" that appears in the resulting Word document has Indentation->Left set to 0.0, rather than 0.5.

**Comment by ctrlaltca** [comment]
"indent"  takes a single numeric value, not an array of tab stops. I suppose what you are trying to achieve is "hanging", anyway.

**Comment by mburton603** [comment]
In my error report, the code sets the indent value to $tabStop, not $tabs. $tabStop is a single value.

**Comment by ctrlaltca** [comment]
Still, the value you are passing is broken.
The array should look something like:
```
array(
	'align' => 'left',
	'indentation' => array('left' => 60, 'right' => 60, 'hanging' => 360),
);
```

**Comment by mburton603** [comment]
This does not work. I now have the following extracted code:

$docObj->addParagraphStyle('lhba', array('align'=>'left', 'spaceBefore'=>$space6, 'spaceAfter'=>$space6, 'spacing'=>0, 'indent'=>array('left'=>$tabStop, 'hanging'=>$tabStop), 'lineHeight'=>1, 'tabs'=>$tabs));

 

$docPara->addText("(a)\tThe Materials are being provided to " . $agmtData['xferOrgAbbr'] . " by " . $agmtData['contactName'] . " (" . $agmtData['orgName'] . ") for purposes of ", 'm11');

 

which produces the attached result.

**Comment by ctrlaltca** [comment]
> I now have the following extracted code:
> 
> $docObj->addParagraphStyle('lhba', array('align'=>'left', 'spaceBefore'=>$space6, 'spaceAfter'=>$space6, 'spacing'=>0, 'indent'=>array('left'=>$tabStop, 'hanging'=>$tabStop), 'lineHeight'=>1, 'tabs'=>$tabs));

in my example i used "indentation", not "indent"

> which produces the attached result.

I assume you replied to a notification email and attached something, but email attachments doesn't end up on github.

**Comment by mburton603** [comment]
I saw that you used 'indentation', but there's no reference to that in my copy of the manual, which is why I used 'indent'. I've switched to 'indentation', and there's an improvement, but it still doesn't work.
[Test.txt](https://github.com/PHPOffice/PHPWord/files/1117901/Test.txt)

[Test_11988.docx](https://github.com/PHPOffice/PHPWord/files/1117903/Test_11988.docx)

The file Test.txt is the .php code which produced the second file Test_11988.docx. Note that the first line of the last paragraph is not indented.

**Comment by mburton603** [comment]
I changed to ‘indentation’, but no luck. I uploaded some files directly to GitHub.

**Comment by ctrlaltca** [comment]
> but there's no reference to that in my copy of the manual,

Well, i have to agree with you that documentation sucks. I usually make my way between samples and directly reading through the code.

> Note that the first line of the last paragraph is not indented.

In this case, you may want to have a look at the [sample #8](https://github.com/PHPOffice/PHPWord/blob/develop/samples/Sample_08_ParagraphPagination.php), that shows a bit how to paginate paragraphs. Here's the relevant output of the sample:

![schermata 2017-07-03 alle 10 23 04](https://user-images.githubusercontent.com/1631111/27784211-b3e8e5ec-5fd9-11e7-912a-a3cc3a81672e.png)

**Comment by mburton603** [comment]
Thanks very much - your suggestion helped, and I've been able to achieve what I wanted. I'll admit that I don't normally look that closely at samples (particularly when there's documentation), because most of the time they don't cover what I'm looking for.
