### ISSUE TITLE
New paragraph with accents

### ISSUE THREAD

**Issue by josespinal** [PHPOffice/PHPWord#914]
In a docx file I have some accents as the file is written in spanish. When I try to output it to HTML, here's what I get from the text "La noticia se regó como pólvora...": 

![image](https://cloud.githubusercontent.com/assets/10059/19497632/45ef5aba-955b-11e6-96ce-961c32772008.png)

Doing some digging I found out that it had to do that XML is being handled by the XMLReader as a new run. Here's the XML output from XMLReader:

![image](https://cloud.githubusercontent.com/assets/10059/19497758/c9804f7e-955b-11e6-81a6-0c059072d92b.png)

Then the HTML Writer adds paragraph tags to every new text (run?) via the addText() function. I believe that what's happening is that the writer is not taking in account the "xml:space" attribute which is set to "preserve". I was playing around with the AbstractPart of PhpOffice\PhpWord\Reader\Word2007 with no luck. 

Any help or ideas on how to solve this?

**Comment by LuanHimmlisch** [comment]
@josespinal you should have shared your solution if you close this
