### ISSUE TITLE
bgColor not read from TableCell (+possible fix)

### ISSUE THREAD

**Issue by TheCollector2K** [PHPOffice/PHPWord#916]
Hi,

i've had a problem reading the background color (bgColor) from a table cell in a docx document. Trying this using the getBgColor() method in the class PhpOffice\PhpWord\Style\Cell

Problem: no background color was returned.

After looking into the sourcecode, it seems the 'w:fill' is read as node, but it should be read as an attribute.

In file \PhpWord\Reader\Word2007\AbstractPart.php, and the method readCellStyle, i believe this code:
`'bgColor'       => array(self::READ_VALUE, 'w:shd/w:fill'),`
Should be changed into:
`'bgColor'       => array(self::READ_VALUE, 'w:shd', 'w:fill'),`

**Comment by FBnil** [comment]
Indeed it should. Good catch!

**Comment by FBnil** [comment]
This also works:
`$cell->getStyle()->getShading()->getFill()` of course, there is a `setFill()`. Use `get_class_methods()` to dump all functions a class, like cell, has.

**Comment by troosan** [comment]
should be OK in 0.14
