### ISSUE TITLE
addImage base64 support?

### ISSUE THREAD

**Issue by koosvanderkolk** [PHPOffice/PHPWord#921]
In my code I have the image as a base64 encoded string. Of course I can write it to a temp file and then add it to my Word-file with addImage, but wouldnt it be more efficient if I could immediately feed addImage with my string? 

I did not really dive into the code, but the existence of the getImageStringData function seems to suggest that base64 encoding is already been used internally (http://phpoffice.github.io/PHPWord/docs/master/classes/PhpOffice.PhpWord.Element.Image.html).

**Comment by troosan** [comment]
resolved in develop branch

**Comment by koosvanderkolk** [comment]
Thanks!

**Comment by nicdnepr** [comment]
Why in develop? Will it go to release?

**Comment by nicdnepr** [comment]
Also its not work, I try dev-master and dev-develop and get error 
`Invalid image: data:image/png;base64` in `PhpWord/Element/Image.php` 385

**Comment by padre** [comment]
@nicdnepr I have the same problem (I've also tried dev-master and dev-develop). Have you been able to fix it?

**Comment by nicdnepr** [comment]
@padre No
I used url to return image

**Comment by padre** [comment]
@nicdnepr ok, thanks.

Theoretically it should work, but after trying for hours there's no way :-(

@troosan, have you ever managed to use an image as a base64 encoded string?

**Comment by markmorris** [comment]
@troosan Can confirm this dont work at all. Tried base64_decode as you suggested too and still nothing. Also tested my string online and its perfect and produces the image. Is there anyway we can add support for base64 encoded image?

either way i get a fatal error.

**Comment by npth** [comment]
It works, if crop "data:image/png;base64," string from base64 code string, ex:
`$find = strpos($file_contents, ';base64,'); 
if ($find !== false) {
                $encoded_string = substr($file_contents, $find + 8);
            }
$section->addImage(base64_decode($encoded_string));`
