### ISSUE TITLE
Assign no bullet/numbering for list item

### ISSUE THREAD

**Issue by giltroymeren** [PHPOffice/PHPWord#924]
I would like to assign an empty bullet (similar to CSS's `list-style-type: none`) for `addListItem()` instances to include a body for an item head. Currently item contents (AFAIK) are assigned with the default `TYPE_BULLET_FILLED`.

```
1. Head 1
   Head 1 body    
    A. Head A
    B. Head B
    C. Head C
       Head C body
2. Head 2
   Head 2 body
```

I have tried removing the default value in `Styles/ListItem.php::setListItem()` but it broke the library. I also added an `addText()` directly after the head `addListItem()` hoping it would obey the indention but it did not which makes sense. I do not want to manually add indentions to each of my item bodies either.

Is this currently possible with a trick I may have missed?

**Comment by thorne51** [comment]
Not sure if you managed to work it out, but I'd guess you'd need to start a ListRun for multi-line items. Then use a break for your line breaks. I'll try to get around building an example later on with your requirements

**Comment by troosan** [comment]
@giltroymeren have you tried setListType(ListItem::TYPE_BULLET_EMPTY)
