### ISSUE TITLE
Illegal string offset warning in PHP 7

### ISSUE THREAD

**Issue by likeuntomurphy** [PHPOffice/PHPWord#927]
Saving a document triggers an `Illegal string offset 'w:compatSetting'` warning, because `$this->settings['w:compat']` is initialized as an empty string instead of an empty array in `src/PhpWord/Writer/Word2007/Part/Settings.php`. This appears to be the case with PHP7 — PHP5 does not raise the warning.

**Comment by germansokolov13** [comment]
I've just downloaded PHPWord 0.13.0 via Composer and it's still an empty string instead of an empty array there. Not merged into a release?

**Comment by philwu** [comment]
I've just downloaded PHPWord 0.13.0 via Composer still get the problem.
Win10 build 14393+IIS
PHP 7.1.1

**Comment by thibaultvanc** [comment]
FOR PHP 7.1

`
try {
      $objWriter->save($path);

    } catch (Exception $e) {
      // dd(123);
      // dd('cat');
    }
    return redirect('/'.$path);
`
WORK FOR ME

**Comment by shad0wfir3** [comment]
@thibaultvanc can you expand on where you implemented this? currently getting the same error on php 7.1.2

**Comment by sazal836** [comment]
Doc file created successfully 
but why this message is showing....

Warning: Illegal string offset 'w:compatSetting' in C:\xampp\htdocs\greek\vendor\phpoffice\phpword\src\PhpWord\Writer\Word2007\Part\Settings.php on line 173

Notice: Array to string conversion in C:\xampp\htdocs\greek\vendor\phpoffice\phpword\src\PhpWord\Writer\Word2007\Part\Settings.php on line 173

Warning: Invalid argument supplied for foreach() in C:\xampp\htdocs\greek\vendor\phpoffice\phpword\src\PhpWord\Writer\Word2007\Part\Settings.php on line 80

**Comment by wqj97** [comment]
Still have problem today

**Comment by Jaspur** [comment]
Same issue here. PHP 7.1.3

**Comment by likeuntomurphy** [comment]
This has been merged into the `develop` branch and is slated for inclusion in [v0.14.0](https://github.com/PHPOffice/PHPWord/milestone/17). However, the [release is on hold indefinitely](https://github.com/PHPOffice/PHPWord/issues/848) because the project does not have an active maintainer.

Your best bet is to fork the `develop` branch or apply the [patch](https://github.com/PHPOffice/PHPWord/commit/6da9d8a0bf0363dac1a8a39ecf8b60db3d6814b3.patch) to your local copy.

**Comment by Jaspur** [comment]
Still, when I add this in composer.json:
```
"phpoffice/phpword": "dev-master",
```
It returns the error:
```
Illegal string offset 'w:compatSetting'
```
@likeuntomurphy

**Comment by likeuntomurphy** [comment]
Ok, try `composer require phpoffice/phpword:dev-develop` — that should do it once for all:

```shell
$ composer require phpoffice/phpword:dev-develop
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 0 installs, 1 update, 0 removals
  - Updating phpoffice/phpword (dev-master 0a3f873 => dev-develop 4decaff):  Checking out 4decaffd53
```

There are still many things I don’t know about `composer`, and I didn't realize this would work.

**Comment by JuanWilde** [comment]
dev-develop did the trick! Now it's time to wait for 0.14 release

**Comment by Alexmg86** [comment]
https://github.com/PHPOffice/PHPWord/pull/1013/commits/000e36acfe9c8a8e039821bb583e4635e619fd53

**Comment by ezintz** [comment]
Is it possible that someone pushes a fix e.g. 0.13.1? Thanks in advance.

**Comment by maulik37** [comment]
this is work fine for me
https://stackoverflow.com/questions/46202824/how-to-fix-warning-illegal-string-offset-in-laravel-5-4/46482346#46482346

**Comment by carlosmolano** [comment]
private function getSettings()
    {
           .......

            'w:compat' => ' ',

           ........
    }
Updated to

private function getSettings()
    {
           .......

            'w:compat' => array('@attributes' => array('w:val' => '')),

           ........
    }

**Comment by germansokolov13** [comment]
Times change, generations replace each other. And they still fight their formidable foe. The two single quotes keep the upper hand in the php-development battle.

**Comment by wlnoor** [comment]
> Change en file...
> 
> PHPOffice\PHPWord\Writer\Word2007\Part\Settings
> 
> private function getSettings()
> {
> .......
> 
> ```
>         'w:compat' => ' ',
> 
>        ........
> }
> ```
> 
> Updated to
> 
> private function getSettings()
> {
> .......
> 
> ```
>         'w:compat' => array('@attributes' => array('w:val' => '')),
> 
>        ........
> }
> ```

its work for me, thanks
