### ISSUE TITLE
how add image place holder for MS word template?

### ISSUE THREAD

**Issue by hamedmoody** [PHPOffice/PHPWord#939]
how add image place holder for MS word template and how replace with php?
and how use loop in word template and PHP?

**Comment by walkerdigital** [comment]
+1 - I too came here looking for some insight on this.  The template injection works great but I haven't figured out how to inject an image in the DOCX.

**Comment by vierkantemeter** [comment]
+1 
I would like to know the same thing!

**Comment by troosan** [comment]
PR #1084 implements this
