### ISSUE TITLE
Getting started

### ISSUE THREAD

**Issue by edmozley** [PHPOffice/PHPWord#943]
First apologies if I am posting this in the wrong place - I have looked for a support forum but couldn't find one.

I am trying to get up and running with phpWord but don't really know what I am doing.  I have an IIS server running php 5.6.28.

I have installed composer and run these commands:

composer require zendframework/zendframework
composer require phpoffice/phpword "v0.13.*"

I don't really know what to do next - I would be very grateful for any pointers.

Thank

Ed

**Comment by raf-sh** [comment]
Hello! have you checked this section of official doc http://phpword.readthedocs.io/en/latest/installing.html#using-samples
? try build-in samples - they are very helpful at the beginning

**Comment by zubairayub** [comment]
how to instal packages i am not getting this any help please

**Comment by carrillo455** [comment]
Hello @zubairayub , just create a "composer.json" on your root directory of your project with this:
{
    "require": {
       "phpoffice/phpword": "v0.13.*"
    }
} 

Open Git Bash / CMD and dive into your proyect. Run "composer install" (it begins installing stuff) and it shall be done dude (y) Cheers.
