### ISSUE TITLE
Composer.json Require zendframework/zend-stdlib ^2.4.0 (instead of 2.4.*)

### ISSUE THREAD

**Issue by BrandonNoad** [PHPOffice/PHPWord#947]
I'm trying to install phpoffice/phpword via composer. My app also requires the microsoft/windowsazure package.

Unfortunately, both of these packages depend on different versions of the zendframework/zend-stdlib package.

`phpoffice/phpword v0.13.0 requires zendframework/zend-stdlib 2.4.* -> satisfiable by zendframework/zend-stdlib[2.4.0, 2.4.1, 2.4.10, 2.4.2, 2.4.3, 2.4.4, 2.4.5, 2.4.6, 2.4.7, 2.4.8, 2.4.9].`

`microsoft/windowsazure requires zendframework/zend-stdlib ^2.7 || ^3.0 -> satisfiable by zendframework/zend-stdlib[2.7.0, 2.7.1, 2.7.2, 2.7.3, 2.7.4, 2.7.5, 2.7.6, 2.7.7, 3.0.0, 3.0.1, 3.1.0]`

Can you update the dependencies in your composer.json to use caret ranges?

It shouldn't result in any breaking changes (https://getcomposer.org/doc/articles/versions.md#caret): 

"The ^ operator behaves very similarly but it sticks closer to semantic versioning, and will always allow non-breaking updates. For example ^1.2.3 is equivalent to >=1.2.3 <2.0.0 as none of the releases until 2.0 should break backwards compatibility. For pre-1.0 versions it also acts with safety in mind and treats ^0.3 as >=0.3.0 <0.4.0."

**Comment by jarrettj** [comment]
+1

**Comment by marcelto** [comment]
+1

**Comment by stephanvierkant** [comment]
See this PR: #903

**Comment by marcomenzel** [comment]
+1

**Comment by troosan** [comment]
fixed with #1138
