### ISSUE TITLE
PHPWord is looking for a new maintainer

### ISSUE THREAD

**Issue by Progi1984** [PHPOffice/PHPWord#948]
@RomanSyroeshko has done a very good job in PHPWord. But it decided to discover new horizons.

Actually, @MarkBaker work on PHPExcel / PhpSpreadsheet, and me I work on PhpPresentation.

So we are looking for a maintainer / lead dev for PHPWord.

Its work :
* Review all pull requests
* Improve code quality
* Fix bugs... all bugs !!!
* Optimize
* Add features

May be some old developers : @ivanlanin or @gabrielbull would be interested.
We would study any propositions.

**Comment by samael205** [comment]
Here a new interested. But I do not know anything about the library. It would be more to learn to program better in PHP. To work on weekends

**Comment by Progi1984** [comment]
@samael205 Can you contact me in mail ?

**Comment by samael205** [comment]
@Progi1984 I send to you an mail!

**Comment by juch** [comment]
@Progi1984 hi there, if you're interested i can manage current Pull Request @ issues but nothing more as i haven't enough time

**Comment by Progi1984** [comment]
@juch We are looking for a maintainer for long term :) so he needs to have enough time.

**Comment by ctrlaltca** [comment]
@Progi1984 I can help with existing issues and PRs, but i don't have enough experience with PHPWord at the moment to say i can be a maintainer for a long term.
Maybe having a small team of people taking care of the major issues while you can find a new maintainer is a good idea, instead of letting it stagnate with blocking bugs like composer being currently broken.

**Comment by cookiekiller** [comment]
I would like to support this project as well. I'm experienced with PHP word in several projects.

**Comment by Progi1984** [comment]
@ctrlaltca I prefer having a maintainer for a long term which manage differents contributions & contributors. That permits to have a direction to the project.

@cookiekiller I just sent you a mail.

**Comment by Trumind** [comment]
I am interested in doing that, my email address can I send my email address?

**Comment by Progi1984** [comment]
@Trumind Yeap, you can send me an email (progi1984@gmail.com).

**Comment by gabrielkolbe** [comment]
Hi, I am interested in help maintaining PHPWord, you can view my skill set and proficiency and contact me and view my online CV at  http://www.skillbooker.com/online/cv/gabrielk

**Comment by rsmalc** [comment]
What is a current status of maintain this package? Who is handling pull request till now?

**Comment by Progi1984** [comment]
@gabrielkolbe Hi, Firstly, thank you for being interested by this project.

Before becoming the maintainer of PHPWord, we need to "test" you for this position.

How ?

Simply : you will do what a maintainer make... Answer tickets, valid PR, create PR for fixing tickets, answer questions on StackOverflow, answer questions on Gitter, improve documentation and unit tests, etc...
You must have one direction : quality of the project is very important.
Why ? 
- Have a good documentation and you will have fewer questions
- Have a good unit test and you will have fewer issues
- Have good samples and users will have a best quickstart

You can send me mails for any question when you want

For some time, you will mention me for closing a ticket or valid a PR.
After this time, if we are ok and you are ok, I will give you the right in Github. 

Why we do that ? Simply because a lot of people gave up very early at this stage .

@rsmalc At the moment, the package is not maintained, because we are looking for a maintainer (for long term). Mark Baker cares of PhpSpreadsheet, and I care of PhpPresentation.

**Comment by johnHuan** [comment]
> 

> 

- 

- [ ] 

- `[

@1. 
2. 
3. ](url)`

**Comment by Progi1984** [comment]
Congratulations, @troosan :)
