### ISSUE TITLE
Updating TOC page numbers

### ISSUE THREAD

**Issue by sivaram-blr** [PHPOffice/PHPWord#951]
Hello Team,

I am generating docx using template. I am dynamically updating few tables in template. So on each scenario table content may be short or long so total page numbers will differ on each document that gets created. 

And list of headings(TOC items) remain always same, but their content will vary dynamically.

Now what is happening is when click one heading in TOC, it takes me to right position. But the page number in TOC is not matching with actual page number of that.

Note: addTOC function helps to add new TOC item. I am looking something like updateTOC to update the existing TOC items in TEMPLATE based on dynamic content i write.

So i am looking for help to "Update the page numbers" at just before end of document created.

Thanks

**Comment by mattsagen** [comment]
Hi there I am dealing with something similar, and I am investigating Macros - all these things (bookmarks, titles, etc) are "Fields" - in Word you can set an option to "Update fields before printing" and "Update linked data before printing" - if the person doesn't have that set, then they either have to be updated manually or you can have a macro that runs at open or close...

**Comment by deepakgup** [comment]
@mattsagen Any luck solving this one?

**Comment by troosan** [comment]
maybe we should just implement http://www.datypic.com/sc/ooxml/e-w_updateFields-1.html

**Comment by troosan** [comment]
implemented in 0.14

**Comment by deepakgup** [comment]
That was super fast. Thanks @troosan. Sry I am new to Git/hub how do I get hold of 0.14

Cheers!

**Comment by troosan** [comment]
@deepakgup you either wait for the final 0.14 version or you point to the development branch.
To do this you use version "dev-master"

**Comment by vinayak-infinity** [comment]
@sivaram-blr  I am generating ToC but it dosen't gives page no in ToC output.

**Comment by vinayak-infinity** [comment]
hi

**Comment by waghyogesh** [comment]
@sivaram-blr  Hi, I am generating TOC in phpword doc but it dosent generating page numbers or indexing numbers ..can you please help out me on issue.

**Comment by fgali** [comment]
Where can I get an example code on how to make a table of contents?

**Comment by troosan** [comment]
see answer to same question in #707

**Comment by brucelin0325** [comment]
Hi @troosan 
I like this library very much, I have a question, sample 17 (Title TOC) works fine on my local machine, 
I mean addTOC and force update all fields when opening document.
But why it doesn't work on live domain?
I'm using office 2013 and it doesn't update when opening doc.
You can check it on this url.
http://www.thruline.com/intranet/CreateGridReport.php?v=20
Thanks in advance.

**Comment by troosan** [comment]
@brucelin0325 
Indeed, when I open the document, the TOC is being updated, but the page numbers are hidden.
I'll have to dig into it to find the cause.

FYI, your index can be built using XE and INDEX fields, see http://phpword.readthedocs.io/en/latest/elements.html#fields

**Comment by brucelin0325** [comment]
Really Thank you @troosan 
I make a huge progress, I tried as 1 column TOC, and page numbers are shown since I update the document.
Current TOC looks something like this.

`A SERIES OF UNFORTUNATE EVENTS, SEASON 3	................6`
`GUESS WHO DIED	..........................................8`
`VALLEY OF THE BOOM	......................................10`
`AMERICAN VANDAL, SEASON 2	...............................11`
`RUSSIAN DOLL	............................................12`
`THE OA, SEASON 2	........................................13`
`....`

My goal is create TOC looks like this one.
https://www.dropbox.com/s/36gx56p88auwm99/My%20Goal.png?dl=0

Can I add normal text section between TOC?
Can I rearrange the TOC?
Can I archieve this?

I'd appreciate if you can give me the solution. 
I hope my questions help a little to enhance this library.
All the best.

**Comment by troosan** [comment]
@brucelin0325 That's not a TOC but an index (with XE (index entry) and INDEX fields.
Could you please open a question on StackOverFlow so we can continue this discussion there. It will benefit more people this way.

**Comment by brucelin0325** [comment]
@troosan 
Yes, right this is not TOC just index.
I will open a question on stackoverflow.

**Comment by fgali** [comment]
Hello, I would like to know how to present special characters (<,>,> =, <=, among others) of correct way, I have tried several unsuccessfully.

**Comment by brucelin0325** [comment]
@troosan 
I opened a question as you said.
You can find it on here.
https://stackoverflow.com/questions/48155765/generate-index-with-phpword

**Comment by chaitanyagubbala** [comment]
Unable to display page numbers in TOC even after setting setUpdateFields as true. 
Can you please someone help on this!

**Comment by Kozin-br** [comment]
the same unable to display page numbers in TOC even after setting setUpdateFields as true

**Comment by pavarnos** [comment]
same. if i call `setUpdateFields(true)` then every time i open the file (Mac) is asks 'This document contains fields that may refer to other files. Do you want to update the fields in this document?'

**Comment by simogeo** [comment]
Ho, I'm using 0.18.3 version but still I'm not able to display page number in TOC, neither available in Word nor LibreOffice.

Could someone help me ?
