### ISSUE TITLE
unnecassary p tags generated from word file

### ISSUE THREAD

**Issue by brnogz** [PHPOffice/PHPWord#955]
Hi,

I try to use phpword to create pdf file from word files. However, there is a lot of new line in the output file. When i created an html file, i saw a lot of empty p tags in the file where new lines appeared. In case of corrupted source file, I tried on a new file with dummy content, new lines appeared again where i use tabs.

this one is from the input file

![input](https://cloud.githubusercontent.com/assets/1465450/21081338/e6c2cf6c-bfcc-11e6-9d37-0cf0d8516300.png)

this one is from the output file
![image](https://cloud.githubusercontent.com/assets/1465450/21081348/1fc40a6a-bfcd-11e6-87fc-cf22514425ed.png)

**Comment by loppi** [comment]
I have same problem. I must upgrade from 0.11.* to 0.13.* to support PHP7, but HTML conversion works very different in this versions.

**Comment by vinigarcia87** [comment]
I have the same problem. Anyone now how to solve this?

**Comment by troosan** [comment]
please try with dev-master (or 0.14) version
