### ISSUE TITLE
Charts - Can't Edit Data

### ISSUE THREAD

**Issue by phpdave** [PHPOffice/PHPWord#956]
If you right click on a chart created by PHPWord and click "Edit Data..." nothing happens.  Normally, an excel spreadsheet would pop-up and you could edit the data for the chart.

### **PHPWord Generated Chart**
![image](https://cloud.githubusercontent.com/assets/5050955/21200847/c0bda0de-c216-11e6-8cc0-cff5f4809c57.png)

### **Word - User Generated Chart**
![image](https://cloud.githubusercontent.com/assets/5050955/21200989/44e4318e-c217-11e6-9fa2-48b54f5a3227.png)

Online Example using PHPWord to create a chart:
http://elumina.co/libs/PHPWord-master/samples/Sample_32_Chart.php
Online Result:
http://elumina.co/libs/PHPWord-master/samples/results/Sample_32_Chart.docx

It appears that the relationship id rId1 is missing which targets "embeddings/Microsoft_Excel_Worksheet1.xlsx" which must be the embedded spreadsheet:
```
<pkg:xmlData>
    <Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">
    <Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/package" Target="../embeddings/Microsoft_Excel_Worksheet1.xlsx"/>
</Relationships>
```

Here's where the spreadsheet is but im not sure how you create the excel binary data.  I might look into addObject ```$section->addObject('resources/_sheet.xls');```referenced http://phpword.readthedocs.io/en/latest/elements.html and here  http://elumina.co/libs/PHPWord-master/samples/Sample_16_Object.php
```
<pkg:part pkg:name="/word/embeddings/Microsoft_Excel_Worksheet1.xlsx" pkg:contentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" pkg:compression="store">
<pkg:binaryData> ---EXCEL BINARY DATA HERE---
```

It appears that the generated charts are missing this data:
```
<c:ser>
                <c:idx val="0"/>
                <c:order val="0"/>
                <c:tx>
                    <c:strRef>
                        <c:f>Sheet1!$B$1</c:f>
                        <c:strCache>
                            <c:ptCount val="1"/>
                            <c:pt idx="0">
                                <c:v>Chart Title</c:v>
                            </c:pt>
                        </c:strCache>
                    </c:strRef>
                </c:tx>
                <c:cat>
                    <c:numRef>
                        <c:f>Sheet1!$A$2:$A$3</c:f>
                        <c:numCache>
                            <c:formatCode>General</c:formatCode>
                            <c:ptCount val="2"/>
                            <c:pt idx="0">
                                <c:v>2015</c:v>
                            </c:pt>
                            <c:pt idx="1">
                                <c:v>2016</c:v>
                            </c:pt>
                        </c:numCache>
                    </c:numRef>
                </c:cat>
                <c:val>
                    <c:numRef>
                        <c:f>Sheet1!$B$2:$B$3</c:f>
                        <c:numCache>
                            <c:formatCode>General</c:formatCode>
                            <c:ptCount val="2"/>
                            <c:pt idx="0">
                                <c:v>665</c:v>
                            </c:pt>
                            <c:pt idx="1">
                                <c:v>725</c:v>
                            </c:pt>
                        </c:numCache>
                    </c:numRef>
                </c:val>
                <c:smooth val="0"/>
            </c:ser>
```

Instead the charts are outputed with this data:

```
                <c:ser>
                    <c:idx val="0"/>
                    <c:order val="0"/>
                    <c:cat>
                        <c:strLit>
                            <c:ptCount val="1"/>
                            <c:pt idx="0">
                                <c:v>A</c:v>
                            </c:pt>
                        </c:strLit>
                    </c:cat>
                    <c:val>
                        <c:numLit>
                            <c:ptCount val="0"/>
                        </c:numLit>
                    </c:val>
                    <c:smooth val="1"/>
                </c:ser>
                <c:ser>
                    <c:idx val="1"/>
                    <c:order val="1"/>
                    <c:cat>
                        <c:strLit>
                            <c:ptCount val="1"/>
                            <c:pt idx="0">
                                <c:v>A</c:v>
                            </c:pt>
                        </c:strLit>
                    </c:cat>
                    <c:val>
                        <c:numLit>
                            <c:formatCode>General</c:formatCode>
                            <c:ptCount val="2"/>
                            <c:pt idx="0">
                                <c:v>843</c:v>
                            </c:pt>
                            <c:pt idx="1">
                                <c:v>821</c:v>
                            </c:pt>
                        </c:numLit>
                    </c:val>
                    <c:smooth val="1"/>
                </c:ser>
```

**Comment by zarte** [comment]
up

**Comment by jbebe** [comment]
Two years and not even a dev input? I wish you guys get a decent salary once for working on this.

**Comment by adlanarifzr** [comment]
> Two years and not even a dev input? I wish you guys get a decent salary once for working on this.

Are you sure you still unable to Edit Data? I tested it and able to edit without any problem.

**Comment by jbebe** [comment]
> I tested it and able to edit without any problem.
Which version are you using? I'm using 0.15.0 with Sample_32_Chart.php and MS Office 2017 and not a single window shows up.

**Comment by adlanarifzr** [comment]
> Which version are you using? I'm using 0.15.0 with Sample_32_Chart.php and MS Office 2017 and not a single window shows up.

I've been using v0.15.0 as well, opened with MS Office 2016.

**Comment by phpdave** [comment]
Someone could always post a bounty :-). Then this might get solved quicker. But what can you expect from open source. Some people can fix it and hopefully someone will pro bono or via bounty

**Comment by jbebe** [comment]
I created a chart with Word 2016 and then with PHPWord@dev-master. The comparison speaks for itself. You can't edit the data because it does not exist (as a spreadsheet). So yeah, we either wait or pay for a fix but as long as there are other solutions to consider I guess my non-profit project can avoid paying bounties. :)  
![image](https://user-images.githubusercontent.com/1939926/44111185-0983cefe-a002-11e8-97bf-641a9aca1897.png)

**Comment by Godisfooler** [comment]
Has this problem been fixed ?
