### ISSUE TITLE
Charts - Missing ability to modify Chart Settings

### ISSUE THREAD

**Issue by phpdave** [PHPOffice/PHPWord#957]
Missing ability to modify Chart Settings

### Data Labels above line graph points

![](https://cloud.githubusercontent.com/assets/5050955/21201943/dc6c9e26-c21a-11e6-8166-c6d7e582f6b0.png)

1. Data Label Position (http://www.datypic.com/sc/ooxml/t-draw-chart_ST_DLblPos.html)
2. Show Value of Label (http://www.datypic.com/sc/ooxml/e-draw-chart_showVal-1.html)

### Location of where these values are set:
```
<c:chart>
<c:plotArea>
<c:lineChart>
<c:dLbls>
	<c:dLblPos val="t"/>
	<c:showVal val="1"/>
</c:dLbls>
</c:lineChart>
</c:lineChart>
```

## Other Missing XML data that I'd like to help get working
Note I removed xml data that already is being set and just showing tags that appear to not be set
3. Set Axis Number Format (http://www.datypic.com/sc/ooxml/e-draw-chart_numFmt-1.html)
4. Set Axis Tick Label Position (http://www.datypic.com/sc/ooxml/e-draw-chart_tickLblPos-1.html)
5. Set Axis Shape Properties Shape Properties (http://www.datypic.com/sc/ooxml/e-draw-chart_spPr-1.html)
6. Set Axis No Multi-level Labels (http://www.datypic.com/sc/ooxml/e-draw-chart_noMultiLvlLbl-1.html)
7. Set Axis Major Gridlines (http://www.datypic.com/sc/ooxml/e-draw-chart_majorGridlines-1.html)
8. Set Legend Position (http://www.datypic.com/sc/ooxml/t-draw-chart_CT_LegendPos.html)
9. Set Legend Overlay http://www.datypic.com/sc/ooxml/e-draw-chart_overlay-1.html
10. Set Display Blanks As http://www.datypic.com/sc/ooxml/e-draw-chart_dispBlanksAs-1.html
11. Show Data Labels over Maximum http://www.datypic.com/sc/ooxml/e-draw-chart_showDLblsOverMax-1.html
12. Set External Data Relationship  http://www.datypic.com/sc/ooxml/e-draw-chart_externalData-1.html
```
<pkg:part>
<pkg:xmlData> 
<c:chart>
		<c:plotArea>
			<c:layout/>
			<c:lineChart>
				<c:ser>
					<c:catAx>
						<c:numFmt formatCode="General" sourceLinked="1"/>
						<c:tickLblPos val="nextTo"/>
						<c:spPr>
							<a:ln>
								<a:solidFill/>
							</a:ln>
						</c:spPr>
						<c:noMultiLvlLbl val="0"/>
					</c:catAx>
					<c:valAx>
						<c:majorGridlines/>
						<c:numFmt formatCode="General" sourceLinked="1"/>
						<c:tickLblPos val="nextTo"/>
						<c:spPr>
							<a:ln w="9525">
								<a:noFill/>
							</a:ln>
						</c:spPr>
					</c:valAx>
		</c:plotArea>
    <c:legend>
        <c:legendPos val="b"/>
        <c:overlay val="0"/>
    </c:legend>
<c:dispBlanksAs val="gap"/>
<c:showDLblsOverMax val="0"/>
</c:chart>	
	<c:externalData r:id="rId1">
		<c:autoUpdate val="0"/>
	</c:externalData>
</c:chartSpace>
</pkg:xmlData>
</pkg:part>
```

**Comment by phpdave** [comment]
It seems a user needs to be able to pass the graph options (data labels options, axis options, etc...) to the **PhpOffice\PhpWord\Element\Chart** class.  

In the **PhpOffice\PhpWord\Writer\Word2007\Part\Chart** class's **writeSeries** function after it writes all the series data it needs to take the private class variable **$element** which is a **PhpOffice\PhpWord\Element\Chart**  and use the data labels options to output **c:dLbls** values

**Comment by scalco19** [comment]
How can I implement these Data Label properties
[http://www.datypic.com/sc/ooxml/e-draw-chart_dLbl-1.html](url)

**Comment by phpdave** [comment]
@scalco19 not sure, that's a bar graph and not a line graph in the issue I was working on.  I'd recommend looking into reverse engineering the xml and just writing the rawxml of the entire graph from a template.

**Comment by phuwin** [comment]
Do you know how I can add to a piechart a legend that shows which part of the chart belongs to which data?

**Comment by marwankhanfar** [comment]
@phpdave did you manage to add legends and chart data

**Comment by diggamies** [comment]
@marwankhanfar If you follow his instructions stated in this thread, everything works like a charm for me. I think, if you have the time, you could build some setters for the data labels and legend if you want to, so that you don't have to work with the raw xml.

@phpdave Do you have an idea how to position multiple chart elements in a row side-by-side. As far I have tested, I only get them like a block element beneath each other.

**Comment by phpdave** [comment]
@Diggamies I would make that change in word, save it as xml and view the difference it made to the xml.  That seems like the quickest way to figure out how to do it. 

@marwabjhanfar yes if you follow what I wrote it will work.

**Comment by diggamies** [comment]
@phpdave Yeah, been there, done that. As I have found out, there is always a new paragraph around a chart element. Wenn you put them in word side-by-side you have both of them inside one paragraph. I found a variable $withoutP in the AbstractElement but it is not working on the Chart Element, when you change it to true.

**Comment by marwankhanfar** [comment]
@phpdave @diggamies  can you please send me the package with the changes, I tried to implement yours with no luck

**Comment by LDKJJ** [comment]
Hello @phpdave thank you for your post 
i am see last change for show axis and datalabel in chart using PHPWORD with add same XML and it's working for me.
Now my need is how to set style color in chart for example (radar chart) thanx :)

**Comment by arc113** [comment]
@phpdave  thank you so much for the Legend. It now shows up in the pie-chart. I now want to display the DATA LABELS in pie chart. Would the hard coding suggested by you work with pie-chart?

**Comment by arc113** [comment]
Also, WRT the hard coding data, I am getting error: LINE:            $chart->setOptions($chartOptions);

ERROR: PHP Fatal error:  Uncaught Error: Call to undefined method PhpOffice\PhpWord\Element\Chart::getOptions() in /var/www/html/phpword/samples/Sample_32_Chart.php:66
Stack trace:

**Comment by diggamies** [comment]
@arc113 Sorry, for not answering in such a long time, but I think with a new version of PHPWord the setOptions function has been removed. There are some options available now in the style object of the Chart class, but these are not working really good.

@phpdave Did you update to the current version and can tell us a workaround to get the legend back?

**Comment by phpdave** [comment]
I’d recommend looking over the recent changes https://github.com/PHPOffice/PHPWord/commit/65b0f062ad05836d939a76b3f62fdae0e0895e0c#diff-f95e31bde7c0c2535019d08b30203161

**Comment by phpdave** [comment]
@JAEK-S did some work to charts that may fix the issues I was running into

**Comment by phpdave** [comment]
Looks like he added Data labels :-)

**Comment by diggamies** [comment]
@phpdave Yeah, I was just checking these changes and since the setOptions method is not available anymore and only dataLabels are supported, I lost the otion to add the legend. Maybe i have to fork and set up a pull request in some time in the future to add legends to charts. Since I am using mostly pieCharts the dataLabels are not a big help in my case.

**Comment by phpdave** [comment]
Ah I understand your issue now.  Looks like fork and PR is the best approach. At least you have the documentation above to help.  Good luck sir!
