### ISSUE TITLE
Line height (line spacing) is setted to 1.5 even defining lineHeight to 1.00

### ISSUE THREAD

**Issue by JFSebastianVillalba** [PHPOffice/PHPWord#958]
Creating a Word document, even defining lineHeight to 1.0, the generated document dont respect that definition in lists, paragraphs, headers, footers... the lineHeight is setted to 1.5.

The lineHeight 1.00 specification is only respected in Word 15.29 for macOS 15.29, not in Windows version neither Word online.

Also, in Word online (Office 365), the document can be only opened in “view mode”.

Any help or advice?
Thank you.

Screenshot:
![captura 2016-12-16 a las 9 43 24](https://cloud.githubusercontent.com/assets/15821443/21256780/947045a4-c374-11e6-86d0-428576c0a510.png)

**Comment by JFSebastianVillalba** [comment]
Reset all the PHP code, the lineHeight stays in 1.00.
The problem opening document is related with tables in document.

**Comment by carlosmolano** [comment]
`$phpWord = new PhpWord();
        $phpWord->setDefaultParagraphStyle(
            array(
                'spaceAfter' => \PhpOffice\PhpWord\Shared\Converter::pointToTwip(0),
                'spacing'    => 120,
                'lineHeight' => 1,
            )
        );`

**Comment by henryseron** [comment]
I had the same problem with text spacing in a table and this helped me to fix it: 'spaceAfter' => \PhpOffice\PhpWord\Shared\Converter::pointToTwip(0),

Thanks.
