### ISSUE TITLE
templateProcessor issues

### ISSUE THREAD

**Issue by feakuru** [PHPOffice/PHPWord#959]
So I'm trying to use a phpword template processor. But the template vars are not substituted if there is more than one in a table row (or maybe for another reason, i can't get it). Are there any limitations on what a template tag should be? Alphanumeric? Length? Please give me some info on them if they exist

**Comment by ozilion** [comment]
just not use any special characters

**Comment by bonanAngeLOL** [comment]
I´m trying to fill a word template, i´m not using any special character, nor I have error in my code (I can assure). Sometimes when is executed my php program, it doesn't fill some labels (${example}), when template is modified,  some labels that didn't work at beggining begans to work, and others that worked fine are let of being filled, I don't know why I get this strange behavior

**Comment by feakuru** [comment]
@bonanAngeLOL it's most probably due to the fact that word styles some words differently in different parts (well, it was this way in my case). So, you might not notice, but the xml might be
```<w:p>${</w:p>example}```
The quick fix is to try and erase the bugged template tag and print it by hand again. The more profound fix is to review the XML.

**Comment by feakuru** [comment]
hey y'all, i'll go ahead and close this, sorry for necroposting and have a great day!
