### ISSUE TITLE
Does PhpWord support the creation of dotx files?

### ISSUE THREAD

**Issue by chris-fa** [PHPOffice/PHPWord#963]
I'm still trying to figure out what I need specifically, so I'll put the raws idea and you guys let me know if this can be done with PhpWord or if I should look for a different approach:

(**NOTE**: when I say **template** in this question, I mean a `dotx` file, not the template processor package from this library)

**I need to create templates (`.dotx` files) with certain paragraph/sentences/words protected from edition, and with tracking changes on**. Once the actual document (the `.docx` file) is created from the template, the user will work on that one using Microsoft Word (and of course should have revision enabled and the paragraphs protected too).

I know (or at least I think so) that I can directly create protected `.docx` document with revision enabled using `PhpWord`, but since the document's content needs to be created programmatically from a template/draft file, I'm figuring out whether to use a `.dotx` file as the template, or just save a text string to a database and populate `.docx` with that string (probably with some tokens to know which paragraph to protect).

Thanks in advance

**Comment by troosan** [comment]
you cannot create .dotx files with PHPWord. With latest 0.14 version you can enable track changes.
