### ISSUE TITLE
Support for zend 2.5?

### ISSUE THREAD

**Issue by chris-fa** [PHPOffice/PHPWord#967]
I just realized version `0.13.*` uses zend libraries on their `2.4` release. Is there an incompatibility with 2.5?

**Comment by stephanvierkant** [comment]
zend-stdlib 3.1.0 is the latest stable at the moment: https://github.com/zendframework/zend-stdlib/releases

**Comment by stephanvierkant** [comment]
When looking at all release notes from >2.4.0, I don't see any reason why the latest version in the 2.*-branch, I don't see any reason why it won't work.

I'll fork this repository, try 2.7 and let you know if it works.

**Comment by stephanvierkant** [comment]
See #865. It has a PR.

I think we should close this issue.
