### ISSUE TITLE
IOFactory::load() destroys format - Can't read a document

### ISSUE THREAD

**Issue by chris-fa** [PHPOffice/PHPWord#969]
Maybe I'm just missing something basic like an extension or something, please help:

Here's a [pastebin](http://pastebin.com/1GgVVcWc) with the dump of my `$ php -i`

### Step to reproduce
1. Clone this repository
  1.1 [Optional] Checkout your favorite version, I tried 0.13 and 0.12
2. `$ cd samples`
3. `$ php Sample_11_ReadWord2007.php`   (with php 5.6.27 here)
4. `$ open results/Sample_11_ReadWord2007.docx`

### Expected Results
The opened document maintains the same formatting (spaces, breaklines, etc) as the original one:
<img width="1316" alt="screen shot 2016-12-23 at 08 23 21" src="https://cloud.githubusercontent.com/assets/22173137/21454770/2eeee8f0-c8e9-11e6-8542-ee17730d3c89.png">

### Actual Results
<img width="1291" alt="screen shot 2016-12-23 at 08 23 28" src="https://cloud.githubusercontent.com/assets/22173137/21454774/315b97dc-c8e9-11e6-962c-76d692cdf871.png">

**Comment by ericdsw** [comment]
Can confirm, I got the same output by reproducing the steps above.

I'm using PHP 7.0.14, and I opened the document with Word 2016.

<img width="1440" alt="screen shot 2016-12-23 at 11 09 30 am" src="https://cloud.githubusercontent.com/assets/3594423/21457926/c6188044-c900-11e6-9cf0-edc7f3a46795.png">

**Comment by schnauss** [comment]
I'm having the same issue, PHP 5.4.

**Comment by Arthi93** [comment]
Got the same issue trying to save documents as PDF or HTML.

IOFactory::load destroys formatting

**Comment by leefuwa** [comment]
Excuse me, is this problem settled?

**Comment by troosan** [comment]
should be, in the dev branch at least.
It will be part of v0.14
