### ISSUE TITLE
can not send the generated doxc file to browser

### ISSUE THREAD

**Issue by Gargamel13** [PHPOffice/PHPWord#974]
Really need your help!!!

I still can not find a solution for my problem. my generated "docx"-file can not send to the browser. I tried so many options.

here is my Code:

    <?php
    require_once 'autoload.php';
    $phpword = new \PhpOffice\PhpWord\PhpWord();

    $section = $phpword->addSection();

    // Simple text
    $section->addTitle('Welcome to PhpWord', 1);
    $section->addText('Hello World!');

    // Two text break
    $section->addTextBreak(2);

    // Define styles
    $section->addText('I am styled by a font style definition.');
    $section->addText('I am styled by a paragraph style definition.');
    $section->addText('I am styled by both font and paragraph style.');
    
    $section->addTextBreak();
    
    // Inline font style
    $fontStyle['name'] = 'Times New Roman';
    $fontStyle['size'] = 20;
    
    $textrun = $section->addTextRun();
    $textrun->addText('I am inline styled ', $fontStyle);
    $textrun->addText('with ');
    $textrun->addText('color', array('color' => '996699'));
    $textrun->addText(', ');
   

    $filename = "Perfomance_Appraisal.docx";

    $objWriter = \PhpOffice\PhpWord\IOFactory::createWriter($phpword, 'Word2007');
    $objWriter->save($filename);

    header('Content-Description: File Transfer');
    header('Content-Type: application/octet-stream');
    header('Content-Disposition: attachment; filename='.$filename);
    header('Content-Transfer-Encoding: binary');
    header('Expires: 0');
    header('Cache-Control: must-revalidate, post-check=0, pre-check=0');
    header('Pragma: public');
    header('Content-Length: ' . filesize($filename));
    flush();
    readfile($filename);
    unlink($filename); // deletes the temporary file

Is it because i am working on my local webserver? in the network panel of my browser it shows random symbols

**Comment by troosan** [comment]
just do
```php
$phpword->save('Perfomance_Appraisal.docx', 'Word2007', true);
```
